#pragma once

// Dependencies
#include "system/basetypes.h"
#include "system/dos.h"
#include "system/fstream.h"
#include "system/iostream.h"
#include "system/math.h"
#include "system/signal.h"
#include "system/stat.h"
#include "system/stdarg.h"
#include "system/stdio.h"
#include "system/stdlib.h"
#include "system/strstream.h"
#include "system/time.h"
#include "system/utime.h"
#include "system/watcom.h"
#include "system/winbase.h"
#include "system/wincon.h"
#include "system/windef.h"
#include "system/winnt.h"

// =============================================================================
// FUNCTION PROTOTYPES - Range 0x600000
// =============================================================================

double __cdecl crt_math_c_ldexp_FUN_00600002(double x,int exp);
int __cdecl crt_stdio_c_string_getc_FUN_006000d0(scanf_state_t *state);
int __cdecl crt_stdio_c_string_ungetc_FUN_006000f8(int ch,scanf_state_t *state);
int __cdecl crt_stdio_c_vsscanf_FUN_00600100(char *str,char *format,va_list_t args);
int __cdecl crt_stdio_c_sscanf_FUN_0060013c(char *str,char *format,...) __attribute__((format(scanf, 2, 3)));
double __fpustack_safe crt_math_c_acos_FUN_00600162(double x);
double __crtmath crt_math_c_ceil_FUN_006001b2(double value);
time_t __cdecl crt_time_c__time_FUN_006001f0(int *time);
_tm * __cdecl crt_time_c_localtime_r_FUN_00600230(time_t *timer,_tm *result);
_tm * __cdecl crt_time_c__localtime_FUN_00600288(time_t *timer);
void __cdecl crt_stdio_c_formatTwoDigits_FUN_006002a0(char *buffer,int value);
uint __cdecl crt_time_c__strftime_FUN_006002d4(char *dest_buffer,uint buffer_size,char *format_string,_tm *time_ptr);
char * __cdecl crt_string_c_strupr_FUN_00600770(char *string);
void __cdecl crt_system_c_sleep_FUN_00600790(DWORD milliseconds);
int __cdecl crt_stdio_c_fputc_FUN_006007a0(int character,_FILE *file);
uint __watcallRegister crt_watcom_c_memavl_FUN_006008f0(void);
uint crt_watcom_c__memmax_FUN_00600940(void);
undefined4 crt_unknown_c_FUN_00600990(uint *param_1);
uint crt_unknown_c_FUN_00600a64(byte *param_1);
int __cdecl crt_watcom_c__heapchk_FUN_00600ad0(void);
float10 __fpustack_safe crt_math_c_asin_FUN_00600b94(float10 sine_value);
void * __cdecl crt_memory_c___arrcopy_FUN_00600bc2(void *dest,void *source,int count,WatcomTypeInfo *type_info);
int __cdecl crt_io_c_stat_00600c18(char *filename,_stat *file_info);
int __cdecl crt_io_c_utime_00600c1e(char *filename,utimbuf *timestamps);
DWORD __cdecl engine_dosio_c_setReadonlyAttribute_FUN_00600c30(char *filename,DWORD file_attributes);
void __cdecl crt_unknown_c_FUN_00600c80(int param_1,int param_2,SIZE_T param_3);
int __cdecl crt_io_c_chsize_FUN_00600cf0(int file_handle,long new_size);
int __cdecl crt_watcom_c__mkdir_FUN_00600e10(char *path);
void __cdecl crt_stdio_c_fflush_FUN_00600e29(_FILE *stream);
uint __cdecl crt_iostream_cpp_ios_clear_FUN_00600e64(ios *this_ptr,uint state_flags);
void __cdecl crt_fstream_cpp_openFile_FUN_00600e85(void *stream_obj,char *filename,int open_mode,SIZE_T buffer_size);
_istream * __cdecl crt_fstream_cpp_istream_seekg_FUN_00600ee4(void *this_ptr,int offset);
char * __cdecl crt_string_c__strncpy_FUN_00600f40(char *dest,char *src,SIZE_T count);
time_t __cdecl crt_time_c__mktime_FUN_00600f80(_tm *timeptr);
char * __cdecl crt_stdlib_c__fullpath_FUN_00601140(char *buffer,char *path,SIZE_T buffer_size);
void * __cdecl crt_memory_c___arrinit_dispatch_FUN_00601200(void *array_ptr,int element_count,WatcomTypeInfo *type_info);
void * __cdecl crt_memory_c___vec_new_FUN_00601232(void *dest,int element_count,WatcomTypeInfo *type_info);
void crt_unknown_c_AnotherFunctorCall2_FUN_00601258 (void *param_1,int param_2,WatcomTypeInfo *param_3);
void * __cdecl crt_memory_c___vec_new_FUN_00601272(void *array_memory,int element_count,WatcomTypeInfo *type_info);
char * __cdecl crt_watcom_c__getcwd_FUN_00608d20(char *buffer,SIZE_T size);
int __cdecl crt_io_c_chdir_FUN_006012a0(char *path);
int __cdecl crt_heap_c__heapwalk_FUN_006012c0(_heapinfo *heap_info);
int __cdecl crt_heap_c_heapWalk_FUN_006012d0(HeapState *heap_state_ptr,Heap *heap_ptr);
int __cdecl crt_heap_c_heapCheck_FUN_00601374(void *heap_state_ptr);
float10 __fpureg crt_math_c_atan2_FUN_006013b1(float10 y,float10 x);
char * __cdecl crt_env_c_getenv_FUN_006013f0(char *name);
int * crt_errno_c__errno_FUN_00601450(void);
char * __watcallStack crt_string_c_strerror_FUN_00601470(int errnum);
int __cdecl crt_stdio_c_setvbuf_FUN_00601490(_FILE *stream_ptr,char *buffer_ptr,int buffer_mode,SIZE_T buffer_size);
int __cdecl crt_stdio_c_fflush_FUN_00601540(_FILE *stream);
long __cdecl crt_stdio_c_ftell_FUN_00601560(_FILE *file_handle);
int __watcallStack crt_stdio_c_rename_FUN_006015d0(char *old_filename,char *new_filename);
void crt_cpp_c_handlePureVirtualCall_FUN_006015f1(void);
void __watcallRegister crt_startup_c_notifyAbnormalTermination_FUN_00601620(void);
void __watcallRegister crt_startup_c_reportAbnormalTermination_FUN_00601628(void);
void __watcallStack crt_time_c_formatTwoDigits_FUN_00601640(int number,int position,char *buffer);
char * __watcallStack crt_time_c_asctimeFormat_FUN_00601678(_tm *timeptr,char *buffer);
char * __cdecl crt_time_c__asctime_FUN_00601768(_tm *timeptr);
int __cdecl crt_stdio_c_OpenModeStringParser_FUN_006017d0(char *mode_string,char *output_flags);
_FILE * __cdecl crt_stdio_c_OpenFileAndInitialize_FUN_0060190c(char *filename,char mode_char,int parsed_mode_flags,int stage1_result, int additional_flags,_FILE *file_struct);
_FILE * __cdecl crt_stdio_c_fopenWithFlags_FUN_00601a20(char *filename,char *mode,int flags);
_FILE * __cdecl crt_stdio_c_fopen_FUN_00601a7c(char *filename,char *mode);
_FILE * crt_unknown_c_MultipleDoNothingCalls_FUN_00601a94(_FILE *param_1);
_FILE * __cdecl crt_stdio_c__freopen_FUN_00601b14(char *filename,char *mode,_FILE *stream);
void * __cdecl crt_memory_c_malloc_FUN_00601bb0(ulong size);
void * __cdecl crt_heap_c_InternalHeapAlloc_FUN_00601bc0(ulong size);
void __cdecl crt_memory_c_free_FUN_00601cd0(void *ptr);
void __cdecl crt_heap_c_ValidateHeapIntegrity_FUN_00601ce0(void *ptr);
void * __cdecl crt_memory_c_realloc_FUN_00601df0(void *ptr,ulong new_size);
void * __cdecl crt_memory_c_realloc__FUN_00601e08(void *ptr,ulong new_size);
int __cdecl crt_stdio_c_fclose_FUN_00601ea0(_FILE *file_handle);
int __cdecl crt_stdio_c___CClose_FUN_00601ee4(_FILE *file_handle,int close_flags);
char __watcallStack crt_string_c_hexDigitToChar_FUN_00601f0c(int digit);
void __watcallStack crt_io_c__tempnam_FUN_00601f1c(char *buffer,int file_handle);
int __cdecl crt_stdio_c__fclose_FUN_00601fd0(_FILE *file_handle,int force_close_flag);
void * __cdecl crt_memory_c___arr_op_FUN_006020c2(void *dest,void *source,int count,int element_size,void *copy_func);
int __cdecl crt_string_c__stricmp_FUN_005fe7f0(char *str1,char *str2);
double __crtmath crt_math_c_modf_FUN_00602102(double value,double *integer_part);
int __watcallStack crt_stdlib_c_system_FUN_00602130(char *command);
void __cdecl crt_stdio_c_fprintf_FUN_006021c0(_FILE *stream,char *format,...) __attribute__((format(printf, 2, 3)));
void * __cdecl shape_memdbg_cpp_malloc_FUN_006021da(SIZE_T size);
HANDLE __cdecl crt_io_c__findfirst_FUN_006021f0(char *filespec,LPWIN32_FIND_DATAA find_data);
void __watcallStack crt_io_c_convertFileInfo_FUN_00602264(LPWIN32_FIND_DATAA win32_data,_find_t *dos_info);
int __cdecl crt_io_c__findnext_FUN_00602300(HANDLE find_handle,LPWIN32_FIND_DATAA find_data);
int __cdecl crt_io_c__findclose_FUN_00602380(HANDLE find_handle);
void __watcallRegister entry(void);
void __cdecl crt_unknown_c_staticInit_FUN_0060240e(void);
ThreadData * __cdecl crt_thread_c_GetTLS_FUN_0060242c(void);
void __cdecl crt_sync_c_CriticalSectionStub_FUN_00602434(void);
int __cdecl crt_io_c_register_handler_wrapper_FUN_00602438(HANDLE file_handle);
void __cdecl crt_io_c_invalidate_handle_wrapper_FUN_00602448(int handle_index);
void crt_sync_c_CriticalSectionStub_FUN_00602458(void);
void __cdecl crt_startup_c_initialize_runtime_FUN_0060245c(HMODULE hModule,void *pThreadParam,int unused);
void __watcallRegister crt_startup_cpp_InitializeWinAppRuntime_FUN_006026a8(void *pParam);
void __cdecl crt_exit_c_ExitProcess_FUN_00602700(int exit_code);
void __cdecl crt_unknown_c_staticFinal_FUN_00602748(void);
void __cdecl crt_errno_c_setErrno_FUN_00602790(int error_code);
void __cdecl crt_math_c_set_domain_error_errno_FUN_006027a0(void);
void __cdecl crt_math_c_set_range_error_errno_FUN_006027ac(void);
void __cdecl crt_errno_c_SetWindowsError_FUN_006027c8(DWORD windows_error_code);
void __cdecl crt_stdio_c_InitializeFileBuffer_FUN_006027e0(_FILE *file);
int __watcallStack crt_stdio_c_ReadFileWithDeviceAbstraction_FUN_00602880 (int file_handle_index,void *buffer,int bytes_to_read);
int __cdecl crt_stdio_c_FormatEngine_FUN_00602950(void *output_context,char *format,va_list_t args,OUTPUT_CALLBACK callback);
char * __cdecl crt_stdio_c_ScanFormatSpec_FUN_00602d78(char *format,va_list_t *args,FormatSpec *spec_info);
char * __cdecl crt_stdio_c_ParseFormatFlags_FUN_00602edc(char *format,FormatSpec *spec_info);
int __cdecl crt_string_c_strlen_far_FUN_00602f4c(char *string_offset,ushort segment,int max_length);
int __cdecl crt_stdio_c_WideStringToMultiByteLen_FUN_00602f7c(wchar_t *wide_string_offset,ushort segment,int max_chars);
void __cdecl crt_stdio_c_FormatHexWithPadding_FUN_00602ff8(int value,char *buffer,int width);
void __cdecl crt_stdio_c_FormatFixedPoint_FUN_0060305c(char *buffer,int fixed_point_value,FormatSpec *spec_info);
void __cdecl crt_stdio_c_FloatingPointStub_FUN_00603160(char *buffer,va_list_t *args,FormatSpec *spec_info);
void __cdecl crt_stdio_c_CalculateZeroPadding_FUN_0060317c(FormatSpec *spec_info);
void __cdecl crt_stdio_c_FormatWideString_FUN_006031c0(wchar_t *wide_string_offset,ushort segment,FormatSpec *spec_info, OUTPUT_CALLBACK output_func);
char * __cdecl crt_stdio_c_ConvertFormatSpec_FUN_00603238(char *output_buffer,va_list_t *args,FormatSpec *spec_info);
char * __cdecl crt_string_c_strupr_FUN_0060389c(char *string);
int __watcallStack crt_stdio_c_write_FUN_006038c0(int file_handle_index,void *buffer,int bytes_to_write);
int __watcallStack crt_stdio_c_fflushInternal_FUN_006039d0(_FILE *file_handle);
void * __watcallRegister crt_memory_c___memfill_FUN_00603b00(void *dest,uint replicated_value,uint count);
void __watcallRegister crt_memory_c___stosd_FUN_00603b37(void *dest,uint replicated_value,uint dword_count);
void __cdecl crt_strtod_c_staticInit_FUN_00603bb0(void);
void __cdecl crt_unknown_c_FUN_00603bc9(char *str,double *output);
int __cdecl crt_unknown_c_FUN_00603bf5(void);
void __cdecl crt_unknown_c_FUN_00603c74(void);
void __cdecl crt_unknown_c_CondCallDoNothing_FUN_00603ccc(void);
void __cdecl crt_unknown_c_FUN_00603d60(void);
void __cdecl crt_unknown_c_FUN_00603dc8(void);
void __cdecl crt_unknown_c_FUN_0060403f(undefined4 param_1,float10 *param_2,undefined4 param_3,char *param_4,uint param_5, char *param_6,char *param_7,char *param_8,uint param_9,undefined4 param_10, char *param_11);
void __cdecl crt_unknown_c_FUN_006040d7(uint param_1,undefined4 param_2,char *unaff_EBX,undefined4 param_4,char *param_5, undefined4 param_6,char *param_7,uint param_8,undefined4 param_9,char *param_10);
void __cdecl crt_unknown_c_FUN_006040ed(uint param_1,undefined4 param_2,char *unaff_EBX,undefined4 param_4,char *param_5);
void __cdecl crt_unknown_c_FUN_00604104(ushort param_1,undefined4 param_2,char *unaff_EBX);
void crt_unknown_c_FUN_0060411c (undefined4 param_1,undefined4 param_2,undefined4 param_3,float10 *param_4, undefined4 param_5,undefined4 param_6,undefined4 param_7,char *param_8, undefined4 param_9,char *param_10,uint param_11,undefined4 param_12,char *param_13);
void crt_unknown_c_FUN_00604267(uint *param_1,char *param_2,uint param_3,uint param_4,char *param_5);
void crt_unknown_c_FUN_0060445e(void);
void crt_unknown_c_FUN_00604478 (int *param_1,undefined4 *param_2,uint param_3,int param_4,undefined4 *param_5);
void crt_unknown_c_thunk_FUN_0060b142 (undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4, undefined4 param_5);
void crt_stdio_c_reportCPPFloatingPointSupportProblem_FUN_0060477f(void);
void crt_unknown_c_FUN_006047a4(void);
void __cdecl crt_fpu_c_staticInit_FUN_006047e0(void);
void crt_unknown_c_FUN_00604824(void);
void __watcallStack crt_stdio_c_OutputCallback_FUN_00604830(FORMAT_OUTPUT_CONTEXT *context,int character);
int __watcallStack crt_stdio_c_vfprintf_FUN_00604850(_FILE *file,char *format,va_list_t args);
int __cdecl crt_stdio_c_scanf_getc_wrapper_FUN_00604930(scanf_state_t *state);
int __cdecl crt_stdio_c_scanf_ungetc_wrapper_FUN_0060493c(int character,scanf_state_t *state);
int __cdecl crt_stdio_c_doscan_FUN_00604950(scanf_state_t *state,char **format_ptr,va_list_t *args);
char * __cdecl crt_stdio_c_parse_format_spec_FUN_00604c1c(char *format_ptr,scanf_state_t *state);
int __cdecl crt_stdio_c_skip_whitespace_FUN_00604d18(scanf_state_t *state);
int __cdecl crt_stdio_c_scanf_char_FUN_00604d54(scanf_state_t *state,va_list_t *args);
int __cdecl crt_stdio_c_scanf_string_FUN_00604e4c(scanf_state_t *state,va_list_t *args);
void __cdecl crt_stdio_c_store_count_FUN_00604fb0(scanf_state_t *state,va_list_t *args,int chars_consumed);
byte * crt_unknown_c_FUN_0060501c(byte *param_1,void *param_2);
int __cdecl crt_stdio_c_scanf_scanset_FUN_00605064(scanf_state_t *state,va_list_t *args,char **format_ptr);
int __cdecl crt_stdio_c_scanf_float_FUN_00605178(scanf_state_t *state,va_list_t *args);
int __cdecl crt_stdio_c_scanf_integer_FUN_0060547c(scanf_state_t *state,va_list_t *args,int base,int is_signed);
int __cdecl crt_stdio_c_char_to_digit_FUN_006058e8(int ch);
int __cdecl crt_stdio_c_scanf_getc_with_width_FUN_00605918(scanf_state_t *state);
void crt_unknown_c_FUN_00605950(void);
int __watcallStack crt_stdio_c_FlushFilesByMask_FUN_0060595c(uint file_mode_mask);
int crt_stdio_c_SetupConsoleInputMode_FUN_006059b0(void);
int __watcallStack crt_string_c_mbtowc_peek_FUN_006059e0(char *str);
void __watcallStack crt_locale_c_wchar_to_bytes_FUN_00605a20(wchar_t character,char *output_buffer);
int __watcallStack crt_locale_c_mblen_FUN_00605a40(char *mb_string);
char * __watcallStack crt_string_c_mbtowc_next_FUN_00605a70(char *str);
char * __cdecl crt_string_c_mb_get_last_char_FUN_00605aa0(char *start,char *end);
void __watcallStack crt_cpp_c_reportPureVirtualError_FUN_00605b23(char *error_message,int exit_code);
void __cdecl crt_unknown_c_staticFinal_FUN_00605b62(void);
void __cdecl crt_stdlib_c_atexitRegisterNode_FUN_00605b89(WatcomStaticDestructorNode *node_ptr);
int __cdecl crt_string_c_parseFloatString_FUN_00605b9b(char *str,void *result,char **endptr);
double __cdecl crt_string_c_strtod_main_FUN_00605d5d(char *str,char **endptr);
int __watcallStack crt_string_c_mbstrnlen_FUN_00605e50(char *str,int max_bytes);
char * __watcallStack crt_string_c_mbstrncpy_FUN_00605e90(char *dest,char *src,int char_count);
int __watcallStack crt_string_c_mbstrnbytes_FUN_00605ec0(char *str,int char_count);
int __watcallStack crt_stdio_c_stream_setup_FUN_00605f20(_FILE *stream,int operation_type);
_FILE * __watcallStack crt_stdio_c_fgetcInternal_FUN_00605fad(_FILE *stream,byte *output_byte);
void __cdecl crt_stdio_c_reportStreamError_FUN_00606020(FileEmbeddedData *embedded_data,uint error_flags);
BOOL __cdecl crt_stdio_c_prepare_stream_for_write_FUN_00606055(_FILE *stream);
_FILE * __watcallStack crt_stdio_c_stream_flush_FUN_006060bb(_FILE *stream);
strstreambase * __cdecl crt_strstream_cpp_strstreambase_ctor_FUN_006060fe(strstreambase *this_ptr,int ctor_flags,char *buffer,int size,char *pstart);
void __cdecl crt_strstream_cpp_strstreambase_destructor_thunk_FUN_0060618a(ios *this_ptr,int dtor_flags);
_ostream * __cdecl crt_iostream_cpp_ostream_ctor_FUN_006061a2(_ostream *this_ptr,uint c1);
void __cdecl crt_iostream_cpp_ostream_destructor_thunk_FUN_006061e4(ios *this_ptr,int dtor_flags);
ios * __cdecl crt_iostream_cpp_ios_ctor_FUN_006061fc(ios *this_ptr);
_ostream * __cdecl crt_iostream_cpp_ostream_dtor_FUN_00606231(_ostream *this_ptr,uint flags);
strstreambase * __cdecl crt_strstream_cpp_strstreambase_dtor_FUN_006062a6(strstreambase *this_ptr,uint flags);
ios * __cdecl crt_iostream_cpp_ios_dtor_FUN_0060632c(ios *this_ptr,uint flags);
_istream * __cdecl crt_iostream_cpp_istream_ctor_FUN_00606376(_istream *this_ptr,uint c1);
void __cdecl crt_iostream_cpp_istream_destructor_thunk_from_ios_FUN_006063c9(ios *this_ptr,int dtor_flags);
_istream * __cdecl crt_iostream_cpp_istream_dtor_FUN_006063e1(_istream *this_ptr,uint flags);
void __cdecl crt_fstream_cpp_fstreambase_ctor_FUN_00606456(fstreambase *this_ptr,int ctor_flags,int fd,int mode,char *buffer,SIZE_T buffer_size );
void __cdecl crt_fstream_cpp_fstream_destructor_thunk_from_ios_FUN_006064f1(ios *this_ptr,int dtor_flags);
fstreambase * __cdecl crt_fstream_cpp_fstreambase_dtor_FUN_00606509(fstreambase *this_ptr,uint flags);
fstreambase * __cdecl crt_fstream_cpp_fstreambase_ctor_FUN_0060658f(fstreambase *this_ptr,uint c1);
int __watcallStack crt_stdio_c_remove_FUN_00606600(char *filename);
void __cdecl crt_startup_c_WriteErrorAndExit_FUN_00606620(char *error_message,int exit_code);
void __cdecl crt_startup_c_HandleRuntimeError_FUN_00606660(char *error_message,int error_level);
int __watcallStack crt_stdio_c_lseek_FUN_00606690(int file_handle_index,long distance_to_move,int move_method);
long __watcallStack crt_io_c_tell_FUN_00606720(int file_handle_index);
int __watcallStack crt_iostream_cpp_streambuf_do_sputn_FUN_00606780 (streambuf *buffer,void *input_buffer,SIZE_T bytes_to_write);
double __cdecl crt_math_c_math_domain_error_FUN_00606832(double x,double y,uchar error_type);
float10 __fpureg_safe crt_math_c_exp_FUN_006068e2(float10 x);
float10 __fpustack_safe crt_math_c_fdiv_FUN_00606960(float10 dividend,float10 divisor);
float10 __watcallRegister crt_math_c_function_dispatch_FUN_00606a77(int function_index);
float10 __watcallRegister crt_math_c_generate_nan_FUN_00606a81(void);
void __watcallRegister crt_math_c_fatal_math_error_FUN_00606a87(void);
float10 __watcallRegister crt_math_c_generate_nan_FUN_00606a8c(void);
void __watcallRegister crt_math_c_fatal_math_error_FUN_00606a92(void);
float10 __watcallRegister crt_math_c_generate_nan_FUN_00606a97(void);
float10 __watcallRegister crt_math_c_generate_nan_FUN_00606a9d(void);
float10 __watcallRegister crt_math_c_generate_nan_FUN_00606aa3(void);
float10 __watcallRegister crt_math_c_generate_nan_FUN_00606aa9(void);
float10 __watcallRegister crt_math_c_dispatch_divide_FUN_00606aaf(void);
void crt_math_c_FUN_00606acb(void);
void crt_math_c_FUN_00606ad0(void);
void crt_math_c_FUN_00606ae6(void);
float10 __fpu_thunk crt_math_c_fdiv_thunk_FUN_00606aeb(void);
void crt_math_c_FUN_00606b07(void);
float10 __fpu_thunk crt_math_c_fdiv_thunk_FUN_00606b17(void);
void crt_math_c_FUN_00606b2b(void);
void crt_math_c_FUN_00606b3b(void);
void crt_math_c_FUN_00606b5b(void);
void crt_math_c_FUN_00606b60(void);
void crt_math_c_FUN_00606b7a(void);
float10 __fpu_thunk crt_math_c_fdiv_thunk_FUN_00606b7f(void);
void crt_math_c_FUN_00606b9f(void);
float10 __fpu_thunk crt_math_c_fdiv_thunk_FUN_00606bb3(void);
void crt_math_c_FUN_00606bcb(void);
void crt_math_c_FUN_00606bdf(void);
void crt_math_c_FUN_00606bff(void);
void crt_math_c_FUN_00606c04(void);
void crt_math_c_FUN_00606c1e(void);
void crt_math_c_FUN_00606c23(void);
void crt_math_c_FUN_00606c43(void);
void crt_math_c_FUN_00606c57(void);
void crt_math_c_FUN_00606c6f(void);
void crt_math_c_FUN_00606c83(void);
void crt_math_c_FUN_00606ca3(void);
void crt_math_c_FUN_00606ca8(void);
void crt_math_c_FUN_00606cc2(void);
float10 __fpu_thunk crt_math_c_fdiv_thunk_FUN_00606cc7(void);
void crt_math_c_FUN_00606ce7(void);
float10 __fpu_thunk crt_math_c_fdiv_thunk_FUN_00606cfb(void);
void crt_math_c_FUN_00606d13(void);
void crt_math_c_FUN_00606d27(void);
void crt_math_c_FUN_00606d47(void);
void crt_math_c_FUN_00606d4c(void);
void crt_math_c_FUN_00606d66(void);
float10 __fpu_thunk crt_math_c_fdiv_thunk_FUN_00606d6b(void);
void crt_math_c_FUN_00606d8b(void);
float10 __fpu_thunk crt_math_c_fdiv_thunk_FUN_00606d9f(void);
void crt_math_c_FUN_00606db7(void);
void crt_math_c_FUN_00606dcb(void);
void crt_math_c_FUN_00606deb(void);
void crt_math_c_FUN_00606df0(void);
void crt_math_c_FUN_00606e0a(void);
float10 __fpu_thunk crt_math_c_fdiv_thunk_FUN_00606e0f(void);
void crt_math_c_FUN_00606e2f(void);
float10 __fpu_thunk crt_math_c_fdiv_thunk_FUN_00606e43(void);
void crt_math_c_FUN_00606e5b(void);
void crt_math_c_FUN_00606e6f(void);
void crt_math_c_FUN_00606e8f(void);
void crt_math_c_FUN_00606e94(void);
void crt_math_c_FUN_00606eae(void);
void crt_math_c_FUN_00606eb3(void);
void crt_math_c_FUN_00606ed3(void);
float10 __fpu_thunk crt_math_c_fdiv_thunk_FUN_00606ee7(void);
void crt_math_c_FUN_00606eff(void);
float10 __fpustack_safe crt_math_c_pentiumFdivpWorkaround_FUN_00606f13(float10 dividend,float10 divisor);
float10 __fpustack crt_math_c_pentiumFdivBugWorkaroundDouble_FUN_00606f98(float10 param0,double param1);
void crt_unknown_c_FUN_00607080(void *param_1,byte *param_2);
double __fpureg_safe crt_math_c_sqrt_FUN_0060710c(double value);
int __watcallStack crt_time_c_get_local_time_FUN_00607150(_tm *tm_output);
void __cdecl crt_time_c_tzset_FUN_006072f8(void);
char * __cdecl crt_string_c_parse_uint_FUN_00607318(char *str,int *result);
char * __cdecl crt_time_c_parse_timezone_spec_FUN_00607348(char *tz_string,char *name_buffer,int *offset_seconds);
char * __cdecl crt_time_c_parse_dst_rule_FUN_00607464(char *rule_string,dst_rule *rule);
void __cdecl crt_time_c_parse_tz_string_FUN_0060756c(char *tz_string);
undefined4 * __cdecl crt_time_c_gmtime_r_FUN_00607690(int days,uint seconds,int timezone_offset,undefined4 *param_4);
int __cdecl crt_time_c_is_leap_year_FUN_00607820(int year);
int crt_unknown_c_FUN_00607858(int param_1,int param_2);
undefined4 crt_unknown_c_FUN_00607958(int param_1,int param_2,undefined4 param_3);
int __cdecl crt_time_c_determine_dst_status_FUN_006079b4(_tm *timeptr);
undefined4 crt_unknown_c_FUN_00607c88(int *param_1,int *param_2);
char * __cdecl crt_stdlib_c_itoa_FUN_00607cc0(int value,char *buffer,int base);
char * __cdecl crt_stdio_c_IntegerToString_FUN_00607d18(int value,char *buffer,int base);
uint __watcallStack crt_io_c_analyze_file_type_FUN_00607d50(uint open_flags,char *filename);
int __cdecl crt_io_c_stat_FUN_00607e64(char *filename,_stat *file_info);
int __cdecl crt_io_c_utime_FUN_00608160(char *filename,utimbuf *timestamps);
DWORD __cdecl crt_file_c___getfileattr_FUN_006082e0(char *filename);
int __cdecl crt_errno_c_convertWindowsErrorToErrno_FUN_00608390(DWORD windows_error);
DWORD __cdecl crt_errno_c___set_errno_FUN_006083fc(void);
int __cdecl crt_io_c_extend_file_for_append_FUN_00608410(int fd);
int __cdecl crt_io_c_write_FUN_006084ec(int fd,void *buffer,SIZE_T count);
uint __watcallStack crt_io_c_getFileTypeFlags_FUN_006088b0(int file_handle_index);
void __watcallStack crt_io_c_setFileDescriptorFlags_FUN_00608908(int file_handle_index,uint flags);
int __cdecl crt_io_c_CheckFileHandleAvailability_FUN_00608940(void);
int __cdecl crt_io_c_register_handle_FUN_00608990(HANDLE handle);
void crt_unknown_c_SetStdHandleToSomething_FUN_00608a1c(HANDLE param_1,uint param_2);
void __cdecl crt_io_c_invalidate_handle_FUN_00608af4(int handle_index);
int __cdecl crt_io_c_InitializeStandardHandles_FUN_00608b20(void);
HANDLE __cdecl crt_io_c_CreateFallbackHandle_FUN_00608b88(void);
void __cdecl crt_unknown_c_staticFinal_FUN_00608bb0(void);
filebuf * __watcallStack crt_fstream_cpp_filebuf_close_FUN_00608bcc(filebuf *this_ptr);
int __cdecl crt_fstream_cpp_filebuf_open_FUN_00608c15(filebuf *this_ptr,char *filename,int mode,int permissions);
int __watcallStack crt_stdio_c_stream_valid_FUN_00608cd1(_FILE *stream,int operation_type);
char * __cdecl crt_watcom_c_getcwd_FUN_00608d20(char *buffer,SIZE_T size);
void * __cdecl crt_memory_c___arrinit__FUN_00608dc8(void *array_start,int element_count,WatcomTypeInfo *type_info);
float10 __fpustack crt_math_c_atan2_FUN_00608e14(float10 y,float10 x);
int __cdecl crt_string_c__mbstrnicmp_FUN_00608e50(char *str1,char *str2,SIZE_T count);
void __cdecl crt_stdio_c_DetectDeviceAndSetBuffering_FUN_00608ee0(_FILE *file);
void __cdecl crt_ioinit_c_staticInit_FUN_00608f20(void);
void __cdecl crt_unknown_c_staticFinal_FUN_00608fc0(void);
int crt_unknown_c_FUN_00608fdc(int param_1);
int __cdecl crt_stdio_c_CreateFileVariadic_FUN_00609074(char *filename,int access_mode,int share_mode,...);
HANDLE __cdecl crt_stdio_c_CreateFileImpl_FUN_006090a0(char *filename,dword access_mode,dword share_mode,va_list_t *extra_args);
_FILE * __cdecl crt_stdio_c___allocfp_FUN_006092f0(int unused_param);
void __cdecl crt_stdio_c___freefp_FUN_006093b0(_FILE *file_handle);
void crt_unknown_c_FUN_006093e8(void);
void * __watcallRegister crt_heap_c_AllocateFromFreeList_FUN_00609410(ulong size,HeapBlock *free_block,ushort ds_segment);
void __watcallRegister crt_heap_c_CoalesceAndAddFreeBlock_FUN_006094c0(void *ptr,HeapBlock *heap_block,ushort segment);
HeapBlock * __cdecl crt_heap_c_InsertHeapBlockInOrder_FUN_006095f0(HeapBlock *new_block);
int __cdecl crt_heap_c_AllocateNewHeapBlock_FUN_00609668(uint size);
void * __cdecl crt_heap_c_SystemAllocWrapper_FUN_00609718(ulong size);
int __cdecl crt_heap_c_CalculateHeapBlockSize_FUN_0060972c(uint *pSize);
int __cdecl crt_heap_c_AllocatorFallbackStub_FUN_00609780(uint size);
ulong __cdecl crt_heap_c_GetBlockSize_FUN_00609790(void *ptr);
int __watcallRegister crt_heap_c_ResizeBlockInPlace_FUN_006097b8 (ushort segment,void *ptr,ulong new_size,ulong *pExtraNeeded);
void * __cdecl crt_heap_c_TryResizeInPlace_FUN_00609974(void *ptr,ulong new_size);
void __cdecl crt_process_c_getpid_FUN_006099c0(void);
char * __cdecl crt_io_c_getTempDirectory_FUN_00609afc(void);
int __cdecl crt_io_c_close_FUN_00609bd0(int fd);
void __cdecl crt_process_c_set_shell_execute_flag_FUN_00609c80(char *buffer);
int __watcallStack crt_process_c_spawnCommand_FUN_00609c90 (int mode,char *cmdPath,char *cmdName,char *args,void *envp,int *result);
void __cdecl crt_time_c_filetime_to_dos_datetime_FUN_00609cb0(FILETIME *filetime,WORD *dos_date,WORD *dos_time);
int __cdecl crt_io_c_findNextWithAttributes_FUN_00609d5c(HANDLE hFindFile,DWORD dwAttributeMask,LPWIN32_FIND_DATAA lpFindFileData);
time_t __cdecl crt_time_c_filetime_to_time_t_FUN_00609da0(FILETIME *filetime);
void __watcallRegister crt_startup_cpp_WinMainBootstrap_FUN_00609e70(void);
void crt_sync_c_criticalSectionStub_FUN_00609f20(void);
LPCRITICAL_SECTION __cdecl crt_sync_c_allocate_critical_section_FUN_00609f24(void);
void crt_unknown_c_FUN_00609fc8(void);
void crt_unknown_c_DeleteCritcalSectionsMaybe_FUN_00609ff4(void);
void __cdecl crt_sync_c_reset_reentrant_critical_section_state_FUN_0060a04c(ReentrantCriticalSection *rcs);
void __cdecl crt_sync_c_enter_reentrant_critical_section_FUN_0060a060(ReentrantCriticalSection *rcs);
void __cdecl crt_sync_c_leave_reentrant_critical_section_FUN_0060a0c4(ReentrantCriticalSection *rcs);
void __cdecl crt_sync_c_enter_global_critical_section_FUN_0060a0ec(void);
void __cdecl crt_sync_c_leave_global_critical_section_FUN_0060a0fc(void);
void __cdecl crt_tls_c_enter_critical_section_by_index_FUN_0060a10c(int sectionIndex);
void __cdecl crt_tls_c_leave_critical_section_by_index_FUN_0060a128(int sectionIndex);
int __cdecl crt_io_c_register_handle_wrapper_FUN_0060a144(HANDLE handle);
void __cdecl crt_io_c_invalidate_handle_wrapper_FUN_0060a154(int handle_index);
void __cdecl crt_sync_c_enter_global_memory_critical_section_FUN_0060a17c(void);
void __cdecl crt_sync_c_leave_global_memory_critical_section_FUN_0060a18c(void);
void __cdecl crt_sync_c_enter_global_thread_critical_section_FUN_0060a19c(void);
void __cdecl crt_sync_c_leave_global_thread_critical_section_FUN_0060a1ac(void);
void __cdecl crt_sync_c_enter_global_io_critical_section_FUN_0060a1bc(void);
void __cdecl crt_sync_c_leave_global_io_critical_section_FUN_0060a1cc(void);
void crt_unknown_c_FUN_0060a1dc(void);
void __cdecl crt_sync_c_leave_global_runtime_critical_section_FUN_0060a1ec(void);
LPVOID __cdecl crt_tls_c_get_thread_local_data_FUN_0060a1fc(void);
void * __cdecl crt_startup_cpp_GetOrCreateThreadData_FUN_0060a23c(void *pThreadData);
BOOL __cdecl crt_tls_c_allocate_tls_index_FUN_0060a27c(void);
BOOL __cdecl crt_tls_c_initialize_thread_tls_data_FUN_0060a2d8(void *init_param);
void __cdecl crt_tls_c_cleanup_thread_tls_data_FUN_0060a334(int shutdownMode);
void __cdecl crt_tls_c_shutdown_tls_infrastructure_FUN_0060a388(void);
void crt_unknown_c_FUN_0060a394(void);
void __cdecl crt_tls_c_initialize_tls_infrastructure_FUN_0060a3b4(void);
void __cdecl crt_unknown_c_staticFinal_FUN_0060a4cc(void);
DWORD __cdecl crt_startup_c_GetModuleFileNameCompat_FUN_0060a560(HMODULE hModule,LPWSTR lpFilename,DWORD nSize);
char * __cdecl crt_string_c_strdup_FUN_0060a610(char *str);
WCHAR * __watcallRegister crt_string_c_wcsdup_FUN_0060a660(WCHAR *str);
void __cdecl crt_memory_c___GetStackLimits_FUN_0060a6a0(ThreadData *pStackBound,uint *pHeapBound);
BOOL __cdecl crt_windows_c_has_active_window_FUN_0060a710(void);
void __cdecl crt_exception_c_FormatHexString_FUN_0060a748(char *dest,char *format,DWORD value);
long __cdecl crt_exception_c_TopLevelExceptionFilter_FUN_0060a7a4(_EXCEPTION_POINTERS *ExceptionInfo);
EXCEPTION_DISPOSITION __cdecl crt_exception_c_ExceptionHandler_FUN_0060a9d8(EXCEPTION_RECORD *ExceptionRecord,void *EstablisherFrame,CONTEXT *ContextRecord, void *DispatcherContext);
void __cdecl crt_exception_c_installExceptionHandler_FUN_0060aba8(ExceptionFrame *pExceptionFrame);
void __cdecl crt_exception_c_RemoveExceptionHandler_FUN_0060abf4(void);
void __cdecl crt_util_c_invokeRuntimeHandler_FUN_0060ac20(RUNTIME_HANDLER_FUNC **ppHandler);
void __cdecl crt_init_c_ProcessInitTermHandlers_FUN_0060ac30(int max_priority);
void __cdecl crt_exit_c_ProcessExitHandlers_FUN_0060ac88(uchar min_priority,uchar max_priority);
int __cdecl crt_stdio_c_WideCharToSingleByte_FUN_0060acf0(wchar_t wide_char,char *output_buffer);
void __cdecl crt_stdio_c_ReportFloatingPointNotLoaded_FUN_0060ad30(void);
char * __cdecl crt_stdlib_c_i64toa_FUN_0060ad40(longlong *value,char *buffer,int base);
char * crt_unknown_c_FUN_0060ade0(uint *param_1,char *param_2,int param_3);
char * __cdecl crt_stdlib_c_utoa_FUN_0060ae50(uint value,char *buffer,int base);
void __cdecl crt_startup_c_staticInit_FUN_0060aef4(void);
int __watcallStack crt_stdio_c_flushFileBuffers_FUN_0060af00(int file_handle_index);
undefined8 crt_unknown_c_FUN_0060af5d(int param_1,int *param_2,int param_3);
undefined4 crt_unknown_c_FUN_0060b07a(int *param_1);
char * crt_unknown_c_FUN_0060b0c8(char *param_1,int param_2);
void crt_unknown_c_FUN_0060b106 (undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4, undefined4 param_5);
void crt_unknown_c_FUN_0060b133(void);
void crt_unknown_c_FUN_0060b142 (undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4, undefined4 param_5);
void __cdecl crt_thread_c_noop_lock_FUN_0060b180(void);
ushort crt_unknown_c_FUN_0060b190(void);
int __watcallStack crt_locale_c_mbtowc_FUN_0060b1c0(wchar_t *wide_char,char *mb_string,SIZE_T max_bytes);
float __watcallRegister crt_math_c_doubleToFloat_FUN_0060b26c(double val);
ulonglong __watcallRegister crt_math_c_multiply64_FUN_0060b2b8(ulonglong a,ulonglong b);
int __watcallStack crt_stdio_c_DrainConsoleInputWithBuffering_FUN_0060b2e0(HANDLE hConsoleInput);
int crt_stdio_c_DrainConsoleInputAndSetup_FUN_0060b3f8(void);
int __watcallStack crt_stdio_c_WriteConsoleChar_FUN_0060b490(int character);
int __cdecl crt_debug_c_TriggerDebuggerBreak_FUN_0060b500(char *error_message,ushort flags);
void __cdecl crt_exit_c_ExitHookStub_FUN_0060b530(void);
void __cdecl crt_startup_c_ExitApplication_FUN_0060b534(int exit_code);
void __cdecl crt_exit_c_FinalExitHandler_FUN_0060b560(int exit_code);
void __cdecl crt_unknown_c_FUN_0060b586(byte *param_1,undefined8 *param_2);
double __watcallRegister crt_unknown_c_FUN_0060b5e8(uint param_1,uint param_2);
int __watcallStack crt_string_c_mbstring_termination_check_FUN_0060b630(char *str);
char * crt_unknown_c_FUN_0060b670(char *param_1,char *param_2,ulong param_3);
char * __watcallStack crt_string_c_mbstrncpy_core_FUN_0060b670(char *dest,char *src,int count);
void __watcallStack crt_stdio_c_storeErrorState_FUN_0060b78e(uint *destination,uint error_state);
_FILE * __cdecl crt_stdio_c_get_standard_file_handle_FUN_0060b7a0(int fd);
streambuf * __cdecl crt_iostream_cpp_streambuf_ctor_FUN_0060b7c2(streambuf *this_ptr);
void __watcallStack crt_strstream_cpp_strstreambuf_init_FUN_0060b815 (strstreambuf *this_ptr,char *buffer_ptr,int buffer_size,char *put_start);
void __watcallStack crt_iostream_cpp_streambuf_initBuffer_FUN_0060b815(streambuf *this_ptr,char *buffer_ptr);
int __watcallStack crt_iostream_cpp_streambuf_do_sgetn_FUN_0060b932 (streambuf *buffer,void *output_buffer,SIZE_T bytes_to_read);
int __watcallStack crt_stdio_c_closeUnsupported_FUN_0060b9b7(void);
int __watcallStack crt_strstream_cpp_strstreambuf_overflow_FUN_0060b9bd(strstreambuf *this_ptr,int character);
int __watcallStack crt_strstream_cpp_strstreambuf_underflow_FUN_0060ba25(strstreambuf *this_ptr);
strstreambuf * __watcallStack crt_strstream_cpp_strstreambuf_setbuf_FUN_0060ba70 (strstreambuf *this_ptr,char *ignored_buffer,int allocation_size);
int __watcallStack crt_strstream_cpp_strstreambuf_seekoff_FUN_0060ba80 (strstreambuf *this_ptr,int seek_distance,int seek_mode,int flags);
void __watcallStack crt_iostream_cpp_streambuf_seekoff_FUN_0060bb5f(streambuf *this_ptr,int off,int dir,int which);
int __watcallStack crt_strstream_cpp_strstreambuf_sync_FUN_0060bb7c(void);
strstreambuf * __cdecl crt_strstream_cpp_strstreambuf_dtor_FUN_0060bb7f(strstreambuf *this_ptr,uint flags);
strstreambuf * __cdecl crt_strstream_cpp_strstreambuf_ctor_FUN_0060bbf8(strstreambuf *this_ptr);
int __watcallStack crt_strstream_cpp_strstreambuf_doallocate_FUN_0060bc22(strstreambuf *this_ptr);
void __cdecl crt_iostream_cpp_ios_freeBufferChain_FUN_0060bdc0(ios *stream_ptr);
filebuf * __cdecl crt_fstream_cpp_filebuf_ctor_FUN_0060bddd(filebuf *this_ptr);
filebuf * __watcallStack crt_fstream_cpp_filebuf_dtor_FUN_0060bdf9(filebuf *this_ptr,uint flags);
void __cdecl crt_fpemu_c_staticInit_FUN_0060be80(void);
double __cdecl crt_math_c_set_math_errno_FUN_0060befa(int errorFlags,double *valuePtr);
double __cdecl crt_math_c_process_math_error_FUN_0060bf2d(int errorFlags,double *value1,double *value2);
double __mathinternal crt_math_c_handle_math_error_FUN_0060c02b(void);
int __cdecl crt_string_c_wcstombs_FUN_0060c0c0(char *dest,wchar_t *src,SIZE_T dest_size);
char * __cdecl crt_string_c_strpbrk_FUN_0060c190(char *str,char *char_set);
time_t __cdecl crt_time_c_dos_datetime_to_time_t_FUN_0060c1e0(WORD dos_date,WORD dos_time);
int __cdecl crt_stack_c_GetStackUsage_FUN_0060c260(void);
int __cdecl crt_io_c_IsSpecialDevice_FUN_0060c270(int handle_index);
int __cdecl crt_io_c_close_handle_safe_FUN_0060c2e0(int handle_index);
int __cdecl crt_fstream_cpp_convertModesAndOpenFile_FUN_0060c340(char *filename,int *iostream_mode,int permissions);
float10 __fpustack crt_math_c_atan2_FUN_0060c440(float10 y,float10 x);
float10 __watcallRegister crt_math_c_atan2_epilogue_FUN_0060c5a0(void);
float10 __watcallRegister crt_math_c_atan2_negate_epilogue_FUN_0060c5ab(void);
float10 __watcallRegister crt_math_c_atan2_pi_minus_epilogue_FUN_0060c5b8(void);
float10 __watcallRegister crt_math_c_atan2_minus_pi_epilogue_FUN_0060c5cb(void);
float10 __watcallRegister crt_math_c_atan2_pi_half_minus_epilogue_FUN_0060c5e0(void);
float10 __watcallRegister crt_math_c_atan2_minus_pi_half_epilogue_FUN_0060c5f3(void);
float10 __watcallRegister crt_math_c_atan2_pi_half_plus_epilogue_FUN_0060c608(void);
float10 __watcallRegister crt_math_c_atan2_minus_pi_half_minus_epilogue_FUN_0060c61b(void);
void crt_unknown_c_FUN_0060c640(ulong param_1);
void __cdecl crt_environ_c_staticInit_FUN_0060c650(void);
void __cdecl crt_environ_c_staticFinal_FUN_0060c73c(void);
int __cdecl crt_string_c_compare_mb_chars_ci_FUN_0060c790(char *str1,char *str2);
void __cdecl crt_io_c_ConvertAccessMode_FUN_0060c850(int access_mode,DWORD *desired_access,DWORD *share_mode);
void __cdecl crt_io_c_ConvertCreationDisposition_FUN_0060c894(DWORD mode_flags,DWORD *creation_disposition);
void __cdecl crt_heap_c_CompactHeapBlocks_FUN_0060c920(void);
int __cdecl crt_heap_c_VirtualFreeBlock_FUN_0060c95c(HeapBlock *block);
void __cdecl crt_heap_c_UnlinkAndFreeBlock_FUN_0060c9bc(HeapBlock *block);
int __watcallStack crt_io_c_access_FUN_0060c9f0(char *filename,int access_mode);
int __watcallStack crt_process_c_spawnvp_FUN_0060ca20(int mode,char *cmdname,char **argv);
void __cdecl crt_startup_c_PlaceholderStub_FUN_0060ca80(void);
void * __cdecl crt_memory_c_calloc_FUN_0060ca90(ulong count,ulong size);
LPVOID __watcallRegister crt_tls_c_create_thread_local_data_FUN_0060cac0(void);
void * __watcallRegister crt_tls_c_getThreadLocalData_FUN_0060caf8(void);
BOOL __cdecl crt_tls_c_register_thread_data_FUN_0060cbd0(void *tls_data,void *thread_param);
void __cdecl crt_tls_c_unregister_thread_data_FUN_0060cc3c(void *threadDataKey);
void crt_unknown_c_FUN_0060ccb4(void);
void __cdecl crt_thread_c_InitializeThreadContext_FUN_0060ccf0(ThreadData *pThreadData);
void crt_unknown_c_FUN_0060ccb4(void);
ulong __cdecl crt_string_c_wcslen_FUN_0060cd30(LPWSTR str);
void * __cdecl crt_string_c_memcpy_FUN_0060cd60(void *dest,void *src,SIZE_T count);
int __watcallStack crt_stdio_c_IsRelevantKeyEvent_FUN_0060cd90(_INPUT_RECORD *pInputRecord);
void __watcallRegister crt_stdio_c_InitializeConsoleHandles_FUN_0060cdbc(void);
HANDLE __watcallRegister crt_stdio_c_GetConsoleInputHandle_FUN_0060ce30(void);
HANDLE __cdecl crt_stdio_c_GetConsoleOutputHandle_FUN_0060ce3c(void);
void __cdecl crt_fpu_c_ClearFPUExceptions_FUN_0060ce50(void);
SIGNAL_HANDLER_TYPE __watcallStack crt_signal_c_setSignalHandler_FUN_0060ce60(int signal_number,SIGNAL_HANDLER_TYPE new_handler_type);
SIGNAL_HANDLER_TYPE __watcallStack crt_signal_c_getSignalHandler_FUN_0060ceb4(int signal_number);
SIGNAL_HANDLER_TYPE crt_unknown_c_FUN_0060ced8(int param_1);
BOOL __stdcall crt_signal_c_consoleCtrlHandler_FUN_0060cf20(DWORD dwCtrlType);
undefined4 crt_unknown_c_FUN_0060cf80(void);
BOOL __watcallRegister crt_signal_c_registerConsoleHandler_FUN_0060cfb8(void);
bool crt_signal_c_unregisterConsoleHandler_FUN_0060cfe4(void);
int __cdecl crt_signal_c_raiseFPE_FUN_0060d028(int fpe_code);
SIGNAL_HANDLER_TYPE crt_unknown_c_DoSomethingAndSetCtrlHandler_FUN_0060d068(int param_1,int param_2);
int __watcallStack crt_signal_c_processSignal_FUN_0060d128(int signal_number);
undefined2 crt_unknown_c_FUN_0060d1a8(void);
void crt_unknown_c_FUN_0060d1ec(void);
void __cdecl crt_thread_c_staticInit_FUN_0060d214(void);
int __cdecl crt_startup_c_FUN_0060d230(UINT cp);
ulonglong __watcallRegister crt_math_c_udivmod64_FUN_0060d3ed(ulonglong dividend,ulonglong divisor);
undefined1 * crt_unknown_c_FUN_0060d480(void);
undefined4 crt_unknown_c_FUN_0060d48c(void);
int __watcallStack crt_stdio_c_fgetc_buffered_FUN_0060d510(_FILE *stream);
uint crt_unknown_c_FUN_0060d576(_FILE *param_1);
streambuf * __watcallStack crt_iostream_cpp_streambuf_setbuf_FUN_0060d5ff (streambuf *this_ptr,void *buffer_start,int buffer_size);
streambuf * __watcallStack crt_iostream_cpp_streambuf_destructor_FUN_0060d64f(streambuf *this_ptr);
int __watcallStack crt_iostream_cpp_doallocate_FUN_0060d677(streambuf *this_ptr);
void __watcallStack crt_iostream_cpp_setBuffer_FUN_0060d6a8 (streambuf *this_ptr,void *new_buffer,void *buffer_end,int ownership_flag);
int __watcallStack crt_iostream_cpp_validateBufferSeek_FUN_0060d725 (int seek_distance,int whence,char *buffer_start,char *current_ptr,char *buffer_end1, char *buffer_end2);
void * __watcallStack crt_iostream_cpp_streambuf_allocBuffer_FUN_0060d790(uint size);
void __watcallStack crt_iostream_cpp_freeBuffer_FUN_0060d7a0(void *buffer);
int __watcallStack crt_fstream_cpp_filebuf_pbackfail_FUN_0060d7ae(filebuf *this_ptr,int character);
int __watcallStack crt_fstream_cpp_filebuf_overflow_FUN_0060d881(filebuf *this_ptr,int character);
int __watcallStack crt_fstream_cpp_filebuf_underflow_FUN_0060da87(filebuf *this_ptr);
streambuf * __watcallStack crt_fstream_cpp_filebuf_setbuf_FUN_0060db8c(filebuf *this_ptr,char *buffer_ptr,int buffer_size);
int __watcallStack crt_fstream_cpp_filebuf_seekoff_FUN_0060dbe8(filebuf *this_ptr,long offset,int direction,int mode);
int __watcallStack crt_fstream_cpp_filebuf_sync_FUN_0060dc5e(filebuf *this_ptr);
double crt_unknown_c_FUN_0060dcf6(void);
double __watcallRegister crt_math_c_dadd_FUN_0060defc(double a,double b);
double __watcallRegister crt_math_c_dmul_FUN_0060e0b9(double a,double b);
int crt_unknown_c_FUN_0060e256(void);
void __cdecl crt_math_c_print_error_message_FUN_0060e298(int errorType,char *errorData);
double __cdecl crt_math_c_report_math_error_FUN_0060e2e5(MathErrorContext *errorCtx);
char * __cdecl crt_string_c_char_in_set_FUN_0060e340(char *charset,wchar_t wc);
void __cdecl crt_io_c_parseFileInfo_FUN_0060e3b0(void);
undefined4 crt_unknown_c_FUN_0060e4f0(void);
void __cdecl crt_mbstring_c_copyMbChar_FUN_0060e590(char *dest,char *src);
char * crt_unknown_c_SomethingWithUppercaseCharacterConvert_FUN_0060e5d0(char *param_1);
int __cdecl crt_string_c_mbcmp_FUN_0060e640(char *str1,char *str2);
int __cdecl crt_process_c_spawnvp_with_path_search_FUN_0060e6a0(int mode,char *program,char **argv,char **envp);
undefined4 crt_unknown_c_ReturnZero6_FUN_0060e850(void);
void crt_unknown_c_FUN_0060e854 (undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4);
void crt_unknown_c_SomethingThatCallsExitThreadAfterCommunicate_FUN_0060e878(void);
void crt_unknown_c_CallReturnZero6_FUN_0060e880(undefined4 param_1);
void crt_unknown_c_FUN_0060e890(undefined4 *param_1,undefined4 *param_2,undefined4 *param_3);
uint crt_unknown_c_SomethingFPUControlWord_FUN_0060e8e0(uint param_1,uint param_2);
uint crt_unknown_c_ReadFileBytesMaybe_FUN_0060e930 (uint param_1,char *param_2,DWORD param_3,undefined4 param_4,undefined4 param_5, int param_6);
undefined8 crt_unknown_c_FUN_0060eb3a(void);
ulonglong __cdecl crt_unknown_c_FUN_0060eb4b(void);
ulonglong __cdecl crt_unknown_c_FUN_0060eb57(void);
int __watcallRegister crt_operation_c_always_zero_FUN_0060fa8b(void);
int __cdecl crt_stdio_c_fputs_FUN_0060ebb0(char *str,_FILE *file);
long __cdecl crt_stdlib_c_strtol_internal_FUN_0060ec70(char *str,char **endptr,int base,int is_signed);
ulong __cdecl crt_stdlib_c_strtoul_FUN_0060ede0(char *str,char **endptr,int base);
long __cdecl crt_stdlib_c_strtol_FUN_0060edfc(char *str,char **endptr,int base);
int __cdecl crt_stdlib_c_charToDigit_FUN_0060ee18(char ch);
int __cdecl crt_env_c_putenv_internal_FUN_0060ee80(char *envstr);
int __cdecl crt_env_c_updateEnvironTable_FUN_0060f04c(char *envstr);
int __cdecl crt_env_c_findEnvVar_FUN_0060f1f0(char *name,int delete_flag);
wchar_t __watcallStack crt_locale_c_toupper_multibyte_FUN_0060f300(char *mb_char,char *output_buffer);
BOOL __watcallStack crt_io_c_exists_FUN_0060f380(char *filename);
int __cdecl crt_process_c_spawnvp_FUN_0060f39c(int mode,char *cmdname,char **argv,char **envp);
int __cdecl crt_string_c_strlen_FUN_0060f870(char *str);
char * __cdecl crt_string_c_strchr_FUN_0060f890(char *str,int ch);
void __cdecl crt_thread_c_threadStartupWrapper_FUN_0060f8c0(ThreadStartupInfo *info);
HANDLE __cdecl crt_thread_c_create_thread_with_sync_FUN_0060f960(LPVOID thread_param,SIZE_T stack_size_hint,LPVOID sync_param, HANDLE *out_thread_handle);
void __cdecl crt_thread_c_exit_thread_FUN_0060fa58(void);
void __cdecl crt_unknown_c_FUN_0060fa80(void);
int __watcallRegister crt_operation_c_always_zero_FUN_0060fa8b(void);
int crt_unknown_c_FUN_0060fa90(char *param_1);
int crt_unknown_c_FUN_0060fac0(wchar_t *param_1,char *param_2,int param_3);
int crt_unknown_c_FUN_0060fb40(LPWSTR param_1);
undefined4 crt_unknown_c_FUN_0060fcf4(short *param_1);
int crt_unknown_c_FUN_0060fe94(short *param_1,int param_2);
wchar_t __watcallStack crt_locale_c_fullwidth_toupper_FUN_0060ffb0(wchar_t character);
char * __cdecl crt_process_c_build_file_info_env_FUN_0060ffd0(void);

