#pragma once

// Dependencies
#include "system/basetypes.h"
#include "system/dos.h"
#include "system/fstream.h"
#include "system/iostream.h"
#include "system/math.h"
#include "system/misc.h"
#include "system/signal.h"
#include "system/stat.h"
#include "system/stdarg.h"
#include "system/stdio.h"
#include "system/stdlib.h"
#include "system/strstream.h"
#include "system/time.h"
#include "system/utime.h"
#include "system/watcom.h"
#include "system/winbase.h"
#include "system/wincon.h"
#include "system/windef.h"
#include "system/winnt.h"

// =============================================================================
// FUNCTION PROTOTYPES - Range 0x600000
// =============================================================================

double crt_math_c_ldexp_FUN_00600002(double x, int exp);
int crt_stdio_c_string_getc_FUN_006000d0(scanf_state_t * state);
int crt_stdio_c_string_ungetc_FUN_006000f8(int ch, scanf_state_t * state);
int crt_stdio_c_vsscanf_FUN_00600100(char * str, char * format, va_list_t args);
int crt_stdio_c_sscanf_FUN_0060013c(char * str, char * format, ...);
double crt_math_c_acos_FUN_00600162(double x);
double crt_math_c_ceil_FUN_006001b2(double value);
time_t crt_time_c_time_with_rounding_FUN_006001f0(time_t * optional_output);
tm * crt_time_c_localtime_r_FUN_00600230(time_t * timer, tm * result);
tm * crt_time_c_localtime_FUN_00600288(time_t * timer);
void crt_stdio_c_formatTwoDigits_FUN_006002a0(char * buffer, int value);
uint crt_time_c_strftime_FUN_006002d4(char * dest_buffer, uint buffer_size, char * format_string, tm * time_ptr);
char * crt_string_c_strupr_FUN_00600770(char * string);
void crt_system_c_sleep_FUN_00600790(DWORD milliseconds);
int crt_stdio_c_fputc_FUN_006007a0(int character, FILE * file);
uint crt_watcom_c_memavl_FUN_006008f0(void);
undefined crt_watcom_c_memmax_FUN_00600940();
undefined crt_unknown_c_FUN_00600990();
undefined crt_unknown_c_FUN_00600a64();
undefined crt_watcom_c_heapchk_FUN_00600ad0();
float10 crt_math_c_asin_FUN_00600b94(float10 sine_value);
void * crt_memory_c_copyObjectArray_FUN_00600bc2(void * dest, void * source, int count, WatcomTypeInfo * type_info);
int crt_io_c_stat_thunk_00600c18(char * filename, stat * file_info);
int crt_io_c_utime_thunk_00600c1e(char * filename, utimbuf * timestamps);
DWORD crt_file_c_setReadonlyAttribute_FUN_00600c30(char * filename, DWORD file_attributes);
undefined crt_unknown_c_FUN_00600c80();
int crt_io_c_ftruncate_FUN_00600cf0(int file_handle, long new_size);
int crt_file_c_create_directory_FUN_00600e10(char * path);
int crt_stdio_c_fflush_FUN_00600e29(FILE * stream);
uint crt_stdio_c_clear_and_preserve_state_FUN_00600e64(FileEmbeddedData * embedded_data, uint error_code);
void crt_fstream_cpp_openFile_FUN_00600e85(ifstream * stream_obj, char * filename, int open_mode, SIZE_T buffer_size);
undefined crt_unknown_c_FUN_00600ee4();
char * crt_string_c_strncpy_FUN_00600f40(char * dest, char * src, SIZE_T count);
time_t crt_time_c_mktime_FUN_00600f80(tm * timeptr);
char * crt_io_c_realpath_FUN_00601140(char * buffer, char * path, SIZE_T buffer_size);
void * crt_memory_c_dispatchObjectArrayConstructor_FUN_00601200(void * array_ptr, int element_count, WatcomTypeInfo * type_info);
void * crt_memory_c_constructTypedObjectArray_FUN_00601232(void * dest, int element_count, WatcomTypeInfo * type_info);
undefined crt_unknown_c_AnotherFunctorCall2_FUN_00601258();
void * crt_memory_c_constructTypedObjectArray_FUN_00601272(void * array_memory, int element_count, WatcomTypeInfo * type_info);
char * crt_io_c_getcwd_wrapper_FUN_00608d20(char * buffer, SIZE_T size);
int crt_io_c_chdir_FUN_006012a0(char * path);
int crt_heap_c_heapCheckWrapper_FUN_006012c0(void * heap_state_ptr);
int crt_heap_c_heapWalk_FUN_006012d0(HeapState * heap_state_ptr, Heap * heap_ptr);
int crt_heap_c_heapCheck_FUN_00601374(void * heap_state_ptr);
float10 crt_math_c_atan2_FUN_006013b1(float10 y, float10 x);
char * crt_env_c_getenv_FUN_006013f0(char * name);
undefined crt_errno_c_errno_FUN_00601450();
char * crt_string_c_strerror_FUN_00601470(int errnum);
int crt_stdio_c_setvbuf_FUN_00601490(FILE * stream_ptr, char * buffer_ptr, int buffer_mode, SIZE_T buffer_size);
int crt_stdio_c_fflush_FUN_00601540(FILE * stream);
long crt_stdio_c_ftell_FUN_00601560(FILE * file_handle);
int crt_stdio_c_rename_FUN_006015d0(char * old_filename, char * new_filename);
undefined crt_cpp_c_handlePureVirtualCall_FUN_006015f1();
void crt_startup_c_notifyAbnormalTermination_FUN_00601620(void);
void crt_startup_c_reportAbnormalTermination_FUN_00601628(void);
void crt_time_c_formatTwoDigits_FUN_00601640(int number, int position, char * buffer);
char * crt_time_c_asctimeFormat_FUN_00601678(tm * timeptr, char * buffer);
char * crt_time_c_asctime_FUN_00601768(tm * timeptr);
int crt_stdio_c_OpenModeStringParser_FUN_006017d0(char * mode_string, char * output_flags);
FILE * crt_stdio_c_OpenFileAndInitialize_FUN_0060190c(char * filename, char mode_char, int parsed_mode_flags, int stage1_result, int additional_flags, FILE * file_struct);
FILE * crt_stdio_c_fopenWithFlags_FUN_00601a20(char * filename, char * mode, int flags);
FILE * crt_stdio_c_fopen_FUN_00601a7c(char * filename, char * mode);
undefined crt_unknown_c_MultipleDoNothingCalls_FUN_00601a94();
FILE * crt_stdio_c_fopenThreadSafe_FUN_00601b14(char * filename, char * mode, FILE * * output_file_ptr);
void * crt_memory_c_malloc_FUN_00601bb0(ulong size);
void * crt_heap_c_InternalHeapAlloc_FUN_00601bc0(ulong size);
void crt_memory_c_free_FUN_00601cd0(void * ptr);
void crt_heap_c_ValidateHeapIntegrity_FUN_00601ce0(void * ptr);
void * crt_memory_c_realloc_FUN_00601df0(void * ptr, ulong new_size);
void * crt_memory_c_realloc_implementation_FUN_00601e08(void * ptr, ulong new_size);
int crt_stdio_c_closeTrackedFile_FUN_00601ea0(FILE * file_handle);
int crt_stdio_c_closeAndDeallocateFile_FUN_00601ee4(FILE * file_handle, int close_flags);
char crt_string_c_hexDigitToChar_FUN_00601f0c(int digit);
void crt_io_c_generateTempFilename_FUN_00601f1c(char * buffer, int file_handle);
int crt_stdio_c_fclose_force_FUN_00601fd0(FILE * file_handle, int force_close_flag);
void * crt_memory_c_copyArrayWithFunction_FUN_006020c2(void * dest, void * source, int count, int element_size, void * copy_func);
int crt_string_c_stricmp_FUN_005fe7f0(char * str1, char * str2);
double crt_math_c_modf_FUN_00602102(double value, double * integer_part);
int crt_stdlib_c_system_FUN_00602130(char * command);
void crt_stdio_c_fprintf_FUN_006021c0(FILE * stream, char * format, ...);
void * crt_memory_c_malloc_FUN_006021da(SIZE_T size);
HANDLE crt_io_c_findFirstFileWrapper_FUN_006021f0(char * filespec, LPWIN32_FIND_DATAA find_data);
void crt_io_c_convertFileInfo_FUN_00602264(LPWIN32_FIND_DATAA win32_data, find_t * dos_info);
int crt_io_c_findNextFileWrapper_FUN_00602300(HANDLE find_handle, LPWIN32_FIND_DATAA find_data);
int crt_io_c_findCloseWrapper_FUN_00602380(HANDLE find_handle);
void entry(void);
void crt_unknown_c_staticInit_FUN_0060240e(void);
ThreadData * crt_thread_c_GetTLS_FUN_0060242c(void);
void crt_sync_c_CriticalSectionStub_FUN_00602434(void);
int crt_io_c_register_handler_wrapper_FUN_00602438(HANDLE file_handle);
void crt_io_c_invalidate_handle_wrapper_FUN_00602448(int handle_index);
undefined crt_sync_c_CriticalSectionStub_FUN_00602458();
void crt_startup_c_initialize_runtime_FUN_0060245c(HMODULE hModule, void * pThreadParam, int unused);
void crt_startup_cpp_InitializeWinAppRuntime_FUN_006026a8(void * pParam);
void crt_exit_c_ExitProcess_FUN_00602700(int exit_code);
void crt_unknown_c_staticFinal_FUN_00602748(void);
void crt_errno_c_setErrno_FUN_00602790(int error_code);
void crt_math_c_set_domain_error_errno_FUN_006027a0(void);
void crt_math_c_set_range_error_errno_FUN_006027ac(void);
void crt_errno_c_SetWindowsError_FUN_006027c8(DWORD windows_error_code);
void crt_stdio_c_InitializeFileBuffer_FUN_006027e0(FILE * file);
int crt_stdio_c_ReadFileWithDeviceAbstraction_FUN_00602880(int file_handle_index, void * buffer, int bytes_to_read);
int crt_stdio_c_FormatEngine_FUN_00602950(void * output_context, char * format, va_list_t args, OUTPUT_CALLBACK callback);
char * crt_stdio_c_ScanFormatSpec_FUN_00602d78(char * format, va_list_t * args, FormatSpec * spec_info);
char * crt_stdio_c_ParseFormatFlags_FUN_00602edc(char * format, FormatSpec * spec_info);
int crt_string_c_strlen_far_FUN_00602f4c(char * string_offset, ushort segment, int max_length);
int crt_stdio_c_WideStringToMultiByteLen_FUN_00602f7c(wchar_t * wide_string_offset, ushort segment, int max_chars);
void crt_stdio_c_FormatHexWithPadding_FUN_00602ff8(int value, char * buffer, int width);
void crt_stdio_c_FormatFixedPoint_FUN_0060305c(char * buffer, int fixed_point_value, FormatSpec * spec_info);
void crt_stdio_c_FloatingPointStub_FUN_00603160(char * buffer, va_list_t * args, FormatSpec * spec_info);
void crt_stdio_c_CalculateZeroPadding_FUN_0060317c(FormatSpec * spec_info);
void crt_stdio_c_FormatWideString_FUN_006031c0(wchar_t * wide_string_offset, ushort segment, FormatSpec * spec_info, OUTPUT_CALLBACK output_func);
char * crt_stdio_c_ConvertFormatSpec_FUN_00603238(char * output_buffer, va_list_t * args, FormatSpec * spec_info);
char * crt_string_c_strupr_FUN_0060389c(char * string);
int crt_stdio_c_write_FUN_006038c0(int file_handle_index, void * buffer, int bytes_to_write);
int crt_stdio_c_fflushInternal_FUN_006039d0(FILE * file_handle);
void crt_memory_c_OptimizedMemFill_FUN_00603b00(void * dest, uint replicated_value, uint count);
void crt_memory_c_BulkDwordFill_FUN_00603b37(void * dest, uint replicated_value, uint dword_count);
void crt_strtod_c_staticInit_FUN_00603bb0(void);
undefined crt_unknown_c_FUN_00603bc9();
undefined crt_unknown_c_FUN_00603bf5();
undefined crt_unknown_c_FUN_00603c74();
undefined crt_unknown_c_CondCallDoNothing_FUN_00603ccc();
undefined crt_unknown_c_FUN_00603d60();
undefined crt_unknown_c_FUN_00603dc8();
undefined crt_unknown_c_FUN_0060403f();
undefined crt_unknown_c_FUN_006040d7();
undefined crt_unknown_c_FUN_006040ed();
undefined crt_unknown_c_FUN_00604104();
undefined crt_unknown_c_FUN_0060411c();
undefined crt_unknown_c_FUN_00604267();
undefined crt_unknown_c_FUN_0060445e();
undefined crt_unknown_c_FUN_00604478();
undefined crt_unknown_c_thunk_FUN_0060b142();
undefined crt_stdio_c_reportCPPFloatingPointSupportProblem_FUN_0060477f();
undefined crt_unknown_c_FUN_006047a4();
void crt_fpu_c_staticInit_FUN_006047e0(void);
undefined crt_unknown_c_FUN_00604824();
void crt_stdio_c_OutputCallback_FUN_00604830(FORMAT_OUTPUT_CONTEXT * context, int character);
int crt_stdio_c_vfprintf_FUN_00604850(FILE * file, char * format, va_list_t args);
int crt_stdio_c_scanf_getc_wrapper_FUN_00604930(scanf_state_t * state);
int crt_stdio_c_scanf_ungetc_wrapper_FUN_0060493c(int character, scanf_state_t * state);
int crt_stdio_c_doscan_FUN_00604950(scanf_state_t * state, char * * format_ptr, va_list_t * args);
char * crt_stdio_c_parse_format_spec_FUN_00604c1c(char * format_ptr, scanf_state_t * state);
int crt_stdio_c_skip_whitespace_FUN_00604d18(scanf_state_t * state);
int crt_stdio_c_scanf_char_FUN_00604d54(scanf_state_t * state, va_list_t * args);
int crt_stdio_c_scanf_string_FUN_00604e4c(scanf_state_t * state, va_list_t * args);
void crt_stdio_c_store_count_FUN_00604fb0(scanf_state_t * state, va_list_t * args, int chars_consumed);
undefined crt_unknown_c_FUN_0060501c();
int crt_stdio_c_scanf_scanset_FUN_00605064(scanf_state_t * state, va_list_t * args, char * * format_ptr);
int crt_stdio_c_scanf_float_FUN_00605178(scanf_state_t * state, va_list_t * args);
int crt_stdio_c_scanf_integer_FUN_0060547c(scanf_state_t * state, va_list_t * args, int base, int is_signed);
int crt_stdio_c_char_to_digit_FUN_006058e8(int ch);
int crt_stdio_c_scanf_getc_with_width_FUN_00605918(scanf_state_t * state);
undefined crt_unknown_c_FUN_00605950();
int crt_stdio_c_FlushFilesByMask_FUN_0060595c(uint file_mode_mask);
undefined crt_stdio_c_SetupConsoleInputMode_FUN_006059b0();
wchar_t crt_string_c_mbtowc_peek_FUN_006059e0(char * str);
void crt_locale_c_wchar_to_bytes_FUN_00605a20(wchar_t character, char * output_buffer);
int crt_locale_c_mblen_FUN_00605a40(char * mb_string);
char * crt_string_c_mbtowc_next_FUN_00605a70(char * str);
char * crt_string_c_mb_get_last_char_FUN_00605aa0(char * start, char * end);
void crt_cpp_c_reportPureVirtualError_FUN_00605b23(char * error_message, int exit_code);
void crt_unknown_c_staticFinal_FUN_00605b62(void);
void crt_stdlib_c_atexitRegisterNode_FUN_00605b89(WatcomStaticDestructorNode * node_ptr);
int crt_string_c_parseFloatString_FUN_00605b9b(char * str, void * result, char * * endptr);
double crt_string_c_strtod_main_FUN_00605d5d(char * str, char * * endptr);
int crt_string_c_mbstrnlen_FUN_00605e50(char * str, int max_bytes);
char * crt_string_c_mbstrncpy_FUN_00605e90(char * dest, char * src, int char_count);
int crt_string_c_mbstrnbytes_FUN_00605ec0(char * str, int char_count);
int crt_stdio_c_stream_setup_FUN_00605f20(FILE * stream, int operation_type);
FILE * crt_stdio_c_fgetcInternal_FUN_00605fad(FILE * stream, byte * output_byte);
void crt_stdio_c_reportStreamError_FUN_00606020(FileEmbeddedData * embedded_data, uint error_flags);
bool crt_stdio_c_prepare_stream_for_write_FUN_00606055(FILE * stream);
FILE * crt_stdio_c_stream_flush_FUN_006060bb(FILE * stream);
strstreambase * crt_strstream_cpp_strstreambase_constructor_FUN_006060fe(strstreambase * this_ptr, int ctor_flags, char * buffer, int size, char * pstart);
void crt_strstream_cpp_strstreambase_destructor_thunk_FUN_0060618a(ios * this_ptr, int dtor_flags);
ostream * crt_iostream_cpp_ostream_ctor_FUN_006061a2(ostream * this_ptr, uint c1);
void crt_iostream_cpp_ostream_destructor_thunk_FUN_006061e4(ios * this_ptr, int dtor_flags);
ios * crt_iostream_cpp_ios_ctor_FUN_006061fc(ios * this_ptr);
ostream * crt_iostream_cpp_ostream_dtor_FUN_00606231(ostream * this_ptr, uint d1, uint d2);
strstreambase * crt_strstream_cpp_strstreambase_dtor_FUN_006062a6(strstreambase * this_ptr, uint d1, uint d2, uint d3);
ios * crt_iostream_cpp_ios_dtor_FUN_0060632c(ios * this_ptr, uint d1, uint d2);
istream * crt_iostream_cpp_istream_ctor_FUN_00606376(istream * this_ptr, uint c1);
void crt_iostream_cpp_istream_destructor_thunk_from_ios_FUN_006063c9(ios * this_ptr, int dtor_flags);
istream * crt_iostream_cpp_istream_dtor_FUN_006063e1(istream * this_ptr, uint d1, uint d2);
void crt_fstream_cpp_fstreambase_constructor_FUN_00606456(fstreambase * this_ptr, int ctor_flags, int fd, int mode, char * buffer, SIZE_T buffer_size);
void crt_fstream_cpp_fstream_destructor_thunk_from_ios_FUN_006064f1(ios * this_ptr, int dtor_flags);
fstreambase * crt_fstream_cpp_fstreambase_dtor_FUN_00606509(fstreambase * this_ptr, uint d1, uint d2, uint d3);
fstreambase * crt_fstream_cpp_fstreambase_ctor_FUN_0060658f(fstreambase * this_ptr, uint c1);
int crt_stdio_c_remove_FUN_00606600(char * filename);
void crt_startup_c_WriteErrorAndExit_FUN_00606620(char * error_message, int exit_code);
void crt_startup_c_HandleRuntimeError_FUN_00606660(char * error_message, int error_level);
int crt_stdio_c_lseek_FUN_00606690(int file_handle_index, long distance_to_move, int move_method);
long crt_io_c_tell_FUN_00606720(int file_handle_index);
int crt_iostream_cpp_streambuf_do_sputn_FUN_00606780(streambuf * buffer, void * input_buffer, SIZE_T bytes_to_write);
double crt_math_c_math_domain_error_FUN_00606832(double x, double y, uchar error_type);
float10 crt_math_c_exp_FUN_006068e2(float10 x);
float10 crt_math_c_fdiv_FUN_00606960(float10 dividend, float10 divisor);
void crt_math_c_function_dispatch_FUN_00606a77(int function_index);
float10 crt_math_c_generate_nan_FUN_00606a81(void);
void crt_math_c_fatal_math_error_FUN_00606a87(void);
float10 crt_math_c_generate_nan_FUN_00606a8c(void);
void crt_math_c_fatal_math_error_FUN_00606a92(void);
float10 crt_math_c_generate_nan_FUN_00606a97(void);
float10 crt_math_c_generate_nan_FUN_00606a9d(void);
float10 crt_math_c_generate_nan_FUN_00606aa3(void);
float10 crt_math_c_generate_nan_FUN_00606aa9(void);
float10 crt_math_c_dispatch_divide_FUN_00606aaf(void);
undefined crt_math_c_FUN_00606acb();
undefined crt_math_c_FUN_00606ad0();
undefined crt_math_c_FUN_00606ae6();
float10 crt_math_c_fdiv_thunk_FUN_00606aeb(void);
undefined crt_math_c_FUN_00606b07();
float10 crt_math_c_fdiv_thunk_FUN_00606b17(void);
undefined crt_math_c_FUN_00606b2b();
undefined crt_math_c_FUN_00606b3b();
undefined crt_math_c_FUN_00606b5b();
undefined crt_math_c_FUN_00606b60();
undefined crt_math_c_FUN_00606b7a();
float10 crt_math_c_fdiv_thunk_FUN_00606b7f(void);
undefined crt_math_c_FUN_00606b9f();
float10 crt_math_c_fdiv_thunk_FUN_00606bb3(void);
undefined crt_math_c_FUN_00606bcb();
undefined crt_math_c_FUN_00606bdf();
undefined crt_math_c_FUN_00606bff();
undefined crt_math_c_FUN_00606c04();
undefined crt_math_c_FUN_00606c1e();
undefined crt_math_c_FUN_00606c23();
undefined crt_math_c_FUN_00606c43();
undefined crt_math_c_FUN_00606c57();
undefined crt_math_c_FUN_00606c6f();
undefined crt_math_c_FUN_00606c83();
undefined crt_math_c_FUN_00606ca3();
undefined crt_math_c_FUN_00606ca8();
undefined crt_math_c_FUN_00606cc2();
float10 crt_math_c_fdiv_thunk_FUN_00606cc7(void);
undefined crt_math_c_FUN_00606ce7();
float10 crt_math_c_fdiv_thunk_FUN_00606cfb(void);
undefined crt_math_c_FUN_00606d13();
undefined crt_math_c_FUN_00606d27();
undefined crt_math_c_FUN_00606d47();
undefined crt_math_c_FUN_00606d4c();
undefined crt_math_c_FUN_00606d66();
float10 crt_math_c_fdiv_thunk_FUN_00606d6b(void);
undefined crt_math_c_FUN_00606d8b();
float10 crt_math_c_fdiv_thunk_FUN_00606d9f(void);
undefined crt_math_c_FUN_00606db7();
undefined crt_math_c_FUN_00606dcb();
undefined crt_math_c_FUN_00606deb();
undefined crt_math_c_FUN_00606df0();
undefined crt_math_c_FUN_00606e0a();
float10 crt_math_c_fdiv_thunk_FUN_00606e0f(void);
undefined crt_math_c_FUN_00606e2f();
float10 crt_math_c_fdiv_thunk_FUN_00606e43(void);
undefined crt_math_c_FUN_00606e5b();
undefined crt_math_c_FUN_00606e6f();
undefined crt_math_c_FUN_00606e8f();
undefined crt_math_c_FUN_00606e94();
undefined crt_math_c_FUN_00606eae();
undefined crt_math_c_FUN_00606eb3();
undefined crt_math_c_FUN_00606ed3();
float10 crt_math_c_fdiv_thunk_FUN_00606ee7(void);
undefined crt_math_c_FUN_00606eff();
float10 crt_math_c_pentiumFdivpWorkaround_FUN_00606f13(float10 dividend, float10 divisor);
float10 crt_math_c_pentiumFdivBugWorkaroundDouble_FUN_00606f98(float10 param0, double param1);
undefined crt_unknown_c_FUN_00607080();
double crt_math_c_sqrt_FUN_0060710c(double value);
void crt_time_c_get_local_time_FUN_00607150(tm * tm_output);
void crt_time_c_tzset_FUN_006072f8(void);
char * crt_string_c_parse_uint_FUN_00607318(char * str, int * result);
char * crt_time_c_parse_timezone_spec_FUN_00607348(char * tz_string, char * name_buffer, int * offset_seconds);
char * crt_time_c_parse_dst_rule_FUN_00607464(char * rule_string, dst_rule * rule);
void crt_time_c_parse_tz_string_FUN_0060756c(char * tz_string);
undefined crt_time_c_gmtime_r_FUN_00607690(time_t days, time_t seconds, time_t timezone_offset, undefined1 result);
int crt_time_c_is_leap_year_FUN_00607820(int year);
undefined crt_unknown_c_FUN_00607858();
undefined crt_unknown_c_FUN_00607958();
int crt_time_c_determine_dst_status_FUN_006079b4(tm * timeptr);
undefined crt_unknown_c_FUN_00607c88();
char * crt_stdlib_c_itoa_FUN_00607cc0(int value, char * buffer, int base);
char * crt_stdio_c_IntegerToString_FUN_00607d18(int value, char * buffer, int base);
uint crt_io_c_analyze_file_type_FUN_00607d50(uint open_flags, char * filename);
int crt_io_c_stat_FUN_00607e64(char * filename, stat * file_info);
int crt_io_c_utime_FUN_00608160(char * filename, utimbuf * timestamps);
DWORD crt_file_c_get_file_attributes_FUN_006082e0(char * filename);
int crt_errno_c_convertWindowsErrorToErrno_FUN_00608390(DWORD windows_error);
DWORD crt_errno_c_getLastErrorAndSetErrno_FUN_006083fc(void);
int crt_io_c_extend_file_for_append_FUN_00608410(int fd);
int crt_io_c_write_FUN_006084ec(int fd, void * buffer, SIZE_T count);
uint crt_io_c_getFileTypeFlags_FUN_006088b0(int file_handle_index);
void crt_io_c_setFileDescriptorFlags_FUN_00608908(int file_handle_index, uint flags);
int crt_io_c_CheckFileHandleAvailability_FUN_00608940(void);
int crt_io_c_register_handle_FUN_00608990(HANDLE handle);
undefined crt_unknown_c_SetStdHandleToSomething_FUN_00608a1c();
void crt_io_c_invalidate_handle_FUN_00608af4(int handle_index);
int crt_io_c_InitializeStandardHandles_FUN_00608b20(void);
HANDLE crt_io_c_CreateFallbackHandle_FUN_00608b88(void);
void crt_unknown_c_staticFinal_FUN_00608bb0(void);
filebuf * crt_fstream_cpp_filebuf_close_FUN_00608bcc(filebuf * this_ptr);
int crt_fstream_cpp_filebuf_open_FUN_00608c15(filebuf * this_ptr, char * filename, int mode, int permissions);
int crt_stdio_c_stream_valid_FUN_00608cd1(FILE * stream, int operation_type);
char * crt_io_c_getcwd_FUN_00608d20(char * buffer, SIZE_T size);
void * crt_memory_c_constructObjectArray_FlaggedCtor_FUN_00608dc8(void * array_start, int element_count, WatcomTypeInfo * type_info);
undefined crt_unknown_c_FUN_00608e14();
int crt_string_c_mbstrnicmp_FUN_00608e50(char * str1, char * str2, SIZE_T count);
void crt_stdio_c_DetectDeviceAndSetBuffering_FUN_00608ee0(FILE * file);
void crt_ioinit_c_staticInit_FUN_00608f20(void);
void crt_unknown_c_staticFinal_FUN_00608fc0(void);
undefined crt_unknown_c_FUN_00608fdc();
int crt_stdio_c_CreateFileVariadic_FUN_00609074(char * filename, int access_mode, int share_mode, ...);
HANDLE crt_stdio_c_CreateFileImpl_FUN_006090a0(char * filename, dword access_mode, dword share_mode, va_list_t * extra_args);
FILE * crt_stdio_c_AllocateFileStruct_FUN_006092f0(int unused_param);
void crt_stdio_c_DeallocateFileStruct_FUN_006093b0(FILE * file_struct);
undefined crt_unknown_c_FUN_006093e8();
void * crt_heap_c_AllocateFromFreeList_FUN_00609410(ulong size, HeapBlock * free_block, ushort ds_segment);
void crt_heap_c_CoalesceAndAddFreeBlock_FUN_006094c0(void * ptr, HeapBlock * heap_block, ushort segment);
HeapBlock * crt_heap_c_InsertHeapBlockInOrder_FUN_006095f0(HeapBlock * new_block);
int crt_heap_c_AllocateNewHeapBlock_FUN_00609668(uint size);
void * crt_heap_c_SystemAllocWrapper_FUN_00609718(ulong size);
int crt_heap_c_CalculateHeapBlockSize_FUN_0060972c(uint * pSize);
int crt_heap_c_AllocatorFallbackStub_FUN_00609780(uint size);
ulong crt_heap_c_GetBlockSize_FUN_00609790(void * ptr);
int crt_heap_c_ResizeBlockInPlace_FUN_006097b8(ushort segment, void * ptr, ulong new_size, ulong * pExtraNeeded);
void * crt_heap_c_TryResizeInPlace_FUN_00609974(void * ptr, ulong new_size);
undefined crt_process_c_getpid_FUN_006099c0(void);
undefined crt_io_c_getTempDirectory_FUN_00609afc();
int crt_io_c_close_FUN_00609bd0(int fd);
void crt_process_c_set_shell_execute_flag_FUN_00609c80(char * buffer);
int crt_process_c_spawnCommand_FUN_00609c90(int mode, char * cmdPath, char * cmdName, char * args, void * envp, int * result);
void crt_time_c_filetime_to_dos_datetime_FUN_00609cb0(FILETIME * filetime, WORD * dos_date, WORD * dos_time);
int crt_io_c_findNextWithAttributes_FUN_00609d5c(HANDLE hFindFile, DWORD dwAttributeMask, LPWIN32_FIND_DATAA lpFindFileData);
time_t crt_time_c_filetime_to_time_t_FUN_00609da0(FILETIME * filetime);
void crt_startup_cpp_WinMainBootstrap_FUN_00609e70(void);
undefined crt_sync_c_criticalSectionStub_FUN_00609f20();
LPCRITICAL_SECTION crt_sync_c_allocate_critical_section_FUN_00609f24(void);
undefined crt_unknown_c_FUN_00609fc8();
undefined crt_unknown_c_DeleteCritcalSectionsMaybe_FUN_00609ff4();
void crt_sync_c_reset_reentrant_critical_section_state_FUN_0060a04c(ReentrantCriticalSection * rcs);
void crt_sync_c_enter_reentrant_critical_section_FUN_0060a060(ReentrantCriticalSection * rcs);
void crt_sync_c_leave_reentrant_critical_section_FUN_0060a0c4(ReentrantCriticalSection * rcs);
void crt_sync_c_enter_global_critical_section_FUN_0060a0ec(void);
void crt_sync_c_leave_global_critical_section_FUN_0060a0fc(void);
void crt_tls_c_enter_critical_section_by_index_FUN_0060a10c(int sectionIndex);
void crt_tls_c_leave_critical_section_by_index_FUN_0060a128(int sectionIndex);
int crt_io_c_register_handle_wrapper_FUN_0060a144(HANDLE handle);
void crt_io_c_invalidate_handle_wrapper_FUN_0060a154(int handle_index);
void crt_sync_c_enter_global_memory_critical_section_FUN_0060a17c(void);
void crt_sync_c_leave_global_memory_critical_section_FUN_0060a18c(void);
void crt_sync_c_enter_global_thread_critical_section_FUN_0060a19c(void);
void crt_sync_c_leave_global_thread_critical_section_FUN_0060a1ac(void);
void crt_sync_c_enter_global_io_critical_section_FUN_0060a1bc(void);
undefined crt_sync_c_leave_global_io_critical_section_FUN_0060a1cc();
undefined crt_unknown_c_FUN_0060a1dc();
void crt_sync_c_leave_global_runtime_critical_section_FUN_0060a1ec(void);
LPVOID crt_tls_c_get_thread_local_data_FUN_0060a1fc(void);
void * crt_startup_cpp_GetOrCreateThreadData_FUN_0060a23c(void * pThreadData);
BOOL crt_tls_c_allocate_tls_index_FUN_0060a27c(void);
BOOL crt_tls_c_initialize_thread_tls_data_FUN_0060a2d8(void * init_param);
void crt_tls_c_cleanup_thread_tls_data_FUN_0060a334(int shutdownMode);
BOOL crt_tls_c_shutdown_tls_infrastructure_FUN_0060a388(void);
undefined crt_unknown_c_FUN_0060a394();
void crt_tls_c_initialize_tls_infrastructure_FUN_0060a3b4(void);
void crt_unknown_c_staticFinal_FUN_0060a4cc(void);
DWORD crt_startup_c_GetModuleFileNameCompat_FUN_0060a560(HMODULE hModule, LPWSTR lpFilename, DWORD nSize);
char * crt_string_c_strdup_FUN_0060a610(char * str);
WCHAR * crt_string_c_wcsdup_FUN_0060a660(WCHAR * str);
void crt_memory_c_GetMemoryBounds_FUN_0060a6a0(ThreadData * pStackBound, uint * pHeapBound);
BOOL crt_windows_c_has_active_window_FUN_0060a710(void);
void crt_exception_c_FormatHexString_FUN_0060a748(char * dest, char * format, DWORD value);
long crt_exception_c_TopLevelExceptionFilter_FUN_0060a7a4(_EXCEPTION_POINTERS * ExceptionInfo);
EXCEPTION_DISPOSITION crt_exception_c_ExceptionHandler_FUN_0060a9d8(EXCEPTION_RECORD * ExceptionRecord, void * EstablisherFrame, CONTEXT * ContextRecord, void * DispatcherContext);
void crt_exception_c_installExceptionHandler_FUN_0060aba8(ExceptionFrame * pExceptionFrame);
void crt_exception_c_RemoveExceptionHandler_FUN_0060abf4(void);
void crt_util_c_invokeRuntimeHandler_FUN_0060ac20(RUNTIME_HANDLER_FUNC * * ppHandler);
void crt_init_c_ProcessInitTermHandlers_FUN_0060ac30(int max_priority);
void crt_exit_c_ProcessExitHandlers_FUN_0060ac88(uchar min_priority, uchar max_priority);
int crt_stdio_c_WideCharToSingleByte_FUN_0060acf0(wchar_t wide_char, char * output_buffer);
void crt_stdio_c_ReportFloatingPointNotLoaded_FUN_0060ad30(void);
char * crt_stdlib_c_i64toa_FUN_0060ad40(longlong * value, char * buffer, int base);
undefined crt_unknown_c_FUN_0060ade0();
char * crt_stdlib_c_utoa_FUN_0060ae50(uint value, char * buffer, int base);
void crt_startup_c_staticInit_FUN_0060aef4(void);
int crt_stdio_c_flushFileBuffers_FUN_0060af00(int file_handle_index);
undefined crt_unknown_c_FUN_0060af5d();
undefined crt_unknown_c_FUN_0060b07a();
undefined crt_unknown_c_FUN_0060b0c8();
undefined crt_unknown_c_FUN_0060b106();
undefined crt_unknown_c_FUN_0060b133();
undefined crt_unknown_c_FUN_0060b142();
undefined crt_thread_c_noop_lock_FUN_0060b180();
undefined crt_unknown_c_FUN_0060b190();
int crt_locale_c_mbtowc_FUN_0060b1c0(wchar_t * wide_char, char * mb_string, SIZE_T max_bytes);
float crt_math_c_doubleToFloat_FUN_0060b26c(double val);
ulonglong crt_math_c_multiply64_FUN_0060b2b8(ulonglong a, ulonglong b);
int crt_stdio_c_DrainConsoleInputWithBuffering_FUN_0060b2e0(HANDLE hConsoleInput);
undefined crt_stdio_c_DrainConsoleInputAndSetup_FUN_0060b3f8();
int crt_stdio_c_WriteConsoleChar_FUN_0060b490(int character);
int crt_debug_c_TriggerDebuggerBreak_FUN_0060b500(char * error_message, ushort flags);
undefined crt_exit_c_ExitHookStub_FUN_0060b530();
void crt_startup_c_ExitApplication_FUN_0060b534(int exit_code);
void crt_exit_c_FinalExitHandler_FUN_0060b560(int exit_code);
undefined crt_unknown_c_FUN_0060b586();
undefined crt_unknown_c_FUN_0060b5e8();
int crt_string_c_mbstring_termination_check_FUN_0060b630(char * str);
undefined crt_unknown_c_FUN_0060b670();
char * crt_string_c_mbstrncpy_core_FUN_0060b670(char * dest, char * src, int count);
void crt_stdio_c_storeErrorState_FUN_0060b78e(uint * destination, uint error_state);
FILE * crt_stdio_c_get_standard_file_handle_FUN_0060b7a0(int fd);
streambuf * crt_iostream_cpp_streambuf_constructor_FUN_0060b7c2(streambuf * this_ptr);
void crt_strstream_cpp_strstreambuf_init_FUN_0060b815(strstreambuf * this_ptr, char * buffer_ptr, int buffer_size, char * put_start);
void crt_iostream_cpp_streambuf_initBuffer_FUN_0060b815(streambuf * this_ptr, char * buffer_ptr, int buffer_size, char * put_start);
int crt_iostream_cpp_streambuf_do_sgetn_FUN_0060b932(streambuf * buffer, void * output_buffer, SIZE_T bytes_to_read);
int crt_stdio_c_closeUnsupported_FUN_0060b9b7(void);
int crt_strstream_cpp_strstreambuf_overflow_FUN_0060b9bd(strstreambuf * this_ptr, int character);
int crt_strstream_cpp_strstreambuf_underflow_FUN_0060ba25(strstreambuf * this_ptr);
strstreambuf * crt_strstream_cpp_strstreambuf_setbuf_FUN_0060ba70(strstreambuf * this_ptr, char * ignored_buffer, int allocation_size);
int crt_strstream_cpp_strstreambuf_seekoff_FUN_0060ba80(strstreambuf * this_ptr, int seek_distance, int seek_mode, int flags);
void crt_iostream_cpp_streambuf_seekoff_FUN_0060bb5f(streambuf * this_ptr, int off, int dir, int which);
int crt_strstream_cpp_strstreambuf_sync_FUN_0060bb7c(void);
strstreambuf * crt_strstream_cpp_strstreambuf_dtor_FUN_0060bb7f(strstreambuf * this_ptr, uint d1);
strstreambuf * crt_strstream_cpp_strstreambuf_ctor_FUN_0060bbf8(strstreambuf * this_ptr);
int crt_strstream_cpp_strstreambuf_doallocate_FUN_0060bc22(strstreambuf * this_ptr);
void crt_iostream_cpp_ios_freeBufferChain_FUN_0060bdc0(ios * stream_ptr);
filebuf * crt_fstream_cpp_filebuf_ctor_FUN_0060bddd(filebuf * this_ptr);
filebuf * crt_fstream_cpp_filebuf_dtor_FUN_0060bdf9(filebuf * this_ptr, uint d1, uint d2, uint d3);
void crt_fpemu_c_staticInit_FUN_0060be80(void);
double crt_math_c_set_math_errno_FUN_0060befa(int errorFlags, double * valuePtr);
double crt_math_c_process_math_error_FUN_0060bf2d(int errorFlags, double * value1, double * value2);
double crt_math_c_handle_math_error_FUN_0060c02b(void);
int crt_string_c_wcstombs_FUN_0060c0c0(char * dest, wchar_t * src, SIZE_T dest_size);
char * crt_string_c_strpbrk_FUN_0060c190(char * str, char * char_set);
time_t crt_time_c_dos_datetime_to_time_t_FUN_0060c1e0(WORD dos_date, WORD dos_time);
int crt_stack_c_GetStackUsage_FUN_0060c260(void);
int crt_io_c_IsSpecialDevice_FUN_0060c270(int handle_index);
int crt_io_c_close_handle_safe_FUN_0060c2e0(int handle_index);
int crt_fstream_cpp_convertModesAndOpenFile_FUN_0060c340(char * filename, int * iostream_mode, int permissions);
float10 crt_math_c_atan2_FUN_0060c440(float10 y, float10 x);
float10 crt_math_c_atan2_epilogue_FUN_0060c5a0(void);
float10 crt_math_c_atan2_negate_epilogue_FUN_0060c5ab(void);
float10 crt_math_c_atan2_pi_minus_epilogue_FUN_0060c5b8(void);
float10 crt_math_c_atan2_minus_pi_epilogue_FUN_0060c5cb(void);
float10 crt_math_c_atan2_pi_half_minus_epilogue_FUN_0060c5e0(void);
float10 crt_math_c_atan2_minus_pi_half_epilogue_FUN_0060c5f3(void);
float10 crt_math_c_atan2_pi_half_plus_epilogue_FUN_0060c608(void);
float10 crt_math_c_atan2_minus_pi_half_minus_epilogue_FUN_0060c61b(void);
undefined crt_unknown_c_FUN_0060c640();
void crt_environ_c_staticInit_FUN_0060c650(void);
void crt_environ_c_staticFinal_FUN_0060c73c(void);
int crt_string_c_compare_mb_chars_ci_FUN_0060c790(char * str1, char * str2);
void crt_io_c_ConvertAccessMode_FUN_0060c850(int access_mode, DWORD * desired_access, DWORD * share_mode);
void crt_io_c_ConvertCreationDisposition_FUN_0060c894(DWORD mode_flags, DWORD * creation_disposition);
void crt_heap_c_CompactHeapBlocks_FUN_0060c920(void);
int crt_heap_c_VirtualFreeBlock_FUN_0060c95c(HeapBlock * block);
void crt_heap_c_UnlinkAndFreeBlock_FUN_0060c9bc(HeapBlock * block);
int crt_io_c_check_file_access_FUN_0060c9f0(char * filename, int access_mode);
int crt_process_c_spawnvp_FUN_0060ca20(int mode, char * cmdname, char * * argv);
undefined crt_startup_c_PlaceholderStub_FUN_0060ca80();
void * crt_memory_c_calloc_FUN_0060ca90(ulong count, ulong size);
LPVOID crt_tls_c_create_thread_local_data_FUN_0060cac0(void);
void * crt_tls_c_getThreadLocalData_FUN_0060caf8(void);
BOOL crt_tls_c_register_thread_data_FUN_0060cbd0(void * tls_data, void * thread_param);
void crt_tls_c_unregister_thread_data_FUN_0060cc3c(void * threadDataKey);
undefined crt_unknown_c_FUN_0060ccb4();
void crt_thread_c_InitializeThreadContext_FUN_0060ccf0(ThreadData * pThreadData);
undefined crt_unknown_c_FUN_0060ccb4();
ulong crt_string_c_wcslen_FUN_0060cd30(LPWSTR str);
void * crt_string_c_memcpy_FUN_0060cd60(void * dest, void * src, SIZE_T count);
int crt_stdio_c_IsRelevantKeyEvent_FUN_0060cd90(_INPUT_RECORD * pInputRecord);
void crt_stdio_c_InitializeConsoleHandles_FUN_0060cdbc(void);
HANDLE crt_stdio_c_GetConsoleInputHandle_FUN_0060ce30(void);
HANDLE crt_stdio_c_GetConsoleOutputHandle_FUN_0060ce3c(void);
void crt_fpu_c_ClearFPUExceptions_FUN_0060ce50(void);
SIGNAL_HANDLER_TYPE crt_signal_c_setSignalHandler_FUN_0060ce60(int signal_number, SIGNAL_HANDLER_TYPE new_handler_type);
SIGNAL_HANDLER_TYPE crt_signal_c_getSignalHandler_FUN_0060ceb4(int signal_number);
undefined crt_unknown_c_FUN_0060ced8();
BOOL crt_signal_c_consoleCtrlHandler_FUN_0060cf20(DWORD dwCtrlType);
undefined crt_unknown_c_FUN_0060cf80();
bool crt_signal_c_registerConsoleHandler_FUN_0060cfb8(void);
undefined crt_signal_c_unregisterConsoleHandler_FUN_0060cfe4();
int crt_signal_c_raiseFPE_FUN_0060d028(int fpe_code);
undefined crt_unknown_c_DoSomethingAndSetCtrlHandler_FUN_0060d068();
int crt_signal_c_processSignal_FUN_0060d128(int signal_number);
undefined crt_unknown_c_FUN_0060d1a8();
undefined crt_unknown_c_FUN_0060d1ec();
void crt_thread_c_staticInit_FUN_0060d214(void);
int crt_startup_c_FUN_0060d230(UINT cp);
ulonglong crt_math_c_udivmod64_FUN_0060d3ed(ulonglong dividend, ulonglong divisor);
undefined crt_unknown_c_FUN_0060d480();
undefined crt_unknown_c_FUN_0060d48c();
int crt_stdio_c_fgetc_buffered_FUN_0060d510(FILE * stream);
undefined crt_unknown_c_FUN_0060d576();
streambuf * crt_iostream_cpp_streambuf_setbuf_FUN_0060d5ff(streambuf * this_ptr, void * buffer_start, int buffer_size);
streambuf * crt_iostream_cpp_streambuf_destructor_FUN_0060d64f(streambuf * this_ptr);
int crt_iostream_cpp_doallocate_FUN_0060d677(streambuf * this_ptr);
void crt_iostream_cpp_setBuffer_FUN_0060d6a8(streambuf * this_ptr, void * new_buffer, void * buffer_end, int ownership_flag);
int crt_iostream_cpp_validateBufferSeek_FUN_0060d725(int seek_distance, int whence, char * buffer_start, char * current_ptr, char * buffer_end1, char * buffer_end2);
void * crt_iostream_cpp_streambuf_allocBuffer_FUN_0060d790(uint size);
void crt_iostream_cpp_freeBuffer_FUN_0060d7a0(void * buffer);
int crt_fstream_cpp_filebuf_pbackfail_FUN_0060d7ae(filebuf * this_ptr, int character);
int crt_fstream_cpp_filebuf_overflow_FUN_0060d881(filebuf * this_ptr, int character);
int crt_fstream_cpp_filebuf_underflow_FUN_0060da87(filebuf * this_ptr);
streambuf * crt_fstream_cpp_filebuf_setbuf_FUN_0060db8c(filebuf * this_ptr, char * buffer_ptr, int buffer_size);
int crt_fstream_cpp_filebuf_seekoff_FUN_0060dbe8(filebuf * this_ptr, long offset, int direction, int mode);
int crt_fstream_cpp_filebuf_sync_FUN_0060dc5e(filebuf * this_ptr);
undefined crt_unknown_c_FUN_0060dcf6();
double crt_math_c_dadd_FUN_0060defc(double a, double b);
double crt_math_c_dmul_FUN_0060e0b9(double a, double b);
undefined crt_unknown_c_FUN_0060e256();
void crt_math_c_print_error_message_FUN_0060e298(int errorType, char * errorData);
double crt_math_c_report_math_error_FUN_0060e2e5(MathErrorContext * errorCtx);
char * crt_string_c_char_in_set_FUN_0060e340(char * charset, wchar_t wc);
void crt_io_c_parseFileInfo_FUN_0060e3b0(void);
undefined crt_unknown_c_FUN_0060e4f0();
void crt_mbstring_c_copyMbChar_FUN_0060e590(char * dest, char * src);
undefined crt_unknown_c_SomethingWithUppercaseCharacterConvert_FUN_0060e5d0();
int crt_string_c_mbcmp_FUN_0060e640(char * str1, char * str2);
int crt_process_c_spawnvp_with_path_search_FUN_0060e6a0(int mode, char * program, char * * argv);
undefined crt_unknown_c_ReturnZero6_FUN_0060e850();
undefined crt_unknown_c_SomethingThatCallsExitThreadAfterCommunicate_FUN_0060e878();
undefined crt_unknown_c_CallReturnZero6_FUN_0060e880();
undefined crt_unknown_c_SomethingFPUControlWord_FUN_0060e8e0();
undefined crt_unknown_c_ReadFileBytesMaybe_FUN_0060e930();
undefined crt_unknown_c_FUN_0060eb3a();
undefined crt_unknown_c_FUN_0060eb4b();
undefined crt_unknown_c_FUN_0060eb57();
int crt_operation_c_always_zero_FUN_0060fa8b(void);
int crt_stdio_c_fputs_FUN_0060ebb0(char * str, FILE * file);
long crt_stdlib_c_strtol_internal_FUN_0060ec70(char * str, char * * endptr, int base, int is_signed);
ulong crt_stdlib_c_strtoul_FUN_0060ede0(char * str, char * * endptr, int base);
long crt_stdlib_c_strtol_FUN_0060edfc(char * str, char * * endptr, int base);
int crt_stdlib_c_charToDigit_FUN_0060ee18(char ch);
int crt_env_c_putenv_internal_FUN_0060ee80(char * envstr);
int crt_env_c_updateEnvironTable_FUN_0060f04c(char * envstr);
int crt_env_c_findEnvVar_FUN_0060f1f0(char * name, int delete_flag);
wchar_t crt_locale_c_toupper_multibyte_FUN_0060f300(char * mb_char, char * output_buffer);
bool crt_io_c_file_exists_FUN_0060f380(char * filename);
int crt_process_c_spawnvp_FUN_0060f39c(int mode, char * cmdname, char * * argv);
int crt_string_c_strlen_FUN_0060f870(char * str);
char * crt_string_c_strchr_FUN_0060f890(char * str, int ch);
void crt_thread_c_threadStartupWrapper_FUN_0060f8c0(ThreadStartupInfo * info);
HANDLE crt_thread_c_create_thread_with_sync_FUN_0060f960(LPVOID thread_param, SIZE_T stack_size_hint, LPVOID sync_param, HANDLE * out_thread_handle);
undefined crt_thread_c_exit_thread_FUN_0060fa58();
undefined crt_unknown_c_FUN_0060fa80();
int crt_operation_c_always_zero_FUN_0060fa8b(void);
undefined crt_unknown_c_FUN_0060fa90();
undefined crt_unknown_c_FUN_0060fac0();
undefined crt_unknown_c_FUN_0060fb40();
undefined crt_unknown_c_FUN_0060fcf4();
undefined crt_unknown_c_FUN_0060fe94();
wchar_t crt_locale_c_fullwidth_toupper_FUN_0060ffb0(wchar_t character);
undefined crt_process_c_build_file_info_env_FUN_0060ffd0();

