#pragma once

// Type dependencies
#include "system/basetypes.h"
#include "system/watcom.h"
#include "types/classes/CBoneGuy_full_vtable.h"
#include "types/classes/CCharacter_full_vtable.h"
#include "types/classes/CCodec_vtable.h"
#include "types/classes/CDemonActor_vtable.h"
#include "types/classes/CEnemy_full_vtable.h"
#include "types/classes/CHero_full_vtable.h"
#include "types/classes/CKeys_vtable.h"
#include "types/classes/CParticle_vtable.h"
#include "types/classes/CPickList_full_vtable.h"
#include "types/classes/CStrList_vtable.h"
#include "types/classes/CWeapon_full_vtable.h"

// =============================================================================
// GLOBAL VARIABLES - Range 0x590000
// =============================================================================

// CBoneGuy_full_vtable
extern CBoneGuy_full_vtable g_CBoneGuyVTable;

// CCharacter_full_vtable
extern CCharacter_full_vtable g_CCharacterVTable;
extern CCharacter_full_vtable g_CHiramVTable;
extern CCharacter_full_vtable g_CHostageVTable;
extern CCharacter_full_vtable g_CHighPriestOfGardathVTable;

// CCodec_vtable
extern CCodec_vtable g_CCodecVTable;
extern CCodec_vtable g_CLZWCompressVTable;
extern CCodec_vtable g_CLZWDecompressVTable;

// CDemonActor_vtable
extern CDemonActor_vtable g_CDemonActorVTable;
extern CDemonActor_vtable g_CAmmoVTable;
extern CDemonActor_vtable g_CAmmoBoxVTable;
extern CDemonActor_vtable g_CAnvilVTable;
extern CDemonActor_vtable g_CBackgroundActorVTable;
extern CDemonActor_vtable g_CBarrierVTable;
extern CDemonActor_vtable g_CBatVTable;
extern CDemonActor_vtable g_CBatteryVTable;
extern CDemonActor_vtable g_CBodyPartVTable;
extern CDemonActor_vtable g_CBoxActorVTable;
extern CDemonActor_vtable g_CLightActorVTable;
extern CDemonActor_vtable g_CChainVTable;
extern CDemonActor_vtable g_CConveyorVTable;
extern CDemonActor_vtable g_CCrateVTable;
extern CDemonActor_vtable g_CCurtainVTable;
extern CDemonActor_vtable g_CActorDestinationVTable;
extern CDemonActor_vtable g_CDoorVTable;
extern CDemonActor_vtable g_CDripVTable;
extern CDemonActor_vtable g_CEmitterVTable;
extern CDemonActor_vtable g_CFilmReelVTable;
extern CDemonActor_vtable g_CFilmProjectorVTable;
extern CDemonActor_vtable g_CFlameVTable;
extern CDemonActor_vtable g_CFlameCanVTable;
extern CDemonActor_vtable g_CFliesVTable;
extern CDemonActor_vtable g_CFrankenstienMachineVTable;
extern CDemonActor_vtable g_CGasMaskVTable;
extern CDemonActor_vtable g_CGlassVTable;
extern CDemonActor_vtable g_CGraveVTable;
extern CDemonActor_vtable g_CHealthItemVTable;
extern CDemonActor_vtable g_CHeroPlaceholderVTable;
extern CDemonActor_vtable g_CKeyActorVTable;
extern CDemonActor_vtable g_CLadderVTable;
extern CDemonActor_vtable g_CLeverVTable;
extern CDemonActor_vtable g_CLightConeVTable;

// CEnemy_full_vtable
extern CEnemy_full_vtable g_CArmourVTable;
extern CEnemy_full_vtable g_CBatCreatureVTable;
extern CEnemy_full_vtable g_CBatmanVTable;
extern CEnemy_full_vtable g_CBeastVTable;
extern CEnemy_full_vtable g_CBiggsVTable;
extern CEnemy_full_vtable g_CBrideVTable;
extern CEnemy_full_vtable g_CBugsVTable;
extern CEnemy_full_vtable g_CZombieCowVTable;
extern CEnemy_full_vtable g_CZombieDogVTable;
extern CEnemy_full_vtable g_CDraculaBrideVTable;
extern CEnemy_full_vtable g_CDroneVTable;
extern CEnemy_full_vtable g_CEnemyVTable;
extern CEnemy_full_vtable g_CGargoyleVTable;
extern CEnemy_full_vtable g_CGhoulVTable;
extern CEnemy_full_vtable g_CHotDemonVTable;
extern CEnemy_full_vtable g_CImpVTable;
extern CEnemy_full_vtable g_CLarvaVTable;

// CHero_full_vtable
extern CHero_full_vtable g_CBaronVTable;
extern CHero_full_vtable g_CColonelVTable;
extern CHero_full_vtable g_CGabriellaVTable;
extern CHero_full_vtable g_CHaystackVTable;
extern CHero_full_vtable g_CHeroVTable;
extern CHero_full_vtable g_CIcePickVTable;

// CKeys_vtable
extern CKeys_vtable g_CKeysVTable;

// CParticle_vtable
extern CParticle_vtable g_CRainDropVTable;
extern CParticle_vtable g_CPopcornVTable;
extern CParticle_vtable g_CShellVTable;
extern CParticle_vtable g_CGlassParticleVTable;
extern CParticle_vtable g_CRockVTable;
extern CParticle_vtable g_CFireballVTable;
extern CParticle_vtable g_CSparkVTable;
extern CParticle_vtable g_CBloodParticleVTable;

// CPickList_full_vtable
extern CPickList_full_vtable g_CPickListVTable;

// CStrList_vtable
extern CStrList_vtable g_CStrListVTable;

// CWeapon_full_vtable
extern CWeapon_full_vtable g_CBaronWeaponVTable;
extern CWeapon_full_vtable g_CCrossbowVTable;
extern CWeapon_full_vtable g_CDynamiteVTable;
extern CWeapon_full_vtable g_CElephantGunVTable;
extern CWeapon_full_vtable g_CFlameThrowerVTable;
extern CWeapon_full_vtable g_CFlashlightVTable;
extern CWeapon_full_vtable g_CGunVTable;
extern CWeapon_full_vtable g_CLightGunVTable;

// WatcomDestructorCall
extern WatcomDestructorCall g_WatcomDestructorCall_0059aaa0;
extern WatcomDestructorCall g_WatcomDestructorCall_0059b6e0;
extern WatcomDestructorCall g_WatcomDestructorCall_0059bdd0;
extern WatcomDestructorCall g_WatcomDestructorCall_0059bf60;
extern WatcomDestructorCall g_WatcomDestructorCall_0059bf6c;
extern WatcomDestructorCall g_WatcomDestructorCall_0059bf78;
extern WatcomDestructorCall g_WatcomDestructorCall_0059bf84;
extern WatcomDestructorCall g_WatcomDestructorCall_0059c050;
extern WatcomDestructorCall g_WatcomDestructorCall_0059c3c0;
extern WatcomDestructorCall g_WatcomDestructorCall_0059ca40;
extern WatcomDestructorCall g_WatcomDestructorCall_0059d180;
extern WatcomDestructorCall g_WatcomDestructorCall_0059d18c;
extern WatcomDestructorCall g_WatcomDestructorCall_0059d198;
extern WatcomDestructorCall g_WatcomDestructorCall_0059d1a4;
extern WatcomDestructorCall g_WatcomDestructorCall_0059d1b0;
extern WatcomDestructorCall g_WatcomDestructorCall_0059d1bc;
extern WatcomDestructorCall g_WatcomDestructorCall_0059d1c8;
extern WatcomDestructorCall g_WatcomDestructorCall_0059d1d4;
extern WatcomDestructorCall g_WatcomDestructorCall_0059d1e0;
extern WatcomDestructorCall g_WatcomDestructorCall_0059d1ec;
extern WatcomDestructorCall g_WatcomDestructorCall_0059de60;
extern WatcomDestructorCall g_WatcomDestructorCall_0059de6c;
extern WatcomDestructorCall g_WatcomDestructorCall_0059de78;
extern WatcomDestructorCall g_WatcomDestructorCall_0059e4b0;
extern WatcomDestructorCall g_WatcomDestructorCall_0059e4bc;
extern WatcomDestructorCall g_WatcomDestructorCall_0059e4c8;
extern WatcomDestructorCall g_WatcomDestructorCall_0059e6d0;
extern WatcomDestructorCall g_WatcomDestructorCall_0059f730;
extern WatcomDestructorCall g_WatcomDestructorCall_0059f73c;
extern WatcomDestructorCall g_WatcomDestructorCall_0059f748;
extern WatcomDestructorCall g_WatcomDestructorCall_0059f754;
extern WatcomDestructorCall g_WatcomDestructorCall_0059f760;
extern WatcomDestructorCall g_WatcomDestructorCall_0059f76c;
extern WatcomDestructorCall g_WatcomDestructorCall_0059f778;
extern WatcomDestructorCall g_WatcomDestructorCall_0059f784;
extern WatcomDestructorCall g_WatcomDestructorCall_0059f790;
extern WatcomDestructorCall g_WatcomDestructorCall_0059f79c;
extern WatcomDestructorCall g_WatcomDestructorCall_0059f7a8;
extern WatcomDestructorCall g_WatcomDestructorCall_0059f7b4;
extern WatcomDestructorCall g_WatcomDestructorCall_0059f7c0;
extern WatcomDestructorCall g_WatcomDestructorCall_0059f7cc;
extern WatcomDestructorCall g_WatcomDestructorCall_0059fbf0;
extern WatcomDestructorCall g_WatcomDestructorCall_0059ffd0;
extern WatcomDestructorCall g_WatcomDestructorCall_0059ffdc;
extern WatcomDestructorCall g_WatcomDestructorCall_0059ffe8;
extern WatcomDestructorCall g_WatcomDestructorCall_0059fff4;

// WatcomTypeInfo
extern WatcomTypeInfo g_CVectorTypeInfo_005993b0;
extern WatcomTypeInfo g_CDemonActorTypeInfo_005993d0;
extern WatcomTypeInfo g_CBoundingBox3D_005993f0;
extern WatcomTypeInfo g_SDamageInfoTypeInfo_00599410;
extern WatcomTypeInfo g_CAmmoTypeInfo_00599530;
extern WatcomTypeInfo g_CAmmoBoxTypeInfo_00599650;
extern WatcomTypeInfo g_CAnvilTypeInfo_00599770;
extern WatcomTypeInfo g_CArmourTypeInfo_00599900;
extern WatcomTypeInfo g_CEnemyTypeInfo_00599920;
extern WatcomTypeInfo g_CFlameTypeInfo_00599940;
extern WatcomTypeInfo g_SFireTypeInfo_00599960;
extern WatcomTypeInfo g_CBackgroundActorTypeInfo_00599a80;
extern WatcomTypeInfo g_CBaronWeaponTypeInfo_00599d10;
extern WatcomTypeInfo g_CBaronTypeInfo_00599d30;
extern WatcomTypeInfo g_CBarrierTypeInfo_00599e50;
extern WatcomTypeInfo g_CBatTypeInfo_00599f70;
extern WatcomTypeInfo g_CBatCreatureTypeInfo_0059a110;
extern WatcomTypeInfo g_CBatmanTypeInfo_0059a2b0;
extern WatcomTypeInfo g_CBatteryTypeInfo_0059a3d0;
extern WatcomTypeInfo g_CBeastTypeInfo_0059a560;
extern WatcomTypeInfo g_CBiggsTypeInfo_0059a700;
extern WatcomTypeInfo g_SBodyPartModelTypeInfo_0059a820;
extern WatcomTypeInfo g_SBodyPartFireTypeInfo_0059a840;
extern WatcomTypeInfo g_CBodyPartTypeInfo_0059a860;
extern WatcomTypeInfo g_SBoneGuyBoxTypeInfo_0059aa00;
extern WatcomTypeInfo g_CBoneGuyTypeInfo_0059aa20;
extern WatcomTypeInfo g_SScrapeTypeInfo_0059aa60;
extern WatcomTypeInfo g_CDemonFilterTypeInfo_0059ac90;
extern WatcomTypeInfo g_CLightActorTypeInfo_0059acb0;
extern WatcomTypeInfo g_CBoxActorTypeInfo_0059acd0;
extern WatcomTypeInfo g_CBrideTypeInfo_0059ae70;
extern WatcomTypeInfo g_SBugsTypeInfo_0059b010;
extern WatcomTypeInfo g_CKeyFramedModelInstanceTypeInfo_0059b030;
extern WatcomTypeInfo g_CBugsTypeInfo_0059b050;
extern WatcomTypeInfo g_SPoseTypeInfo_0059b1e0;
extern WatcomTypeInfo g_CCharacterTypeInfo_0059b200;
extern WatcomTypeInfo g_SChainVertexTypeInfo_0059b320;
extern WatcomTypeInfo g_CChainTypeInfo_0059b340;
extern WatcomTypeInfo g_SClothVertexTypeInfo_0059b3a0;
extern WatcomTypeInfo g_SClothBoneTypeInfo_0059b3c0;
extern WatcomTypeInfo g_CCodecTypeInfo_0059b470;
extern WatcomTypeInfo g_ostrstreamTypeInfo_0059b490;
extern WatcomTypeInfo g_ifstreamTypeInfo_0059b4d0;
extern WatcomTypeInfo g_ofstreamTypeInfo_0059b4f0;
extern WatcomTypeInfo g_CLZWDecompressTypeInfo_0059b510;
extern WatcomTypeInfo g_CLZWCompressTypeInfo_0059b530;
extern WatcomTypeInfo g_CColonelTypeInfo_0059b6c0;
extern WatcomTypeInfo g_CConveyorTypeInfo_0059b810;
extern WatcomTypeInfo g_CPlatformTypeInfo_0059b830;
extern WatcomTypeInfo g_CZombieCowTypeInfo_0059b9f0;
extern WatcomTypeInfo g_CCrateTypeInfo_0059bb10;
extern WatcomTypeInfo g_CCrossbowTypeInfo_0059bc50;
extern WatcomTypeInfo g_SCollisionInfoTypeInfo_0059bd70;
extern WatcomTypeInfo g_SCurtainVertexTypeInfo_0059bd90;
extern WatcomTypeInfo g_CCurtainTypeInfo_0059bdb0;
extern WatcomTypeInfo g_CActorDestinationTypeInfo_0059bf40;
extern WatcomTypeInfo g_CFilterCacheTypeInfo_0059bf90;
extern WatcomTypeInfo g_CFilterFXTypeInfo_0059bfb0;
extern WatcomTypeInfo g_CDemonTriangleTypeInfo_0059c080;
extern WatcomTypeInfo g_CKeyFramedModelTypeInfo_0059c0a0;
extern WatcomTypeInfo g_CZombieDogTypeInfo_0059c240;
extern WatcomTypeInfo g_CDoorTypeInfo_0059c360;
extern WatcomTypeInfo g_CFileFinder_0059c380;
extern WatcomTypeInfo g_SFreakyTypeInfo_0059c560;
extern WatcomTypeInfo g_CDraculaBrideTypeInfo_0059c580;
extern WatcomTypeInfo g_CDripTypeInfo_0059c6c0;
extern WatcomTypeInfo g_CDroneTypeInfo_0059c860;
extern WatcomTypeInfo g_CDemonCubeTypeInfo_0059c8c0;
extern WatcomTypeInfo g_CDynamiteTypeInfo_0059ca20;
extern WatcomTypeInfo g_CEditorToolsTypeInfo_0059cab0;
extern WatcomTypeInfo g_CPickListTypeInfo_0059cad0;
extern WatcomTypeInfo g_CStrListTypeInfo_0059caf0;
extern WatcomTypeInfo g_CElephantGunTypeInfo_0059cc30;
extern WatcomTypeInfo g_SLaserInfoTypeInfo_0059cd50;
extern WatcomTypeInfo g_CEmitterTypeInfo_0059cd70;
extern WatcomTypeInfo g_CFilmReelTypeInfo_0059d140;
extern WatcomTypeInfo g_CFilmProjectorTypeInfo_0059d160;
extern WatcomTypeInfo g_CSmokeParticleTypeInfo_0059d300;
extern WatcomTypeInfo g_CBulletHoleTypeInfo_0059d320;
extern WatcomTypeInfo g_CStakeTypeInfo_0059d340;
extern WatcomTypeInfo g_CSparkTypeInfo_0059d360;
extern WatcomTypeInfo g_CMuzzleFlashTypeInfo_0059d380;
extern WatcomTypeInfo g_CGlassParticleTypeInfo_0059d3a0;
extern WatcomTypeInfo g_CBulletTrailTypeInfo_0059d3c0;
extern WatcomTypeInfo g_CFireballTypeInfo_0059d3e0;
extern WatcomTypeInfo g_CRockTypeInfo_0059d400;
extern WatcomTypeInfo g_CLaserBeamTypeInfo_0059d420;
extern WatcomTypeInfo g_CExplosionTypeInfo_0059d440;
extern WatcomTypeInfo g_CTossTypeInfo_0059d460;
extern WatcomTypeInfo g_CCraterTypeInfo_0059d480;
extern WatcomTypeInfo g_CGunFlameTypeInfo_0059d4a0;
extern WatcomTypeInfo g_CLightningBoltTypeInfo_0059d4c0;
extern WatcomTypeInfo g_CTrailTypeInfo_0059d4e0;
extern WatcomTypeInfo g_CShellTypeInfo_0059d500;
extern WatcomTypeInfo g_CPopcornTypeInfo_0059d520;
extern WatcomTypeInfo g_CRainDropTypeInfo_0059d540;
extern WatcomTypeInfo g_CFlameCanTypeInfo_0059d760;
extern WatcomTypeInfo g_CFlameThrowerTypeInfo_0059d8b0;
extern WatcomTypeInfo g_CFlashlightTypeInfo_0059d9f0;
extern WatcomTypeInfo g_SFlyTypeInfo_0059db10;
extern WatcomTypeInfo g_CFliesTypeInfo_0059db30;
extern WatcomTypeInfo g_CFrankenstienMachineTypeInfo_0059dc60;
extern WatcomTypeInfo g_CGabriellaTypeInfo_0059de40;
extern WatcomTypeInfo g_CDemonLightTypeInfo_0059dea0;
extern WatcomTypeInfo g_CGameTypeInfo_0059dec0;
extern WatcomTypeInfo g_CSlewTypeInfo_0059dee0;
extern WatcomTypeInfo g_CAlphaBitmapTypeInfo_0059df00;
extern WatcomTypeInfo g_CGargoyleTypeInfo_0059e0a0;
extern WatcomTypeInfo g_CGasMaskTypeInfo_0059e1c0;
extern WatcomTypeInfo g_CGhoulTypeInfo_0059e370;
extern WatcomTypeInfo g_CGlassTypeInfo_0059e490;
extern WatcomTypeInfo g_CGoreTypeInfo_0059e510;
extern WatcomTypeInfo g_CBloodParticleTypeInfo_0059e530;
extern WatcomTypeInfo g_CBloodSplatTypeInfo_0059e550;
extern WatcomTypeInfo g_CBloodPoolTypeInfo_0059e570;
extern WatcomTypeInfo g_CFootstepTypeInfo_0059e590;
extern WatcomTypeInfo g_CGraveTypeInfo_0059e6b0;
extern WatcomTypeInfo g_CGroundTypeInfo_0059e700;
extern WatcomTypeInfo g_CGunTypeInfo_0059e840;
extern WatcomTypeInfo g_CHaystackTypeInfo_0059e9d0;
extern WatcomTypeInfo g_CHealthItemTypeInfo_0059eaf0;
extern WatcomTypeInfo g_CHeroPlaceholderTypeInfo_0059ed60;
extern WatcomTypeInfo g_CHiramTypeInfo_0059eee0;
extern WatcomTypeInfo g_CNPCTypeInfo_0059ef00;
extern WatcomTypeInfo g_CHostageTypeInfo_0059f080;
extern WatcomTypeInfo g_CHotDemonTypeInfo_0059f220;
extern WatcomTypeInfo g_CHighPriestOfGardathTypeInfo_0059f3a0;
extern WatcomTypeInfo g_CIcePickTypeInfo_0059f530;
extern WatcomTypeInfo g_CImpTypeInfo_0059f6d0;
extern WatcomTypeInfo g_CIniTypeInfo_0059f6f0;
extern WatcomTypeInfo g_CKeyActorTypeInfo_0059f900;
extern WatcomTypeInfo g_CLadderTypeInfo_0059fa30;
extern WatcomTypeInfo g_CLarvaTypeInfo_0059fbd0;
extern WatcomTypeInfo g_CLeverTypeInfo_0059fd20;
extern WatcomTypeInfo g_CLightGunTypeInfo_0059fe90;
extern WatcomTypeInfo g_CLightConeTypeInfo_0059ffb0;

// undefined1
extern undefined1 DAT_005992ac;

