#!/usr/bin/env bash
# build.sh — bootstrap the cmake configure step, then build a Nocturne preset.
#
# Unlike run.sh / debug.sh (which are generated by cmake), this script has to
# work BEFORE cmake has ever run, so it lives at the repo root and is
# hand-maintained.
#
# Default preset is `exe-linux-asan` (matches what dbg.sh / build/exe-linux-asan
# expects). Override via the first arg or the BUILD_PRESET env var:
#
#   ./build.sh                     # build exe-linux-asan (default)
#   ./build.sh exe-linux           # build the non-ASan exe
#   ./build.sh check-linux         # syntax-check only
#   BUILD_PRESET=exe-linux ./build.sh
#
# Extra args after the preset get passed through to cmake --build:
#
#   ./build.sh exe-linux-asan -j 4
#   ./build.sh exe-linux-asan --target nocturne_globals
#
# Re-glob trigger: collect_sources.py runs at cmake-configure time, so newly
# added .keep.cpp files don't enter the ninja graph unless cmake reconfigures.
# `touch`ing a CMAKE_CONFIGURE_DEPENDS file makes the next `cmake --build`
# reconfigure first; reconfigure is a no-op (~0.2s) when nothing else changed.

set -u

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
cd "${SCRIPT_DIR}"

PRESET="${1:-${BUILD_PRESET:-exe-linux-asan}}"
[ $# -ge 1 ] && shift

BUILD_DIR="${SCRIPT_DIR}/build/${PRESET}"

# First-time configure — skipped if the build tree already exists.
if [[ ! -d "${BUILD_DIR}" ]]; then
    echo "build.sh: configuring preset '${PRESET}' (first run)"
    cmake --preset "${PRESET}" || exit $?
fi

# Force a re-glob so newly added .keep.cpp / .keep.c files end up in the ninja
# graph. Without this, cmake only reconfigures when something already in
# CMAKE_CONFIGURE_DEPENDS changes, which keep files aren't.
touch "${SCRIPT_DIR}/cmake/skip_list.txt"

exec cmake --build "${BUILD_DIR}" "$@"
