#!/usr/bin/env python3
"""
Generate compile-time struct layout verification files.

Reads annotations/<exe>/data_types/data_types.json and emits one .cpp file per
leaf category into annotations/<exe>/pseudocode/src/checks/struct_layout/.
Each file contains static_assert()s for every struct's total size plus every
field's offset, using __builtin_offsetof so the check works on polymorphic
classes without a conditionally-supported warning.

Re-running overwrites previous output. Commit the result — these files are
the reference, not build artifacts.

Skip list: scripts/Python/gen_struct_layout_checks_skip.txt (one struct name
per line, # comments, blanks OK). Use this for structs whose C++ definition
doesn't exist or intentionally differs from the recorded layout.
"""

import argparse
import json
import os
import re
import sys
from collections import defaultdict


REPO_ROOT_DEFAULT = os.path.abspath(
    os.path.join(os.path.dirname(__file__), '..', '..'))


def slugify_leaf(cat):
    """Turn '/Nocturne/Struct/System/winnt.h' into 'winnt'."""
    if not cat:
        return 'uncategorized'
    leaf = cat.rstrip('/').split('/')[-1]
    if leaf.endswith('.h'):
        leaf = leaf[:-2]
    leaf = re.sub(r'[^A-Za-z0-9_]', '_', leaf)
    if not leaf:
        leaf = 'uncategorized'
    return leaf.lower()


def load_skip_list(path):
    if not path or not os.path.exists(path):
        return set()
    names = set()
    with open(path, 'r') as f:
        for raw in f:
            line = raw.strip()
            if not line or line.startswith('#'):
                continue
            names.add(line)
    return names


def is_valid_c_ident(s):
    return bool(s) and bool(re.match(r'^[A-Za-z_][A-Za-z0-9_]*$', s))


def emit_file(out_path, leaf, structs):
    """Write a single layout check .cpp file."""
    lines = []
    lines.append('// Auto-generated by scripts/Python/gen_struct_layout_checks.py')
    lines.append('// DO NOT EDIT BY HAND. Re-run the generator after updating types.')
    lines.append('//')
    lines.append('// Category: %s' % leaf)
    lines.append('// Structs : %d' % len(structs))
    lines.append('')
    lines.append('#include "nocturne.h"')
    lines.append('')
    lines.append('namespace nocturne_layout_%s {' % leaf)
    lines.append('')

    for s in structs:
        name = s['name']
        total = s['len']
        lines.append('// ---- %s (%d bytes) ----' % (name, total))
        lines.append('static_assert(sizeof(%s) == %d,' % (name, total))
        lines.append('              "sizeof(%s) != %d");' % (name, total))
        for f in s.get('fields', []):
            fname = f.get('name', '')
            foff  = f.get('offset', None)
            if foff is None or not is_valid_c_ident(fname):
                continue
            lines.append(
                'static_assert(__builtin_offsetof(%s, %s) == %d,' % (name, fname, foff))
            lines.append(
                '              "offsetof(%s, %s) != %d");' % (name, fname, foff))
        lines.append('')

    lines.append('} // namespace')
    lines.append('')

    with open(out_path, 'w') as f:
        f.write('\n'.join(lines))


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--data-types', required=True,
                    help='path to data_types.json')
    ap.add_argument('--out-dir', required=True,
                    help='target directory (e.g. src/checks/struct_layout)')
    ap.add_argument('--skip-list', default=None,
                    help='newline-delimited list of struct names to skip')
    ap.add_argument('--clean', action='store_true',
                    help='delete existing .cpp files in out-dir before writing')
    args = ap.parse_args()

    with open(args.data_types, 'r') as f:
        dt = json.load(f)
    structs = dt.get('structs', [])
    skip = load_skip_list(args.skip_list)

    os.makedirs(args.out_dir, exist_ok=True)

    if args.clean:
        for name in os.listdir(args.out_dir):
            if name.endswith('.cpp'):
                os.remove(os.path.join(args.out_dir, name))

    # Group by leaf category.
    groups = defaultdict(list)
    skipped = []
    for s in structs:
        name = s.get('name', '')
        if not is_valid_c_ident(name):
            skipped.append((name, 'non-ident name'))
            continue
        if name in skip:
            skipped.append((name, 'skip-list'))
            continue
        leaf = slugify_leaf(s.get('cat', ''))
        groups[leaf].append(s)

    # Emit one file per leaf, sorted by struct name inside.
    for leaf, lst in sorted(groups.items()):
        lst.sort(key=lambda x: x['name'])
        out_path = os.path.join(args.out_dir, '%s.cpp' % leaf)
        emit_file(out_path, leaf, lst)
        print('  %-20s %4d structs  -> %s' % (leaf, len(lst), out_path))

    if skipped:
        print('Skipped %d structs:' % len(skipped))
        for name, why in skipped[:20]:
            print('  %s (%s)' % (name, why))
        if len(skipped) > 20:
            print('  ... and %d more' % (len(skipped) - 20))

    return 0


if __name__ == '__main__':
    sys.exit(main())
