#pragma once

// Structure: EXCEPTION_REGISTRATION_RECORD
typedef struct EXCEPTION_REGISTRATION_RECORD {
    EXCEPTION_REGISTRATION_RECORD* Next;
    PEXCEPTION_ROUTINE Handler;
} EXCEPTION_REGISTRATION_RECORD;

