#pragma once

// Typedef: FILETIME
typedef _FILETIME FILETIME;

// Typedef: FLOATING_SAVE_AREA
typedef _FLOATING_SAVE_AREA FLOATING_SAVE_AREA;

// Typedef: LPCPINFO
// pointer to _cpinfo
typedef _cpinfo* LPCPINFO;

// Typedef: LPFILETIME
// pointer to _FILETIME
typedef _FILETIME* LPFILETIME;

// Typedef: LPMEMORYSTATUS
// pointer to _MEMORYSTATUS
typedef _MEMORYSTATUS* LPMEMORYSTATUS;

// Typedef: LPOVERLAPPED
// pointer to _OVERLAPPED
typedef _OVERLAPPED* LPOVERLAPPED;

// Typedef: LPPROCESS_INFORMATION
// pointer to _PROCESS_INFORMATION
typedef _PROCESS_INFORMATION* LPPROCESS_INFORMATION;

// Typedef: LPSECURITY_ATTRIBUTES
// pointer to _SECURITY_ATTRIBUTES
typedef _SECURITY_ATTRIBUTES* LPSECURITY_ATTRIBUTES;

// Typedef: LPSTARTUPINFOA
// pointer to _STARTUPINFOA
typedef _STARTUPINFOA* LPSTARTUPINFOA;

// Typedef: LPSYSTEMTIME
// pointer to _SYSTEMTIME
typedef _SYSTEMTIME* LPSYSTEMTIME;

// Typedef: LPTHREAD_START_ROUTINE
// pointer to PTHREAD_START_ROUTINE_FUNC
typedef PTHREAD_START_ROUTINE LPTHREAD_START_ROUTINE;

// Typedef: LPTIME_ZONE_INFORMATION
// pointer to _TIME_ZONE_INFORMATION
typedef _TIME_ZONE_INFORMATION* LPTIME_ZONE_INFORMATION;

// Typedef: LPTOP_LEVEL_EXCEPTION_FILTER
// pointer to PTOP_LEVEL_EXCEPTION_FILTER_FUNC
typedef PTOP_LEVEL_EXCEPTION_FILTER LPTOP_LEVEL_EXCEPTION_FILTER;

// Typedef: LPWIN32_FIND_DATAA
// pointer to _WIN32_FIND_DATAA
typedef _WIN32_FIND_DATAA* LPWIN32_FIND_DATAA;

// Typedef: LPWSADATA
// pointer to WSADATA
typedef WSADATA* LPWSADATA;

// Typedef: PFILETIME
// pointer to FILETIME
typedef FILETIME* PFILETIME;

// Typedef: PHANDLER_ROUTINE
// pointer to PHANDLER_ROUTINE_FUNC
typedef PHANDLER_ROUTINE_FUNC* PHANDLER_ROUTINE;

// Typedef: PMEMORY_BASIC_INFORMATION
// pointer to _MEMORY_BASIC_INFORMATION
typedef _MEMORY_BASIC_INFORMATION* PMEMORY_BASIC_INFORMATION;

// Typedef: PTHREAD_START_ROUTINE
// pointer to PTHREAD_START_ROUTINE_FUNC
typedef PTHREAD_START_ROUTINE_FUNC* PTHREAD_START_ROUTINE;

// Typedef: PTOP_LEVEL_EXCEPTION_FILTER
// pointer to PTOP_LEVEL_EXCEPTION_FILTER_FUNC
typedef PTOP_LEVEL_EXCEPTION_FILTER_FUNC* PTOP_LEVEL_EXCEPTION_FILTER;

// Typedef: SYSTEMTIME
typedef _SYSTEMTIME SYSTEMTIME;

// Typedef: WIN32_FIND_DATAA
typedef _WIN32_FIND_DATAA WIN32_FIND_DATAA;

