// Auto-generated by scripts/Python/gen_struct_layout_checks.py
// DO NOT EDIT BY HAND. Re-run the generator after updating types.
//
// Category: d3d
// Structs : 1

#include "nocturne.h"

namespace nocturne_layout_d3d {

// ---- D3DVECTOR (12 bytes) ----
static_assert(sizeof(D3DVECTOR) == 12,
              "sizeof(D3DVECTOR) != 12");
static_assert(__builtin_offsetof(D3DVECTOR, x) == 0,
              "offsetof(D3DVECTOR, x) != 0");
static_assert(__builtin_offsetof(D3DVECTOR, y) == 4,
              "offsetof(D3DVECTOR, y) != 4");
static_assert(__builtin_offsetof(D3DVECTOR, z) == 8,
              "offsetof(D3DVECTOR, z) != 8");

} // namespace
