// Auto-generated by scripts/Python/gen_struct_layout_checks.py
// DO NOT EDIT BY HAND. Re-run the generator after updating types.
//
// Category: ddraw
// Structs : 12

#include "nocturne.h"

// The assertions below encode the 32-bit (matching-target) struct layout
// from Ghidra's data_types.json, so they are only valid when pointers are
// 4 bytes. On a native 64-bit build, pointer-containing structs
// legitimately change size/offset, so the checks are compiled out there;
// the file still compiles (catching type/name regressions) in both lanes.
#if __SIZEOF_POINTER__ == 4

namespace nocturne_layout_ddraw {

// ---- DDCOLORKEY (8 bytes) ----
static_assert(sizeof(DDCOLORKEY) == 8,
              "sizeof(DDCOLORKEY) != 8");
static_assert(__builtin_offsetof(DDCOLORKEY, dwColorSpaceLowValue) == 0,
              "offsetof(DDCOLORKEY, dwColorSpaceLowValue) != 0");
static_assert(__builtin_offsetof(DDCOLORKEY, dwColorSpaceHighValue) == 4,
              "offsetof(DDCOLORKEY, dwColorSpaceHighValue) != 4");

// ---- DDPIXELFORMAT (32 bytes) ----
static_assert(sizeof(DDPIXELFORMAT) == 32,
              "sizeof(DDPIXELFORMAT) != 32");
static_assert(__builtin_offsetof(DDPIXELFORMAT, dwSize) == 0,
              "offsetof(DDPIXELFORMAT, dwSize) != 0");
static_assert(__builtin_offsetof(DDPIXELFORMAT, dwFlags) == 4,
              "offsetof(DDPIXELFORMAT, dwFlags) != 4");
static_assert(__builtin_offsetof(DDPIXELFORMAT, dwFourCC) == 8,
              "offsetof(DDPIXELFORMAT, dwFourCC) != 8");
static_assert(__builtin_offsetof(DDPIXELFORMAT, dwBitCount) == 12,
              "offsetof(DDPIXELFORMAT, dwBitCount) != 12");
static_assert(__builtin_offsetof(DDPIXELFORMAT, dwRedYMask) == 16,
              "offsetof(DDPIXELFORMAT, dwRedYMask) != 16");
static_assert(__builtin_offsetof(DDPIXELFORMAT, dwGreenUMask) == 20,
              "offsetof(DDPIXELFORMAT, dwGreenUMask) != 20");
static_assert(__builtin_offsetof(DDPIXELFORMAT, dwBlueVMask) == 24,
              "offsetof(DDPIXELFORMAT, dwBlueVMask) != 24");
static_assert(__builtin_offsetof(DDPIXELFORMAT, dwAlphaBitMask) == 28,
              "offsetof(DDPIXELFORMAT, dwAlphaBitMask) != 28");

// ---- DDSCAPS (4 bytes) ----
static_assert(sizeof(DDSCAPS) == 4,
              "sizeof(DDSCAPS) != 4");
static_assert(__builtin_offsetof(DDSCAPS, dwCaps) == 0,
              "offsetof(DDSCAPS, dwCaps) != 0");

// ---- DDSURFACEDESC (108 bytes) ----
static_assert(sizeof(DDSURFACEDESC) == 108,
              "sizeof(DDSURFACEDESC) != 108");
static_assert(__builtin_offsetof(DDSURFACEDESC, dwSize) == 0,
              "offsetof(DDSURFACEDESC, dwSize) != 0");
static_assert(__builtin_offsetof(DDSURFACEDESC, dwFlags) == 4,
              "offsetof(DDSURFACEDESC, dwFlags) != 4");
static_assert(__builtin_offsetof(DDSURFACEDESC, dwHeight) == 8,
              "offsetof(DDSURFACEDESC, dwHeight) != 8");
static_assert(__builtin_offsetof(DDSURFACEDESC, dwWidth) == 12,
              "offsetof(DDSURFACEDESC, dwWidth) != 12");
static_assert(__builtin_offsetof(DDSURFACEDESC, dwPitchOrLinearSize) == 16,
              "offsetof(DDSURFACEDESC, dwPitchOrLinearSize) != 16");
static_assert(__builtin_offsetof(DDSURFACEDESC, dwBackBufferCount) == 20,
              "offsetof(DDSURFACEDESC, dwBackBufferCount) != 20");
static_assert(__builtin_offsetof(DDSURFACEDESC, dwMipMapOrRefresh) == 24,
              "offsetof(DDSURFACEDESC, dwMipMapOrRefresh) != 24");
static_assert(__builtin_offsetof(DDSURFACEDESC, dwAlphaBitDepth) == 28,
              "offsetof(DDSURFACEDESC, dwAlphaBitDepth) != 28");
static_assert(__builtin_offsetof(DDSURFACEDESC, dwReserved) == 32,
              "offsetof(DDSURFACEDESC, dwReserved) != 32");
static_assert(__builtin_offsetof(DDSURFACEDESC, lpSurface) == 36,
              "offsetof(DDSURFACEDESC, lpSurface) != 36");
static_assert(__builtin_offsetof(DDSURFACEDESC, ddckCKDestOverlay) == 40,
              "offsetof(DDSURFACEDESC, ddckCKDestOverlay) != 40");
static_assert(__builtin_offsetof(DDSURFACEDESC, ddckCKDestBlt) == 48,
              "offsetof(DDSURFACEDESC, ddckCKDestBlt) != 48");
static_assert(__builtin_offsetof(DDSURFACEDESC, ddckCKSrcOverlay) == 56,
              "offsetof(DDSURFACEDESC, ddckCKSrcOverlay) != 56");
static_assert(__builtin_offsetof(DDSURFACEDESC, ddckCKSrcBlt) == 64,
              "offsetof(DDSURFACEDESC, ddckCKSrcBlt) != 64");
static_assert(__builtin_offsetof(DDSURFACEDESC, ddpfPixelFormat) == 72,
              "offsetof(DDSURFACEDESC, ddpfPixelFormat) != 72");
static_assert(__builtin_offsetof(DDSURFACEDESC, ddsCaps) == 104,
              "offsetof(DDSURFACEDESC, ddsCaps) != 104");

// ---- IDirectDraw (4 bytes) ----
static_assert(sizeof(IDirectDraw) == 4,
              "sizeof(IDirectDraw) != 4");
static_assert(__builtin_offsetof(IDirectDraw, vtable) == 0,
              "offsetof(IDirectDraw, vtable) != 0");

// ---- IDirectDrawClipper (4 bytes) ----
static_assert(sizeof(IDirectDrawClipper) == 4,
              "sizeof(IDirectDrawClipper) != 4");
static_assert(__builtin_offsetof(IDirectDrawClipper, vtable) == 0,
              "offsetof(IDirectDrawClipper, vtable) != 0");

// ---- IDirectDrawPalette (4 bytes) ----
static_assert(sizeof(IDirectDrawPalette) == 4,
              "sizeof(IDirectDrawPalette) != 4");
static_assert(__builtin_offsetof(IDirectDrawPalette, lpVtbl) == 0,
              "offsetof(IDirectDrawPalette, lpVtbl) != 0");

// ---- IDirectDrawSurface (4 bytes) ----
static_assert(sizeof(IDirectDrawSurface) == 4,
              "sizeof(IDirectDrawSurface) != 4");
static_assert(__builtin_offsetof(IDirectDrawSurface, vtable) == 0,
              "offsetof(IDirectDrawSurface, vtable) != 0");

// ---- IDirectDrawSurface_vtable (144 bytes) ----
static_assert(sizeof(IDirectDrawSurface_vtable) == 144,
              "sizeof(IDirectDrawSurface_vtable) != 144");
static_assert(__builtin_offsetof(IDirectDrawSurface_vtable, QueryInterface) == 0,
              "offsetof(IDirectDrawSurface_vtable, QueryInterface) != 0");
static_assert(__builtin_offsetof(IDirectDrawSurface_vtable, AddRef) == 4,
              "offsetof(IDirectDrawSurface_vtable, AddRef) != 4");
static_assert(__builtin_offsetof(IDirectDrawSurface_vtable, Release) == 8,
              "offsetof(IDirectDrawSurface_vtable, Release) != 8");
static_assert(__builtin_offsetof(IDirectDrawSurface_vtable, AddAttachedSurface) == 12,
              "offsetof(IDirectDrawSurface_vtable, AddAttachedSurface) != 12");
static_assert(__builtin_offsetof(IDirectDrawSurface_vtable, AddOverlayDirtyRect) == 16,
              "offsetof(IDirectDrawSurface_vtable, AddOverlayDirtyRect) != 16");
static_assert(__builtin_offsetof(IDirectDrawSurface_vtable, Blt) == 20,
              "offsetof(IDirectDrawSurface_vtable, Blt) != 20");
static_assert(__builtin_offsetof(IDirectDrawSurface_vtable, BltBatch) == 24,
              "offsetof(IDirectDrawSurface_vtable, BltBatch) != 24");
static_assert(__builtin_offsetof(IDirectDrawSurface_vtable, BltFast) == 28,
              "offsetof(IDirectDrawSurface_vtable, BltFast) != 28");
static_assert(__builtin_offsetof(IDirectDrawSurface_vtable, DeleteAttachedSurface) == 32,
              "offsetof(IDirectDrawSurface_vtable, DeleteAttachedSurface) != 32");
static_assert(__builtin_offsetof(IDirectDrawSurface_vtable, EnumAttachedSurfaces) == 36,
              "offsetof(IDirectDrawSurface_vtable, EnumAttachedSurfaces) != 36");
static_assert(__builtin_offsetof(IDirectDrawSurface_vtable, EnumOverlayZOrders) == 40,
              "offsetof(IDirectDrawSurface_vtable, EnumOverlayZOrders) != 40");
static_assert(__builtin_offsetof(IDirectDrawSurface_vtable, Flip) == 44,
              "offsetof(IDirectDrawSurface_vtable, Flip) != 44");
static_assert(__builtin_offsetof(IDirectDrawSurface_vtable, GetAttachedSurface) == 48,
              "offsetof(IDirectDrawSurface_vtable, GetAttachedSurface) != 48");
static_assert(__builtin_offsetof(IDirectDrawSurface_vtable, GetBltStatus) == 52,
              "offsetof(IDirectDrawSurface_vtable, GetBltStatus) != 52");
static_assert(__builtin_offsetof(IDirectDrawSurface_vtable, GetCaps) == 56,
              "offsetof(IDirectDrawSurface_vtable, GetCaps) != 56");
static_assert(__builtin_offsetof(IDirectDrawSurface_vtable, GetClipper) == 60,
              "offsetof(IDirectDrawSurface_vtable, GetClipper) != 60");
static_assert(__builtin_offsetof(IDirectDrawSurface_vtable, GetColorKey) == 64,
              "offsetof(IDirectDrawSurface_vtable, GetColorKey) != 64");
static_assert(__builtin_offsetof(IDirectDrawSurface_vtable, GetDC) == 68,
              "offsetof(IDirectDrawSurface_vtable, GetDC) != 68");
static_assert(__builtin_offsetof(IDirectDrawSurface_vtable, GetFlipStatus) == 72,
              "offsetof(IDirectDrawSurface_vtable, GetFlipStatus) != 72");
static_assert(__builtin_offsetof(IDirectDrawSurface_vtable, GetOverlayPosition) == 76,
              "offsetof(IDirectDrawSurface_vtable, GetOverlayPosition) != 76");
static_assert(__builtin_offsetof(IDirectDrawSurface_vtable, GetPalette) == 80,
              "offsetof(IDirectDrawSurface_vtable, GetPalette) != 80");
static_assert(__builtin_offsetof(IDirectDrawSurface_vtable, GetPixelFormat) == 84,
              "offsetof(IDirectDrawSurface_vtable, GetPixelFormat) != 84");
static_assert(__builtin_offsetof(IDirectDrawSurface_vtable, GetSurfaceDesc) == 88,
              "offsetof(IDirectDrawSurface_vtable, GetSurfaceDesc) != 88");
static_assert(__builtin_offsetof(IDirectDrawSurface_vtable, Initialize) == 92,
              "offsetof(IDirectDrawSurface_vtable, Initialize) != 92");
static_assert(__builtin_offsetof(IDirectDrawSurface_vtable, IsLost) == 96,
              "offsetof(IDirectDrawSurface_vtable, IsLost) != 96");
static_assert(__builtin_offsetof(IDirectDrawSurface_vtable, Lock) == 100,
              "offsetof(IDirectDrawSurface_vtable, Lock) != 100");
static_assert(__builtin_offsetof(IDirectDrawSurface_vtable, ReleaseDC) == 104,
              "offsetof(IDirectDrawSurface_vtable, ReleaseDC) != 104");
static_assert(__builtin_offsetof(IDirectDrawSurface_vtable, Restore) == 108,
              "offsetof(IDirectDrawSurface_vtable, Restore) != 108");
static_assert(__builtin_offsetof(IDirectDrawSurface_vtable, SetClipper) == 112,
              "offsetof(IDirectDrawSurface_vtable, SetClipper) != 112");
static_assert(__builtin_offsetof(IDirectDrawSurface_vtable, SetColorKey) == 116,
              "offsetof(IDirectDrawSurface_vtable, SetColorKey) != 116");
static_assert(__builtin_offsetof(IDirectDrawSurface_vtable, SetOverlayPosition) == 120,
              "offsetof(IDirectDrawSurface_vtable, SetOverlayPosition) != 120");
static_assert(__builtin_offsetof(IDirectDrawSurface_vtable, SetPalette) == 124,
              "offsetof(IDirectDrawSurface_vtable, SetPalette) != 124");
static_assert(__builtin_offsetof(IDirectDrawSurface_vtable, Unlock) == 128,
              "offsetof(IDirectDrawSurface_vtable, Unlock) != 128");
static_assert(__builtin_offsetof(IDirectDrawSurface_vtable, UpdateOverlay) == 132,
              "offsetof(IDirectDrawSurface_vtable, UpdateOverlay) != 132");
static_assert(__builtin_offsetof(IDirectDrawSurface_vtable, UpdateOverlayDisplay) == 136,
              "offsetof(IDirectDrawSurface_vtable, UpdateOverlayDisplay) != 136");
static_assert(__builtin_offsetof(IDirectDrawSurface_vtable, UpdateOverlayZOrder) == 140,
              "offsetof(IDirectDrawSurface_vtable, UpdateOverlayZOrder) != 140");

// ---- IDirectDraw_vtable (92 bytes) ----
static_assert(sizeof(IDirectDraw_vtable) == 92,
              "sizeof(IDirectDraw_vtable) != 92");
static_assert(__builtin_offsetof(IDirectDraw_vtable, QueryInterface) == 0,
              "offsetof(IDirectDraw_vtable, QueryInterface) != 0");
static_assert(__builtin_offsetof(IDirectDraw_vtable, AddRef) == 4,
              "offsetof(IDirectDraw_vtable, AddRef) != 4");
static_assert(__builtin_offsetof(IDirectDraw_vtable, Release) == 8,
              "offsetof(IDirectDraw_vtable, Release) != 8");
static_assert(__builtin_offsetof(IDirectDraw_vtable, Compact) == 12,
              "offsetof(IDirectDraw_vtable, Compact) != 12");
static_assert(__builtin_offsetof(IDirectDraw_vtable, CreateClipper) == 16,
              "offsetof(IDirectDraw_vtable, CreateClipper) != 16");
static_assert(__builtin_offsetof(IDirectDraw_vtable, CreatePalette) == 20,
              "offsetof(IDirectDraw_vtable, CreatePalette) != 20");
static_assert(__builtin_offsetof(IDirectDraw_vtable, CreateSurface) == 24,
              "offsetof(IDirectDraw_vtable, CreateSurface) != 24");
static_assert(__builtin_offsetof(IDirectDraw_vtable, DuplicateSurface) == 28,
              "offsetof(IDirectDraw_vtable, DuplicateSurface) != 28");
static_assert(__builtin_offsetof(IDirectDraw_vtable, EnumDisplayModes) == 32,
              "offsetof(IDirectDraw_vtable, EnumDisplayModes) != 32");
static_assert(__builtin_offsetof(IDirectDraw_vtable, EnumSurfaces) == 36,
              "offsetof(IDirectDraw_vtable, EnumSurfaces) != 36");
static_assert(__builtin_offsetof(IDirectDraw_vtable, FlipToGDISurface) == 40,
              "offsetof(IDirectDraw_vtable, FlipToGDISurface) != 40");
static_assert(__builtin_offsetof(IDirectDraw_vtable, GetCaps) == 44,
              "offsetof(IDirectDraw_vtable, GetCaps) != 44");
static_assert(__builtin_offsetof(IDirectDraw_vtable, GetDisplayMode) == 48,
              "offsetof(IDirectDraw_vtable, GetDisplayMode) != 48");
static_assert(__builtin_offsetof(IDirectDraw_vtable, GetFourCCCodes) == 52,
              "offsetof(IDirectDraw_vtable, GetFourCCCodes) != 52");
static_assert(__builtin_offsetof(IDirectDraw_vtable, GetGDISurface) == 56,
              "offsetof(IDirectDraw_vtable, GetGDISurface) != 56");
static_assert(__builtin_offsetof(IDirectDraw_vtable, GetMonitorFrequency) == 60,
              "offsetof(IDirectDraw_vtable, GetMonitorFrequency) != 60");
static_assert(__builtin_offsetof(IDirectDraw_vtable, GetScanLine) == 64,
              "offsetof(IDirectDraw_vtable, GetScanLine) != 64");
static_assert(__builtin_offsetof(IDirectDraw_vtable, GetVerticalBlankStatus) == 68,
              "offsetof(IDirectDraw_vtable, GetVerticalBlankStatus) != 68");
static_assert(__builtin_offsetof(IDirectDraw_vtable, Initialize) == 72,
              "offsetof(IDirectDraw_vtable, Initialize) != 72");
static_assert(__builtin_offsetof(IDirectDraw_vtable, RestoreDisplayMode) == 76,
              "offsetof(IDirectDraw_vtable, RestoreDisplayMode) != 76");
static_assert(__builtin_offsetof(IDirectDraw_vtable, SetCooperativeLevel) == 80,
              "offsetof(IDirectDraw_vtable, SetCooperativeLevel) != 80");
static_assert(__builtin_offsetof(IDirectDraw_vtable, SetDisplayMode) == 84,
              "offsetof(IDirectDraw_vtable, SetDisplayMode) != 84");
static_assert(__builtin_offsetof(IDirectDraw_vtable, WaitForVerticalBlank) == 88,
              "offsetof(IDirectDraw_vtable, WaitForVerticalBlank) != 88");

// ---- PALETTEENTRY (4 bytes) ----
static_assert(sizeof(PALETTEENTRY) == 4,
              "sizeof(PALETTEENTRY) != 4");
static_assert(__builtin_offsetof(PALETTEENTRY, red) == 0,
              "offsetof(PALETTEENTRY, red) != 0");
static_assert(__builtin_offsetof(PALETTEENTRY, green) == 1,
              "offsetof(PALETTEENTRY, green) != 1");
static_assert(__builtin_offsetof(PALETTEENTRY, blue) == 2,
              "offsetof(PALETTEENTRY, blue) != 2");
static_assert(__builtin_offsetof(PALETTEENTRY, flags) == 3,
              "offsetof(PALETTEENTRY, flags) != 3");

// ---- RGB_ENTRY (3 bytes) ----
static_assert(sizeof(RGB_ENTRY) == 3,
              "sizeof(RGB_ENTRY) != 3");
static_assert(__builtin_offsetof(RGB_ENTRY, red) == 0,
              "offsetof(RGB_ENTRY, red) != 0");
static_assert(__builtin_offsetof(RGB_ENTRY, green) == 1,
              "offsetof(RGB_ENTRY, green) != 1");
static_assert(__builtin_offsetof(RGB_ENTRY, blue) == 2,
              "offsetof(RGB_ENTRY, blue) != 2");

} // namespace

#endif  // __SIZEOF_POINTER__ == 4 (32-bit layout only)
