// Auto-generated by scripts/Python/gen_struct_layout_checks.py
// DO NOT EDIT BY HAND. Re-run the generator after updating types.
//
// Category: excpt
// Structs : 3

#include "nocturne.h"

// The assertions below encode the 32-bit (matching-target) struct layout
// from Ghidra's data_types.json, so they are only valid when pointers are
// 4 bytes. On a native 64-bit build, pointer-containing structs
// legitimately change size/offset, so the checks are compiled out there;
// the file still compiles (catching type/name regressions) in both lanes.
#if __SIZEOF_POINTER__ == 4

namespace nocturne_layout_excpt {

// ---- _CONTEXT (716 bytes) ----
static_assert(sizeof(_CONTEXT) == 716,
              "sizeof(_CONTEXT) != 716");
static_assert(__builtin_offsetof(_CONTEXT, ContextFlags) == 0,
              "offsetof(_CONTEXT, ContextFlags) != 0");
static_assert(__builtin_offsetof(_CONTEXT, Dr0) == 4,
              "offsetof(_CONTEXT, Dr0) != 4");
static_assert(__builtin_offsetof(_CONTEXT, Dr1) == 8,
              "offsetof(_CONTEXT, Dr1) != 8");
static_assert(__builtin_offsetof(_CONTEXT, Dr2) == 12,
              "offsetof(_CONTEXT, Dr2) != 12");
static_assert(__builtin_offsetof(_CONTEXT, Dr3) == 16,
              "offsetof(_CONTEXT, Dr3) != 16");
static_assert(__builtin_offsetof(_CONTEXT, Dr6) == 20,
              "offsetof(_CONTEXT, Dr6) != 20");
static_assert(__builtin_offsetof(_CONTEXT, Dr7) == 24,
              "offsetof(_CONTEXT, Dr7) != 24");
static_assert(__builtin_offsetof(_CONTEXT, FloatSave) == 28,
              "offsetof(_CONTEXT, FloatSave) != 28");
static_assert(__builtin_offsetof(_CONTEXT, SegGs) == 140,
              "offsetof(_CONTEXT, SegGs) != 140");
static_assert(__builtin_offsetof(_CONTEXT, SegFs) == 144,
              "offsetof(_CONTEXT, SegFs) != 144");
static_assert(__builtin_offsetof(_CONTEXT, SegEs) == 148,
              "offsetof(_CONTEXT, SegEs) != 148");
static_assert(__builtin_offsetof(_CONTEXT, SegDs) == 152,
              "offsetof(_CONTEXT, SegDs) != 152");
static_assert(__builtin_offsetof(_CONTEXT, Edi) == 156,
              "offsetof(_CONTEXT, Edi) != 156");
static_assert(__builtin_offsetof(_CONTEXT, Esi) == 160,
              "offsetof(_CONTEXT, Esi) != 160");
static_assert(__builtin_offsetof(_CONTEXT, Ebx) == 164,
              "offsetof(_CONTEXT, Ebx) != 164");
static_assert(__builtin_offsetof(_CONTEXT, Edx) == 168,
              "offsetof(_CONTEXT, Edx) != 168");
static_assert(__builtin_offsetof(_CONTEXT, Ecx) == 172,
              "offsetof(_CONTEXT, Ecx) != 172");
static_assert(__builtin_offsetof(_CONTEXT, Eax) == 176,
              "offsetof(_CONTEXT, Eax) != 176");
static_assert(__builtin_offsetof(_CONTEXT, Ebp) == 180,
              "offsetof(_CONTEXT, Ebp) != 180");
static_assert(__builtin_offsetof(_CONTEXT, Eip) == 184,
              "offsetof(_CONTEXT, Eip) != 184");
static_assert(__builtin_offsetof(_CONTEXT, SegCs) == 188,
              "offsetof(_CONTEXT, SegCs) != 188");
static_assert(__builtin_offsetof(_CONTEXT, EFlags) == 192,
              "offsetof(_CONTEXT, EFlags) != 192");
static_assert(__builtin_offsetof(_CONTEXT, Esp) == 196,
              "offsetof(_CONTEXT, Esp) != 196");
static_assert(__builtin_offsetof(_CONTEXT, SegSs) == 200,
              "offsetof(_CONTEXT, SegSs) != 200");
static_assert(__builtin_offsetof(_CONTEXT, ExtendedRegisters) == 204,
              "offsetof(_CONTEXT, ExtendedRegisters) != 204");

// ---- _EXCEPTION_POINTERS (8 bytes) ----
static_assert(sizeof(_EXCEPTION_POINTERS) == 8,
              "sizeof(_EXCEPTION_POINTERS) != 8");
static_assert(__builtin_offsetof(_EXCEPTION_POINTERS, ExceptionRecord) == 0,
              "offsetof(_EXCEPTION_POINTERS, ExceptionRecord) != 0");
static_assert(__builtin_offsetof(_EXCEPTION_POINTERS, ContextRecord) == 4,
              "offsetof(_EXCEPTION_POINTERS, ContextRecord) != 4");

// ---- _EXCEPTION_RECORD (80 bytes) ----
static_assert(sizeof(_EXCEPTION_RECORD) == 80,
              "sizeof(_EXCEPTION_RECORD) != 80");
static_assert(__builtin_offsetof(_EXCEPTION_RECORD, ExceptionCode) == 0,
              "offsetof(_EXCEPTION_RECORD, ExceptionCode) != 0");
static_assert(__builtin_offsetof(_EXCEPTION_RECORD, ExceptionFlags) == 4,
              "offsetof(_EXCEPTION_RECORD, ExceptionFlags) != 4");
static_assert(__builtin_offsetof(_EXCEPTION_RECORD, ExceptionRecord) == 8,
              "offsetof(_EXCEPTION_RECORD, ExceptionRecord) != 8");
static_assert(__builtin_offsetof(_EXCEPTION_RECORD, ExceptionAddress) == 12,
              "offsetof(_EXCEPTION_RECORD, ExceptionAddress) != 12");
static_assert(__builtin_offsetof(_EXCEPTION_RECORD, NumberParameters) == 16,
              "offsetof(_EXCEPTION_RECORD, NumberParameters) != 16");
static_assert(__builtin_offsetof(_EXCEPTION_RECORD, ExceptionInformation) == 20,
              "offsetof(_EXCEPTION_RECORD, ExceptionInformation) != 20");

} // namespace

#endif  // __SIZEOF_POINTER__ == 4 (32-bit layout only)
