// Auto-generated by scripts/Python/gen_struct_layout_checks.py
// DO NOT EDIT BY HAND. Re-run the generator after updating types.
//
// Category: fstream
// Structs : 6

#include "nocturne.h"

// The assertions below encode the 32-bit (matching-target) struct layout
// from Ghidra's data_types.json, so they are only valid when pointers are
// 4 bytes. On a native 64-bit build, pointer-containing structs
// legitimately change size/offset, so the checks are compiled out there;
// the file still compiles (catching type/name regressions) in both lanes.
#if __SIZEOF_POINTER__ == 4

namespace nocturne_layout_fstream {

// ---- filebuf (60 bytes) ----
static_assert(sizeof(filebuf) == 60,
              "sizeof(filebuf) != 60");
static_assert(__builtin_offsetof(filebuf, _streambuf) == 0,
              "offsetof(filebuf, _streambuf) != 0");
static_assert(__builtin_offsetof(filebuf, __vtable) == 40,
              "offsetof(filebuf, __vtable) != 40");
static_assert(__builtin_offsetof(filebuf, __file_handle) == 44,
              "offsetof(filebuf, __file_handle) != 44");
static_assert(__builtin_offsetof(filebuf, __file_mode) == 48,
              "offsetof(filebuf, __file_mode) != 48");
static_assert(__builtin_offsetof(filebuf, __unbuffered_get_area) == 52,
              "offsetof(filebuf, __unbuffered_get_area) != 52");
static_assert(__builtin_offsetof(filebuf, __attached) == 57,
              "offsetof(filebuf, __attached) != 57");
static_assert(__builtin_offsetof(filebuf, padding_0x3E) == 58,
              "offsetof(filebuf, padding_0x3E) != 58");

// ---- filebuf_vtable (44 bytes) ----
static_assert(sizeof(filebuf_vtable) == 44,
              "sizeof(filebuf_vtable) != 44");
static_assert(__builtin_offsetof(filebuf_vtable, do_sgetn) == 0,
              "offsetof(filebuf_vtable, do_sgetn) != 0");
static_assert(__builtin_offsetof(filebuf_vtable, do_sputn) == 4,
              "offsetof(filebuf_vtable, do_sputn) != 4");
static_assert(__builtin_offsetof(filebuf_vtable, pbackfail) == 8,
              "offsetof(filebuf_vtable, pbackfail) != 8");
static_assert(__builtin_offsetof(filebuf_vtable, overflow) == 12,
              "offsetof(filebuf_vtable, overflow) != 12");
static_assert(__builtin_offsetof(filebuf_vtable, underflow) == 16,
              "offsetof(filebuf_vtable, underflow) != 16");
static_assert(__builtin_offsetof(filebuf_vtable, setbuf) == 20,
              "offsetof(filebuf_vtable, setbuf) != 20");
static_assert(__builtin_offsetof(filebuf_vtable, seekoff) == 24,
              "offsetof(filebuf_vtable, seekoff) != 24");
static_assert(__builtin_offsetof(filebuf_vtable, seekpos) == 28,
              "offsetof(filebuf_vtable, seekpos) != 28");
static_assert(__builtin_offsetof(filebuf_vtable, sync) == 32,
              "offsetof(filebuf_vtable, sync) != 32");
static_assert(__builtin_offsetof(filebuf_vtable, destructor) == 36,
              "offsetof(filebuf_vtable, destructor) != 36");
static_assert(__builtin_offsetof(filebuf_vtable, doallocate) == 40,
              "offsetof(filebuf_vtable, doallocate) != 40");

// ---- fstreambase (116 bytes) ----
static_assert(sizeof(fstreambase) == 116,
              "sizeof(fstreambase) != 116");
static_assert(__builtin_offsetof(fstreambase, base) == 0,
              "offsetof(fstreambase, base) != 0");
static_assert(__builtin_offsetof(fstreambase, padding_0x44) == 68,
              "offsetof(fstreambase, padding_0x44) != 68");
static_assert(__builtin_offsetof(fstreambase, ios_base) == 72,
              "offsetof(fstreambase, ios_base) != 72");

// ---- fstreambase_core (68 bytes) ----
static_assert(sizeof(fstreambase_core) == 68,
              "sizeof(fstreambase_core) != 68");
static_assert(__builtin_offsetof(fstreambase_core, layout_info) == 0,
              "offsetof(fstreambase_core, layout_info) != 0");
static_assert(__builtin_offsetof(fstreambase_core, _filebuf) == 4,
              "offsetof(fstreambase_core, _filebuf) != 4");
static_assert(__builtin_offsetof(fstreambase_core, destructor_vtable) == 64,
              "offsetof(fstreambase_core, destructor_vtable) != 64");

// ---- ifstream (128 bytes) ----
static_assert(sizeof(ifstream) == 128,
              "sizeof(ifstream) != 128");
static_assert(__builtin_offsetof(ifstream, _fstreambase_core) == 0,
              "offsetof(ifstream, _fstreambase_core) != 0");
static_assert(__builtin_offsetof(ifstream, _istream_core) == 68,
              "offsetof(ifstream, _istream_core) != 68");
static_assert(__builtin_offsetof(ifstream, _ios) == 84,
              "offsetof(ifstream, _ios) != 84");

// ---- ofstream (124 bytes) ----
static_assert(sizeof(ofstream) == 124,
              "sizeof(ofstream) != 124");
static_assert(__builtin_offsetof(ofstream, _fstreambase_core) == 0,
              "offsetof(ofstream, _fstreambase_core) != 0");
static_assert(__builtin_offsetof(ofstream, _ostream_core) == 68,
              "offsetof(ofstream, _ostream_core) != 68");
static_assert(__builtin_offsetof(ofstream, _ios) == 80,
              "offsetof(ofstream, _ios) != 80");

} // namespace

#endif  // __SIZEOF_POINTER__ == 4 (32-bit layout only)
