// Auto-generated by scripts/Python/gen_struct_layout_checks.py
// DO NOT EDIT BY HAND. Re-run the generator after updating types.
//
// Category: iostream
// Structs : 7

#include "nocturne.h"

// The assertions below encode the 32-bit (matching-target) struct layout
// from Ghidra's data_types.json, so they are only valid when pointers are
// 4 bytes. On a native 64-bit build, pointer-containing structs
// legitimately change size/offset, so the checks are compiled out there;
// the file still compiles (catching type/name regressions) in both lanes.
#if __SIZEOF_POINTER__ == 4

namespace nocturne_layout_iostream {

// ---- _istream (60 bytes) ----
static_assert(sizeof(_istream) == 60,
              "sizeof(_istream) != 60");
static_assert(__builtin_offsetof(_istream, _istream_core) == 0,
              "offsetof(_istream, _istream_core) != 0");
static_assert(__builtin_offsetof(_istream, _ios) == 16,
              "offsetof(_istream, _ios) != 16");

// ---- _ostream (56 bytes) ----
static_assert(sizeof(_ostream) == 56,
              "sizeof(_ostream) != 56");
static_assert(__builtin_offsetof(_ostream, _ostream_core) == 0,
              "offsetof(_ostream, _ostream_core) != 0");
static_assert(__builtin_offsetof(_ostream, _ios) == 12,
              "offsetof(_ostream, _ios) != 12");

// ---- ios (44 bytes) ----
static_assert(sizeof(ios) == 44,
              "sizeof(ios) != 44");
static_assert(__builtin_offsetof(ios, __strmbuf) == 0,
              "offsetof(ios, __strmbuf) != 0");
static_assert(__builtin_offsetof(ios, __tied_stream) == 4,
              "offsetof(ios, __tied_stream) != 4");
static_assert(__builtin_offsetof(ios, __format_flags) == 8,
              "offsetof(ios, __format_flags) != 8");
static_assert(__builtin_offsetof(ios, __error_state) == 12,
              "offsetof(ios, __error_state) != 12");
static_assert(__builtin_offsetof(ios, __enabled_exceptions) == 16,
              "offsetof(ios, __enabled_exceptions) != 16");
static_assert(__builtin_offsetof(ios, __float_precision) == 20,
              "offsetof(ios, __float_precision) != 20");
static_assert(__builtin_offsetof(ios, __field_width) == 24,
              "offsetof(ios, __field_width) != 24");
static_assert(__builtin_offsetof(ios, __xalloc_list) == 28,
              "offsetof(ios, __xalloc_list) != 28");
static_assert(__builtin_offsetof(ios, __fill_character) == 32,
              "offsetof(ios, __fill_character) != 32");
static_assert(__builtin_offsetof(ios, padding) == 33,
              "offsetof(ios, padding) != 33");
static_assert(__builtin_offsetof(ios, __i_lock) == 36,
              "offsetof(ios, __i_lock) != 36");
static_assert(__builtin_offsetof(ios, cleanup_vtable) == 40,
              "offsetof(ios, cleanup_vtable) != 40");

// ---- istream_core (16 bytes) ----
static_assert(sizeof(istream_core) == 16,
              "sizeof(istream_core) != 16");
static_assert(__builtin_offsetof(istream_core, layout_info) == 0,
              "offsetof(istream_core, layout_info) != 0");
static_assert(__builtin_offsetof(istream_core, __last_read_length) == 4,
              "offsetof(istream_core, __last_read_length) != 4");
static_assert(__builtin_offsetof(istream_core, destructor_vtable) == 8,
              "offsetof(istream_core, destructor_vtable) != 8");
static_assert(__builtin_offsetof(istream_core, istream_data) == 12,
              "offsetof(istream_core, istream_data) != 12");

// ---- ostream_core (12 bytes) ----
static_assert(sizeof(ostream_core) == 12,
              "sizeof(ostream_core) != 12");
static_assert(__builtin_offsetof(ostream_core, layout_info) == 0,
              "offsetof(ostream_core, layout_info) != 0");
static_assert(__builtin_offsetof(ostream_core, destructor_vtable) == 4,
              "offsetof(ostream_core, destructor_vtable) != 4");
static_assert(__builtin_offsetof(ostream_core, ostream_data) == 8,
              "offsetof(ostream_core, ostream_data) != 8");

// ---- streambuf (40 bytes) ----
static_assert(sizeof(streambuf) == 40,
              "sizeof(streambuf) != 40");
static_assert(__builtin_offsetof(streambuf, __b_lock) == 0,
              "offsetof(streambuf, __b_lock) != 0");
static_assert(__builtin_offsetof(streambuf, __reserve_base) == 4,
              "offsetof(streambuf, __reserve_base) != 4");
static_assert(__builtin_offsetof(streambuf, __reserve_end) == 8,
              "offsetof(streambuf, __reserve_end) != 8");
static_assert(__builtin_offsetof(streambuf, __get_base) == 12,
              "offsetof(streambuf, __get_base) != 12");
static_assert(__builtin_offsetof(streambuf, __get_end) == 16,
              "offsetof(streambuf, __get_end) != 16");
static_assert(__builtin_offsetof(streambuf, __get_ptr) == 20,
              "offsetof(streambuf, __get_ptr) != 20");
static_assert(__builtin_offsetof(streambuf, __put_base) == 24,
              "offsetof(streambuf, __put_base) != 24");
static_assert(__builtin_offsetof(streambuf, __put_end) == 28,
              "offsetof(streambuf, __put_end) != 28");
static_assert(__builtin_offsetof(streambuf, __put_ptr) == 32,
              "offsetof(streambuf, __put_ptr) != 32");
static_assert(__builtin_offsetof(streambuf, __flags) == 36,
              "offsetof(streambuf, __flags) != 36");

// ---- streambuf_vtable (52 bytes) ----
static_assert(sizeof(streambuf_vtable) == 52,
              "sizeof(streambuf_vtable) != 52");
static_assert(__builtin_offsetof(streambuf_vtable, do_sgetn) == 0,
              "offsetof(streambuf_vtable, do_sgetn) != 0");
static_assert(__builtin_offsetof(streambuf_vtable, do_sputn) == 4,
              "offsetof(streambuf_vtable, do_sputn) != 4");
static_assert(__builtin_offsetof(streambuf_vtable, pbackfail) == 8,
              "offsetof(streambuf_vtable, pbackfail) != 8");
static_assert(__builtin_offsetof(streambuf_vtable, overflow) == 12,
              "offsetof(streambuf_vtable, overflow) != 12");
static_assert(__builtin_offsetof(streambuf_vtable, underflow) == 16,
              "offsetof(streambuf_vtable, underflow) != 16");
static_assert(__builtin_offsetof(streambuf_vtable, setbuf) == 20,
              "offsetof(streambuf_vtable, setbuf) != 20");
static_assert(__builtin_offsetof(streambuf_vtable, seekoff) == 24,
              "offsetof(streambuf_vtable, seekoff) != 24");
static_assert(__builtin_offsetof(streambuf_vtable, seekpos) == 28,
              "offsetof(streambuf_vtable, seekpos) != 28");
static_assert(__builtin_offsetof(streambuf_vtable, sync) == 32,
              "offsetof(streambuf_vtable, sync) != 32");
static_assert(__builtin_offsetof(streambuf_vtable, destructor) == 36,
              "offsetof(streambuf_vtable, destructor) != 36");
static_assert(__builtin_offsetof(streambuf_vtable, doallocate) == 40,
              "offsetof(streambuf_vtable, doallocate) != 40");
static_assert(__builtin_offsetof(streambuf_vtable, reserved) == 44,
              "offsetof(streambuf_vtable, reserved) != 44");
static_assert(__builtin_offsetof(streambuf_vtable, base_object_size) == 48,
              "offsetof(streambuf_vtable, base_object_size) != 48");

} // namespace

#endif  // __SIZEOF_POINTER__ == 4 (32-bit layout only)
