// Auto-generated by scripts/Python/gen_struct_layout_checks.py
// DO NOT EDIT BY HAND. Re-run the generator after updating types.
//
// Category: math
// Structs : 1

#include "nocturne.h"

// The assertions below encode the 32-bit (matching-target) struct layout
// from Ghidra's data_types.json, so they are only valid when pointers are
// 4 bytes. On a native 64-bit build, pointer-containing structs
// legitimately change size/offset, so the checks are compiled out there;
// the file still compiles (catching type/name regressions) in both lanes.
#if __SIZEOF_POINTER__ == 4

namespace nocturne_layout_math {

// ---- MathErrorContext (32 bytes) ----
static_assert(sizeof(MathErrorContext) == 32,
              "sizeof(MathErrorContext) != 32");
static_assert(__builtin_offsetof(MathErrorContext, errorType) == 0,
              "offsetof(MathErrorContext, errorType) != 0");
static_assert(__builtin_offsetof(MathErrorContext, errorData) == 4,
              "offsetof(MathErrorContext, errorData) != 4");
static_assert(__builtin_offsetof(MathErrorContext, inputValue1) == 8,
              "offsetof(MathErrorContext, inputValue1) != 8");
static_assert(__builtin_offsetof(MathErrorContext, inputValue2) == 16,
              "offsetof(MathErrorContext, inputValue2) != 16");
static_assert(__builtin_offsetof(MathErrorContext, resultValue) == 24,
              "offsetof(MathErrorContext, resultValue) != 24");

} // namespace

#endif  // __SIZEOF_POINTER__ == 4 (32-bit layout only)
