// Auto-generated by scripts/Python/gen_struct_layout_checks.py
// DO NOT EDIT BY HAND. Re-run the generator after updating types.
//
// Category: pe
// Structs : 14

#include "nocturne.h"

namespace nocturne_layout_pe {

// ---- IMAGE_DATA_DIRECTORY (8 bytes) ----
static_assert(sizeof(IMAGE_DATA_DIRECTORY) == 8,
              "sizeof(IMAGE_DATA_DIRECTORY) != 8");
static_assert(__builtin_offsetof(IMAGE_DATA_DIRECTORY, VirtualAddress) == 0,
              "offsetof(IMAGE_DATA_DIRECTORY, VirtualAddress) != 0");
static_assert(__builtin_offsetof(IMAGE_DATA_DIRECTORY, Size) == 4,
              "offsetof(IMAGE_DATA_DIRECTORY, Size) != 4");

// ---- IMAGE_FILE_HEADER (20 bytes) ----
static_assert(sizeof(IMAGE_FILE_HEADER) == 20,
              "sizeof(IMAGE_FILE_HEADER) != 20");
static_assert(__builtin_offsetof(IMAGE_FILE_HEADER, Machine) == 0,
              "offsetof(IMAGE_FILE_HEADER, Machine) != 0");
static_assert(__builtin_offsetof(IMAGE_FILE_HEADER, NumberOfSections) == 2,
              "offsetof(IMAGE_FILE_HEADER, NumberOfSections) != 2");
static_assert(__builtin_offsetof(IMAGE_FILE_HEADER, TimeDateStamp) == 4,
              "offsetof(IMAGE_FILE_HEADER, TimeDateStamp) != 4");
static_assert(__builtin_offsetof(IMAGE_FILE_HEADER, PointerToSymbolTable) == 8,
              "offsetof(IMAGE_FILE_HEADER, PointerToSymbolTable) != 8");
static_assert(__builtin_offsetof(IMAGE_FILE_HEADER, NumberOfSymbols) == 12,
              "offsetof(IMAGE_FILE_HEADER, NumberOfSymbols) != 12");
static_assert(__builtin_offsetof(IMAGE_FILE_HEADER, SizeOfOptionalHeader) == 16,
              "offsetof(IMAGE_FILE_HEADER, SizeOfOptionalHeader) != 16");
static_assert(__builtin_offsetof(IMAGE_FILE_HEADER, Characteristics) == 18,
              "offsetof(IMAGE_FILE_HEADER, Characteristics) != 18");

// ---- IMAGE_NT_HEADERS32 (248 bytes) ----
static_assert(sizeof(IMAGE_NT_HEADERS32) == 248,
              "sizeof(IMAGE_NT_HEADERS32) != 248");
static_assert(__builtin_offsetof(IMAGE_NT_HEADERS32, Signature) == 0,
              "offsetof(IMAGE_NT_HEADERS32, Signature) != 0");
static_assert(__builtin_offsetof(IMAGE_NT_HEADERS32, FileHeader) == 4,
              "offsetof(IMAGE_NT_HEADERS32, FileHeader) != 4");
static_assert(__builtin_offsetof(IMAGE_NT_HEADERS32, OptionalHeader) == 24,
              "offsetof(IMAGE_NT_HEADERS32, OptionalHeader) != 24");

// ---- IMAGE_OPTIONAL_HEADER32 (224 bytes) ----
static_assert(sizeof(IMAGE_OPTIONAL_HEADER32) == 224,
              "sizeof(IMAGE_OPTIONAL_HEADER32) != 224");
static_assert(__builtin_offsetof(IMAGE_OPTIONAL_HEADER32, Magic) == 0,
              "offsetof(IMAGE_OPTIONAL_HEADER32, Magic) != 0");
static_assert(__builtin_offsetof(IMAGE_OPTIONAL_HEADER32, MajorLinkerVersion) == 2,
              "offsetof(IMAGE_OPTIONAL_HEADER32, MajorLinkerVersion) != 2");
static_assert(__builtin_offsetof(IMAGE_OPTIONAL_HEADER32, MinorLinkerVersion) == 3,
              "offsetof(IMAGE_OPTIONAL_HEADER32, MinorLinkerVersion) != 3");
static_assert(__builtin_offsetof(IMAGE_OPTIONAL_HEADER32, SizeOfCode) == 4,
              "offsetof(IMAGE_OPTIONAL_HEADER32, SizeOfCode) != 4");
static_assert(__builtin_offsetof(IMAGE_OPTIONAL_HEADER32, SizeOfInitializedData) == 8,
              "offsetof(IMAGE_OPTIONAL_HEADER32, SizeOfInitializedData) != 8");
static_assert(__builtin_offsetof(IMAGE_OPTIONAL_HEADER32, SizeOfUninitializedData) == 12,
              "offsetof(IMAGE_OPTIONAL_HEADER32, SizeOfUninitializedData) != 12");
static_assert(__builtin_offsetof(IMAGE_OPTIONAL_HEADER32, AddressOfEntryPoint) == 16,
              "offsetof(IMAGE_OPTIONAL_HEADER32, AddressOfEntryPoint) != 16");
static_assert(__builtin_offsetof(IMAGE_OPTIONAL_HEADER32, BaseOfCode) == 20,
              "offsetof(IMAGE_OPTIONAL_HEADER32, BaseOfCode) != 20");
static_assert(__builtin_offsetof(IMAGE_OPTIONAL_HEADER32, BaseOfData) == 24,
              "offsetof(IMAGE_OPTIONAL_HEADER32, BaseOfData) != 24");
static_assert(__builtin_offsetof(IMAGE_OPTIONAL_HEADER32, ImageBase) == 28,
              "offsetof(IMAGE_OPTIONAL_HEADER32, ImageBase) != 28");
static_assert(__builtin_offsetof(IMAGE_OPTIONAL_HEADER32, SectionAlignment) == 32,
              "offsetof(IMAGE_OPTIONAL_HEADER32, SectionAlignment) != 32");
static_assert(__builtin_offsetof(IMAGE_OPTIONAL_HEADER32, FileAlignment) == 36,
              "offsetof(IMAGE_OPTIONAL_HEADER32, FileAlignment) != 36");
static_assert(__builtin_offsetof(IMAGE_OPTIONAL_HEADER32, MajorOperatingSystemVersion) == 40,
              "offsetof(IMAGE_OPTIONAL_HEADER32, MajorOperatingSystemVersion) != 40");
static_assert(__builtin_offsetof(IMAGE_OPTIONAL_HEADER32, MinorOperatingSystemVersion) == 42,
              "offsetof(IMAGE_OPTIONAL_HEADER32, MinorOperatingSystemVersion) != 42");
static_assert(__builtin_offsetof(IMAGE_OPTIONAL_HEADER32, MajorImageVersion) == 44,
              "offsetof(IMAGE_OPTIONAL_HEADER32, MajorImageVersion) != 44");
static_assert(__builtin_offsetof(IMAGE_OPTIONAL_HEADER32, MinorImageVersion) == 46,
              "offsetof(IMAGE_OPTIONAL_HEADER32, MinorImageVersion) != 46");
static_assert(__builtin_offsetof(IMAGE_OPTIONAL_HEADER32, MajorSubsystemVersion) == 48,
              "offsetof(IMAGE_OPTIONAL_HEADER32, MajorSubsystemVersion) != 48");
static_assert(__builtin_offsetof(IMAGE_OPTIONAL_HEADER32, MinorSubsystemVersion) == 50,
              "offsetof(IMAGE_OPTIONAL_HEADER32, MinorSubsystemVersion) != 50");
static_assert(__builtin_offsetof(IMAGE_OPTIONAL_HEADER32, Win32VersionValue) == 52,
              "offsetof(IMAGE_OPTIONAL_HEADER32, Win32VersionValue) != 52");
static_assert(__builtin_offsetof(IMAGE_OPTIONAL_HEADER32, SizeOfImage) == 56,
              "offsetof(IMAGE_OPTIONAL_HEADER32, SizeOfImage) != 56");
static_assert(__builtin_offsetof(IMAGE_OPTIONAL_HEADER32, SizeOfHeaders) == 60,
              "offsetof(IMAGE_OPTIONAL_HEADER32, SizeOfHeaders) != 60");
static_assert(__builtin_offsetof(IMAGE_OPTIONAL_HEADER32, CheckSum) == 64,
              "offsetof(IMAGE_OPTIONAL_HEADER32, CheckSum) != 64");
static_assert(__builtin_offsetof(IMAGE_OPTIONAL_HEADER32, Subsystem) == 68,
              "offsetof(IMAGE_OPTIONAL_HEADER32, Subsystem) != 68");
static_assert(__builtin_offsetof(IMAGE_OPTIONAL_HEADER32, DllCharacteristics) == 70,
              "offsetof(IMAGE_OPTIONAL_HEADER32, DllCharacteristics) != 70");
static_assert(__builtin_offsetof(IMAGE_OPTIONAL_HEADER32, SizeOfStackReserve) == 72,
              "offsetof(IMAGE_OPTIONAL_HEADER32, SizeOfStackReserve) != 72");
static_assert(__builtin_offsetof(IMAGE_OPTIONAL_HEADER32, SizeOfStackCommit) == 76,
              "offsetof(IMAGE_OPTIONAL_HEADER32, SizeOfStackCommit) != 76");
static_assert(__builtin_offsetof(IMAGE_OPTIONAL_HEADER32, SizeOfHeapReserve) == 80,
              "offsetof(IMAGE_OPTIONAL_HEADER32, SizeOfHeapReserve) != 80");
static_assert(__builtin_offsetof(IMAGE_OPTIONAL_HEADER32, SizeOfHeapCommit) == 84,
              "offsetof(IMAGE_OPTIONAL_HEADER32, SizeOfHeapCommit) != 84");
static_assert(__builtin_offsetof(IMAGE_OPTIONAL_HEADER32, LoaderFlags) == 88,
              "offsetof(IMAGE_OPTIONAL_HEADER32, LoaderFlags) != 88");
static_assert(__builtin_offsetof(IMAGE_OPTIONAL_HEADER32, NumberOfRvaAndSizes) == 92,
              "offsetof(IMAGE_OPTIONAL_HEADER32, NumberOfRvaAndSizes) != 92");
static_assert(__builtin_offsetof(IMAGE_OPTIONAL_HEADER32, DataDirectory) == 96,
              "offsetof(IMAGE_OPTIONAL_HEADER32, DataDirectory) != 96");

// ---- IMAGE_RESOURCE_DATA_ENTRY (16 bytes) ----
static_assert(sizeof(IMAGE_RESOURCE_DATA_ENTRY) == 16,
              "sizeof(IMAGE_RESOURCE_DATA_ENTRY) != 16");
static_assert(__builtin_offsetof(IMAGE_RESOURCE_DATA_ENTRY, OffsetToData) == 0,
              "offsetof(IMAGE_RESOURCE_DATA_ENTRY, OffsetToData) != 0");
static_assert(__builtin_offsetof(IMAGE_RESOURCE_DATA_ENTRY, Size) == 4,
              "offsetof(IMAGE_RESOURCE_DATA_ENTRY, Size) != 4");
static_assert(__builtin_offsetof(IMAGE_RESOURCE_DATA_ENTRY, CodePage) == 8,
              "offsetof(IMAGE_RESOURCE_DATA_ENTRY, CodePage) != 8");
static_assert(__builtin_offsetof(IMAGE_RESOURCE_DATA_ENTRY, Reserved) == 12,
              "offsetof(IMAGE_RESOURCE_DATA_ENTRY, Reserved) != 12");

// ---- IMAGE_RESOURCE_DIRECTORY (16 bytes) ----
static_assert(sizeof(IMAGE_RESOURCE_DIRECTORY) == 16,
              "sizeof(IMAGE_RESOURCE_DIRECTORY) != 16");
static_assert(__builtin_offsetof(IMAGE_RESOURCE_DIRECTORY, Characteristics) == 0,
              "offsetof(IMAGE_RESOURCE_DIRECTORY, Characteristics) != 0");
static_assert(__builtin_offsetof(IMAGE_RESOURCE_DIRECTORY, TimeDateStamp) == 4,
              "offsetof(IMAGE_RESOURCE_DIRECTORY, TimeDateStamp) != 4");
static_assert(__builtin_offsetof(IMAGE_RESOURCE_DIRECTORY, MajorVersion) == 8,
              "offsetof(IMAGE_RESOURCE_DIRECTORY, MajorVersion) != 8");
static_assert(__builtin_offsetof(IMAGE_RESOURCE_DIRECTORY, MinorVersion) == 10,
              "offsetof(IMAGE_RESOURCE_DIRECTORY, MinorVersion) != 10");
static_assert(__builtin_offsetof(IMAGE_RESOURCE_DIRECTORY, NumberOfNamedEntries) == 12,
              "offsetof(IMAGE_RESOURCE_DIRECTORY, NumberOfNamedEntries) != 12");
static_assert(__builtin_offsetof(IMAGE_RESOURCE_DIRECTORY, NumberOfIdEntries) == 14,
              "offsetof(IMAGE_RESOURCE_DIRECTORY, NumberOfIdEntries) != 14");

// ---- IMAGE_RESOURCE_DIRECTORY_ENTRY_NameStruct (8 bytes) ----
static_assert(sizeof(IMAGE_RESOURCE_DIRECTORY_ENTRY_NameStruct) == 8,
              "sizeof(IMAGE_RESOURCE_DIRECTORY_ENTRY_NameStruct) != 8");
static_assert(__builtin_offsetof(IMAGE_RESOURCE_DIRECTORY_ENTRY_NameStruct, NameOffset) == 0,
              "offsetof(IMAGE_RESOURCE_DIRECTORY_ENTRY_NameStruct, NameOffset) != 0");
static_assert(__builtin_offsetof(IMAGE_RESOURCE_DIRECTORY_ENTRY_NameStruct, NameIsString) == 4,
              "offsetof(IMAGE_RESOURCE_DIRECTORY_ENTRY_NameStruct, NameIsString) != 4");

// ---- IMAGE_SECTION_HEADER (40 bytes) ----
static_assert(sizeof(IMAGE_SECTION_HEADER) == 40,
              "sizeof(IMAGE_SECTION_HEADER) != 40");
static_assert(__builtin_offsetof(IMAGE_SECTION_HEADER, Name) == 0,
              "offsetof(IMAGE_SECTION_HEADER, Name) != 0");
static_assert(__builtin_offsetof(IMAGE_SECTION_HEADER, Misc) == 8,
              "offsetof(IMAGE_SECTION_HEADER, Misc) != 8");
static_assert(__builtin_offsetof(IMAGE_SECTION_HEADER, VirtualAddress) == 12,
              "offsetof(IMAGE_SECTION_HEADER, VirtualAddress) != 12");
static_assert(__builtin_offsetof(IMAGE_SECTION_HEADER, SizeOfRawData) == 16,
              "offsetof(IMAGE_SECTION_HEADER, SizeOfRawData) != 16");
static_assert(__builtin_offsetof(IMAGE_SECTION_HEADER, PointerToRawData) == 20,
              "offsetof(IMAGE_SECTION_HEADER, PointerToRawData) != 20");
static_assert(__builtin_offsetof(IMAGE_SECTION_HEADER, PointerToRelocations) == 24,
              "offsetof(IMAGE_SECTION_HEADER, PointerToRelocations) != 24");
static_assert(__builtin_offsetof(IMAGE_SECTION_HEADER, PointerToLinenumbers) == 28,
              "offsetof(IMAGE_SECTION_HEADER, PointerToLinenumbers) != 28");
static_assert(__builtin_offsetof(IMAGE_SECTION_HEADER, NumberOfRelocations) == 32,
              "offsetof(IMAGE_SECTION_HEADER, NumberOfRelocations) != 32");
static_assert(__builtin_offsetof(IMAGE_SECTION_HEADER, NumberOfLinenumbers) == 34,
              "offsetof(IMAGE_SECTION_HEADER, NumberOfLinenumbers) != 34");
static_assert(__builtin_offsetof(IMAGE_SECTION_HEADER, Characteristics) == 36,
              "offsetof(IMAGE_SECTION_HEADER, Characteristics) != 36");

// ---- StringFileInfo (6 bytes) ----
static_assert(sizeof(StringFileInfo) == 6,
              "sizeof(StringFileInfo) != 6");
static_assert(__builtin_offsetof(StringFileInfo, wLength) == 0,
              "offsetof(StringFileInfo, wLength) != 0");
static_assert(__builtin_offsetof(StringFileInfo, wValueLength) == 2,
              "offsetof(StringFileInfo, wValueLength) != 2");
static_assert(__builtin_offsetof(StringFileInfo, wType) == 4,
              "offsetof(StringFileInfo, wType) != 4");

// ---- StringInfo (6 bytes) ----
static_assert(sizeof(StringInfo) == 6,
              "sizeof(StringInfo) != 6");
static_assert(__builtin_offsetof(StringInfo, wLength) == 0,
              "offsetof(StringInfo, wLength) != 0");
static_assert(__builtin_offsetof(StringInfo, wValueLength) == 2,
              "offsetof(StringInfo, wValueLength) != 2");
static_assert(__builtin_offsetof(StringInfo, wType) == 4,
              "offsetof(StringInfo, wType) != 4");

// ---- StringTable (6 bytes) ----
static_assert(sizeof(StringTable) == 6,
              "sizeof(StringTable) != 6");
static_assert(__builtin_offsetof(StringTable, wLength) == 0,
              "offsetof(StringTable, wLength) != 0");
static_assert(__builtin_offsetof(StringTable, wValueLength) == 2,
              "offsetof(StringTable, wValueLength) != 2");
static_assert(__builtin_offsetof(StringTable, wType) == 4,
              "offsetof(StringTable, wType) != 4");

// ---- VS_VERSION_INFO (92 bytes) ----
static_assert(sizeof(VS_VERSION_INFO) == 92,
              "sizeof(VS_VERSION_INFO) != 92");
static_assert(__builtin_offsetof(VS_VERSION_INFO, StructLength) == 0,
              "offsetof(VS_VERSION_INFO, StructLength) != 0");
static_assert(__builtin_offsetof(VS_VERSION_INFO, ValueLength) == 2,
              "offsetof(VS_VERSION_INFO, ValueLength) != 2");
static_assert(__builtin_offsetof(VS_VERSION_INFO, StructType) == 4,
              "offsetof(VS_VERSION_INFO, StructType) != 4");
static_assert(__builtin_offsetof(VS_VERSION_INFO, Info) == 6,
              "offsetof(VS_VERSION_INFO, Info) != 6");
static_assert(__builtin_offsetof(VS_VERSION_INFO, Padding) == 38,
              "offsetof(VS_VERSION_INFO, Padding) != 38");
static_assert(__builtin_offsetof(VS_VERSION_INFO, Signature) == 40,
              "offsetof(VS_VERSION_INFO, Signature) != 40");
static_assert(__builtin_offsetof(VS_VERSION_INFO, StructVersion) == 44,
              "offsetof(VS_VERSION_INFO, StructVersion) != 44");
static_assert(__builtin_offsetof(VS_VERSION_INFO, FileVersion) == 48,
              "offsetof(VS_VERSION_INFO, FileVersion) != 48");
static_assert(__builtin_offsetof(VS_VERSION_INFO, ProductVersion) == 56,
              "offsetof(VS_VERSION_INFO, ProductVersion) != 56");
static_assert(__builtin_offsetof(VS_VERSION_INFO, FileFlagsMask) == 64,
              "offsetof(VS_VERSION_INFO, FileFlagsMask) != 64");
static_assert(__builtin_offsetof(VS_VERSION_INFO, FileFlags) == 72,
              "offsetof(VS_VERSION_INFO, FileFlags) != 72");
static_assert(__builtin_offsetof(VS_VERSION_INFO, FileOS) == 76,
              "offsetof(VS_VERSION_INFO, FileOS) != 76");
static_assert(__builtin_offsetof(VS_VERSION_INFO, FileType) == 80,
              "offsetof(VS_VERSION_INFO, FileType) != 80");
static_assert(__builtin_offsetof(VS_VERSION_INFO, FileSubtype) == 84,
              "offsetof(VS_VERSION_INFO, FileSubtype) != 84");
static_assert(__builtin_offsetof(VS_VERSION_INFO, FileTimestamp) == 88,
              "offsetof(VS_VERSION_INFO, FileTimestamp) != 88");

// ---- Var (6 bytes) ----
static_assert(sizeof(Var) == 6,
              "sizeof(Var) != 6");
static_assert(__builtin_offsetof(Var, wLength) == 0,
              "offsetof(Var, wLength) != 0");
static_assert(__builtin_offsetof(Var, wValueLength) == 2,
              "offsetof(Var, wValueLength) != 2");
static_assert(__builtin_offsetof(Var, wType) == 4,
              "offsetof(Var, wType) != 4");

// ---- VarFileInfo (6 bytes) ----
static_assert(sizeof(VarFileInfo) == 6,
              "sizeof(VarFileInfo) != 6");
static_assert(__builtin_offsetof(VarFileInfo, wLength) == 0,
              "offsetof(VarFileInfo, wLength) != 0");
static_assert(__builtin_offsetof(VarFileInfo, wValueLength) == 2,
              "offsetof(VarFileInfo, wValueLength) != 2");
static_assert(__builtin_offsetof(VarFileInfo, wType) == 4,
              "offsetof(VarFileInfo, wType) != 4");

} // namespace
