// Auto-generated by scripts/Python/gen_struct_layout_checks.py
// DO NOT EDIT BY HAND. Re-run the generator after updating types.
//
// Category: signal
// Structs : 1

#include "nocturne.h"

// The assertions below encode the 32-bit (matching-target) struct layout
// from Ghidra's data_types.json, so they are only valid when pointers are
// 4 bytes. On a native 64-bit build, pointer-containing structs
// legitimately change size/offset, so the checks are compiled out there;
// the file still compiles (catching type/name regressions) in both lanes.
#if __SIZEOF_POINTER__ == 4

namespace nocturne_layout_signal {

// ---- SignalHandlerEntry (8 bytes) ----
static_assert(sizeof(SignalHandlerEntry) == 8,
              "sizeof(SignalHandlerEntry) != 8");
static_assert(__builtin_offsetof(SignalHandlerEntry, flags) == 0,
              "offsetof(SignalHandlerEntry, flags) != 0");
static_assert(__builtin_offsetof(SignalHandlerEntry, type) == 4,
              "offsetof(SignalHandlerEntry, type) != 4");

} // namespace

#endif  // __SIZEOF_POINTER__ == 4 (32-bit layout only)
