// Auto-generated by scripts/Python/gen_struct_layout_checks.py
// DO NOT EDIT BY HAND. Re-run the generator after updating types.
//
// Category: stat
// Structs : 1

#include "nocturne.h"

// The assertions below encode the 32-bit (matching-target) struct layout
// from Ghidra's data_types.json, so they are only valid when pointers are
// 4 bytes. On a native 64-bit build, pointer-containing structs
// legitimately change size/offset, so the checks are compiled out there;
// the file still compiles (catching type/name regressions) in both lanes.
#if __SIZEOF_POINTER__ == 4

namespace nocturne_layout_stat {

// ---- _stat (70 bytes) ----
static_assert(sizeof(_stat) == 70,
              "sizeof(_stat) != 70");
static_assert(__builtin_offsetof(_stat, _st_dev) == 0,
              "offsetof(_stat, _st_dev) != 0");
static_assert(__builtin_offsetof(_stat, _st_ino) == 4,
              "offsetof(_stat, _st_ino) != 4");
static_assert(__builtin_offsetof(_stat, _st_mode) == 8,
              "offsetof(_stat, _st_mode) != 8");
static_assert(__builtin_offsetof(_stat, _st_nlink) == 10,
              "offsetof(_stat, _st_nlink) != 10");
static_assert(__builtin_offsetof(_stat, _st_uid) == 12,
              "offsetof(_stat, _st_uid) != 12");
static_assert(__builtin_offsetof(_stat, _st_gid) == 16,
              "offsetof(_stat, _st_gid) != 16");
static_assert(__builtin_offsetof(_stat, _st_rdev) == 18,
              "offsetof(_stat, _st_rdev) != 18");
static_assert(__builtin_offsetof(_stat, _st_size) == 22,
              "offsetof(_stat, _st_size) != 22");
static_assert(__builtin_offsetof(_stat, _st_atime) == 26,
              "offsetof(_stat, _st_atime) != 26");
static_assert(__builtin_offsetof(_stat, _st_mtime) == 30,
              "offsetof(_stat, _st_mtime) != 30");
static_assert(__builtin_offsetof(_stat, _st_ctime) == 34,
              "offsetof(_stat, _st_ctime) != 34");
static_assert(__builtin_offsetof(_stat, _st_btime) == 38,
              "offsetof(_stat, _st_btime) != 38");
static_assert(__builtin_offsetof(_stat, _st_attr) == 42,
              "offsetof(_stat, _st_attr) != 42");
static_assert(__builtin_offsetof(_stat, _st_archivedID) == 46,
              "offsetof(_stat, _st_archivedID) != 46");
static_assert(__builtin_offsetof(_stat, _st_updatedID) == 50,
              "offsetof(_stat, _st_updatedID) != 50");
static_assert(__builtin_offsetof(_stat, _st_inheritedRightsMask) == 54,
              "offsetof(_stat, _st_inheritedRightsMask) != 54");
static_assert(__builtin_offsetof(_stat, _st_originatingNameSpace) == 56,
              "offsetof(_stat, _st_originatingNameSpace) != 56");
static_assert(__builtin_offsetof(_stat, _st_name) == 57,
              "offsetof(_stat, _st_name) != 57");

} // namespace

#endif  // __SIZEOF_POINTER__ == 4 (32-bit layout only)
