// Auto-generated by scripts/Python/gen_struct_layout_checks.py
// DO NOT EDIT BY HAND. Re-run the generator after updating types.
//
// Category: stdarg
// Structs : 1

#include "nocturne.h"

// The assertions below encode the 32-bit (matching-target) struct layout
// from Ghidra's data_types.json, so they are only valid when pointers are
// 4 bytes. On a native 64-bit build, pointer-containing structs
// legitimately change size/offset, so the checks are compiled out there;
// the file still compiles (catching type/name regressions) in both lanes.
#if __SIZEOF_POINTER__ == 4

namespace nocturne_layout_stdarg {

// ---- va_list_t (4 bytes) ----
static_assert(sizeof(va_list_t) == 4,
              "sizeof(va_list_t) != 4");
static_assert(__builtin_offsetof(va_list_t, value) == 0,
              "offsetof(va_list_t, value) != 0");

} // namespace

#endif  // __SIZEOF_POINTER__ == 4 (32-bit layout only)
