// Auto-generated by scripts/Python/gen_struct_layout_checks.py
// DO NOT EDIT BY HAND. Re-run the generator after updating types.
//
// Category: stdarg
// Structs : 1

#include "nocturne.h"

namespace nocturne_layout_stdarg {

// ---- va_list_t (4 bytes) ----
static_assert(sizeof(va_list_t) == 4,
              "sizeof(va_list_t) != 4");
static_assert(__builtin_offsetof(va_list_t, value) == 0,
              "offsetof(va_list_t, value) != 0");

} // namespace
