// Auto-generated by scripts/Python/gen_struct_layout_checks.py
// DO NOT EDIT BY HAND. Re-run the generator after updating types.
//
// Category: stdio
// Structs : 10

#include "nocturne.h"

namespace nocturne_layout_stdio {

// ---- FORMAT_OUTPUT_CONTEXT (40 bytes) ----
static_assert(sizeof(FORMAT_OUTPUT_CONTEXT) == 40,
              "sizeof(FORMAT_OUTPUT_CONTEXT) != 40");
static_assert(__builtin_offsetof(FORMAT_OUTPUT_CONTEXT, output_file) == 0,
              "offsetof(FORMAT_OUTPUT_CONTEXT, output_file) != 0");
static_assert(__builtin_offsetof(FORMAT_OUTPUT_CONTEXT, format_ptr) == 4,
              "offsetof(FORMAT_OUTPUT_CONTEXT, format_ptr) != 4");
static_assert(__builtin_offsetof(FORMAT_OUTPUT_CONTEXT, args) == 8,
              "offsetof(FORMAT_OUTPUT_CONTEXT, args) != 8");
static_assert(__builtin_offsetof(FORMAT_OUTPUT_CONTEXT, field_width) == 12,
              "offsetof(FORMAT_OUTPUT_CONTEXT, field_width) != 12");
static_assert(__builtin_offsetof(FORMAT_OUTPUT_CONTEXT, char_count) == 16,
              "offsetof(FORMAT_OUTPUT_CONTEXT, char_count) != 16");
static_assert(__builtin_offsetof(FORMAT_OUTPUT_CONTEXT, precision) == 20,
              "offsetof(FORMAT_OUTPUT_CONTEXT, precision) != 20");
static_assert(__builtin_offsetof(FORMAT_OUTPUT_CONTEXT, format_flags) == 24,
              "offsetof(FORMAT_OUTPUT_CONTEXT, format_flags) != 24");
static_assert(__builtin_offsetof(FORMAT_OUTPUT_CONTEXT, error_status) == 28,
              "offsetof(FORMAT_OUTPUT_CONTEXT, error_status) != 28");
static_assert(__builtin_offsetof(FORMAT_OUTPUT_CONTEXT, buffer_ptr) == 32,
              "offsetof(FORMAT_OUTPUT_CONTEXT, buffer_ptr) != 32");
static_assert(__builtin_offsetof(FORMAT_OUTPUT_CONTEXT, buffer_limit) == 36,
              "offsetof(FORMAT_OUTPUT_CONTEXT, buffer_limit) != 36");

// ---- FileBase (8 bytes) ----
static_assert(sizeof(FileBase) == 8,
              "sizeof(FileBase) != 8");
static_assert(__builtin_offsetof(FileBase, type_or_magic) == 0,
              "offsetof(FileBase, type_or_magic) != 0");
static_assert(__builtin_offsetof(FileBase, data_offset) == 4,
              "offsetof(FileBase, data_offset) != 4");

// ---- FileContext (4 bytes) ----
static_assert(sizeof(FileContext) == 4,
              "sizeof(FileContext) != 4");
static_assert(__builtin_offsetof(FileContext, base) == 0,
              "offsetof(FileContext, base) != 0");

// ---- FileDescriptor (4 bytes) ----
static_assert(sizeof(FileDescriptor) == 4,
              "sizeof(FileDescriptor) != 4");
static_assert(__builtin_offsetof(FileDescriptor, file_type) == 0,
              "offsetof(FileDescriptor, file_type) != 0");
static_assert(__builtin_offsetof(FileDescriptor, device_flags) == 1,
              "offsetof(FileDescriptor, device_flags) != 1");
static_assert(__builtin_offsetof(FileDescriptor, access_flags) == 2,
              "offsetof(FileDescriptor, access_flags) != 2");
static_assert(__builtin_offsetof(FileDescriptor, extended_flags) == 3,
              "offsetof(FileDescriptor, extended_flags) != 3");

// ---- FileEmbeddedData (24 bytes) ----
static_assert(sizeof(FileEmbeddedData) == 24,
              "sizeof(FileEmbeddedData) != 24");
static_assert(__builtin_offsetof(FileEmbeddedData, flags) == 0,
              "offsetof(FileEmbeddedData, flags) != 0");
static_assert(__builtin_offsetof(FileEmbeddedData, stream) == 4,
              "offsetof(FileEmbeddedData, stream) != 4");
static_assert(__builtin_offsetof(FileEmbeddedData, index) == 8,
              "offsetof(FileEmbeddedData, index) != 8");
static_assert(__builtin_offsetof(FileEmbeddedData, pos) == 12,
              "offsetof(FileEmbeddedData, pos) != 12");
static_assert(__builtin_offsetof(FileEmbeddedData, state_field) == 16,
              "offsetof(FileEmbeddedData, state_field) != 16");
static_assert(__builtin_offsetof(FileEmbeddedData, error_mask) == 20,
              "offsetof(FileEmbeddedData, error_mask) != 20");

// ---- FileListNode (33 bytes) ----
static_assert(sizeof(FileListNode) == 33,
              "sizeof(FileListNode) != 33");
static_assert(__builtin_offsetof(FileListNode, next) == 0,
              "offsetof(FileListNode, next) != 0");
static_assert(__builtin_offsetof(FileListNode, file_struct) == 4,
              "offsetof(FileListNode, file_struct) != 4");
static_assert(__builtin_offsetof(FileListNode, back_pointer) == 8,
              "offsetof(FileListNode, back_pointer) != 8");
static_assert(__builtin_offsetof(FileListNode, flags) == 12,
              "offsetof(FileListNode, flags) != 12");
static_assert(__builtin_offsetof(FileListNode, reserved) == 16,
              "offsetof(FileListNode, reserved) != 16");

// ---- FormatSpec (60 bytes) ----
static_assert(sizeof(FormatSpec) == 60,
              "sizeof(FormatSpec) != 60");
static_assert(__builtin_offsetof(FormatSpec, unknown_0x00) == 0,
              "offsetof(FormatSpec, unknown_0x00) != 0");
static_assert(__builtin_offsetof(FormatSpec, width) == 4,
              "offsetof(FormatSpec, width) != 4");
static_assert(__builtin_offsetof(FormatSpec, precision) == 8,
              "offsetof(FormatSpec, precision) != 8");
static_assert(__builtin_offsetof(FormatSpec, total_output_count) == 12,
              "offsetof(FormatSpec, total_output_count) != 12");
static_assert(__builtin_offsetof(FormatSpec, padding1) == 16,
              "offsetof(FormatSpec, padding1) != 16");
static_assert(__builtin_offsetof(FormatSpec, format_char) == 17,
              "offsetof(FormatSpec, format_char) != 17");
static_assert(__builtin_offsetof(FormatSpec, padding_char) == 18,
              "offsetof(FormatSpec, padding_char) != 18");
static_assert(__builtin_offsetof(FormatSpec, padding2) == 19,
              "offsetof(FormatSpec, padding2) != 19");
static_assert(__builtin_offsetof(FormatSpec, conversion_char) == 21,
              "offsetof(FormatSpec, conversion_char) != 21");
static_assert(__builtin_offsetof(FormatSpec, zerofill) == 22,
              "offsetof(FormatSpec, zerofill) != 22");
static_assert(__builtin_offsetof(FormatSpec, unknown_0x17) == 23,
              "offsetof(FormatSpec, unknown_0x17) != 23");
static_assert(__builtin_offsetof(FormatSpec, extended_length_flags) == 24,
              "offsetof(FormatSpec, extended_length_flags) != 24");
static_assert(__builtin_offsetof(FormatSpec, unknown_0x1C) == 28,
              "offsetof(FormatSpec, unknown_0x1C) != 28");
static_assert(__builtin_offsetof(FormatSpec, flags) == 30,
              "offsetof(FormatSpec, flags) != 30");
static_assert(__builtin_offsetof(FormatSpec, length_flags) == 31,
              "offsetof(FormatSpec, length_flags) != 31");
static_assert(__builtin_offsetof(FormatSpec, output_length) == 32,
              "offsetof(FormatSpec, output_length) != 32");
static_assert(__builtin_offsetof(FormatSpec, padding_needed) == 36,
              "offsetof(FormatSpec, padding_needed) != 36");
static_assert(__builtin_offsetof(FormatSpec, content_length) == 40,
              "offsetof(FormatSpec, content_length) != 40");
static_assert(__builtin_offsetof(FormatSpec, prefix_length) == 44,
              "offsetof(FormatSpec, prefix_length) != 44");
static_assert(__builtin_offsetof(FormatSpec, suffix_length) == 48,
              "offsetof(FormatSpec, suffix_length) != 48");
static_assert(__builtin_offsetof(FormatSpec, alternate_form_length) == 52,
              "offsetof(FormatSpec, alternate_form_length) != 52");
static_assert(__builtin_offsetof(FormatSpec, length_modifier_flags) == 56,
              "offsetof(FormatSpec, length_modifier_flags) != 56");

// ---- StringOutputContext (20 bytes) ----
static_assert(sizeof(StringOutputContext) == 20,
              "sizeof(StringOutputContext) != 20");
static_assert(__builtin_offsetof(StringOutputContext, buffer_ptr) == 0,
              "offsetof(StringOutputContext, buffer_ptr) != 0");
static_assert(__builtin_offsetof(StringOutputContext, unknown) == 4,
              "offsetof(StringOutputContext, unknown) != 4");
static_assert(__builtin_offsetof(StringOutputContext, chars_written) == 16,
              "offsetof(StringOutputContext, chars_written) != 16");

// ---- _FILE (26 bytes) ----
static_assert(sizeof(_FILE) == 26,
              "sizeof(_FILE) != 26");
static_assert(__builtin_offsetof(_FILE, _ptr) == 0,
              "offsetof(_FILE, _ptr) != 0");
static_assert(__builtin_offsetof(_FILE, _cnt) == 4,
              "offsetof(_FILE, _cnt) != 4");
static_assert(__builtin_offsetof(_FILE, _link) == 8,
              "offsetof(_FILE, _link) != 8");
static_assert(__builtin_offsetof(_FILE, _flag) == 12,
              "offsetof(_FILE, _flag) != 12");
static_assert(__builtin_offsetof(_FILE, _handle) == 16,
              "offsetof(_FILE, _handle) != 16");
static_assert(__builtin_offsetof(_FILE, _bufsize) == 20,
              "offsetof(_FILE, _bufsize) != 20");
static_assert(__builtin_offsetof(_FILE, _ungotten) == 24,
              "offsetof(_FILE, _ungotten) != 24");

// ---- scanf_state_t (48 bytes) ----
static_assert(sizeof(scanf_state_t) == 48,
              "sizeof(scanf_state_t) != 48");
static_assert(__builtin_offsetof(scanf_state_t, getc_func) == 0,
              "offsetof(scanf_state_t, getc_func) != 0");
static_assert(__builtin_offsetof(scanf_state_t, ungetc_func) == 4,
              "offsetof(scanf_state_t, ungetc_func) != 4");
static_assert(__builtin_offsetof(scanf_state_t, input_ptr) == 8,
              "offsetof(scanf_state_t, input_ptr) != 8");
static_assert(__builtin_offsetof(scanf_state_t, field_width) == 12,
              "offsetof(scanf_state_t, field_width) != 12");
static_assert(__builtin_offsetof(scanf_state_t, flags) == 16,
              "offsetof(scanf_state_t, flags) != 16");
static_assert(__builtin_offsetof(scanf_state_t, conversion) == 17,
              "offsetof(scanf_state_t, conversion) != 17");
static_assert(__builtin_offsetof(scanf_state_t, base) == 18,
              "offsetof(scanf_state_t, base) != 18");
static_assert(__builtin_offsetof(scanf_state_t, reserved) == 19,
              "offsetof(scanf_state_t, reserved) != 19");
static_assert(__builtin_offsetof(scanf_state_t, assignments_made) == 20,
              "offsetof(scanf_state_t, assignments_made) != 20");
static_assert(__builtin_offsetof(scanf_state_t, chars_consumed) == 24,
              "offsetof(scanf_state_t, chars_consumed) != 24");
static_assert(__builtin_offsetof(scanf_state_t, unget_char) == 28,
              "offsetof(scanf_state_t, unget_char) != 28");
static_assert(__builtin_offsetof(scanf_state_t, char_table) == 32,
              "offsetof(scanf_state_t, char_table) != 32");
static_assert(__builtin_offsetof(scanf_state_t, current_arg) == 36,
              "offsetof(scanf_state_t, current_arg) != 36");
static_assert(__builtin_offsetof(scanf_state_t, scan_set) == 40,
              "offsetof(scanf_state_t, scan_set) != 40");
static_assert(__builtin_offsetof(scanf_state_t, state_flags) == 44,
              "offsetof(scanf_state_t, state_flags) != 44");
static_assert(__builtin_offsetof(scanf_state_t, input_base) == 46,
              "offsetof(scanf_state_t, input_base) != 46");
static_assert(__builtin_offsetof(scanf_state_t, pad) == 47,
              "offsetof(scanf_state_t, pad) != 47");

} // namespace
