// Auto-generated by scripts/Python/gen_struct_layout_checks.py
// DO NOT EDIT BY HAND. Re-run the generator after updating types.
//
// Category: stdlib
// Structs : 4

#include "nocturne.h"

namespace nocturne_layout_stdlib {

// ---- Heap (12 bytes) ----
static_assert(sizeof(Heap) == 12,
              "sizeof(Heap) != 12");
static_assert(__builtin_offsetof(Heap, heap_size) == 0,
              "offsetof(Heap, heap_size) != 0");
static_assert(__builtin_offsetof(Heap, heap_base) == 4,
              "offsetof(Heap, heap_base) != 4");
static_assert(__builtin_offsetof(Heap, next_heap_block) == 8,
              "offsetof(Heap, next_heap_block) != 8");

// ---- HeapBlock (44 bytes) ----
static_assert(sizeof(HeapBlock) == 44,
              "sizeof(HeapBlock) != 44");
static_assert(__builtin_offsetof(HeapBlock, size) == 0,
              "offsetof(HeapBlock, size) != 0");
static_assert(__builtin_offsetof(HeapBlock, prev) == 4,
              "offsetof(HeapBlock, prev) != 4");
static_assert(__builtin_offsetof(HeapBlock, next) == 8,
              "offsetof(HeapBlock, next) != 8");
static_assert(__builtin_offsetof(HeapBlock, heap_info) == 12,
              "offsetof(HeapBlock, heap_info) != 12");
static_assert(__builtin_offsetof(HeapBlock, largest_free) == 16,
              "offsetof(HeapBlock, largest_free) != 16");
static_assert(__builtin_offsetof(HeapBlock, block_size) == 20,
              "offsetof(HeapBlock, block_size) != 20");
static_assert(__builtin_offsetof(HeapBlock, alloc_count) == 24,
              "offsetof(HeapBlock, alloc_count) != 24");
static_assert(__builtin_offsetof(HeapBlock, free_count) == 28,
              "offsetof(HeapBlock, free_count) != 28");
static_assert(__builtin_offsetof(HeapBlock, free_list_area) == 32,
              "offsetof(HeapBlock, free_list_area) != 32");
static_assert(__builtin_offsetof(HeapBlock, data_area) == 40,
              "offsetof(HeapBlock, data_area) != 40");

// ---- HeapState (14 bytes) ----
static_assert(sizeof(HeapState) == 14,
              "sizeof(HeapState) != 14");
static_assert(__builtin_offsetof(HeapState, current_block_ptr) == 0,
              "offsetof(HeapState, current_block_ptr) != 0");
static_assert(__builtin_offsetof(HeapState, segment_selector) == 4,
              "offsetof(HeapState, segment_selector) != 4");
static_assert(__builtin_offsetof(HeapState, block_size) == 6,
              "offsetof(HeapState, block_size) != 6");
static_assert(__builtin_offsetof(HeapState, allocation_status) == 10,
              "offsetof(HeapState, allocation_status) != 10");

// ---- RuntimeHandlerEntry (6 bytes) ----
static_assert(sizeof(RuntimeHandlerEntry) == 6,
              "sizeof(RuntimeHandlerEntry) != 6");
static_assert(__builtin_offsetof(RuntimeHandlerEntry, status) == 0,
              "offsetof(RuntimeHandlerEntry, status) != 0");
static_assert(__builtin_offsetof(RuntimeHandlerEntry, priority) == 1,
              "offsetof(RuntimeHandlerEntry, priority) != 1");
static_assert(__builtin_offsetof(RuntimeHandlerEntry, func) == 2,
              "offsetof(RuntimeHandlerEntry, func) != 2");

} // namespace
