// Auto-generated by scripts/Python/gen_struct_layout_checks.py
// DO NOT EDIT BY HAND. Re-run the generator after updating types.
//
// Category: uncategorized
// Structs : 1

#include "nocturne.h"

// The assertions below encode the 32-bit (matching-target) struct layout
// from Ghidra's data_types.json, so they are only valid when pointers are
// 4 bytes. On a native 64-bit build, pointer-containing structs
// legitimately change size/offset, so the checks are compiled out there;
// the file still compiles (catching type/name regressions) in both lanes.
#if __SIZEOF_POINTER__ == 4

namespace nocturne_layout_uncategorized {

// ---- IMAGE_RESOURCE_DIRECTORY_ENTRY_DirectoryStruct (8 bytes) ----
static_assert(sizeof(IMAGE_RESOURCE_DIRECTORY_ENTRY_DirectoryStruct) == 8,
              "sizeof(IMAGE_RESOURCE_DIRECTORY_ENTRY_DirectoryStruct) != 8");
static_assert(__builtin_offsetof(IMAGE_RESOURCE_DIRECTORY_ENTRY_DirectoryStruct, OffsetToDirectory) == 0,
              "offsetof(IMAGE_RESOURCE_DIRECTORY_ENTRY_DirectoryStruct, OffsetToDirectory) != 0");
static_assert(__builtin_offsetof(IMAGE_RESOURCE_DIRECTORY_ENTRY_DirectoryStruct, DataIsDirectory) == 4,
              "offsetof(IMAGE_RESOURCE_DIRECTORY_ENTRY_DirectoryStruct, DataIsDirectory) != 4");

} // namespace

#endif  // __SIZEOF_POINTER__ == 4 (32-bit layout only)
