// Auto-generated by scripts/Python/gen_struct_layout_checks.py
// DO NOT EDIT BY HAND. Re-run the generator after updating types.
//
// Category: unknwn
// Structs : 2

#include "nocturne.h"

// The assertions below encode the 32-bit (matching-target) struct layout
// from Ghidra's data_types.json, so they are only valid when pointers are
// 4 bytes. On a native 64-bit build, pointer-containing structs
// legitimately change size/offset, so the checks are compiled out there;
// the file still compiles (catching type/name regressions) in both lanes.
#if __SIZEOF_POINTER__ == 4

namespace nocturne_layout_unknwn {

// ---- IUnknown (4 bytes) ----
static_assert(sizeof(IUnknown) == 4,
              "sizeof(IUnknown) != 4");
static_assert(__builtin_offsetof(IUnknown, vtable) == 0,
              "offsetof(IUnknown, vtable) != 0");

// ---- IUnknown_vtable (12 bytes) ----
static_assert(sizeof(IUnknown_vtable) == 12,
              "sizeof(IUnknown_vtable) != 12");
static_assert(__builtin_offsetof(IUnknown_vtable, QueryInterface) == 0,
              "offsetof(IUnknown_vtable, QueryInterface) != 0");
static_assert(__builtin_offsetof(IUnknown_vtable, AddRef) == 4,
              "offsetof(IUnknown_vtable, AddRef) != 4");
static_assert(__builtin_offsetof(IUnknown_vtable, Release) == 8,
              "offsetof(IUnknown_vtable, Release) != 8");

} // namespace

#endif  // __SIZEOF_POINTER__ == 4 (32-bit layout only)
