// Auto-generated by scripts/Python/gen_struct_layout_checks.py
// DO NOT EDIT BY HAND. Re-run the generator after updating types.
//
// Category: unknwn
// Structs : 2

#include "nocturne.h"

namespace nocturne_layout_unknwn {

// ---- IUnknown (4 bytes) ----
static_assert(sizeof(IUnknown) == 4,
              "sizeof(IUnknown) != 4");
static_assert(__builtin_offsetof(IUnknown, vtable) == 0,
              "offsetof(IUnknown, vtable) != 0");

// ---- IUnknown_vtable (12 bytes) ----
static_assert(sizeof(IUnknown_vtable) == 12,
              "sizeof(IUnknown_vtable) != 12");
static_assert(__builtin_offsetof(IUnknown_vtable, QueryInterface) == 0,
              "offsetof(IUnknown_vtable, QueryInterface) != 0");
static_assert(__builtin_offsetof(IUnknown_vtable, AddRef) == 4,
              "offsetof(IUnknown_vtable, AddRef) != 4");
static_assert(__builtin_offsetof(IUnknown_vtable, Release) == 8,
              "offsetof(IUnknown_vtable, Release) != 8");

} // namespace
