// Auto-generated by scripts/Python/gen_struct_layout_checks.py
// DO NOT EDIT BY HAND. Re-run the generator after updating types.
//
// Category: watcom
// Structs : 15

#include "nocturne.h"

namespace nocturne_layout_watcom {

// ---- ExceptionFrame (8 bytes) ----
static_assert(sizeof(ExceptionFrame) == 8,
              "sizeof(ExceptionFrame) != 8");
static_assert(__builtin_offsetof(ExceptionFrame, prev) == 0,
              "offsetof(ExceptionFrame, prev) != 0");
static_assert(__builtin_offsetof(ExceptionFrame, handler) == 4,
              "offsetof(ExceptionFrame, handler) != 4");

// ---- ReentrantCriticalSection (16 bytes) ----
static_assert(sizeof(ReentrantCriticalSection) == 16,
              "sizeof(ReentrantCriticalSection) != 16");
static_assert(__builtin_offsetof(ReentrantCriticalSection, cs) == 0,
              "offsetof(ReentrantCriticalSection, cs) != 0");
static_assert(__builtin_offsetof(ReentrantCriticalSection, initialized) == 4,
              "offsetof(ReentrantCriticalSection, initialized) != 4");
static_assert(__builtin_offsetof(ReentrantCriticalSection, ownerThreadId) == 8,
              "offsetof(ReentrantCriticalSection, ownerThreadId) != 8");
static_assert(__builtin_offsetof(ReentrantCriticalSection, lockCount) == 12,
              "offsetof(ReentrantCriticalSection, lockCount) != 12");

// ---- ThreadData (248 bytes) ----
static_assert(sizeof(ThreadData) == 248,
              "sizeof(ThreadData) != 248");
static_assert(__builtin_offsetof(ThreadData, stack_limit) == 0,
              "offsetof(ThreadData, stack_limit) != 0");
static_assert(__builtin_offsetof(ThreadData, errno_value) == 4,
              "offsetof(ThreadData, errno_value) != 4");
static_assert(__builtin_offsetof(ThreadData, windows_error_code) == 8,
              "offsetof(ThreadData, windows_error_code) != 8");
static_assert(__builtin_offsetof(ThreadData, random_seed) == 12,
              "offsetof(ThreadData, random_seed) != 12");
static_assert(__builtin_offsetof(ThreadData, unknown_10) == 16,
              "offsetof(ThreadData, unknown_10) != 16");
static_assert(__builtin_offsetof(ThreadData, localtime_buffer) == 20,
              "offsetof(ThreadData, localtime_buffer) != 20");
static_assert(__builtin_offsetof(ThreadData, asctime_buffer) == 56,
              "offsetof(ThreadData, asctime_buffer) != 56");
static_assert(__builtin_offsetof(ThreadData, padding_0x52) == 82,
              "offsetof(ThreadData, padding_0x52) != 82");
static_assert(__builtin_offsetof(ThreadData, seh_frame) == 84,
              "offsetof(ThreadData, seh_frame) != 84");
static_assert(__builtin_offsetof(ThreadData, exception_info) == 88,
              "offsetof(ThreadData, exception_info) != 88");
static_assert(__builtin_offsetof(ThreadData, signal_handlers) == 92,
              "offsetof(ThreadData, signal_handlers) != 92");
static_assert(__builtin_offsetof(ThreadData, padding_0xd4) == 212,
              "offsetof(ThreadData, padding_0xd4) != 212");
static_assert(__builtin_offsetof(ThreadData, cleanup_data) == 218,
              "offsetof(ThreadData, cleanup_data) != 218");
static_assert(__builtin_offsetof(ThreadData, thread_handle) == 222,
              "offsetof(ThreadData, thread_handle) != 222");
static_assert(__builtin_offsetof(ThreadData, unknown_E2) == 226,
              "offsetof(ThreadData, unknown_E2) != 226");
static_assert(__builtin_offsetof(ThreadData, heap_info) == 244,
              "offsetof(ThreadData, heap_info) != 244");

// ---- ThreadRegistryEntry (16 bytes) ----
static_assert(sizeof(ThreadRegistryEntry) == 16,
              "sizeof(ThreadRegistryEntry) != 16");
static_assert(__builtin_offsetof(ThreadRegistryEntry, next) == 0,
              "offsetof(ThreadRegistryEntry, next) != 0");
static_assert(__builtin_offsetof(ThreadRegistryEntry, threadDataKey) == 4,
              "offsetof(ThreadRegistryEntry, threadDataKey) != 4");
static_assert(__builtin_offsetof(ThreadRegistryEntry, dataBuffer) == 8,
              "offsetof(ThreadRegistryEntry, dataBuffer) != 8");
static_assert(__builtin_offsetof(ThreadRegistryEntry, shouldFreeData) == 12,
              "offsetof(ThreadRegistryEntry, shouldFreeData) != 12");

// ---- ThreadStartupInfo (20 bytes) ----
static_assert(sizeof(ThreadStartupInfo) == 20,
              "sizeof(ThreadStartupInfo) != 20");
static_assert(__builtin_offsetof(ThreadStartupInfo, thread_proc) == 0,
              "offsetof(ThreadStartupInfo, thread_proc) != 0");
static_assert(__builtin_offsetof(ThreadStartupInfo, param) == 4,
              "offsetof(ThreadStartupInfo, param) != 4");
static_assert(__builtin_offsetof(ThreadStartupInfo, reserved) == 8,
              "offsetof(ThreadStartupInfo, reserved) != 8");
static_assert(__builtin_offsetof(ThreadStartupInfo, start_event) == 12,
              "offsetof(ThreadStartupInfo, start_event) != 12");
static_assert(__builtin_offsetof(ThreadStartupInfo, tls_ptr) == 16,
              "offsetof(ThreadStartupInfo, tls_ptr) != 16");

// ---- WatcomDestructorCall (12 bytes) ----
static_assert(sizeof(WatcomDestructorCall) == 12,
              "sizeof(WatcomDestructorCall) != 12");
static_assert(__builtin_offsetof(WatcomDestructorCall, delete_flags) == 0,
              "offsetof(WatcomDestructorCall, delete_flags) != 0");
static_assert(__builtin_offsetof(WatcomDestructorCall, destructor_func) == 4,
              "offsetof(WatcomDestructorCall, destructor_func) != 4");
static_assert(__builtin_offsetof(WatcomDestructorCall, object_instance) == 8,
              "offsetof(WatcomDestructorCall, object_instance) != 8");

// ---- WatcomDestructorFlags (48 bytes) ----
static_assert(sizeof(WatcomDestructorFlags) == 48,
              "sizeof(WatcomDestructorFlags) != 48");
static_assert(__builtin_offsetof(WatcomDestructorFlags, field0_0x0) == 0,
              "offsetof(WatcomDestructorFlags, field0_0x0) != 0");

// ---- WatcomInheritanceLayout (8 bytes) ----
static_assert(sizeof(WatcomInheritanceLayout) == 8,
              "sizeof(WatcomInheritanceLayout) != 8");
static_assert(__builtin_offsetof(WatcomInheritanceLayout, base_type) == 0,
              "offsetof(WatcomInheritanceLayout, base_type) != 0");
static_assert(__builtin_offsetof(WatcomInheritanceLayout, offset_to_base) == 4,
              "offsetof(WatcomInheritanceLayout, offset_to_base) != 4");

// ---- WatcomStaticDestructorNode (16 bytes) ----
static_assert(sizeof(WatcomStaticDestructorNode) == 16,
              "sizeof(WatcomStaticDestructorNode) != 16");
static_assert(__builtin_offsetof(WatcomStaticDestructorNode, next) == 0,
              "offsetof(WatcomStaticDestructorNode, next) != 0");
static_assert(__builtin_offsetof(WatcomStaticDestructorNode, destructor_info) == 4,
              "offsetof(WatcomStaticDestructorNode, destructor_info) != 4");
static_assert(__builtin_offsetof(WatcomStaticDestructorNode, registration_type) == 8,
              "offsetof(WatcomStaticDestructorNode, registration_type) != 8");
static_assert(__builtin_offsetof(WatcomStaticDestructorNode, object_instance) == 12,
              "offsetof(WatcomStaticDestructorNode, object_instance) != 12");

// ---- WatcomThunkedDestructor (8 bytes) ----
static_assert(sizeof(WatcomThunkedDestructor) == 8,
              "sizeof(WatcomThunkedDestructor) != 8");
static_assert(__builtin_offsetof(WatcomThunkedDestructor, destructor_func) == 0,
              "offsetof(WatcomThunkedDestructor, destructor_func) != 0");
static_assert(__builtin_offsetof(WatcomThunkedDestructor, this_adjustment_ptr) == 4,
              "offsetof(WatcomThunkedDestructor, this_adjustment_ptr) != 4");

// ---- WatcomThunkedDestructorDirect (8 bytes) ----
static_assert(sizeof(WatcomThunkedDestructorDirect) == 8,
              "sizeof(WatcomThunkedDestructorDirect) != 8");
static_assert(__builtin_offsetof(WatcomThunkedDestructorDirect, destructor_func) == 0,
              "offsetof(WatcomThunkedDestructorDirect, destructor_func) != 0");
static_assert(__builtin_offsetof(WatcomThunkedDestructorDirect, this_adjustment) == 4,
              "offsetof(WatcomThunkedDestructorDirect, this_adjustment) != 4");

// ---- WatcomTypeArrayInfo (12 bytes) ----
static_assert(sizeof(WatcomTypeArrayInfo) == 12,
              "sizeof(WatcomTypeArrayInfo) != 12");
static_assert(__builtin_offsetof(WatcomTypeArrayInfo, obj_count) == 0,
              "offsetof(WatcomTypeArrayInfo, obj_count) != 0");
static_assert(__builtin_offsetof(WatcomTypeArrayInfo, type_info) == 4,
              "offsetof(WatcomTypeArrayInfo, type_info) != 4");
static_assert(__builtin_offsetof(WatcomTypeArrayInfo, obj_array) == 8,
              "offsetof(WatcomTypeArrayInfo, obj_array) != 8");

// ---- WatcomTypeInfo (24 bytes) ----
static_assert(sizeof(WatcomTypeInfo) == 24,
              "sizeof(WatcomTypeInfo) != 24");
static_assert(__builtin_offsetof(WatcomTypeInfo, type_flags) == 0,
              "offsetof(WatcomTypeInfo, type_flags) != 0");
static_assert(__builtin_offsetof(WatcomTypeInfo, ctor) == 4,
              "offsetof(WatcomTypeInfo, ctor) != 4");
static_assert(__builtin_offsetof(WatcomTypeInfo, copy) == 8,
              "offsetof(WatcomTypeInfo, copy) != 8");
static_assert(__builtin_offsetof(WatcomTypeInfo, dtor) == 12,
              "offsetof(WatcomTypeInfo, dtor) != 12");
static_assert(__builtin_offsetof(WatcomTypeInfo, instance_size) == 16,
              "offsetof(WatcomTypeInfo, instance_size) != 16");
static_assert(__builtin_offsetof(WatcomTypeInfo, class_name) == 20,
              "offsetof(WatcomTypeInfo, class_name) != 20");

// ---- WatcomVirtualBaseDescriptor (8 bytes) ----
static_assert(sizeof(WatcomVirtualBaseDescriptor) == 8,
              "sizeof(WatcomVirtualBaseDescriptor) != 8");
static_assert(__builtin_offsetof(WatcomVirtualBaseDescriptor, flags) == 0,
              "offsetof(WatcomVirtualBaseDescriptor, flags) != 0");
static_assert(__builtin_offsetof(WatcomVirtualBaseDescriptor, offset_to_vbase) == 4,
              "offsetof(WatcomVirtualBaseDescriptor, offset_to_vbase) != 4");

// ---- _heapinfo (14 bytes) ----
static_assert(sizeof(_heapinfo) == 14,
              "sizeof(_heapinfo) != 14");
static_assert(__builtin_offsetof(_heapinfo, _pentry) == 0,
              "offsetof(_heapinfo, _pentry) != 0");
static_assert(__builtin_offsetof(_heapinfo, _segment) == 4,
              "offsetof(_heapinfo, _segment) != 4");
static_assert(__builtin_offsetof(_heapinfo, _size) == 6,
              "offsetof(_heapinfo, _size) != 6");
static_assert(__builtin_offsetof(_heapinfo, _useflag) == 10,
              "offsetof(_heapinfo, _useflag) != 10");

} // namespace
