// Auto-generated by scripts/Python/gen_struct_layout_checks.py
// DO NOT EDIT BY HAND. Re-run the generator after updating types.
//
// Category: windef
// Structs : 15

#include "nocturne.h"

// The assertions below encode the 32-bit (matching-target) struct layout
// from Ghidra's data_types.json, so they are only valid when pointers are
// 4 bytes. On a native 64-bit build, pointer-containing structs
// legitimately change size/offset, so the checks are compiled out there;
// the file still compiles (catching type/name regressions) in both lanes.
#if __SIZEOF_POINTER__ == 4

namespace nocturne_layout_windef {

// ---- HBITMAP__ (4 bytes) ----
static_assert(sizeof(HBITMAP__) == 4,
              "sizeof(HBITMAP__) != 4");
static_assert(__builtin_offsetof(HBITMAP__, unused) == 0,
              "offsetof(HBITMAP__, unused) != 0");

// ---- HBRUSH__ (4 bytes) ----
static_assert(sizeof(HBRUSH__) == 4,
              "sizeof(HBRUSH__) != 4");
static_assert(__builtin_offsetof(HBRUSH__, unused) == 0,
              "offsetof(HBRUSH__, unused) != 0");

// ---- HDC__ (4 bytes) ----
static_assert(sizeof(HDC__) == 4,
              "sizeof(HDC__) != 4");
static_assert(__builtin_offsetof(HDC__, unused) == 0,
              "offsetof(HDC__, unused) != 0");

// ---- HFONT__ (4 bytes) ----
static_assert(sizeof(HFONT__) == 4,
              "sizeof(HFONT__) != 4");
static_assert(__builtin_offsetof(HFONT__, unused) == 0,
              "offsetof(HFONT__, unused) != 0");

// ---- HICON__ (4 bytes) ----
static_assert(sizeof(HICON__) == 4,
              "sizeof(HICON__) != 4");
static_assert(__builtin_offsetof(HICON__, unused) == 0,
              "offsetof(HICON__, unused) != 0");

// ---- HINSTANCE__ (4 bytes) ----
static_assert(sizeof(HINSTANCE__) == 4,
              "sizeof(HINSTANCE__) != 4");
static_assert(__builtin_offsetof(HINSTANCE__, unused) == 0,
              "offsetof(HINSTANCE__, unused) != 0");

// ---- HINSTANCE__ (4 bytes) ----
static_assert(sizeof(HINSTANCE__) == 4,
              "sizeof(HINSTANCE__) != 4");
static_assert(__builtin_offsetof(HINSTANCE__, unused) == 0,
              "offsetof(HINSTANCE__, unused) != 0");

// ---- HKEY__ (4 bytes) ----
static_assert(sizeof(HKEY__) == 4,
              "sizeof(HKEY__) != 4");
static_assert(__builtin_offsetof(HKEY__, unused) == 0,
              "offsetof(HKEY__, unused) != 0");

// ---- HMENU__ (4 bytes) ----
static_assert(sizeof(HMENU__) == 4,
              "sizeof(HMENU__) != 4");
static_assert(__builtin_offsetof(HMENU__, unused) == 0,
              "offsetof(HMENU__, unused) != 0");

// ---- HWND__ (4 bytes) ----
static_assert(sizeof(HWND__) == 4,
              "sizeof(HWND__) != 4");
static_assert(__builtin_offsetof(HWND__, unused) == 0,
              "offsetof(HWND__, unused) != 0");

// ---- _FILETIME (8 bytes) ----
static_assert(sizeof(_FILETIME) == 8,
              "sizeof(_FILETIME) != 8");
static_assert(__builtin_offsetof(_FILETIME, dwLowDateTime) == 0,
              "offsetof(_FILETIME, dwLowDateTime) != 0");
static_assert(__builtin_offsetof(_FILETIME, dwHighDateTime) == 4,
              "offsetof(_FILETIME, dwHighDateTime) != 4");

// ---- tagPOINT (8 bytes) ----
static_assert(sizeof(tagPOINT) == 8,
              "sizeof(tagPOINT) != 8");
static_assert(__builtin_offsetof(tagPOINT, x) == 0,
              "offsetof(tagPOINT, x) != 0");
static_assert(__builtin_offsetof(tagPOINT, y) == 4,
              "offsetof(tagPOINT, y) != 4");

// ---- tagPOINT (8 bytes) ----
static_assert(sizeof(tagPOINT) == 8,
              "sizeof(tagPOINT) != 8");
static_assert(__builtin_offsetof(tagPOINT, x) == 0,
              "offsetof(tagPOINT, x) != 0");
static_assert(__builtin_offsetof(tagPOINT, y) == 4,
              "offsetof(tagPOINT, y) != 4");

// ---- tagRECT (16 bytes) ----
static_assert(sizeof(tagRECT) == 16,
              "sizeof(tagRECT) != 16");
static_assert(__builtin_offsetof(tagRECT, left) == 0,
              "offsetof(tagRECT, left) != 0");
static_assert(__builtin_offsetof(tagRECT, top) == 4,
              "offsetof(tagRECT, top) != 4");
static_assert(__builtin_offsetof(tagRECT, right) == 8,
              "offsetof(tagRECT, right) != 8");
static_assert(__builtin_offsetof(tagRECT, bottom) == 12,
              "offsetof(tagRECT, bottom) != 12");

// ---- tagSIZE (8 bytes) ----
static_assert(sizeof(tagSIZE) == 8,
              "sizeof(tagSIZE) != 8");
static_assert(__builtin_offsetof(tagSIZE, cx) == 0,
              "offsetof(tagSIZE, cx) != 0");
static_assert(__builtin_offsetof(tagSIZE, cy) == 4,
              "offsetof(tagSIZE, cy) != 4");

} // namespace

#endif  // __SIZEOF_POINTER__ == 4 (32-bit layout only)
