// Auto-generated by scripts/Python/gen_struct_layout_checks.py
// DO NOT EDIT BY HAND. Re-run the generator after updating types.
//
// Category: windef
// Structs : 2

#include "nocturne.h"

namespace nocturne_layout_windef {

// ---- HINSTANCE__ (4 bytes) ----
static_assert(sizeof(HINSTANCE__) == 4,
              "sizeof(HINSTANCE__) != 4");
static_assert(__builtin_offsetof(HINSTANCE__, unused) == 0,
              "offsetof(HINSTANCE__, unused) != 0");

// ---- tagPOINT (8 bytes) ----
static_assert(sizeof(tagPOINT) == 8,
              "sizeof(tagPOINT) != 8");
static_assert(__builtin_offsetof(tagPOINT, x) == 0,
              "offsetof(tagPOINT, x) != 0");
static_assert(__builtin_offsetof(tagPOINT, y) == 4,
              "offsetof(tagPOINT, y) != 4");

} // namespace
