// Auto-generated by scripts/Python/gen_struct_layout_checks.py
// DO NOT EDIT BY HAND. Re-run the generator after updating types.
//
// Category: windef
// Structs : 2

#include "nocturne.h"

// The assertions below encode the 32-bit (matching-target) struct layout
// from Ghidra's data_types.json, so they are only valid when pointers are
// 4 bytes. On a native 64-bit build, pointer-containing structs
// legitimately change size/offset, so the checks are compiled out there;
// the file still compiles (catching type/name regressions) in both lanes.
#if __SIZEOF_POINTER__ == 4

namespace nocturne_layout_windef {

// ---- HINSTANCE__ (4 bytes) ----
static_assert(sizeof(HINSTANCE__) == 4,
              "sizeof(HINSTANCE__) != 4");
static_assert(__builtin_offsetof(HINSTANCE__, unused) == 0,
              "offsetof(HINSTANCE__, unused) != 0");

// ---- tagPOINT (8 bytes) ----
static_assert(sizeof(tagPOINT) == 8,
              "sizeof(tagPOINT) != 8");
static_assert(__builtin_offsetof(tagPOINT, x) == 0,
              "offsetof(tagPOINT, x) != 0");
static_assert(__builtin_offsetof(tagPOINT, y) == 4,
              "offsetof(tagPOINT, y) != 4");

} // namespace

#endif  // __SIZEOF_POINTER__ == 4 (32-bit layout only)
