// Auto-generated by scripts/Python/gen_struct_layout_checks.py
// DO NOT EDIT BY HAND. Re-run the generator after updating types.
//
// Category: wingdi
// Structs : 4

#include "nocturne.h"

// The assertions below encode the 32-bit (matching-target) struct layout
// from Ghidra's data_types.json, so they are only valid when pointers are
// 4 bytes. On a native 64-bit build, pointer-containing structs
// legitimately change size/offset, so the checks are compiled out there;
// the file still compiles (catching type/name regressions) in both lanes.
#if __SIZEOF_POINTER__ == 4

namespace nocturne_layout_wingdi {

// ---- tagBITMAPINFO (44 bytes) ----
static_assert(sizeof(tagBITMAPINFO) == 44,
              "sizeof(tagBITMAPINFO) != 44");
static_assert(__builtin_offsetof(tagBITMAPINFO, bmiHeader) == 0,
              "offsetof(tagBITMAPINFO, bmiHeader) != 0");
static_assert(__builtin_offsetof(tagBITMAPINFO, bmiColors) == 40,
              "offsetof(tagBITMAPINFO, bmiColors) != 40");

// ---- tagBITMAPINFOHEADER (40 bytes) ----
static_assert(sizeof(tagBITMAPINFOHEADER) == 40,
              "sizeof(tagBITMAPINFOHEADER) != 40");
static_assert(__builtin_offsetof(tagBITMAPINFOHEADER, biSize) == 0,
              "offsetof(tagBITMAPINFOHEADER, biSize) != 0");
static_assert(__builtin_offsetof(tagBITMAPINFOHEADER, biWidth) == 4,
              "offsetof(tagBITMAPINFOHEADER, biWidth) != 4");
static_assert(__builtin_offsetof(tagBITMAPINFOHEADER, biHeight) == 8,
              "offsetof(tagBITMAPINFOHEADER, biHeight) != 8");
static_assert(__builtin_offsetof(tagBITMAPINFOHEADER, biPlanes) == 12,
              "offsetof(tagBITMAPINFOHEADER, biPlanes) != 12");
static_assert(__builtin_offsetof(tagBITMAPINFOHEADER, biBitCount) == 14,
              "offsetof(tagBITMAPINFOHEADER, biBitCount) != 14");
static_assert(__builtin_offsetof(tagBITMAPINFOHEADER, biCompression) == 16,
              "offsetof(tagBITMAPINFOHEADER, biCompression) != 16");
static_assert(__builtin_offsetof(tagBITMAPINFOHEADER, biSizeImage) == 20,
              "offsetof(tagBITMAPINFOHEADER, biSizeImage) != 20");
static_assert(__builtin_offsetof(tagBITMAPINFOHEADER, biXPelsPerMeter) == 24,
              "offsetof(tagBITMAPINFOHEADER, biXPelsPerMeter) != 24");
static_assert(__builtin_offsetof(tagBITMAPINFOHEADER, biYPelsPerMeter) == 28,
              "offsetof(tagBITMAPINFOHEADER, biYPelsPerMeter) != 28");
static_assert(__builtin_offsetof(tagBITMAPINFOHEADER, biClrUsed) == 32,
              "offsetof(tagBITMAPINFOHEADER, biClrUsed) != 32");
static_assert(__builtin_offsetof(tagBITMAPINFOHEADER, biClrImportant) == 36,
              "offsetof(tagBITMAPINFOHEADER, biClrImportant) != 36");

// ---- tagLOGBRUSH (12 bytes) ----
static_assert(sizeof(tagLOGBRUSH) == 12,
              "sizeof(tagLOGBRUSH) != 12");
static_assert(__builtin_offsetof(tagLOGBRUSH, lbStyle) == 0,
              "offsetof(tagLOGBRUSH, lbStyle) != 0");
static_assert(__builtin_offsetof(tagLOGBRUSH, lbColor) == 4,
              "offsetof(tagLOGBRUSH, lbColor) != 4");
static_assert(__builtin_offsetof(tagLOGBRUSH, lbHatch) == 8,
              "offsetof(tagLOGBRUSH, lbHatch) != 8");

// ---- tagRGBQUAD (4 bytes) ----
static_assert(sizeof(tagRGBQUAD) == 4,
              "sizeof(tagRGBQUAD) != 4");
static_assert(__builtin_offsetof(tagRGBQUAD, rgbBlue) == 0,
              "offsetof(tagRGBQUAD, rgbBlue) != 0");
static_assert(__builtin_offsetof(tagRGBQUAD, rgbGreen) == 1,
              "offsetof(tagRGBQUAD, rgbGreen) != 1");
static_assert(__builtin_offsetof(tagRGBQUAD, rgbRed) == 2,
              "offsetof(tagRGBQUAD, rgbRed) != 2");
static_assert(__builtin_offsetof(tagRGBQUAD, rgbReserved) == 3,
              "offsetof(tagRGBQUAD, rgbReserved) != 3");

} // namespace

#endif  // __SIZEOF_POINTER__ == 4 (32-bit layout only)
