// Auto-generated by scripts/Python/gen_struct_layout_checks.py
// DO NOT EDIT BY HAND. Re-run the generator after updating types.
//
// Category: winnt
// Structs : 15

#include "nocturne.h"

// The assertions below encode the 32-bit (matching-target) struct layout
// from Ghidra's data_types.json, so they are only valid when pointers are
// 4 bytes. On a native 64-bit build, pointer-containing structs
// legitimately change size/offset, so the checks are compiled out there;
// the file still compiles (catching type/name regressions) in both lanes.
#if __SIZEOF_POINTER__ == 4

namespace nocturne_layout_winnt {

// ---- EXCEPTION_REGISTRATION_RECORD (8 bytes) ----
static_assert(sizeof(EXCEPTION_REGISTRATION_RECORD) == 8,
              "sizeof(EXCEPTION_REGISTRATION_RECORD) != 8");
static_assert(__builtin_offsetof(EXCEPTION_REGISTRATION_RECORD, Next) == 0,
              "offsetof(EXCEPTION_REGISTRATION_RECORD, Next) != 0");
static_assert(__builtin_offsetof(EXCEPTION_REGISTRATION_RECORD, Handler) == 4,
              "offsetof(EXCEPTION_REGISTRATION_RECORD, Handler) != 4");

// ---- HKEY__ (4 bytes) ----
static_assert(sizeof(HKEY__) == 4,
              "sizeof(HKEY__) != 4");
static_assert(__builtin_offsetof(HKEY__, unused) == 0,
              "offsetof(HKEY__, unused) != 0");

// ---- _CONTEXT (716 bytes) ----
static_assert(sizeof(_CONTEXT) == 716,
              "sizeof(_CONTEXT) != 716");
static_assert(__builtin_offsetof(_CONTEXT, ContextFlags) == 0,
              "offsetof(_CONTEXT, ContextFlags) != 0");
static_assert(__builtin_offsetof(_CONTEXT, Dr0) == 4,
              "offsetof(_CONTEXT, Dr0) != 4");
static_assert(__builtin_offsetof(_CONTEXT, Dr1) == 8,
              "offsetof(_CONTEXT, Dr1) != 8");
static_assert(__builtin_offsetof(_CONTEXT, Dr2) == 12,
              "offsetof(_CONTEXT, Dr2) != 12");
static_assert(__builtin_offsetof(_CONTEXT, Dr3) == 16,
              "offsetof(_CONTEXT, Dr3) != 16");
static_assert(__builtin_offsetof(_CONTEXT, Dr6) == 20,
              "offsetof(_CONTEXT, Dr6) != 20");
static_assert(__builtin_offsetof(_CONTEXT, Dr7) == 24,
              "offsetof(_CONTEXT, Dr7) != 24");
static_assert(__builtin_offsetof(_CONTEXT, FloatSave) == 28,
              "offsetof(_CONTEXT, FloatSave) != 28");
static_assert(__builtin_offsetof(_CONTEXT, SegGs) == 140,
              "offsetof(_CONTEXT, SegGs) != 140");
static_assert(__builtin_offsetof(_CONTEXT, SegFs) == 144,
              "offsetof(_CONTEXT, SegFs) != 144");
static_assert(__builtin_offsetof(_CONTEXT, SegEs) == 148,
              "offsetof(_CONTEXT, SegEs) != 148");
static_assert(__builtin_offsetof(_CONTEXT, SegDs) == 152,
              "offsetof(_CONTEXT, SegDs) != 152");
static_assert(__builtin_offsetof(_CONTEXT, Edi) == 156,
              "offsetof(_CONTEXT, Edi) != 156");
static_assert(__builtin_offsetof(_CONTEXT, Esi) == 160,
              "offsetof(_CONTEXT, Esi) != 160");
static_assert(__builtin_offsetof(_CONTEXT, Ebx) == 164,
              "offsetof(_CONTEXT, Ebx) != 164");
static_assert(__builtin_offsetof(_CONTEXT, Edx) == 168,
              "offsetof(_CONTEXT, Edx) != 168");
static_assert(__builtin_offsetof(_CONTEXT, Ecx) == 172,
              "offsetof(_CONTEXT, Ecx) != 172");
static_assert(__builtin_offsetof(_CONTEXT, Eax) == 176,
              "offsetof(_CONTEXT, Eax) != 176");
static_assert(__builtin_offsetof(_CONTEXT, Ebp) == 180,
              "offsetof(_CONTEXT, Ebp) != 180");
static_assert(__builtin_offsetof(_CONTEXT, Eip) == 184,
              "offsetof(_CONTEXT, Eip) != 184");
static_assert(__builtin_offsetof(_CONTEXT, SegCs) == 188,
              "offsetof(_CONTEXT, SegCs) != 188");
static_assert(__builtin_offsetof(_CONTEXT, EFlags) == 192,
              "offsetof(_CONTEXT, EFlags) != 192");
static_assert(__builtin_offsetof(_CONTEXT, Esp) == 196,
              "offsetof(_CONTEXT, Esp) != 196");
static_assert(__builtin_offsetof(_CONTEXT, SegSs) == 200,
              "offsetof(_CONTEXT, SegSs) != 200");
static_assert(__builtin_offsetof(_CONTEXT, ExtendedRegisters) == 204,
              "offsetof(_CONTEXT, ExtendedRegisters) != 204");

// ---- _EXCEPTION_POINTERS (8 bytes) ----
static_assert(sizeof(_EXCEPTION_POINTERS) == 8,
              "sizeof(_EXCEPTION_POINTERS) != 8");
static_assert(__builtin_offsetof(_EXCEPTION_POINTERS, ExceptionRecord) == 0,
              "offsetof(_EXCEPTION_POINTERS, ExceptionRecord) != 0");
static_assert(__builtin_offsetof(_EXCEPTION_POINTERS, ContextRecord) == 4,
              "offsetof(_EXCEPTION_POINTERS, ContextRecord) != 4");

// ---- _EXCEPTION_RECORD (80 bytes) ----
static_assert(sizeof(_EXCEPTION_RECORD) == 80,
              "sizeof(_EXCEPTION_RECORD) != 80");
static_assert(__builtin_offsetof(_EXCEPTION_RECORD, ExceptionCode) == 0,
              "offsetof(_EXCEPTION_RECORD, ExceptionCode) != 0");
static_assert(__builtin_offsetof(_EXCEPTION_RECORD, ExceptionFlags) == 4,
              "offsetof(_EXCEPTION_RECORD, ExceptionFlags) != 4");
static_assert(__builtin_offsetof(_EXCEPTION_RECORD, ExceptionRecord) == 8,
              "offsetof(_EXCEPTION_RECORD, ExceptionRecord) != 8");
static_assert(__builtin_offsetof(_EXCEPTION_RECORD, ExceptionAddress) == 12,
              "offsetof(_EXCEPTION_RECORD, ExceptionAddress) != 12");
static_assert(__builtin_offsetof(_EXCEPTION_RECORD, NumberParameters) == 16,
              "offsetof(_EXCEPTION_RECORD, NumberParameters) != 16");
static_assert(__builtin_offsetof(_EXCEPTION_RECORD, ExceptionInformation) == 20,
              "offsetof(_EXCEPTION_RECORD, ExceptionInformation) != 20");

// ---- _FLOATING_SAVE_AREA (112 bytes) ----
static_assert(sizeof(_FLOATING_SAVE_AREA) == 112,
              "sizeof(_FLOATING_SAVE_AREA) != 112");
static_assert(__builtin_offsetof(_FLOATING_SAVE_AREA, ControlWord) == 0,
              "offsetof(_FLOATING_SAVE_AREA, ControlWord) != 0");
static_assert(__builtin_offsetof(_FLOATING_SAVE_AREA, StatusWord) == 4,
              "offsetof(_FLOATING_SAVE_AREA, StatusWord) != 4");
static_assert(__builtin_offsetof(_FLOATING_SAVE_AREA, TagWord) == 8,
              "offsetof(_FLOATING_SAVE_AREA, TagWord) != 8");
static_assert(__builtin_offsetof(_FLOATING_SAVE_AREA, ErrorOffset) == 12,
              "offsetof(_FLOATING_SAVE_AREA, ErrorOffset) != 12");
static_assert(__builtin_offsetof(_FLOATING_SAVE_AREA, ErrorSelector) == 16,
              "offsetof(_FLOATING_SAVE_AREA, ErrorSelector) != 16");
static_assert(__builtin_offsetof(_FLOATING_SAVE_AREA, DataOffset) == 20,
              "offsetof(_FLOATING_SAVE_AREA, DataOffset) != 20");
static_assert(__builtin_offsetof(_FLOATING_SAVE_AREA, DataSelector) == 24,
              "offsetof(_FLOATING_SAVE_AREA, DataSelector) != 24");
static_assert(__builtin_offsetof(_FLOATING_SAVE_AREA, RegisterArea) == 28,
              "offsetof(_FLOATING_SAVE_AREA, RegisterArea) != 28");
static_assert(__builtin_offsetof(_FLOATING_SAVE_AREA, Cr0NpxState) == 108,
              "offsetof(_FLOATING_SAVE_AREA, Cr0NpxState) != 108");

// ---- _GUID (16 bytes) ----
static_assert(sizeof(_GUID) == 16,
              "sizeof(_GUID) != 16");
static_assert(__builtin_offsetof(_GUID, Data1) == 0,
              "offsetof(_GUID, Data1) != 0");
static_assert(__builtin_offsetof(_GUID, Data2) == 4,
              "offsetof(_GUID, Data2) != 4");
static_assert(__builtin_offsetof(_GUID, Data3) == 6,
              "offsetof(_GUID, Data3) != 6");
static_assert(__builtin_offsetof(_GUID, Data4) == 8,
              "offsetof(_GUID, Data4) != 8");

// ---- _LIST_ENTRY (8 bytes) ----
static_assert(sizeof(_LIST_ENTRY) == 8,
              "sizeof(_LIST_ENTRY) != 8");
static_assert(__builtin_offsetof(_LIST_ENTRY, Flink) == 0,
              "offsetof(_LIST_ENTRY, Flink) != 0");
static_assert(__builtin_offsetof(_LIST_ENTRY, Blink) == 4,
              "offsetof(_LIST_ENTRY, Blink) != 4");

// ---- _RTL_CRITICAL_SECTION (24 bytes) ----
static_assert(sizeof(_RTL_CRITICAL_SECTION) == 24,
              "sizeof(_RTL_CRITICAL_SECTION) != 24");
static_assert(__builtin_offsetof(_RTL_CRITICAL_SECTION, DebugInfo) == 0,
              "offsetof(_RTL_CRITICAL_SECTION, DebugInfo) != 0");
static_assert(__builtin_offsetof(_RTL_CRITICAL_SECTION, LockCount) == 4,
              "offsetof(_RTL_CRITICAL_SECTION, LockCount) != 4");
static_assert(__builtin_offsetof(_RTL_CRITICAL_SECTION, RecursionCount) == 8,
              "offsetof(_RTL_CRITICAL_SECTION, RecursionCount) != 8");
static_assert(__builtin_offsetof(_RTL_CRITICAL_SECTION, OwningThread) == 12,
              "offsetof(_RTL_CRITICAL_SECTION, OwningThread) != 12");
static_assert(__builtin_offsetof(_RTL_CRITICAL_SECTION, LockSemaphore) == 16,
              "offsetof(_RTL_CRITICAL_SECTION, LockSemaphore) != 16");
static_assert(__builtin_offsetof(_RTL_CRITICAL_SECTION, SpinCount) == 20,
              "offsetof(_RTL_CRITICAL_SECTION, SpinCount) != 20");

// ---- _RTL_CRITICAL_SECTION_DEBUG (32 bytes) ----
static_assert(sizeof(_RTL_CRITICAL_SECTION_DEBUG) == 32,
              "sizeof(_RTL_CRITICAL_SECTION_DEBUG) != 32");
static_assert(__builtin_offsetof(_RTL_CRITICAL_SECTION_DEBUG, Type) == 0,
              "offsetof(_RTL_CRITICAL_SECTION_DEBUG, Type) != 0");
static_assert(__builtin_offsetof(_RTL_CRITICAL_SECTION_DEBUG, CreatorBackTraceIndex) == 2,
              "offsetof(_RTL_CRITICAL_SECTION_DEBUG, CreatorBackTraceIndex) != 2");
static_assert(__builtin_offsetof(_RTL_CRITICAL_SECTION_DEBUG, CriticalSection) == 4,
              "offsetof(_RTL_CRITICAL_SECTION_DEBUG, CriticalSection) != 4");
static_assert(__builtin_offsetof(_RTL_CRITICAL_SECTION_DEBUG, ProcessLocksList) == 8,
              "offsetof(_RTL_CRITICAL_SECTION_DEBUG, ProcessLocksList) != 8");
static_assert(__builtin_offsetof(_RTL_CRITICAL_SECTION_DEBUG, EntryCount) == 16,
              "offsetof(_RTL_CRITICAL_SECTION_DEBUG, EntryCount) != 16");
static_assert(__builtin_offsetof(_RTL_CRITICAL_SECTION_DEBUG, ContentionCount) == 20,
              "offsetof(_RTL_CRITICAL_SECTION_DEBUG, ContentionCount) != 20");
static_assert(__builtin_offsetof(_RTL_CRITICAL_SECTION_DEBUG, Flags) == 24,
              "offsetof(_RTL_CRITICAL_SECTION_DEBUG, Flags) != 24");
static_assert(__builtin_offsetof(_RTL_CRITICAL_SECTION_DEBUG, CreatorBackTraceIndexHigh) == 28,
              "offsetof(_RTL_CRITICAL_SECTION_DEBUG, CreatorBackTraceIndexHigh) != 28");
static_assert(__builtin_offsetof(_RTL_CRITICAL_SECTION_DEBUG, SpareWORD) == 30,
              "offsetof(_RTL_CRITICAL_SECTION_DEBUG, SpareWORD) != 30");

// ---- _floatx2 (8 bytes) ----
static_assert(sizeof(_floatx2) == 8,
              "sizeof(_floatx2) != 8");
static_assert(__builtin_offsetof(_floatx2, _p1) == 0,
              "offsetof(_floatx2, _p1) != 0");
static_assert(__builtin_offsetof(_floatx2, _p2) == 4,
              "offsetof(_floatx2, _p2) != 4");

// ---- _struct_19 (8 bytes) ----
static_assert(sizeof(_struct_19) == 8,
              "sizeof(_struct_19) != 8");
static_assert(__builtin_offsetof(_struct_19, LowPart) == 0,
              "offsetof(_struct_19, LowPart) != 0");
static_assert(__builtin_offsetof(_struct_19, HighPart) == 4,
              "offsetof(_struct_19, HighPart) != 4");

// ---- _struct_20 (8 bytes) ----
static_assert(sizeof(_struct_20) == 8,
              "sizeof(_struct_20) != 8");
static_assert(__builtin_offsetof(_struct_20, LowPart) == 0,
              "offsetof(_struct_20, LowPart) != 0");
static_assert(__builtin_offsetof(_struct_20, HighPart) == 4,
              "offsetof(_struct_20, HighPart) != 4");

// ---- _struct_519 (8 bytes) ----
static_assert(sizeof(_struct_519) == 8,
              "sizeof(_struct_519) != 8");
static_assert(__builtin_offsetof(_struct_519, Offset) == 0,
              "offsetof(_struct_519, Offset) != 0");
static_assert(__builtin_offsetof(_struct_519, OffsetHigh) == 4,
              "offsetof(_struct_519, OffsetHigh) != 4");

// ---- _uintx2 (8 bytes) ----
static_assert(sizeof(_uintx2) == 8,
              "sizeof(_uintx2) != 8");
static_assert(__builtin_offsetof(_uintx2, low) == 0,
              "offsetof(_uintx2, low) != 0");
static_assert(__builtin_offsetof(_uintx2, high) == 4,
              "offsetof(_uintx2, high) != 4");

} // namespace

#endif  // __SIZEOF_POINTER__ == 4 (32-bit layout only)
