// Auto-generated by scripts/Python/gen_struct_layout_checks.py
// DO NOT EDIT BY HAND. Re-run the generator after updating types.
//
// Category: winsock
// Structs : 5

#include "nocturne.h"

// The assertions below encode the 32-bit (matching-target) struct layout
// from Ghidra's data_types.json, so they are only valid when pointers are
// 4 bytes. On a native 64-bit build, pointer-containing structs
// legitimately change size/offset, so the checks are compiled out there;
// the file still compiles (catching type/name regressions) in both lanes.
#if __SIZEOF_POINTER__ == 4

namespace nocturne_layout_winsock {

// ---- HOSTENT (16 bytes) ----
static_assert(sizeof(HOSTENT) == 16,
              "sizeof(HOSTENT) != 16");
static_assert(__builtin_offsetof(HOSTENT, h_name) == 0,
              "offsetof(HOSTENT, h_name) != 0");
static_assert(__builtin_offsetof(HOSTENT, h_aliases) == 4,
              "offsetof(HOSTENT, h_aliases) != 4");
static_assert(__builtin_offsetof(HOSTENT, h_addrtype) == 8,
              "offsetof(HOSTENT, h_addrtype) != 8");
static_assert(__builtin_offsetof(HOSTENT, h_length) == 10,
              "offsetof(HOSTENT, h_length) != 10");
static_assert(__builtin_offsetof(HOSTENT, h_addr_list) == 12,
              "offsetof(HOSTENT, h_addr_list) != 12");

// ---- SERVENT (16 bytes) ----
static_assert(sizeof(SERVENT) == 16,
              "sizeof(SERVENT) != 16");
static_assert(__builtin_offsetof(SERVENT, s_name) == 0,
              "offsetof(SERVENT, s_name) != 0");
static_assert(__builtin_offsetof(SERVENT, s_aliases) == 4,
              "offsetof(SERVENT, s_aliases) != 4");
static_assert(__builtin_offsetof(SERVENT, s_port) == 8,
              "offsetof(SERVENT, s_port) != 8");
static_assert(__builtin_offsetof(SERVENT, s_proto) == 12,
              "offsetof(SERVENT, s_proto) != 12");

// ---- SOCKADDR (16 bytes) ----
static_assert(sizeof(SOCKADDR) == 16,
              "sizeof(SOCKADDR) != 16");
static_assert(__builtin_offsetof(SOCKADDR, sin_family) == 0,
              "offsetof(SOCKADDR, sin_family) != 0");
static_assert(__builtin_offsetof(SOCKADDR, sin_port) == 2,
              "offsetof(SOCKADDR, sin_port) != 2");
static_assert(__builtin_offsetof(SOCKADDR, sin_addr) == 4,
              "offsetof(SOCKADDR, sin_addr) != 4");
static_assert(__builtin_offsetof(SOCKADDR, zero) == 8,
              "offsetof(SOCKADDR, zero) != 8");

// ---- SOCKADDR_IN (16 bytes) ----
static_assert(sizeof(SOCKADDR_IN) == 16,
              "sizeof(SOCKADDR_IN) != 16");
static_assert(__builtin_offsetof(SOCKADDR_IN, sin_family) == 0,
              "offsetof(SOCKADDR_IN, sin_family) != 0");
static_assert(__builtin_offsetof(SOCKADDR_IN, sin_port) == 2,
              "offsetof(SOCKADDR_IN, sin_port) != 2");
static_assert(__builtin_offsetof(SOCKADDR_IN, sin_addr) == 4,
              "offsetof(SOCKADDR_IN, sin_addr) != 4");
static_assert(__builtin_offsetof(SOCKADDR_IN, padding_0x08) == 8,
              "offsetof(SOCKADDR_IN, padding_0x08) != 8");

// ---- WSADATA (398 bytes) ----
static_assert(sizeof(WSADATA) == 398,
              "sizeof(WSADATA) != 398");
static_assert(__builtin_offsetof(WSADATA, wVersion) == 0,
              "offsetof(WSADATA, wVersion) != 0");
static_assert(__builtin_offsetof(WSADATA, wHighVersion) == 2,
              "offsetof(WSADATA, wHighVersion) != 2");
static_assert(__builtin_offsetof(WSADATA, szDescription) == 4,
              "offsetof(WSADATA, szDescription) != 4");
static_assert(__builtin_offsetof(WSADATA, szSystemStatus) == 261,
              "offsetof(WSADATA, szSystemStatus) != 261");
static_assert(__builtin_offsetof(WSADATA, iMaxSockets) == 390,
              "offsetof(WSADATA, iMaxSockets) != 390");
static_assert(__builtin_offsetof(WSADATA, iMaxUdpDg) == 392,
              "offsetof(WSADATA, iMaxUdpDg) != 392");
static_assert(__builtin_offsetof(WSADATA, lpVendorInfo) == 394,
              "offsetof(WSADATA, lpVendorInfo) != 394");

} // namespace

#endif  // __SIZEOF_POINTER__ == 4 (32-bit layout only)
