// Auto-generated by scripts/Python/gen_struct_layout_checks.py
// DO NOT EDIT BY HAND. Re-run the generator after updating types.
//
// Category: winuser
// Structs : 3

#include "nocturne.h"

// The assertions below encode the 32-bit (matching-target) struct layout
// from Ghidra's data_types.json, so they are only valid when pointers are
// 4 bytes. On a native 64-bit build, pointer-containing structs
// legitimately change size/offset, so the checks are compiled out there;
// the file still compiles (catching type/name regressions) in both lanes.
#if __SIZEOF_POINTER__ == 4

namespace nocturne_layout_winuser {

// ---- HWND__ (4 bytes) ----
static_assert(sizeof(HWND__) == 4,
              "sizeof(HWND__) != 4");
static_assert(__builtin_offsetof(HWND__, unused) == 0,
              "offsetof(HWND__, unused) != 0");

// ---- tagMSG (28 bytes) ----
static_assert(sizeof(tagMSG) == 28,
              "sizeof(tagMSG) != 28");
static_assert(__builtin_offsetof(tagMSG, hwnd) == 0,
              "offsetof(tagMSG, hwnd) != 0");
static_assert(__builtin_offsetof(tagMSG, message) == 4,
              "offsetof(tagMSG, message) != 4");
static_assert(__builtin_offsetof(tagMSG, wParam) == 8,
              "offsetof(tagMSG, wParam) != 8");
static_assert(__builtin_offsetof(tagMSG, lParam) == 12,
              "offsetof(tagMSG, lParam) != 12");
static_assert(__builtin_offsetof(tagMSG, time) == 16,
              "offsetof(tagMSG, time) != 16");
static_assert(__builtin_offsetof(tagMSG, pt) == 20,
              "offsetof(tagMSG, pt) != 20");

// ---- tagWNDCLASSA (40 bytes) ----
static_assert(sizeof(tagWNDCLASSA) == 40,
              "sizeof(tagWNDCLASSA) != 40");
static_assert(__builtin_offsetof(tagWNDCLASSA, style) == 0,
              "offsetof(tagWNDCLASSA, style) != 0");
static_assert(__builtin_offsetof(tagWNDCLASSA, lpfnWndProc) == 4,
              "offsetof(tagWNDCLASSA, lpfnWndProc) != 4");
static_assert(__builtin_offsetof(tagWNDCLASSA, cbClsExtra) == 8,
              "offsetof(tagWNDCLASSA, cbClsExtra) != 8");
static_assert(__builtin_offsetof(tagWNDCLASSA, cbWndExtra) == 12,
              "offsetof(tagWNDCLASSA, cbWndExtra) != 12");
static_assert(__builtin_offsetof(tagWNDCLASSA, hInstance) == 16,
              "offsetof(tagWNDCLASSA, hInstance) != 16");
static_assert(__builtin_offsetof(tagWNDCLASSA, hIcon) == 20,
              "offsetof(tagWNDCLASSA, hIcon) != 20");
static_assert(__builtin_offsetof(tagWNDCLASSA, hCursor) == 24,
              "offsetof(tagWNDCLASSA, hCursor) != 24");
static_assert(__builtin_offsetof(tagWNDCLASSA, hbrBackground) == 28,
              "offsetof(tagWNDCLASSA, hbrBackground) != 28");
static_assert(__builtin_offsetof(tagWNDCLASSA, lpszMenuName) == 32,
              "offsetof(tagWNDCLASSA, lpszMenuName) != 32");
static_assert(__builtin_offsetof(tagWNDCLASSA, lpszClassName) == 36,
              "offsetof(tagWNDCLASSA, lpszClassName) != 36");

} // namespace

#endif  // __SIZEOF_POINTER__ == 4 (32-bit layout only)
