// Name: shape_design.c_embedCopyrightWatermark_FUN_0046b9a0
// Address: 0046b9a0
// Address Range: [[0046b9a0, 0046bb7a]]
// Convention: __cdecl
// Signature: void __cdecl shape_design_c_embedCopyrightWatermark_FUN_0046b9a0(void *image_buffer,char *output_filename,int texture_size)

#include "nocturne.h"

void __cdecl shape_design_c_embedCopyrightWatermark_FUN_0046b9a0(void *image_buffer,char *output_filename,int texture_size)

{
  _tm *time_ptr;
  char local_4dc [1024];
  char local_dc [200];
  int local_14;
  
  if (texture_size < 0x100) {
    if (texture_size < 0x40) {
      if (0x1f < texture_size) {
        shape_design_c_quantizePaletteColors_FUN_0046b770
                  (image_buffer,texture_size,1,(byte *)texture_size,(int)output_filename,
                   "cTRI");
        shape_design_c_quantizePaletteColors_FUN_0046b770
                  (image_buffer,texture_size,texture_size,(byte *)0x1,(int)output_filename,
                   "Crm3");
        shape_design_c_quantizePaletteColors_FUN_0046b770
                  ((byte *)((int)image_buffer + texture_size + -1),texture_size,texture_size,
                   (byte *)0xffffffff,(int)output_filename,"rsrv");
      }
    }
    else {
      shape_design_c_quantizePaletteColors_FUN_0046b770
                (image_buffer,texture_size,1,(byte *)texture_size,(int)output_filename,
                 "(c)99TRI");
      shape_design_c_quantizePaletteColors_FUN_0046b770
                (image_buffer,texture_size,texture_size,(byte *)0x1,(int)output_filename,
                 "CramTex3");
      shape_design_c_quantizePaletteColors_FUN_0046b770
                ((byte *)((int)image_buffer + texture_size + -1),texture_size,texture_size,
                 (byte *)0xffffffff,(int)output_filename,"Reserved");
    }
  }
  else {
    shape_design_c_quantizePaletteColors_FUN_0046b770
              (image_buffer,texture_size,1,(byte *)texture_size,(int)output_filename,
               "(c) 1999 Terminal Reality Inc.");
    shape_design_c_quantizePaletteColors_FUN_0046b770
              (image_buffer,texture_size,texture_size,(byte *)0x1,(int)output_filename,
               "Image generated by CramTex 3");
    shape_design_c_quantizePaletteColors_FUN_0046b770
              ((byte *)((int)image_buffer + texture_size + -1),texture_size,texture_size,
               (byte *)0xffffffff,(int)output_filename,"All rights reserved");
  }
  _time(&local_14);
  time_ptr = _localtime(&local_14);
  _strftime(local_dc,200,"%m%d%y",time_ptr);
  _sprintf(local_4dc,"%s%s",local_dc,"Jan 10 2000");
  shape_design_c_quantizePaletteColors_FUN_0046b770
            ((byte *)((texture_size + -1) * texture_size + (int)image_buffer),texture_size,1,
             (byte *)-texture_size,(int)output_filename,local_4dc);
  return;
}
