// Name: shape_design.c_embedCopyrightWatermark_FUN_0046b9a0
// Address: 0046b9a0
// Address Range: [[0046b9a0, 0046bb7a]]
// Convention: __cdecl
// Signature: void __cdecl shape_design_c_embedCopyrightWatermark_FUN_0046b9a0(byte *image_buffer,char *palette_data,int texture_size)

#include "nocturne.h"

void __cdecl shape_design_c_embedCopyrightWatermark_FUN_0046b9a0(byte *image_buffer,char *palette_data,int texture_size)

{
  _tm *time_ptr;
  char local_4dc [1024];
  char local_dc [200];
  time_t local_14;
  
  if (texture_size < 0x100) {
    if (texture_size < 0x40) {
      if (0x1f < texture_size) {
        shape_design_c_quantizePaletteColors_FUN_0046b770
                  (image_buffer,texture_size,1,texture_size,palette_data,"cTRI");
        shape_design_c_quantizePaletteColors_FUN_0046b770
                  (image_buffer,texture_size,texture_size,1,palette_data,"Crm3");
        shape_design_c_quantizePaletteColors_FUN_0046b770
                  (image_buffer + texture_size + -1,texture_size,texture_size,-1,palette_data,
                   "rsrv");
      }
    }
    else {
      shape_design_c_quantizePaletteColors_FUN_0046b770
                (image_buffer,texture_size,1,texture_size,palette_data,"(c)99TRI");
      shape_design_c_quantizePaletteColors_FUN_0046b770
                (image_buffer,texture_size,texture_size,1,palette_data,"CramTex3");
      shape_design_c_quantizePaletteColors_FUN_0046b770
                (image_buffer + texture_size + -1,texture_size,texture_size,-1,palette_data,
                 "Reserved");
    }
  }
  else {
    shape_design_c_quantizePaletteColors_FUN_0046b770
              (image_buffer,texture_size,1,texture_size,palette_data,
               "(c) 1999 Terminal Reality Inc.");
    shape_design_c_quantizePaletteColors_FUN_0046b770
              (image_buffer,texture_size,texture_size,1,palette_data,
               "Image generated by CramTex 3");
    shape_design_c_quantizePaletteColors_FUN_0046b770
              (image_buffer + texture_size + -1,texture_size,texture_size,-1,palette_data,
               "All rights reserved");
  }
  _time(&local_14);
  time_ptr = _localtime(&local_14);
  _strftime(local_dc,200,"%m%d%y",time_ptr);
  _sprintf(local_4dc,"%s%s",local_dc,"Jan 10 2000");
  shape_design_c_quantizePaletteColors_FUN_0046b770
            (image_buffer + (texture_size + -1) * texture_size,texture_size,1,-texture_size,
             palette_data,local_4dc);
  return;
}
