// Name: shape_design.c_embedCopyrightWatermark_FUN_0046b9a0
// Address: 0046b9a0
// Address Range: [[0046b9a0, 0046bb7a]]
// Convention: __cdecl
// Signature: void shape_design.c_embedCopyrightWatermark_FUN_0046b9a0(void * image_buffer, char * output_filename, int texture_size)
// Cross-references:
//   shape_design.c_cramTextureList_FUN_0046bb80 (0046bb80) at 0046dab5 [UNCONDITIONAL_CALL]
// Globals:
//   TerminatedCString s_c_1999_Terminal_Reality__0061d3de
//   TerminatedCString s_Image_generated_by_CramT_0061d3fd
//   TerminatedCString s_All_rights_reserved_0061d41a
//   TerminatedCString s_c_99TRI_0061d42e
//   TerminatedCString s_CramTex3_0061d437
//   TerminatedCString s_Reserved_0061d440
//   TerminatedCString s_cTRI_0061d449
//   TerminatedCString s_Crm3_0061d44e
//   TerminatedCString s_rsrv_0061d453
//   TerminatedCString s_m_d_y_0061d458
//   TerminatedCString s_Jan_10_2000_0061d45f
//   TerminatedCString s_s_s_0061d46b
// Function calls:
//   crt_stdio.c_sprintf_FUN_005fdbd0
//   crt_time.c_localtime_FUN_00600288
//   crt_time.c_strftime_FUN_006002d4
//   crt_time.c_time_with_rounding_FUN_006001f0
//   shape_design.c_quantizePaletteColors_FUN_0046b770

#include "nocturne.h"

void __cdecl
shape_design_c_embedCopyrightWatermark_FUN_0046b9a0
          (void *image_buffer,char *output_filename,int texture_size)

{
  tm *time_ptr;
  BADSPACEBASE *in_ESP;
  char local_dc [200];
  time_t local_14;
  
  if (texture_size < 0x100) {
    if (texture_size < 0x40) {
      if (0x1f < texture_size) {
        shape_design_c_quantizePaletteColors_FUN_0046b770
                  ((byte *)image_buffer,texture_size,1,(byte *)texture_size,(int)output_filename,
                   "cTRI");
        shape_design_c_quantizePaletteColors_FUN_0046b770
                  ((byte *)image_buffer,texture_size,texture_size,&DAT_00000001,(int)output_filename
                   ,"Crm3");
        shape_design_c_quantizePaletteColors_FUN_0046b770
                  ((byte *)((int)image_buffer + texture_size + -1),texture_size,texture_size,
                   (byte *)0xffffffff,(int)output_filename,"rsrv");
      }
    }
    else {
      shape_design_c_quantizePaletteColors_FUN_0046b770
                ((byte *)image_buffer,texture_size,1,(byte *)texture_size,(int)output_filename,
                 "(c)99TRI");
      shape_design_c_quantizePaletteColors_FUN_0046b770
                ((byte *)image_buffer,texture_size,texture_size,&DAT_00000001,(int)output_filename,
                 "CramTex3");
      shape_design_c_quantizePaletteColors_FUN_0046b770
                ((byte *)((int)image_buffer + texture_size + -1),texture_size,texture_size,
                 (byte *)0xffffffff,(int)output_filename,"Reserved");
    }
  }
  else {
    shape_design_c_quantizePaletteColors_FUN_0046b770
              ((byte *)image_buffer,texture_size,1,(byte *)texture_size,(int)output_filename,
               "(c) 1999 Terminal Reality Inc.");
    shape_design_c_quantizePaletteColors_FUN_0046b770
              ((byte *)image_buffer,texture_size,texture_size,&DAT_00000001,(int)output_filename,
               "Image generated by CramTex 3");
    shape_design_c_quantizePaletteColors_FUN_0046b770
              ((byte *)((int)image_buffer + texture_size + -1),texture_size,texture_size,
               (byte *)0xffffffff,(int)output_filename,"All rights reserved");
  }
  crt_time_c_time_with_rounding_FUN_006001f0(&local_14);
  time_ptr = crt_time_c_localtime_FUN_00600288(&local_14);
  crt_time_c_strftime_FUN_006002d4(local_dc,200,"%m%d%y",time_ptr);
  crt_stdio_c_sprintf_FUN_005fdbd0(&stack0xfffffb24,"%s%s");
  shape_design_c_quantizePaletteColors_FUN_0046b770
            ((byte *)((texture_size + -1) * texture_size + (int)image_buffer),texture_size,1,
             (byte *)-texture_size,(int)output_filename,&stack0xfffffb24);
  return;
}


// Assembly code:
// 0046b9a0: PUSH EBX
//   Label: shape_design.c_embedCopyrightWatermark_FUN_0046b9a0
// 0046b9a1: PUSH ESI
// 0046b9a2: PUSH EDI
// 0046b9a3: PUSH EBP
// 0046b9a4: MOV EBP,ESP
// 0046b9a6: SUB ESP,0x4cc
// 0046b9ac: CMP dword ptr [EBP + 0x1c],0x100
//   XREF to: Stack[0xc] (READ)
// 0046b9b3: JL 0x0046ba1e
//   XREF to: 0046ba1e (CONDITIONAL_JUMP)
// 0046b9b5: MOV EAX,0x61d3de
//   XREF to: 0061d3de (DATA)
// 0046b9ba: PUSH EAX
//   XREF to: 0061d3de (DATA)
// 0046b9bb: MOV EAX,dword ptr [EBP + 0x18]
//   XREF to: Stack[0x8] (READ)
// 0046b9be: PUSH EAX
// 0046b9bf: MOV EAX,dword ptr [EBP + 0x1c]
//   XREF to: Stack[0xc] (READ)
// 0046b9c2: PUSH EAX
// 0046b9c3: PUSH 0x1
// 0046b9c5: MOV EAX,dword ptr [EBP + 0x1c]
//   XREF to: Stack[0xc] (READ)
// 0046b9c8: PUSH EAX
// 0046b9c9: MOV EAX,dword ptr [EBP + 0x14]
//   XREF to: Stack[0x4] (READ)
// 0046b9cc: PUSH EAX
// 0046b9cd: CALL shape_design.c_quantizePaletteColors_FUN_0046b770
//   XREF to: 0046b770 (UNCONDITIONAL_CALL)
// 0046b9d2: ADD ESP,0x18
// 0046b9d5: MOV EAX,0x61d3fd
//   XREF to: 0061d3fd (DATA)
// 0046b9da: PUSH EAX
//   XREF to: 0061d3fd (DATA)
// 0046b9db: MOV EAX,dword ptr [EBP + 0x18]
//   XREF to: Stack[0x8] (READ)
// 0046b9de: PUSH EAX
// 0046b9df: PUSH 0x1
// 0046b9e1: MOV EAX,dword ptr [EBP + 0x1c]
//   XREF to: Stack[0xc] (READ)
// 0046b9e4: PUSH EAX
// 0046b9e5: MOV EAX,dword ptr [EBP + 0x1c]
//   XREF to: Stack[0xc] (READ)
// 0046b9e8: PUSH EAX
// 0046b9e9: MOV EAX,dword ptr [EBP + 0x14]
//   XREF to: Stack[0x4] (READ)
// 0046b9ec: PUSH EAX
// 0046b9ed: CALL shape_design.c_quantizePaletteColors_FUN_0046b770
//   XREF to: 0046b770 (UNCONDITIONAL_CALL)
// 0046b9f2: ADD ESP,0x18
// 0046b9f5: MOV EAX,0x61d41a
//   XREF to: 0061d41a (DATA)
// 0046b9fa: PUSH EAX
//   XREF to: 0061d41a (DATA)
// 0046b9fb: MOV EAX,dword ptr [EBP + 0x18]
//   XREF to: Stack[0x8] (READ)
// 0046b9fe: PUSH EAX
// 0046b9ff: PUSH -0x1
// 0046ba01: MOV EAX,dword ptr [EBP + 0x1c]
//   XREF to: Stack[0xc] (READ)
// 0046ba04: PUSH EAX
// 0046ba05: MOV EAX,dword ptr [EBP + 0x1c]
//   XREF to: Stack[0xc] (READ)
// 0046ba08: PUSH EAX
// 0046ba09: MOV EAX,dword ptr [EBP + 0x14]
//   XREF to: Stack[0x4] (READ)
// 0046ba0c: ADD EAX,dword ptr [EBP + 0x1c]
//   XREF to: Stack[0xc] (READ)
// 0046ba0f: DEC EAX
// 0046ba10: PUSH EAX
// 0046ba11: CALL shape_design.c_quantizePaletteColors_FUN_0046b770
//   XREF to: 0046b770 (UNCONDITIONAL_CALL)
// 0046ba16: ADD ESP,0x18
// 0046ba19: JMP 0x0046baf4
//   XREF to: 0046baf4 (UNCONDITIONAL_JUMP)
// 0046ba1e: CMP dword ptr [EBP + 0x1c],0x40
//   Label: LAB_0046ba1e
//   XREF to: Stack[0xc] (READ)
// 0046ba22: JL 0x0046ba8a
//   XREF to: 0046ba8a (CONDITIONAL_JUMP)
// 0046ba24: MOV EAX,0x61d42e
//   XREF to: 0061d42e (DATA)
// 0046ba29: PUSH EAX
//   XREF to: 0061d42e (DATA)
// 0046ba2a: MOV EAX,dword ptr [EBP + 0x18]
//   XREF to: Stack[0x8] (READ)
// 0046ba2d: PUSH EAX
// 0046ba2e: MOV EAX,dword ptr [EBP + 0x1c]
//   XREF to: Stack[0xc] (READ)
// 0046ba31: PUSH EAX
// 0046ba32: PUSH 0x1
// 0046ba34: MOV EAX,dword ptr [EBP + 0x1c]
//   XREF to: Stack[0xc] (READ)
// 0046ba37: PUSH EAX
// 0046ba38: MOV EAX,dword ptr [EBP + 0x14]
//   XREF to: Stack[0x4] (READ)
// 0046ba3b: PUSH EAX
// 0046ba3c: CALL shape_design.c_quantizePaletteColors_FUN_0046b770
//   XREF to: 0046b770 (UNCONDITIONAL_CALL)
// 0046ba41: ADD ESP,0x18
// 0046ba44: MOV EAX,0x61d437
//   XREF to: 0061d437 (DATA)
// 0046ba49: PUSH EAX
//   XREF to: 0061d437 (DATA)
// 0046ba4a: MOV EAX,dword ptr [EBP + 0x18]
//   XREF to: Stack[0x8] (READ)
// 0046ba4d: PUSH EAX
// 0046ba4e: PUSH 0x1
// 0046ba50: MOV EAX,dword ptr [EBP + 0x1c]
//   XREF to: Stack[0xc] (READ)
// 0046ba53: PUSH EAX
// 0046ba54: MOV EAX,dword ptr [EBP + 0x1c]
//   XREF to: Stack[0xc] (READ)
// 0046ba57: PUSH EAX
// 0046ba58: MOV EAX,dword ptr [EBP + 0x14]
//   XREF to: Stack[0x4] (READ)
// 0046ba5b: PUSH EAX
// 0046ba5c: CALL shape_design.c_quantizePaletteColors_FUN_0046b770
//   XREF to: 0046b770 (UNCONDITIONAL_CALL)
// 0046ba61: ADD ESP,0x18
// 0046ba64: MOV EAX,0x61d440
//   XREF to: 0061d440 (DATA)
// 0046ba69: PUSH EAX
//   XREF to: 0061d440 (DATA)
// 0046ba6a: MOV EAX,dword ptr [EBP + 0x18]
//   XREF to: Stack[0x8] (READ)
// 0046ba6d: PUSH EAX
// 0046ba6e: PUSH -0x1
// 0046ba70: MOV EAX,dword ptr [EBP + 0x1c]
//   XREF to: Stack[0xc] (READ)
// 0046ba73: PUSH EAX
// 0046ba74: MOV EAX,dword ptr [EBP + 0x1c]
//   XREF to: Stack[0xc] (READ)
// 0046ba77: PUSH EAX
// 0046ba78: MOV EAX,dword ptr [EBP + 0x14]
//   XREF to: Stack[0x4] (READ)
// 0046ba7b: ADD EAX,dword ptr [EBP + 0x1c]
//   XREF to: Stack[0xc] (READ)
// 0046ba7e: DEC EAX
// 0046ba7f: PUSH EAX
// 0046ba80: CALL shape_design.c_quantizePaletteColors_FUN_0046b770
//   XREF to: 0046b770 (UNCONDITIONAL_CALL)
// 0046ba85: ADD ESP,0x18
// 0046ba88: JMP 0x0046baf4
//   XREF to: 0046baf4 (UNCONDITIONAL_JUMP)
// 0046ba8a: CMP dword ptr [EBP + 0x1c],0x20
//   Label: LAB_0046ba8a
//   XREF to: Stack[0xc] (READ)
// 0046ba8e: JL 0x0046baf4
//   XREF to: 0046baf4 (CONDITIONAL_JUMP)
// 0046ba90: MOV EAX,0x61d449
//   XREF to: 0061d449 (DATA)
// 0046ba95: PUSH EAX
//   XREF to: 0061d449 (DATA)
// 0046ba96: MOV EAX,dword ptr [EBP + 0x18]
//   XREF to: Stack[0x8] (READ)
// 0046ba99: PUSH EAX
// 0046ba9a: MOV EAX,dword ptr [EBP + 0x1c]
//   XREF to: Stack[0xc] (READ)
// 0046ba9d: PUSH EAX
// 0046ba9e: PUSH 0x1
// 0046baa0: MOV EAX,dword ptr [EBP + 0x1c]
//   XREF to: Stack[0xc] (READ)
// 0046baa3: PUSH EAX
// 0046baa4: MOV EAX,dword ptr [EBP + 0x14]
//   XREF to: Stack[0x4] (READ)
// 0046baa7: PUSH EAX
// 0046baa8: CALL shape_design.c_quantizePaletteColors_FUN_0046b770
//   XREF to: 0046b770 (UNCONDITIONAL_CALL)
// 0046baad: ADD ESP,0x18
// 0046bab0: MOV EAX,0x61d44e
//   XREF to: 0061d44e (DATA)
// 0046bab5: PUSH EAX
//   XREF to: 0061d44e (DATA)
// 0046bab6: MOV EAX,dword ptr [EBP + 0x18]
//   XREF to: Stack[0x8] (READ)
// 0046bab9: PUSH EAX
// 0046baba: PUSH 0x1
// 0046babc: MOV EAX,dword ptr [EBP + 0x1c]
//   XREF to: Stack[0xc] (READ)
// 0046babf: PUSH EAX
// 0046bac0: MOV EAX,dword ptr [EBP + 0x1c]
//   XREF to: Stack[0xc] (READ)
// 0046bac3: PUSH EAX
// 0046bac4: MOV EAX,dword ptr [EBP + 0x14]
//   XREF to: Stack[0x4] (READ)
// 0046bac7: PUSH EAX
// 0046bac8: CALL shape_design.c_quantizePaletteColors_FUN_0046b770
//   XREF to: 0046b770 (UNCONDITIONAL_CALL)
// 0046bacd: ADD ESP,0x18
// 0046bad0: MOV EAX,0x61d453
//   XREF to: 0061d453 (DATA)
// 0046bad5: PUSH EAX
//   XREF to: 0061d453 (DATA)
// 0046bad6: MOV EAX,dword ptr [EBP + 0x18]
//   XREF to: Stack[0x8] (READ)
// 0046bad9: PUSH EAX
// 0046bada: PUSH -0x1
// 0046badc: MOV EAX,dword ptr [EBP + 0x1c]
//   XREF to: Stack[0xc] (READ)
// 0046badf: PUSH EAX
// 0046bae0: MOV EAX,dword ptr [EBP + 0x1c]
//   XREF to: Stack[0xc] (READ)
// 0046bae3: PUSH EAX
// 0046bae4: MOV EAX,dword ptr [EBP + 0x14]
//   XREF to: Stack[0x4] (READ)
// 0046bae7: ADD EAX,dword ptr [EBP + 0x1c]
//   XREF to: Stack[0xc] (READ)
// 0046baea: DEC EAX
// 0046baeb: PUSH EAX
// 0046baec: CALL shape_design.c_quantizePaletteColors_FUN_0046b770
//   XREF to: 0046b770 (UNCONDITIONAL_CALL)
// 0046baf1: ADD ESP,0x18
// 0046baf4: LEA EAX,[EBP + -0x4]
//   Label: LAB_0046baf4
//   XREF to: Stack[-0x14] (DATA)
// 0046baf7: PUSH EAX
// 0046baf8: CALL crt_time.c_time_with_rounding_FUN_006001f0
//   XREF to: 006001f0 (UNCONDITIONAL_CALL)
// 0046bafd: ADD ESP,0x4
// 0046bb00: LEA EAX,[EBP + -0x4]
//   XREF to: Stack[-0x14] (DATA)
// 0046bb03: PUSH EAX
// 0046bb04: CALL crt_time.c_localtime_FUN_00600288
//   XREF to: 00600288 (UNCONDITIONAL_CALL)
// 0046bb09: ADD ESP,0x4
// 0046bb0c: PUSH EAX
// 0046bb0d: MOV EAX,0x61d458
//   XREF to: 0061d458 (DATA)
// 0046bb12: PUSH EAX
//   XREF to: 0061d458 (DATA)
// 0046bb13: PUSH 0xc8
// 0046bb18: LEA EAX,[EBP + 0xffffff34]
//   XREF to: Stack[-0xdc] (DATA)
// 0046bb1e: PUSH EAX
// 0046bb1f: CALL crt_time.c_strftime_FUN_006002d4
//   XREF to: 006002d4 (UNCONDITIONAL_CALL)
// 0046bb24: ADD ESP,0x10
// 0046bb27: MOV EAX,0x61d45f
//   XREF to: 0061d45f (DATA)
// 0046bb2c: PUSH EAX
//   XREF to: 0061d45f (DATA)
// 0046bb2d: LEA EAX,[EBP + 0xffffff34]
//   XREF to: Stack[-0xdc] (DATA)
// 0046bb33: PUSH EAX
// 0046bb34: MOV EAX,0x61d46b
//   XREF to: 0061d46b (DATA)
// 0046bb39: PUSH EAX
//   XREF to: 0061d46b (DATA)
// 0046bb3a: LEA EAX,[EBP + 0xfffffb34]
//   XREF to: Stack[-0x4dc] (DATA)
// 0046bb40: PUSH EAX
// 0046bb41: CALL crt_stdio.c_sprintf_FUN_005fdbd0
//   XREF to: 005fdbd0 (UNCONDITIONAL_CALL)
// 0046bb46: ADD ESP,0x10
// 0046bb49: LEA EAX,[EBP + 0xfffffb34]
//   XREF to: Stack[-0x4dc] (DATA)
// 0046bb4f: PUSH EAX
// 0046bb50: MOV EAX,dword ptr [EBP + 0x18]
//   XREF to: Stack[0x8] (READ)
// 0046bb53: PUSH EAX
// 0046bb54: MOV EAX,dword ptr [EBP + 0x1c]
//   XREF to: Stack[0xc] (READ)
// 0046bb57: NEG EAX
// 0046bb59: PUSH EAX
// 0046bb5a: PUSH 0x1
// 0046bb5c: MOV EAX,dword ptr [EBP + 0x1c]
//   XREF to: Stack[0xc] (READ)
// 0046bb5f: PUSH EAX
// 0046bb60: MOV EAX,dword ptr [EBP + 0x1c]
//   XREF to: Stack[0xc] (READ)
// 0046bb63: DEC EAX
// 0046bb64: IMUL EAX,dword ptr [EBP + 0x1c]
//   XREF to: Stack[0xc] (READ)
// 0046bb68: ADD EAX,dword ptr [EBP + 0x14]
//   XREF to: Stack[0x4] (READ)
// 0046bb6b: PUSH EAX
// 0046bb6c: CALL shape_design.c_quantizePaletteColors_FUN_0046b770
//   XREF to: 0046b770 (UNCONDITIONAL_CALL)
// 0046bb71: ADD ESP,0x18
// 0046bb74: MOV ESP,EBP
// 0046bb76: POP EBP
// 0046bb77: POP EDI
// 0046bb78: POP ESI
// 0046bb79: POP EBX
// 0046bb7a: RET
