; *****************************************************************************
;                               FUNCTION
; *****************************************************************************
; void __cdecl shape_design_c_embedCopyrightWatermark_FUN_0046b9a0(void *image_buffer,char *output_filename,int texture_size)
;
; Parameters:
; void *           Stack[0x4]:4   image_buffer
; char *           Stack[0x8]:4   output_filename
; int              Stack[0xc]:4   texture_size
; Local Variables:
; undefined1       Stack[-0x4dc]:1  local_4dc
; undefined1       Stack[-0xdc]:1  local_dc
; undefined1       Stack[-0x14]:1  local_14
;
; XREF[1]:
;   shape_design.c_cramTextureList_FUN_0046bb80 at 0046dab5
;
; Referenced Globals:
;   TerminatedCString s_c_1999_Terminal_Reality__0061d3de
;   TerminatedCString s_Image_generated_by_CramT_0061d3fd
;   TerminatedCString s_All_rights_reserved_0061d41a
;   TerminatedCString s_c_99TRI_0061d42e
;   TerminatedCString s_CramTex3_0061d437
;   TerminatedCString s_Reserved_0061d440
;   TerminatedCString s_cTRI_0061d449
;   TerminatedCString s_Crm3_0061d44e
;   TerminatedCString s_rsrv_0061d453
;   TerminatedCString s_m_d_y_0061d458
;   TerminatedCString s_Jan_10_2000_0061d45f
;   TerminatedCString s_s_s_0061d46b
;
; Called Functions:
;   crt_stdio.c__sprintf_FUN_005fdbd0
;   crt_time.c__localtime_FUN_00600288
;   crt_time.c__strftime_FUN_006002d4
;   crt_time.c__time_FUN_006001f0
;   shape_design.c_quantizePaletteColors_FUN_0046b770
;
; *****************************************************************************

section .text

    PUSH EBX                            ; 0046b9a0
        ;   Label: shape_design.c_embedCopyrightWatermark_FUN_0046b9a0
    PUSH ESI                            ; 0046b9a1
    PUSH EDI                            ; 0046b9a2
    PUSH EBP                            ; 0046b9a3
    MOV EBP,ESP                         ; 0046b9a4
    SUB ESP,0x4cc                       ; 0046b9a6
    CMP dword ptr [EBP + 0x1c],0x100    ; 0046b9ac
    JL 0x0046ba1e                       ; 0046b9b3
        ;   XREF to: 0046ba1e (CONDITIONAL_JUMP)  ; LAB_0046ba1e
    MOV EAX,0x61d3de                    ; 0046b9b5 | = "(c) 1999 Terminal Reality Inc."
    PUSH EAX                            ; 0046b9ba | = "(c) 1999 Terminal Reality Inc."
    MOV EAX,dword ptr [EBP + 0x18]      ; 0046b9bb
    PUSH EAX                            ; 0046b9be
    MOV EAX,dword ptr [EBP + 0x1c]      ; 0046b9bf
    PUSH EAX                            ; 0046b9c2
    PUSH 0x1                            ; 0046b9c3
    MOV EAX,dword ptr [EBP + 0x1c]      ; 0046b9c5
    PUSH EAX                            ; 0046b9c8
    MOV EAX,dword ptr [EBP + 0x14]      ; 0046b9c9
    PUSH EAX                            ; 0046b9cc
    CALL shape_design.c_quantizePaletteColors_FUN_0046b770 ; 0046b9cd
        ;   XREF to: 0046b770 (UNCONDITIONAL_CALL)  ; void shape_design.c_quantizePaletteColors_FUN_0046b770(byte * image_data, int pixel_count, int stride, byte * palette_data, ...)
    ADD ESP,0x18                        ; 0046b9d2
    MOV EAX,0x61d3fd                    ; 0046b9d5 | = "Image generated by CramTex 3"
    PUSH EAX                            ; 0046b9da | = "Image generated by CramTex 3"
    MOV EAX,dword ptr [EBP + 0x18]      ; 0046b9db
    PUSH EAX                            ; 0046b9de
    PUSH 0x1                            ; 0046b9df
    MOV EAX,dword ptr [EBP + 0x1c]      ; 0046b9e1
    PUSH EAX                            ; 0046b9e4
    MOV EAX,dword ptr [EBP + 0x1c]      ; 0046b9e5
    PUSH EAX                            ; 0046b9e8
    MOV EAX,dword ptr [EBP + 0x14]      ; 0046b9e9
    PUSH EAX                            ; 0046b9ec
    CALL shape_design.c_quantizePaletteColors_FUN_0046b770 ; 0046b9ed
        ;   XREF to: 0046b770 (UNCONDITIONAL_CALL)  ; void shape_design.c_quantizePaletteColors_FUN_0046b770(byte * image_data, int pixel_count, int stride, byte * palette_data, ...)
    ADD ESP,0x18                        ; 0046b9f2
    MOV EAX,0x61d41a                    ; 0046b9f5 | = "All rights reserved"
    PUSH EAX                            ; 0046b9fa | = "All rights reserved"
    MOV EAX,dword ptr [EBP + 0x18]      ; 0046b9fb
    PUSH EAX                            ; 0046b9fe
    PUSH -0x1                           ; 0046b9ff
    MOV EAX,dword ptr [EBP + 0x1c]      ; 0046ba01
    PUSH EAX                            ; 0046ba04
    MOV EAX,dword ptr [EBP + 0x1c]      ; 0046ba05
    PUSH EAX                            ; 0046ba08
    MOV EAX,dword ptr [EBP + 0x14]      ; 0046ba09
    ADD EAX,dword ptr [EBP + 0x1c]      ; 0046ba0c
    DEC EAX                             ; 0046ba0f
    PUSH EAX                            ; 0046ba10
    CALL shape_design.c_quantizePaletteColors_FUN_0046b770 ; 0046ba11
        ;   XREF to: 0046b770 (UNCONDITIONAL_CALL)  ; void shape_design.c_quantizePaletteColors_FUN_0046b770(byte * image_data, int pixel_count, int stride, byte * palette_data, ...)
    ADD ESP,0x18                        ; 0046ba16
    JMP 0x0046baf4                      ; 0046ba19
        ;   XREF to: 0046baf4 (UNCONDITIONAL_JUMP)  ; LAB_0046baf4
    CMP dword ptr [EBP + 0x1c],0x40     ; 0046ba1e
        ;   Label: LAB_0046ba1e
    JL 0x0046ba8a                       ; 0046ba22
        ;   XREF to: 0046ba8a (CONDITIONAL_JUMP)  ; LAB_0046ba8a
    MOV EAX,0x61d42e                    ; 0046ba24 | = "(c)99TRI"
    PUSH EAX                            ; 0046ba29 | = "(c)99TRI"
    MOV EAX,dword ptr [EBP + 0x18]      ; 0046ba2a
    PUSH EAX                            ; 0046ba2d
    MOV EAX,dword ptr [EBP + 0x1c]      ; 0046ba2e
    PUSH EAX                            ; 0046ba31
    PUSH 0x1                            ; 0046ba32
    MOV EAX,dword ptr [EBP + 0x1c]      ; 0046ba34
    PUSH EAX                            ; 0046ba37
    MOV EAX,dword ptr [EBP + 0x14]      ; 0046ba38
    PUSH EAX                            ; 0046ba3b
    CALL shape_design.c_quantizePaletteColors_FUN_0046b770 ; 0046ba3c
        ;   XREF to: 0046b770 (UNCONDITIONAL_CALL)  ; void shape_design.c_quantizePaletteColors_FUN_0046b770(byte * image_data, int pixel_count, int stride, byte * palette_data, ...)
    ADD ESP,0x18                        ; 0046ba41
    MOV EAX,0x61d437                    ; 0046ba44 | = "CramTex3"
    PUSH EAX                            ; 0046ba49 | = "CramTex3"
    MOV EAX,dword ptr [EBP + 0x18]      ; 0046ba4a
    PUSH EAX                            ; 0046ba4d
    PUSH 0x1                            ; 0046ba4e
    MOV EAX,dword ptr [EBP + 0x1c]      ; 0046ba50
    PUSH EAX                            ; 0046ba53
    MOV EAX,dword ptr [EBP + 0x1c]      ; 0046ba54
    PUSH EAX                            ; 0046ba57
    MOV EAX,dword ptr [EBP + 0x14]      ; 0046ba58
    PUSH EAX                            ; 0046ba5b
    CALL shape_design.c_quantizePaletteColors_FUN_0046b770 ; 0046ba5c
        ;   XREF to: 0046b770 (UNCONDITIONAL_CALL)  ; void shape_design.c_quantizePaletteColors_FUN_0046b770(byte * image_data, int pixel_count, int stride, byte * palette_data, ...)
    ADD ESP,0x18                        ; 0046ba61
    MOV EAX,0x61d440                    ; 0046ba64 | = "Reserved"
    PUSH EAX                            ; 0046ba69 | = "Reserved"
    MOV EAX,dword ptr [EBP + 0x18]      ; 0046ba6a
    PUSH EAX                            ; 0046ba6d
    PUSH -0x1                           ; 0046ba6e
    MOV EAX,dword ptr [EBP + 0x1c]      ; 0046ba70
    PUSH EAX                            ; 0046ba73
    MOV EAX,dword ptr [EBP + 0x1c]      ; 0046ba74
    PUSH EAX                            ; 0046ba77
    MOV EAX,dword ptr [EBP + 0x14]      ; 0046ba78
    ADD EAX,dword ptr [EBP + 0x1c]      ; 0046ba7b
    DEC EAX                             ; 0046ba7e
    PUSH EAX                            ; 0046ba7f
    CALL shape_design.c_quantizePaletteColors_FUN_0046b770 ; 0046ba80
        ;   XREF to: 0046b770 (UNCONDITIONAL_CALL)  ; void shape_design.c_quantizePaletteColors_FUN_0046b770(byte * image_data, int pixel_count, int stride, byte * palette_data, ...)
    ADD ESP,0x18                        ; 0046ba85
    JMP 0x0046baf4                      ; 0046ba88
        ;   XREF to: 0046baf4 (UNCONDITIONAL_JUMP)  ; LAB_0046baf4
    CMP dword ptr [EBP + 0x1c],0x20     ; 0046ba8a
        ;   Label: LAB_0046ba8a
    JL 0x0046baf4                       ; 0046ba8e
        ;   XREF to: 0046baf4 (CONDITIONAL_JUMP)  ; LAB_0046baf4
    MOV EAX,0x61d449                    ; 0046ba90 | = "cTRI"
    PUSH EAX                            ; 0046ba95 | = "cTRI"
    MOV EAX,dword ptr [EBP + 0x18]      ; 0046ba96
    PUSH EAX                            ; 0046ba99
    MOV EAX,dword ptr [EBP + 0x1c]      ; 0046ba9a
    PUSH EAX                            ; 0046ba9d
    PUSH 0x1                            ; 0046ba9e
    MOV EAX,dword ptr [EBP + 0x1c]      ; 0046baa0
    PUSH EAX                            ; 0046baa3
    MOV EAX,dword ptr [EBP + 0x14]      ; 0046baa4
    PUSH EAX                            ; 0046baa7
    CALL shape_design.c_quantizePaletteColors_FUN_0046b770 ; 0046baa8
        ;   XREF to: 0046b770 (UNCONDITIONAL_CALL)  ; void shape_design.c_quantizePaletteColors_FUN_0046b770(byte * image_data, int pixel_count, int stride, byte * palette_data, ...)
    ADD ESP,0x18                        ; 0046baad
    MOV EAX,0x61d44e                    ; 0046bab0 | = "Crm3"
    PUSH EAX                            ; 0046bab5 | = "Crm3"
    MOV EAX,dword ptr [EBP + 0x18]      ; 0046bab6
    PUSH EAX                            ; 0046bab9
    PUSH 0x1                            ; 0046baba
    MOV EAX,dword ptr [EBP + 0x1c]      ; 0046babc
    PUSH EAX                            ; 0046babf
    MOV EAX,dword ptr [EBP + 0x1c]      ; 0046bac0
    PUSH EAX                            ; 0046bac3
    MOV EAX,dword ptr [EBP + 0x14]      ; 0046bac4
    PUSH EAX                            ; 0046bac7
    CALL shape_design.c_quantizePaletteColors_FUN_0046b770 ; 0046bac8
        ;   XREF to: 0046b770 (UNCONDITIONAL_CALL)  ; void shape_design.c_quantizePaletteColors_FUN_0046b770(byte * image_data, int pixel_count, int stride, byte * palette_data, ...)
    ADD ESP,0x18                        ; 0046bacd
    MOV EAX,0x61d453                    ; 0046bad0 | = "rsrv"
    PUSH EAX                            ; 0046bad5 | = "rsrv"
    MOV EAX,dword ptr [EBP + 0x18]      ; 0046bad6
    PUSH EAX                            ; 0046bad9
    PUSH -0x1                           ; 0046bada
    MOV EAX,dword ptr [EBP + 0x1c]      ; 0046badc
    PUSH EAX                            ; 0046badf
    MOV EAX,dword ptr [EBP + 0x1c]      ; 0046bae0
    PUSH EAX                            ; 0046bae3
    MOV EAX,dword ptr [EBP + 0x14]      ; 0046bae4
    ADD EAX,dword ptr [EBP + 0x1c]      ; 0046bae7
    DEC EAX                             ; 0046baea
    PUSH EAX                            ; 0046baeb
    CALL shape_design.c_quantizePaletteColors_FUN_0046b770 ; 0046baec
        ;   XREF to: 0046b770 (UNCONDITIONAL_CALL)  ; void shape_design.c_quantizePaletteColors_FUN_0046b770(byte * image_data, int pixel_count, int stride, byte * palette_data, ...)
    ADD ESP,0x18                        ; 0046baf1
    LEA EAX,[EBP + -0x4]                ; 0046baf4
        ;   Label: LAB_0046baf4
    PUSH EAX                            ; 0046baf7
    CALL crt_time.c__time_FUN_006001f0  ; 0046baf8
        ;   XREF to: 006001f0 (UNCONDITIONAL_CALL)  ; time_t crt_time.c__time_FUN_006001f0(time_t * optional_output)
    ADD ESP,0x4                         ; 0046bafd
    LEA EAX,[EBP + -0x4]                ; 0046bb00
    PUSH EAX                            ; 0046bb03
    CALL crt_time.c__localtime_FUN_00600288 ; 0046bb04
        ;   XREF to: 00600288 (UNCONDITIONAL_CALL)  ; _tm * crt_time.c__localtime_FUN_00600288(time_t * timer)
    ADD ESP,0x4                         ; 0046bb09
    PUSH EAX                            ; 0046bb0c
    MOV EAX,0x61d458                    ; 0046bb0d | = "%m%d%y"
    PUSH EAX                            ; 0046bb12 | = "%m%d%y"
    PUSH 0xc8                           ; 0046bb13
    LEA EAX,[EBP + 0xffffff34]          ; 0046bb18
    PUSH EAX                            ; 0046bb1e
    CALL crt_time.c__strftime_FUN_006002d4 ; 0046bb1f
        ;   XREF to: 006002d4 (UNCONDITIONAL_CALL)  ; uint crt_time.c__strftime_FUN_006002d4(char * dest_buffer, uint buffer_size, char * format_string, _tm * time_ptr)
    ADD ESP,0x10                        ; 0046bb24
    MOV EAX,0x61d45f                    ; 0046bb27 | = "Jan 10 2000"
    PUSH EAX                            ; 0046bb2c | = "Jan 10 2000"
    LEA EAX,[EBP + 0xffffff34]          ; 0046bb2d
    PUSH EAX                            ; 0046bb33
    MOV EAX,0x61d46b                    ; 0046bb34 | = "%s%s"
    PUSH EAX                            ; 0046bb39 | = "%s%s"
    LEA EAX,[EBP + 0xfffffb34]          ; 0046bb3a
    PUSH EAX                            ; 0046bb40
    CALL crt_stdio.c__sprintf_FUN_005fdbd0 ; 0046bb41
        ;   XREF to: 005fdbd0 (UNCONDITIONAL_CALL)  ; int crt_stdio.c__sprintf_FUN_005fdbd0(char * buffer, char * format)
    ADD ESP,0x10                        ; 0046bb46
    LEA EAX,[EBP + 0xfffffb34]          ; 0046bb49
    PUSH EAX                            ; 0046bb4f
    MOV EAX,dword ptr [EBP + 0x18]      ; 0046bb50
    PUSH EAX                            ; 0046bb53
    MOV EAX,dword ptr [EBP + 0x1c]      ; 0046bb54
    NEG EAX                             ; 0046bb57
    PUSH EAX                            ; 0046bb59
    PUSH 0x1                            ; 0046bb5a
    MOV EAX,dword ptr [EBP + 0x1c]      ; 0046bb5c
    PUSH EAX                            ; 0046bb5f
    MOV EAX,dword ptr [EBP + 0x1c]      ; 0046bb60
    DEC EAX                             ; 0046bb63
    IMUL EAX,dword ptr [EBP + 0x1c]     ; 0046bb64
    ADD EAX,dword ptr [EBP + 0x14]      ; 0046bb68
    PUSH EAX                            ; 0046bb6b
    CALL shape_design.c_quantizePaletteColors_FUN_0046b770 ; 0046bb6c
        ;   XREF to: 0046b770 (UNCONDITIONAL_CALL)  ; void shape_design.c_quantizePaletteColors_FUN_0046b770(byte * image_data, int pixel_count, int stride, byte * palette_data, ...)
    ADD ESP,0x18                        ; 0046bb71
    MOV ESP,EBP                         ; 0046bb74
    POP EBP                             ; 0046bb76
    POP EDI                             ; 0046bb77
    POP ESI                             ; 0046bb78
    POP EBX                             ; 0046bb79
    RET                                 ; 0046bb7a

