// Auto-generated by scripts/Python/gen_struct_layout_checks.py
// DO NOT EDIT BY HAND. Re-run the generator after updating types.
//
// Category: dos
// Structs : 2

#include "nocturne.h"

namespace nocturne_layout_dos {

// ---- IMAGE_DOS_HEADER (128 bytes) ----
static_assert(sizeof(IMAGE_DOS_HEADER) == 128,
              "sizeof(IMAGE_DOS_HEADER) != 128");
static_assert(__builtin_offsetof(IMAGE_DOS_HEADER, e_magic) == 0,
              "offsetof(IMAGE_DOS_HEADER, e_magic) != 0");
static_assert(__builtin_offsetof(IMAGE_DOS_HEADER, e_cblp) == 2,
              "offsetof(IMAGE_DOS_HEADER, e_cblp) != 2");
static_assert(__builtin_offsetof(IMAGE_DOS_HEADER, e_cp) == 4,
              "offsetof(IMAGE_DOS_HEADER, e_cp) != 4");
static_assert(__builtin_offsetof(IMAGE_DOS_HEADER, e_crlc) == 6,
              "offsetof(IMAGE_DOS_HEADER, e_crlc) != 6");
static_assert(__builtin_offsetof(IMAGE_DOS_HEADER, e_cparhdr) == 8,
              "offsetof(IMAGE_DOS_HEADER, e_cparhdr) != 8");
static_assert(__builtin_offsetof(IMAGE_DOS_HEADER, e_minalloc) == 10,
              "offsetof(IMAGE_DOS_HEADER, e_minalloc) != 10");
static_assert(__builtin_offsetof(IMAGE_DOS_HEADER, e_maxalloc) == 12,
              "offsetof(IMAGE_DOS_HEADER, e_maxalloc) != 12");
static_assert(__builtin_offsetof(IMAGE_DOS_HEADER, e_ss) == 14,
              "offsetof(IMAGE_DOS_HEADER, e_ss) != 14");
static_assert(__builtin_offsetof(IMAGE_DOS_HEADER, e_sp) == 16,
              "offsetof(IMAGE_DOS_HEADER, e_sp) != 16");
static_assert(__builtin_offsetof(IMAGE_DOS_HEADER, e_csum) == 18,
              "offsetof(IMAGE_DOS_HEADER, e_csum) != 18");
static_assert(__builtin_offsetof(IMAGE_DOS_HEADER, e_ip) == 20,
              "offsetof(IMAGE_DOS_HEADER, e_ip) != 20");
static_assert(__builtin_offsetof(IMAGE_DOS_HEADER, e_cs) == 22,
              "offsetof(IMAGE_DOS_HEADER, e_cs) != 22");
static_assert(__builtin_offsetof(IMAGE_DOS_HEADER, e_lfarlc) == 24,
              "offsetof(IMAGE_DOS_HEADER, e_lfarlc) != 24");
static_assert(__builtin_offsetof(IMAGE_DOS_HEADER, e_ovno) == 26,
              "offsetof(IMAGE_DOS_HEADER, e_ovno) != 26");
static_assert(__builtin_offsetof(IMAGE_DOS_HEADER, e_oemid) == 36,
              "offsetof(IMAGE_DOS_HEADER, e_oemid) != 36");
static_assert(__builtin_offsetof(IMAGE_DOS_HEADER, e_oeminfo) == 38,
              "offsetof(IMAGE_DOS_HEADER, e_oeminfo) != 38");
static_assert(__builtin_offsetof(IMAGE_DOS_HEADER, e_lfanew) == 60,
              "offsetof(IMAGE_DOS_HEADER, e_lfanew) != 60");
static_assert(__builtin_offsetof(IMAGE_DOS_HEADER, e_program) == 64,
              "offsetof(IMAGE_DOS_HEADER, e_program) != 64");

// ---- _find_t (280 bytes) ----
static_assert(sizeof(_find_t) == 280,
              "sizeof(_find_t) != 280");
static_assert(__builtin_offsetof(_find_t, attrib) == 0,
              "offsetof(_find_t, attrib) != 0");
static_assert(__builtin_offsetof(_find_t, padding_0x1) == 1,
              "offsetof(_find_t, padding_0x1) != 1");
static_assert(__builtin_offsetof(_find_t, wr_time) == 4,
              "offsetof(_find_t, wr_time) != 4");
static_assert(__builtin_offsetof(_find_t, cr_time) == 8,
              "offsetof(_find_t, cr_time) != 8");
static_assert(__builtin_offsetof(_find_t, ac_time) == 12,
              "offsetof(_find_t, ac_time) != 12");
static_assert(__builtin_offsetof(_find_t, size) == 16,
              "offsetof(_find_t, size) != 16");
static_assert(__builtin_offsetof(_find_t, name) == 20,
              "offsetof(_find_t, name) != 20");

} // namespace
