// Auto-generated by scripts/Python/gen_struct_layout_checks.py
// DO NOT EDIT BY HAND. Re-run the generator after updating types.
//
// Category: dsound
// Structs : 22

#include "nocturne.h"

namespace nocturne_layout_dsound {

// ---- DS3DBUFFER (64 bytes) ----
static_assert(sizeof(DS3DBUFFER) == 64,
              "sizeof(DS3DBUFFER) != 64");
static_assert(__builtin_offsetof(DS3DBUFFER, dwSize) == 0,
              "offsetof(DS3DBUFFER, dwSize) != 0");
static_assert(__builtin_offsetof(DS3DBUFFER, vPosition) == 4,
              "offsetof(DS3DBUFFER, vPosition) != 4");
static_assert(__builtin_offsetof(DS3DBUFFER, vVelocity) == 16,
              "offsetof(DS3DBUFFER, vVelocity) != 16");
static_assert(__builtin_offsetof(DS3DBUFFER, vConeOrientation) == 28,
              "offsetof(DS3DBUFFER, vConeOrientation) != 28");
static_assert(__builtin_offsetof(DS3DBUFFER, dwInsideConeAngle) == 40,
              "offsetof(DS3DBUFFER, dwInsideConeAngle) != 40");
static_assert(__builtin_offsetof(DS3DBUFFER, dwOutsideConeAngle) == 44,
              "offsetof(DS3DBUFFER, dwOutsideConeAngle) != 44");
static_assert(__builtin_offsetof(DS3DBUFFER, lConeOutsideVolume) == 48,
              "offsetof(DS3DBUFFER, lConeOutsideVolume) != 48");
static_assert(__builtin_offsetof(DS3DBUFFER, flMinDistance) == 52,
              "offsetof(DS3DBUFFER, flMinDistance) != 52");
static_assert(__builtin_offsetof(DS3DBUFFER, flMaxDistance) == 56,
              "offsetof(DS3DBUFFER, flMaxDistance) != 56");
static_assert(__builtin_offsetof(DS3DBUFFER, dwMode) == 60,
              "offsetof(DS3DBUFFER, dwMode) != 60");

// ---- DS3DLISTENER (64 bytes) ----
static_assert(sizeof(DS3DLISTENER) == 64,
              "sizeof(DS3DLISTENER) != 64");
static_assert(__builtin_offsetof(DS3DLISTENER, dwSize) == 0,
              "offsetof(DS3DLISTENER, dwSize) != 0");
static_assert(__builtin_offsetof(DS3DLISTENER, vPosition) == 4,
              "offsetof(DS3DLISTENER, vPosition) != 4");
static_assert(__builtin_offsetof(DS3DLISTENER, vVelocity) == 16,
              "offsetof(DS3DLISTENER, vVelocity) != 16");
static_assert(__builtin_offsetof(DS3DLISTENER, vOrientFront) == 28,
              "offsetof(DS3DLISTENER, vOrientFront) != 28");
static_assert(__builtin_offsetof(DS3DLISTENER, vOrientTop) == 40,
              "offsetof(DS3DLISTENER, vOrientTop) != 40");
static_assert(__builtin_offsetof(DS3DLISTENER, flDistanceFactor) == 52,
              "offsetof(DS3DLISTENER, flDistanceFactor) != 52");
static_assert(__builtin_offsetof(DS3DLISTENER, flRolloffFactor) == 56,
              "offsetof(DS3DLISTENER, flRolloffFactor) != 56");
static_assert(__builtin_offsetof(DS3DLISTENER, flDopplerFactor) == 60,
              "offsetof(DS3DLISTENER, flDopplerFactor) != 60");

// ---- DSBCAPS (20 bytes) ----
static_assert(sizeof(DSBCAPS) == 20,
              "sizeof(DSBCAPS) != 20");
static_assert(__builtin_offsetof(DSBCAPS, dwSize) == 0,
              "offsetof(DSBCAPS, dwSize) != 0");
static_assert(__builtin_offsetof(DSBCAPS, dwFlags) == 4,
              "offsetof(DSBCAPS, dwFlags) != 4");
static_assert(__builtin_offsetof(DSBCAPS, dwBufferBytes) == 8,
              "offsetof(DSBCAPS, dwBufferBytes) != 8");
static_assert(__builtin_offsetof(DSBCAPS, dwUnlockTransferRate) == 12,
              "offsetof(DSBCAPS, dwUnlockTransferRate) != 12");
static_assert(__builtin_offsetof(DSBCAPS, dwPlayCpuOverhead) == 16,
              "offsetof(DSBCAPS, dwPlayCpuOverhead) != 16");

// ---- DSBUFFERDESC (20 bytes) ----
static_assert(sizeof(DSBUFFERDESC) == 20,
              "sizeof(DSBUFFERDESC) != 20");
static_assert(__builtin_offsetof(DSBUFFERDESC, dwSize) == 0,
              "offsetof(DSBUFFERDESC, dwSize) != 0");
static_assert(__builtin_offsetof(DSBUFFERDESC, dwFlags) == 4,
              "offsetof(DSBUFFERDESC, dwFlags) != 4");
static_assert(__builtin_offsetof(DSBUFFERDESC, dwBufferBytes) == 8,
              "offsetof(DSBUFFERDESC, dwBufferBytes) != 8");
static_assert(__builtin_offsetof(DSBUFFERDESC, dwReserved) == 12,
              "offsetof(DSBUFFERDESC, dwReserved) != 12");
static_assert(__builtin_offsetof(DSBUFFERDESC, lpwfxFormat) == 16,
              "offsetof(DSBUFFERDESC, lpwfxFormat) != 16");

// ---- DSCAPS (96 bytes) ----
static_assert(sizeof(DSCAPS) == 96,
              "sizeof(DSCAPS) != 96");
static_assert(__builtin_offsetof(DSCAPS, dwSize) == 0,
              "offsetof(DSCAPS, dwSize) != 0");
static_assert(__builtin_offsetof(DSCAPS, dwFlags) == 4,
              "offsetof(DSCAPS, dwFlags) != 4");
static_assert(__builtin_offsetof(DSCAPS, dwMinSecondarySampleRate) == 8,
              "offsetof(DSCAPS, dwMinSecondarySampleRate) != 8");
static_assert(__builtin_offsetof(DSCAPS, dwMaxSecondarySampleRate) == 12,
              "offsetof(DSCAPS, dwMaxSecondarySampleRate) != 12");
static_assert(__builtin_offsetof(DSCAPS, dwPrimaryBuffers) == 16,
              "offsetof(DSCAPS, dwPrimaryBuffers) != 16");
static_assert(__builtin_offsetof(DSCAPS, dwMaxHwMixingAllBuffers) == 20,
              "offsetof(DSCAPS, dwMaxHwMixingAllBuffers) != 20");
static_assert(__builtin_offsetof(DSCAPS, dwMaxHwMixingStaticBuffers) == 24,
              "offsetof(DSCAPS, dwMaxHwMixingStaticBuffers) != 24");
static_assert(__builtin_offsetof(DSCAPS, dwMaxHwMixingStreamingBuffers) == 28,
              "offsetof(DSCAPS, dwMaxHwMixingStreamingBuffers) != 28");
static_assert(__builtin_offsetof(DSCAPS, dwFreeHwMixingAllBuffers) == 32,
              "offsetof(DSCAPS, dwFreeHwMixingAllBuffers) != 32");
static_assert(__builtin_offsetof(DSCAPS, dwFreeHwMixingStaticBuffers) == 36,
              "offsetof(DSCAPS, dwFreeHwMixingStaticBuffers) != 36");
static_assert(__builtin_offsetof(DSCAPS, dwFreeHwMixingStreamingBuffers) == 40,
              "offsetof(DSCAPS, dwFreeHwMixingStreamingBuffers) != 40");
static_assert(__builtin_offsetof(DSCAPS, dwMaxHw3DAllBuffers) == 44,
              "offsetof(DSCAPS, dwMaxHw3DAllBuffers) != 44");
static_assert(__builtin_offsetof(DSCAPS, dwMaxHw3DStaticBuffers) == 48,
              "offsetof(DSCAPS, dwMaxHw3DStaticBuffers) != 48");
static_assert(__builtin_offsetof(DSCAPS, dwMaxHw3DStreamingBuffers) == 52,
              "offsetof(DSCAPS, dwMaxHw3DStreamingBuffers) != 52");
static_assert(__builtin_offsetof(DSCAPS, dwFreeHw3DAllBuffers) == 56,
              "offsetof(DSCAPS, dwFreeHw3DAllBuffers) != 56");
static_assert(__builtin_offsetof(DSCAPS, dwFreeHw3DStaticBuffers) == 60,
              "offsetof(DSCAPS, dwFreeHw3DStaticBuffers) != 60");
static_assert(__builtin_offsetof(DSCAPS, dwFreeHw3DStreamingBuffers) == 64,
              "offsetof(DSCAPS, dwFreeHw3DStreamingBuffers) != 64");
static_assert(__builtin_offsetof(DSCAPS, dwTotalHwMemBytes) == 68,
              "offsetof(DSCAPS, dwTotalHwMemBytes) != 68");
static_assert(__builtin_offsetof(DSCAPS, dwFreeHwMemBytes) == 72,
              "offsetof(DSCAPS, dwFreeHwMemBytes) != 72");
static_assert(__builtin_offsetof(DSCAPS, dwMaxContigFreeHwMemBytes) == 76,
              "offsetof(DSCAPS, dwMaxContigFreeHwMemBytes) != 76");
static_assert(__builtin_offsetof(DSCAPS, dwUnlockTransferRateHwBuffers) == 80,
              "offsetof(DSCAPS, dwUnlockTransferRateHwBuffers) != 80");
static_assert(__builtin_offsetof(DSCAPS, dwPlayCpuOverheadSwBuffers) == 84,
              "offsetof(DSCAPS, dwPlayCpuOverheadSwBuffers) != 84");
static_assert(__builtin_offsetof(DSCAPS, dwReserved1) == 88,
              "offsetof(DSCAPS, dwReserved1) != 88");
static_assert(__builtin_offsetof(DSCAPS, dwReserved2) == 92,
              "offsetof(DSCAPS, dwReserved2) != 92");

// ---- DSCBCAPS (16 bytes) ----
static_assert(sizeof(DSCBCAPS) == 16,
              "sizeof(DSCBCAPS) != 16");
static_assert(__builtin_offsetof(DSCBCAPS, dwSize) == 0,
              "offsetof(DSCBCAPS, dwSize) != 0");
static_assert(__builtin_offsetof(DSCBCAPS, dwFlags) == 4,
              "offsetof(DSCBCAPS, dwFlags) != 4");
static_assert(__builtin_offsetof(DSCBCAPS, dwBufferBytes) == 8,
              "offsetof(DSCBCAPS, dwBufferBytes) != 8");
static_assert(__builtin_offsetof(DSCBCAPS, dwReserved) == 12,
              "offsetof(DSCBCAPS, dwReserved) != 12");

// ---- DSCBUFFERDESC (28 bytes) ----
static_assert(sizeof(DSCBUFFERDESC) == 28,
              "sizeof(DSCBUFFERDESC) != 28");
static_assert(__builtin_offsetof(DSCBUFFERDESC, dwSize) == 0,
              "offsetof(DSCBUFFERDESC, dwSize) != 0");
static_assert(__builtin_offsetof(DSCBUFFERDESC, dwFlags) == 4,
              "offsetof(DSCBUFFERDESC, dwFlags) != 4");
static_assert(__builtin_offsetof(DSCBUFFERDESC, dwBufferBytes) == 8,
              "offsetof(DSCBUFFERDESC, dwBufferBytes) != 8");
static_assert(__builtin_offsetof(DSCBUFFERDESC, dwReserved) == 12,
              "offsetof(DSCBUFFERDESC, dwReserved) != 12");
static_assert(__builtin_offsetof(DSCBUFFERDESC, lpwfxFormat) == 16,
              "offsetof(DSCBUFFERDESC, lpwfxFormat) != 16");
static_assert(__builtin_offsetof(DSCBUFFERDESC, dwFXCount) == 20,
              "offsetof(DSCBUFFERDESC, dwFXCount) != 20");
static_assert(__builtin_offsetof(DSCBUFFERDESC, lpDSCFXDesc) == 24,
              "offsetof(DSCBUFFERDESC, lpDSCFXDesc) != 24");

// ---- DSCCAPS (16 bytes) ----
static_assert(sizeof(DSCCAPS) == 16,
              "sizeof(DSCCAPS) != 16");
static_assert(__builtin_offsetof(DSCCAPS, dwSize) == 0,
              "offsetof(DSCCAPS, dwSize) != 0");
static_assert(__builtin_offsetof(DSCCAPS, dwFlags) == 4,
              "offsetof(DSCCAPS, dwFlags) != 4");
static_assert(__builtin_offsetof(DSCCAPS, dwFormats) == 8,
              "offsetof(DSCCAPS, dwFormats) != 8");
static_assert(__builtin_offsetof(DSCCAPS, dwChannels) == 12,
              "offsetof(DSCCAPS, dwChannels) != 12");

// ---- IDirectSound (4 bytes) ----
static_assert(sizeof(IDirectSound) == 4,
              "sizeof(IDirectSound) != 4");
static_assert(__builtin_offsetof(IDirectSound, vtable) == 0,
              "offsetof(IDirectSound, vtable) != 0");

// ---- IDirectSound3DBuffer (4 bytes) ----
static_assert(sizeof(IDirectSound3DBuffer) == 4,
              "sizeof(IDirectSound3DBuffer) != 4");
static_assert(__builtin_offsetof(IDirectSound3DBuffer, vtable) == 0,
              "offsetof(IDirectSound3DBuffer, vtable) != 0");

// ---- IDirectSound3DBuffer_vtable (84 bytes) ----
static_assert(sizeof(IDirectSound3DBuffer_vtable) == 84,
              "sizeof(IDirectSound3DBuffer_vtable) != 84");
static_assert(__builtin_offsetof(IDirectSound3DBuffer_vtable, QueryInterface) == 0,
              "offsetof(IDirectSound3DBuffer_vtable, QueryInterface) != 0");
static_assert(__builtin_offsetof(IDirectSound3DBuffer_vtable, AddRef) == 4,
              "offsetof(IDirectSound3DBuffer_vtable, AddRef) != 4");
static_assert(__builtin_offsetof(IDirectSound3DBuffer_vtable, Release) == 8,
              "offsetof(IDirectSound3DBuffer_vtable, Release) != 8");
static_assert(__builtin_offsetof(IDirectSound3DBuffer_vtable, GetAllParameters) == 12,
              "offsetof(IDirectSound3DBuffer_vtable, GetAllParameters) != 12");
static_assert(__builtin_offsetof(IDirectSound3DBuffer_vtable, GetConeAngles) == 16,
              "offsetof(IDirectSound3DBuffer_vtable, GetConeAngles) != 16");
static_assert(__builtin_offsetof(IDirectSound3DBuffer_vtable, GetConeOrientation) == 20,
              "offsetof(IDirectSound3DBuffer_vtable, GetConeOrientation) != 20");
static_assert(__builtin_offsetof(IDirectSound3DBuffer_vtable, GetConeOutsideVolume) == 24,
              "offsetof(IDirectSound3DBuffer_vtable, GetConeOutsideVolume) != 24");
static_assert(__builtin_offsetof(IDirectSound3DBuffer_vtable, GetMaxDistance) == 28,
              "offsetof(IDirectSound3DBuffer_vtable, GetMaxDistance) != 28");
static_assert(__builtin_offsetof(IDirectSound3DBuffer_vtable, GetMinDistance) == 32,
              "offsetof(IDirectSound3DBuffer_vtable, GetMinDistance) != 32");
static_assert(__builtin_offsetof(IDirectSound3DBuffer_vtable, GetMode) == 36,
              "offsetof(IDirectSound3DBuffer_vtable, GetMode) != 36");
static_assert(__builtin_offsetof(IDirectSound3DBuffer_vtable, GetPosition) == 40,
              "offsetof(IDirectSound3DBuffer_vtable, GetPosition) != 40");
static_assert(__builtin_offsetof(IDirectSound3DBuffer_vtable, GetVelocity) == 44,
              "offsetof(IDirectSound3DBuffer_vtable, GetVelocity) != 44");
static_assert(__builtin_offsetof(IDirectSound3DBuffer_vtable, SetAllParameters) == 48,
              "offsetof(IDirectSound3DBuffer_vtable, SetAllParameters) != 48");
static_assert(__builtin_offsetof(IDirectSound3DBuffer_vtable, SetConeAngles) == 52,
              "offsetof(IDirectSound3DBuffer_vtable, SetConeAngles) != 52");
static_assert(__builtin_offsetof(IDirectSound3DBuffer_vtable, SetConeOrientation) == 56,
              "offsetof(IDirectSound3DBuffer_vtable, SetConeOrientation) != 56");
static_assert(__builtin_offsetof(IDirectSound3DBuffer_vtable, SetConeOutsideVolume) == 60,
              "offsetof(IDirectSound3DBuffer_vtable, SetConeOutsideVolume) != 60");
static_assert(__builtin_offsetof(IDirectSound3DBuffer_vtable, SetMaxDistance) == 64,
              "offsetof(IDirectSound3DBuffer_vtable, SetMaxDistance) != 64");
static_assert(__builtin_offsetof(IDirectSound3DBuffer_vtable, SetMinDistance) == 68,
              "offsetof(IDirectSound3DBuffer_vtable, SetMinDistance) != 68");
static_assert(__builtin_offsetof(IDirectSound3DBuffer_vtable, SetMode) == 72,
              "offsetof(IDirectSound3DBuffer_vtable, SetMode) != 72");
static_assert(__builtin_offsetof(IDirectSound3DBuffer_vtable, SetPosition) == 76,
              "offsetof(IDirectSound3DBuffer_vtable, SetPosition) != 76");
static_assert(__builtin_offsetof(IDirectSound3DBuffer_vtable, SetVelocity) == 80,
              "offsetof(IDirectSound3DBuffer_vtable, SetVelocity) != 80");

// ---- IDirectSound3DListener (4 bytes) ----
static_assert(sizeof(IDirectSound3DListener) == 4,
              "sizeof(IDirectSound3DListener) != 4");
static_assert(__builtin_offsetof(IDirectSound3DListener, vtable) == 0,
              "offsetof(IDirectSound3DListener, vtable) != 0");

// ---- IDirectSound3DListener_vtable (72 bytes) ----
static_assert(sizeof(IDirectSound3DListener_vtable) == 72,
              "sizeof(IDirectSound3DListener_vtable) != 72");
static_assert(__builtin_offsetof(IDirectSound3DListener_vtable, QueryInterface) == 0,
              "offsetof(IDirectSound3DListener_vtable, QueryInterface) != 0");
static_assert(__builtin_offsetof(IDirectSound3DListener_vtable, AddRef) == 4,
              "offsetof(IDirectSound3DListener_vtable, AddRef) != 4");
static_assert(__builtin_offsetof(IDirectSound3DListener_vtable, Release) == 8,
              "offsetof(IDirectSound3DListener_vtable, Release) != 8");
static_assert(__builtin_offsetof(IDirectSound3DListener_vtable, GetAllParameters) == 12,
              "offsetof(IDirectSound3DListener_vtable, GetAllParameters) != 12");
static_assert(__builtin_offsetof(IDirectSound3DListener_vtable, GetDistanceFactor) == 16,
              "offsetof(IDirectSound3DListener_vtable, GetDistanceFactor) != 16");
static_assert(__builtin_offsetof(IDirectSound3DListener_vtable, GetDopplerFactor) == 20,
              "offsetof(IDirectSound3DListener_vtable, GetDopplerFactor) != 20");
static_assert(__builtin_offsetof(IDirectSound3DListener_vtable, GetOrientation) == 24,
              "offsetof(IDirectSound3DListener_vtable, GetOrientation) != 24");
static_assert(__builtin_offsetof(IDirectSound3DListener_vtable, GetPosition) == 28,
              "offsetof(IDirectSound3DListener_vtable, GetPosition) != 28");
static_assert(__builtin_offsetof(IDirectSound3DListener_vtable, GetRolloffFactor) == 32,
              "offsetof(IDirectSound3DListener_vtable, GetRolloffFactor) != 32");
static_assert(__builtin_offsetof(IDirectSound3DListener_vtable, GetVelocity) == 36,
              "offsetof(IDirectSound3DListener_vtable, GetVelocity) != 36");
static_assert(__builtin_offsetof(IDirectSound3DListener_vtable, SetAllParameters) == 40,
              "offsetof(IDirectSound3DListener_vtable, SetAllParameters) != 40");
static_assert(__builtin_offsetof(IDirectSound3DListener_vtable, SetDistanceFactor) == 44,
              "offsetof(IDirectSound3DListener_vtable, SetDistanceFactor) != 44");
static_assert(__builtin_offsetof(IDirectSound3DListener_vtable, SetDopplerFactor) == 48,
              "offsetof(IDirectSound3DListener_vtable, SetDopplerFactor) != 48");
static_assert(__builtin_offsetof(IDirectSound3DListener_vtable, SetOrientation) == 52,
              "offsetof(IDirectSound3DListener_vtable, SetOrientation) != 52");
static_assert(__builtin_offsetof(IDirectSound3DListener_vtable, SetPosition) == 56,
              "offsetof(IDirectSound3DListener_vtable, SetPosition) != 56");
static_assert(__builtin_offsetof(IDirectSound3DListener_vtable, SetRolloffFactor) == 60,
              "offsetof(IDirectSound3DListener_vtable, SetRolloffFactor) != 60");
static_assert(__builtin_offsetof(IDirectSound3DListener_vtable, SetVelocity) == 64,
              "offsetof(IDirectSound3DListener_vtable, SetVelocity) != 64");
static_assert(__builtin_offsetof(IDirectSound3DListener_vtable, CommitDeferredSettings) == 68,
              "offsetof(IDirectSound3DListener_vtable, CommitDeferredSettings) != 68");

// ---- IDirectSoundBuffer (4 bytes) ----
static_assert(sizeof(IDirectSoundBuffer) == 4,
              "sizeof(IDirectSoundBuffer) != 4");
static_assert(__builtin_offsetof(IDirectSoundBuffer, vtable) == 0,
              "offsetof(IDirectSoundBuffer, vtable) != 0");

// ---- IDirectSoundBufferMetadata (20 bytes) ----
static_assert(sizeof(IDirectSoundBufferMetadata) == 20,
              "sizeof(IDirectSoundBufferMetadata) != 20");
static_assert(__builtin_offsetof(IDirectSoundBufferMetadata, field_0) == 0,
              "offsetof(IDirectSoundBufferMetadata, field_0) != 0");
static_assert(__builtin_offsetof(IDirectSoundBufferMetadata, field_4) == 4,
              "offsetof(IDirectSoundBufferMetadata, field_4) != 4");
static_assert(__builtin_offsetof(IDirectSoundBufferMetadata, field_8) == 8,
              "offsetof(IDirectSoundBufferMetadata, field_8) != 8");
static_assert(__builtin_offsetof(IDirectSoundBufferMetadata, field_12) == 12,
              "offsetof(IDirectSoundBufferMetadata, field_12) != 12");
static_assert(__builtin_offsetof(IDirectSoundBufferMetadata, ref_count) == 16,
              "offsetof(IDirectSoundBufferMetadata, ref_count) != 16");

// ---- IDirectSoundBuffer_vtable (84 bytes) ----
static_assert(sizeof(IDirectSoundBuffer_vtable) == 84,
              "sizeof(IDirectSoundBuffer_vtable) != 84");
static_assert(__builtin_offsetof(IDirectSoundBuffer_vtable, QueryInterface) == 0,
              "offsetof(IDirectSoundBuffer_vtable, QueryInterface) != 0");
static_assert(__builtin_offsetof(IDirectSoundBuffer_vtable, AddRef) == 4,
              "offsetof(IDirectSoundBuffer_vtable, AddRef) != 4");
static_assert(__builtin_offsetof(IDirectSoundBuffer_vtable, Release) == 8,
              "offsetof(IDirectSoundBuffer_vtable, Release) != 8");
static_assert(__builtin_offsetof(IDirectSoundBuffer_vtable, GetCaps) == 12,
              "offsetof(IDirectSoundBuffer_vtable, GetCaps) != 12");
static_assert(__builtin_offsetof(IDirectSoundBuffer_vtable, GetCurrentPosition) == 16,
              "offsetof(IDirectSoundBuffer_vtable, GetCurrentPosition) != 16");
static_assert(__builtin_offsetof(IDirectSoundBuffer_vtable, GetFormat) == 20,
              "offsetof(IDirectSoundBuffer_vtable, GetFormat) != 20");
static_assert(__builtin_offsetof(IDirectSoundBuffer_vtable, GetVolume) == 24,
              "offsetof(IDirectSoundBuffer_vtable, GetVolume) != 24");
static_assert(__builtin_offsetof(IDirectSoundBuffer_vtable, GetPan) == 28,
              "offsetof(IDirectSoundBuffer_vtable, GetPan) != 28");
static_assert(__builtin_offsetof(IDirectSoundBuffer_vtable, GetFrequency) == 32,
              "offsetof(IDirectSoundBuffer_vtable, GetFrequency) != 32");
static_assert(__builtin_offsetof(IDirectSoundBuffer_vtable, GetStatus) == 36,
              "offsetof(IDirectSoundBuffer_vtable, GetStatus) != 36");
static_assert(__builtin_offsetof(IDirectSoundBuffer_vtable, Initialize) == 40,
              "offsetof(IDirectSoundBuffer_vtable, Initialize) != 40");
static_assert(__builtin_offsetof(IDirectSoundBuffer_vtable, Lock) == 44,
              "offsetof(IDirectSoundBuffer_vtable, Lock) != 44");
static_assert(__builtin_offsetof(IDirectSoundBuffer_vtable, Play) == 48,
              "offsetof(IDirectSoundBuffer_vtable, Play) != 48");
static_assert(__builtin_offsetof(IDirectSoundBuffer_vtable, SetCurrentPosition) == 52,
              "offsetof(IDirectSoundBuffer_vtable, SetCurrentPosition) != 52");
static_assert(__builtin_offsetof(IDirectSoundBuffer_vtable, SetFormat) == 56,
              "offsetof(IDirectSoundBuffer_vtable, SetFormat) != 56");
static_assert(__builtin_offsetof(IDirectSoundBuffer_vtable, SetVolume) == 60,
              "offsetof(IDirectSoundBuffer_vtable, SetVolume) != 60");
static_assert(__builtin_offsetof(IDirectSoundBuffer_vtable, SetPan) == 64,
              "offsetof(IDirectSoundBuffer_vtable, SetPan) != 64");
static_assert(__builtin_offsetof(IDirectSoundBuffer_vtable, SetFrequency) == 68,
              "offsetof(IDirectSoundBuffer_vtable, SetFrequency) != 68");
static_assert(__builtin_offsetof(IDirectSoundBuffer_vtable, Stop) == 72,
              "offsetof(IDirectSoundBuffer_vtable, Stop) != 72");
static_assert(__builtin_offsetof(IDirectSoundBuffer_vtable, Unlock) == 76,
              "offsetof(IDirectSoundBuffer_vtable, Unlock) != 76");
static_assert(__builtin_offsetof(IDirectSoundBuffer_vtable, Restore) == 80,
              "offsetof(IDirectSoundBuffer_vtable, Restore) != 80");

// ---- IDirectSoundCapture (4 bytes) ----
static_assert(sizeof(IDirectSoundCapture) == 4,
              "sizeof(IDirectSoundCapture) != 4");
static_assert(__builtin_offsetof(IDirectSoundCapture, vtable) == 0,
              "offsetof(IDirectSoundCapture, vtable) != 0");

// ---- IDirectSoundCaptureBuffer (4 bytes) ----
static_assert(sizeof(IDirectSoundCaptureBuffer) == 4,
              "sizeof(IDirectSoundCaptureBuffer) != 4");
static_assert(__builtin_offsetof(IDirectSoundCaptureBuffer, vtable) == 0,
              "offsetof(IDirectSoundCaptureBuffer, vtable) != 0");

// ---- IDirectSoundCaptureBuffer_vtable (48 bytes) ----
static_assert(sizeof(IDirectSoundCaptureBuffer_vtable) == 48,
              "sizeof(IDirectSoundCaptureBuffer_vtable) != 48");
static_assert(__builtin_offsetof(IDirectSoundCaptureBuffer_vtable, QueryInterface) == 0,
              "offsetof(IDirectSoundCaptureBuffer_vtable, QueryInterface) != 0");
static_assert(__builtin_offsetof(IDirectSoundCaptureBuffer_vtable, AddRef) == 4,
              "offsetof(IDirectSoundCaptureBuffer_vtable, AddRef) != 4");
static_assert(__builtin_offsetof(IDirectSoundCaptureBuffer_vtable, Release) == 8,
              "offsetof(IDirectSoundCaptureBuffer_vtable, Release) != 8");
static_assert(__builtin_offsetof(IDirectSoundCaptureBuffer_vtable, GetCaps) == 12,
              "offsetof(IDirectSoundCaptureBuffer_vtable, GetCaps) != 12");
static_assert(__builtin_offsetof(IDirectSoundCaptureBuffer_vtable, GetCurrentPosition) == 16,
              "offsetof(IDirectSoundCaptureBuffer_vtable, GetCurrentPosition) != 16");
static_assert(__builtin_offsetof(IDirectSoundCaptureBuffer_vtable, GetFormat) == 20,
              "offsetof(IDirectSoundCaptureBuffer_vtable, GetFormat) != 20");
static_assert(__builtin_offsetof(IDirectSoundCaptureBuffer_vtable, GetStatus) == 24,
              "offsetof(IDirectSoundCaptureBuffer_vtable, GetStatus) != 24");
static_assert(__builtin_offsetof(IDirectSoundCaptureBuffer_vtable, Initialize) == 28,
              "offsetof(IDirectSoundCaptureBuffer_vtable, Initialize) != 28");
static_assert(__builtin_offsetof(IDirectSoundCaptureBuffer_vtable, Lock) == 32,
              "offsetof(IDirectSoundCaptureBuffer_vtable, Lock) != 32");
static_assert(__builtin_offsetof(IDirectSoundCaptureBuffer_vtable, Start) == 36,
              "offsetof(IDirectSoundCaptureBuffer_vtable, Start) != 36");
static_assert(__builtin_offsetof(IDirectSoundCaptureBuffer_vtable, Stop) == 40,
              "offsetof(IDirectSoundCaptureBuffer_vtable, Stop) != 40");
static_assert(__builtin_offsetof(IDirectSoundCaptureBuffer_vtable, Unlock) == 44,
              "offsetof(IDirectSoundCaptureBuffer_vtable, Unlock) != 44");

// ---- IDirectSoundCapture_vtable (24 bytes) ----
static_assert(sizeof(IDirectSoundCapture_vtable) == 24,
              "sizeof(IDirectSoundCapture_vtable) != 24");
static_assert(__builtin_offsetof(IDirectSoundCapture_vtable, QueryInterface) == 0,
              "offsetof(IDirectSoundCapture_vtable, QueryInterface) != 0");
static_assert(__builtin_offsetof(IDirectSoundCapture_vtable, AddRef) == 4,
              "offsetof(IDirectSoundCapture_vtable, AddRef) != 4");
static_assert(__builtin_offsetof(IDirectSoundCapture_vtable, Release) == 8,
              "offsetof(IDirectSoundCapture_vtable, Release) != 8");
static_assert(__builtin_offsetof(IDirectSoundCapture_vtable, CreateCaptureBuffer) == 12,
              "offsetof(IDirectSoundCapture_vtable, CreateCaptureBuffer) != 12");
static_assert(__builtin_offsetof(IDirectSoundCapture_vtable, GetCaps) == 16,
              "offsetof(IDirectSoundCapture_vtable, GetCaps) != 16");
static_assert(__builtin_offsetof(IDirectSoundCapture_vtable, Initialize) == 20,
              "offsetof(IDirectSoundCapture_vtable, Initialize) != 20");

// ---- IDirectSound_vtable (44 bytes) ----
static_assert(sizeof(IDirectSound_vtable) == 44,
              "sizeof(IDirectSound_vtable) != 44");
static_assert(__builtin_offsetof(IDirectSound_vtable, QueryInterface) == 0,
              "offsetof(IDirectSound_vtable, QueryInterface) != 0");
static_assert(__builtin_offsetof(IDirectSound_vtable, AddRef) == 4,
              "offsetof(IDirectSound_vtable, AddRef) != 4");
static_assert(__builtin_offsetof(IDirectSound_vtable, Release) == 8,
              "offsetof(IDirectSound_vtable, Release) != 8");
static_assert(__builtin_offsetof(IDirectSound_vtable, CreateSoundBuffer) == 12,
              "offsetof(IDirectSound_vtable, CreateSoundBuffer) != 12");
static_assert(__builtin_offsetof(IDirectSound_vtable, GetCaps) == 16,
              "offsetof(IDirectSound_vtable, GetCaps) != 16");
static_assert(__builtin_offsetof(IDirectSound_vtable, DuplicateSoundBuffer) == 20,
              "offsetof(IDirectSound_vtable, DuplicateSoundBuffer) != 20");
static_assert(__builtin_offsetof(IDirectSound_vtable, SetCooperativeLevel) == 24,
              "offsetof(IDirectSound_vtable, SetCooperativeLevel) != 24");
static_assert(__builtin_offsetof(IDirectSound_vtable, Compact) == 28,
              "offsetof(IDirectSound_vtable, Compact) != 28");
static_assert(__builtin_offsetof(IDirectSound_vtable, GetSpeakerConfig) == 32,
              "offsetof(IDirectSound_vtable, GetSpeakerConfig) != 32");
static_assert(__builtin_offsetof(IDirectSound_vtable, SetSpeakerConfig) == 36,
              "offsetof(IDirectSound_vtable, SetSpeakerConfig) != 36");
static_assert(__builtin_offsetof(IDirectSound_vtable, Initialize) == 40,
              "offsetof(IDirectSound_vtable, Initialize) != 40");

// ---- tWAVEFORMAT (14 bytes) ----
static_assert(sizeof(tWAVEFORMAT) == 14,
              "sizeof(tWAVEFORMAT) != 14");
static_assert(__builtin_offsetof(tWAVEFORMAT, wFormatTag) == 0,
              "offsetof(tWAVEFORMAT, wFormatTag) != 0");
static_assert(__builtin_offsetof(tWAVEFORMAT, nChannels) == 2,
              "offsetof(tWAVEFORMAT, nChannels) != 2");
static_assert(__builtin_offsetof(tWAVEFORMAT, nSamplesPerSec) == 4,
              "offsetof(tWAVEFORMAT, nSamplesPerSec) != 4");
static_assert(__builtin_offsetof(tWAVEFORMAT, nAvgBytesPerSec) == 8,
              "offsetof(tWAVEFORMAT, nAvgBytesPerSec) != 8");
static_assert(__builtin_offsetof(tWAVEFORMAT, nBlockAlign) == 12,
              "offsetof(tWAVEFORMAT, nBlockAlign) != 12");

} // namespace
