// Auto-generated by scripts/Python/gen_struct_layout_checks.py
// DO NOT EDIT BY HAND. Re-run the generator after updating types.
//
// Category: ksproxy
// Structs : 2

#include "nocturne.h"

namespace nocturne_layout_ksproxy {

// ---- IKsPropertySet (4 bytes) ----
static_assert(sizeof(IKsPropertySet) == 4,
              "sizeof(IKsPropertySet) != 4");
static_assert(__builtin_offsetof(IKsPropertySet, vtable) == 0,
              "offsetof(IKsPropertySet, vtable) != 0");

// ---- IKsPropertySet_vtable (24 bytes) ----
static_assert(sizeof(IKsPropertySet_vtable) == 24,
              "sizeof(IKsPropertySet_vtable) != 24");
static_assert(__builtin_offsetof(IKsPropertySet_vtable, QueryInterface) == 0,
              "offsetof(IKsPropertySet_vtable, QueryInterface) != 0");
static_assert(__builtin_offsetof(IKsPropertySet_vtable, AddRef) == 4,
              "offsetof(IKsPropertySet_vtable, AddRef) != 4");
static_assert(__builtin_offsetof(IKsPropertySet_vtable, Release) == 8,
              "offsetof(IKsPropertySet_vtable, Release) != 8");
static_assert(__builtin_offsetof(IKsPropertySet_vtable, Get) == 12,
              "offsetof(IKsPropertySet_vtable, Get) != 12");
static_assert(__builtin_offsetof(IKsPropertySet_vtable, Set) == 16,
              "offsetof(IKsPropertySet_vtable, Set) != 16");
static_assert(__builtin_offsetof(IKsPropertySet_vtable, QuerySupport) == 20,
              "offsetof(IKsPropertySet_vtable, QuerySupport) != 20");

} // namespace
