// Auto-generated by scripts/Python/gen_struct_layout_checks.py
// DO NOT EDIT BY HAND. Re-run the generator after updating types.
//
// Category: signal
// Structs : 1

#include "nocturne.h"

namespace nocturne_layout_signal {

// ---- SignalHandlerEntry (8 bytes) ----
static_assert(sizeof(SignalHandlerEntry) == 8,
              "sizeof(SignalHandlerEntry) != 8");
static_assert(__builtin_offsetof(SignalHandlerEntry, flags) == 0,
              "offsetof(SignalHandlerEntry, flags) != 0");
static_assert(__builtin_offsetof(SignalHandlerEntry, type) == 4,
              "offsetof(SignalHandlerEntry, type) != 4");

} // namespace
