// Auto-generated by scripts/Python/gen_struct_layout_checks.py
// DO NOT EDIT BY HAND. Re-run the generator after updating types.
//
// Category: strstream
// Structs : 6

#include "nocturne.h"

namespace nocturne_layout_strstream {

// ---- _istrstream (132 bytes) ----
static_assert(sizeof(_istrstream) == 132,
              "sizeof(_istrstream) != 132");
static_assert(__builtin_offsetof(_istrstream, _strstreambase_core) == 0,
              "offsetof(_istrstream, _strstreambase_core) != 0");
static_assert(__builtin_offsetof(_istrstream, _istream_core) == 68,
              "offsetof(_istrstream, _istream_core) != 68");
static_assert(__builtin_offsetof(_istrstream, padding) == 84,
              "offsetof(_istrstream, padding) != 84");
static_assert(__builtin_offsetof(_istrstream, _ios) == 88,
              "offsetof(_istrstream, _ios) != 88");

// ---- _ostrstream (128 bytes) ----
static_assert(sizeof(_ostrstream) == 128,
              "sizeof(_ostrstream) != 128");
static_assert(__builtin_offsetof(_ostrstream, _strstreambase_core) == 0,
              "offsetof(_ostrstream, _strstreambase_core) != 0");
static_assert(__builtin_offsetof(_ostrstream, _ostream_core) == 68,
              "offsetof(_ostrstream, _ostream_core) != 68");
static_assert(__builtin_offsetof(_ostrstream, _ios) == 80,
              "offsetof(_ostrstream, _ios) != 80");
static_assert(__builtin_offsetof(_ostrstream, padding) == 124,
              "offsetof(_ostrstream, padding) != 124");

// ---- strstreambase (116 bytes) ----
static_assert(sizeof(strstreambase) == 116,
              "sizeof(strstreambase) != 116");
static_assert(__builtin_offsetof(strstreambase, _strstreambase_core) == 0,
              "offsetof(strstreambase, _strstreambase_core) != 0");
static_assert(__builtin_offsetof(strstreambase, padding) == 68,
              "offsetof(strstreambase, padding) != 68");
static_assert(__builtin_offsetof(strstreambase, _ios) == 72,
              "offsetof(strstreambase, _ios) != 72");

// ---- strstreambase_core (68 bytes) ----
static_assert(sizeof(strstreambase_core) == 68,
              "sizeof(strstreambase_core) != 68");
static_assert(__builtin_offsetof(strstreambase_core, layout_info) == 0,
              "offsetof(strstreambase_core, layout_info) != 0");
static_assert(__builtin_offsetof(strstreambase_core, _strstreambuf) == 4,
              "offsetof(strstreambase_core, _strstreambuf) != 4");
static_assert(__builtin_offsetof(strstreambase_core, destructor_vtable) == 64,
              "offsetof(strstreambase_core, destructor_vtable) != 64");

// ---- strstreambuf (60 bytes) ----
static_assert(sizeof(strstreambuf) == 60,
              "sizeof(strstreambuf) != 60");
static_assert(__builtin_offsetof(strstreambuf, _streambuf) == 0,
              "offsetof(strstreambuf, _streambuf) != 0");
static_assert(__builtin_offsetof(strstreambuf, __vtable) == 40,
              "offsetof(strstreambuf, __vtable) != 40");
static_assert(__builtin_offsetof(strstreambuf, __alloc_fn) == 44,
              "offsetof(strstreambuf, __alloc_fn) != 44");
static_assert(__builtin_offsetof(strstreambuf, __free_fn) == 48,
              "offsetof(strstreambuf, __free_fn) != 48");
static_assert(__builtin_offsetof(strstreambuf, __allocation_size) == 52,
              "offsetof(strstreambuf, __allocation_size) != 52");
static_assert(__builtin_offsetof(strstreambuf, __minbuf_size) == 56,
              "offsetof(strstreambuf, __minbuf_size) != 56");
static_assert(__builtin_offsetof(strstreambuf, __bit_flags) == 58,
              "offsetof(strstreambuf, __bit_flags) != 58");
static_assert(__builtin_offsetof(strstreambuf, padding) == 59,
              "offsetof(strstreambuf, padding) != 59");

// ---- strstreambuf_vtable (44 bytes) ----
static_assert(sizeof(strstreambuf_vtable) == 44,
              "sizeof(strstreambuf_vtable) != 44");
static_assert(__builtin_offsetof(strstreambuf_vtable, do_sgetn) == 0,
              "offsetof(strstreambuf_vtable, do_sgetn) != 0");
static_assert(__builtin_offsetof(strstreambuf_vtable, do_sputn) == 4,
              "offsetof(strstreambuf_vtable, do_sputn) != 4");
static_assert(__builtin_offsetof(strstreambuf_vtable, pbackfail) == 8,
              "offsetof(strstreambuf_vtable, pbackfail) != 8");
static_assert(__builtin_offsetof(strstreambuf_vtable, overflow) == 12,
              "offsetof(strstreambuf_vtable, overflow) != 12");
static_assert(__builtin_offsetof(strstreambuf_vtable, underflow) == 16,
              "offsetof(strstreambuf_vtable, underflow) != 16");
static_assert(__builtin_offsetof(strstreambuf_vtable, setbuf) == 20,
              "offsetof(strstreambuf_vtable, setbuf) != 20");
static_assert(__builtin_offsetof(strstreambuf_vtable, seekoff) == 24,
              "offsetof(strstreambuf_vtable, seekoff) != 24");
static_assert(__builtin_offsetof(strstreambuf_vtable, seekpos) == 28,
              "offsetof(strstreambuf_vtable, seekpos) != 28");
static_assert(__builtin_offsetof(strstreambuf_vtable, sync) == 32,
              "offsetof(strstreambuf_vtable, sync) != 32");
static_assert(__builtin_offsetof(strstreambuf_vtable, destructor) == 36,
              "offsetof(strstreambuf_vtable, destructor) != 36");
static_assert(__builtin_offsetof(strstreambuf_vtable, doallocate) == 40,
              "offsetof(strstreambuf_vtable, doallocate) != 40");

} // namespace
