// Auto-generated by scripts/Python/gen_struct_layout_checks.py
// DO NOT EDIT BY HAND. Re-run the generator after updating types.
//
// Category: time
// Structs : 2

#include "nocturne.h"

namespace nocturne_layout_time {

// ---- _tm (36 bytes) ----
static_assert(sizeof(_tm) == 36,
              "sizeof(_tm) != 36");
static_assert(__builtin_offsetof(_tm, tm_sec) == 0,
              "offsetof(_tm, tm_sec) != 0");
static_assert(__builtin_offsetof(_tm, tm_min) == 4,
              "offsetof(_tm, tm_min) != 4");
static_assert(__builtin_offsetof(_tm, tm_hour) == 8,
              "offsetof(_tm, tm_hour) != 8");
static_assert(__builtin_offsetof(_tm, tm_mday) == 12,
              "offsetof(_tm, tm_mday) != 12");
static_assert(__builtin_offsetof(_tm, tm_mon) == 16,
              "offsetof(_tm, tm_mon) != 16");
static_assert(__builtin_offsetof(_tm, tm_year) == 20,
              "offsetof(_tm, tm_year) != 20");
static_assert(__builtin_offsetof(_tm, tm_wday) == 24,
              "offsetof(_tm, tm_wday) != 24");
static_assert(__builtin_offsetof(_tm, tm_yday) == 28,
              "offsetof(_tm, tm_yday) != 28");
static_assert(__builtin_offsetof(_tm, tm_isdst) == 32,
              "offsetof(_tm, tm_isdst) != 32");

// ---- dst_rule (32 bytes) ----
static_assert(sizeof(dst_rule) == 32,
              "sizeof(dst_rule) != 32");
static_assert(__builtin_offsetof(dst_rule, seconds) == 0,
              "offsetof(dst_rule, seconds) != 0");
static_assert(__builtin_offsetof(dst_rule, minutes) == 4,
              "offsetof(dst_rule, minutes) != 4");
static_assert(__builtin_offsetof(dst_rule, hours) == 8,
              "offsetof(dst_rule, hours) != 8");
static_assert(__builtin_offsetof(dst_rule, day) == 12,
              "offsetof(dst_rule, day) != 12");
static_assert(__builtin_offsetof(dst_rule, month) == 16,
              "offsetof(dst_rule, month) != 16");
static_assert(__builtin_offsetof(dst_rule, week) == 20,
              "offsetof(dst_rule, week) != 20");
static_assert(__builtin_offsetof(dst_rule, day_of_year) == 24,
              "offsetof(dst_rule, day_of_year) != 24");
static_assert(__builtin_offsetof(dst_rule, rule_type) == 28,
              "offsetof(dst_rule, rule_type) != 28");

} // namespace
