// Auto-generated by scripts/Python/gen_struct_layout_checks.py
// DO NOT EDIT BY HAND. Re-run the generator after updating types.
//
// Category: uncategorized
// Structs : 1

#include "nocturne.h"

namespace nocturne_layout_uncategorized {

// ---- IMAGE_RESOURCE_DIRECTORY_ENTRY_DirectoryStruct (8 bytes) ----
static_assert(sizeof(IMAGE_RESOURCE_DIRECTORY_ENTRY_DirectoryStruct) == 8,
              "sizeof(IMAGE_RESOURCE_DIRECTORY_ENTRY_DirectoryStruct) != 8");
static_assert(__builtin_offsetof(IMAGE_RESOURCE_DIRECTORY_ENTRY_DirectoryStruct, OffsetToDirectory) == 0,
              "offsetof(IMAGE_RESOURCE_DIRECTORY_ENTRY_DirectoryStruct, OffsetToDirectory) != 0");
static_assert(__builtin_offsetof(IMAGE_RESOURCE_DIRECTORY_ENTRY_DirectoryStruct, DataIsDirectory) == 4,
              "offsetof(IMAGE_RESOURCE_DIRECTORY_ENTRY_DirectoryStruct, DataIsDirectory) != 4");

} // namespace
