// Auto-generated by scripts/Python/gen_struct_layout_checks.py
// DO NOT EDIT BY HAND. Re-run the generator after updating types.
//
// Category: utime
// Structs : 1

#include "nocturne.h"

namespace nocturne_layout_utime {

// ---- _utimbuf (8 bytes) ----
static_assert(sizeof(_utimbuf) == 8,
              "sizeof(_utimbuf) != 8");
static_assert(__builtin_offsetof(_utimbuf, actime) == 0,
              "offsetof(_utimbuf, actime) != 0");
static_assert(__builtin_offsetof(_utimbuf, modtime) == 4,
              "offsetof(_utimbuf, modtime) != 4");

} // namespace
