// Auto-generated by scripts/Python/gen_struct_layout_checks.py
// DO NOT EDIT BY HAND. Re-run the generator after updating types.
//
// Category: winuser
// Structs : 8

#include "nocturne.h"

namespace nocturne_layout_winuser {

// ---- HBITMAP__ (4 bytes) ----
static_assert(sizeof(HBITMAP__) == 4,
              "sizeof(HBITMAP__) != 4");
static_assert(__builtin_offsetof(HBITMAP__, unused) == 0,
              "offsetof(HBITMAP__, unused) != 0");

// ---- HBRUSH__ (4 bytes) ----
static_assert(sizeof(HBRUSH__) == 4,
              "sizeof(HBRUSH__) != 4");
static_assert(__builtin_offsetof(HBRUSH__, unused) == 0,
              "offsetof(HBRUSH__, unused) != 0");

// ---- HFONT__ (4 bytes) ----
static_assert(sizeof(HFONT__) == 4,
              "sizeof(HFONT__) != 4");
static_assert(__builtin_offsetof(HFONT__, unused) == 0,
              "offsetof(HFONT__, unused) != 0");

// ---- HICON__ (4 bytes) ----
static_assert(sizeof(HICON__) == 4,
              "sizeof(HICON__) != 4");
static_assert(__builtin_offsetof(HICON__, unused) == 0,
              "offsetof(HICON__, unused) != 0");

// ---- HMENU__ (4 bytes) ----
static_assert(sizeof(HMENU__) == 4,
              "sizeof(HMENU__) != 4");
static_assert(__builtin_offsetof(HMENU__, unused) == 0,
              "offsetof(HMENU__, unused) != 0");

// ---- HWND__ (4 bytes) ----
static_assert(sizeof(HWND__) == 4,
              "sizeof(HWND__) != 4");
static_assert(__builtin_offsetof(HWND__, unused) == 0,
              "offsetof(HWND__, unused) != 0");

// ---- tagMSG (28 bytes) ----
static_assert(sizeof(tagMSG) == 28,
              "sizeof(tagMSG) != 28");
static_assert(__builtin_offsetof(tagMSG, hwnd) == 0,
              "offsetof(tagMSG, hwnd) != 0");
static_assert(__builtin_offsetof(tagMSG, message) == 4,
              "offsetof(tagMSG, message) != 4");
static_assert(__builtin_offsetof(tagMSG, wParam) == 8,
              "offsetof(tagMSG, wParam) != 8");
static_assert(__builtin_offsetof(tagMSG, lParam) == 12,
              "offsetof(tagMSG, lParam) != 12");
static_assert(__builtin_offsetof(tagMSG, time) == 16,
              "offsetof(tagMSG, time) != 16");
static_assert(__builtin_offsetof(tagMSG, pt) == 20,
              "offsetof(tagMSG, pt) != 20");

// ---- tagWNDCLASSA (40 bytes) ----
static_assert(sizeof(tagWNDCLASSA) == 40,
              "sizeof(tagWNDCLASSA) != 40");
static_assert(__builtin_offsetof(tagWNDCLASSA, style) == 0,
              "offsetof(tagWNDCLASSA, style) != 0");
static_assert(__builtin_offsetof(tagWNDCLASSA, lpfnWndProc) == 4,
              "offsetof(tagWNDCLASSA, lpfnWndProc) != 4");
static_assert(__builtin_offsetof(tagWNDCLASSA, cbClsExtra) == 8,
              "offsetof(tagWNDCLASSA, cbClsExtra) != 8");
static_assert(__builtin_offsetof(tagWNDCLASSA, cbWndExtra) == 12,
              "offsetof(tagWNDCLASSA, cbWndExtra) != 12");
static_assert(__builtin_offsetof(tagWNDCLASSA, hInstance) == 16,
              "offsetof(tagWNDCLASSA, hInstance) != 16");
static_assert(__builtin_offsetof(tagWNDCLASSA, hIcon) == 20,
              "offsetof(tagWNDCLASSA, hIcon) != 20");
static_assert(__builtin_offsetof(tagWNDCLASSA, hCursor) == 24,
              "offsetof(tagWNDCLASSA, hCursor) != 24");
static_assert(__builtin_offsetof(tagWNDCLASSA, hbrBackground) == 28,
              "offsetof(tagWNDCLASSA, hbrBackground) != 28");
static_assert(__builtin_offsetof(tagWNDCLASSA, lpszMenuName) == 32,
              "offsetof(tagWNDCLASSA, lpszMenuName) != 32");
static_assert(__builtin_offsetof(tagWNDCLASSA, lpszClassName) == 36,
              "offsetof(tagWNDCLASSA, lpszClassName) != 36");

} // namespace
