#pragma once

// Dependencies
#include "system/basetypes.h"
#include "system/excpt.h"
#include "system/fstream.h"
#include "system/iostream.h"
#include "system/stat.h"
#include "system/stdarg.h"
#include "system/stdio.h"
#include "system/stdlib.h"
#include "system/strstream.h"
#include "system/time.h"
#include "system/utime.h"
#include "system/watcom.h"
#include "system/winbase.h"
#include "system/windef.h"
#include "system/winnt.h"
#include "types/classes/CDemonActor.h"
#include "types/classes/CMatrix3x4f.h"
#include "types/classes/CVector3f.h"
#include "types/classes/CZombie.h"
#include "types/funcdefs/CustomScanlineFunc.h"
#include "types/structs/SDamageInfo.h"
#include "types/structs/SRenderVertex.h"
#include "types/structs/SSoftwareEdge.h"

// =============================================================================
// FUNCTION PROTOTYPES - Range 0x560000
// =============================================================================

void __stack2_esi core_zombie_cpp_CZombie_getCarryObjToBodyXForm_FUN_00560cd0(CZombie *this_ptr,int hand_index,CMatrix3x4f *out_matrix);
int __cdecl core_zombie_cpp_CZombie_FUN_00561010(CZombie *this_ptr,float delta_time);
int __cdecl core_zombie_cpp_CZombie_getPickupHandIndex_FUN_005617e0(CZombie *this_ptr,int object_shape_type);
int __cdecl core_zombie_cpp_CZombie_canPickupWithHand_FUN_00561880(CZombie *this_ptr,int object_shape_type);
void __cdecl core_zombie_cpp_CZombie_dropAndClearTarget_FUN_005618c0(CZombie *this_ptr);
int __cdecl core_zombie_cpp_CZombie_renderOpaque_FUN_00561900(CZombie *this_ptr);
int __cdecl core_zombie_cpp_CZombie_renderTransparent_FUN_00561940(CZombie *this_ptr);
void __cdecl core_zombie_cpp_CZombie_archive_FUN_00561aa0(CZombie *this_ptr);
int __cdecl core_zombie_cpp_CZombie_canBeAttracted_FUN_00561bf0(CZombie *this_ptr,CVector3f *out_attract_position);
void __cdecl core_zombie_cpp_CZombie_processDismemberment_FUN_00561cf0(CZombie *this_ptr,SDamageInfo *damage_info);
void __cdecl core_zombie_cpp_CZombie_processDamage_FUN_00561fc0(CZombie *this_ptr,SDamageInfo *damage_info);
int __cdecl core_zombie_cpp_CZombie_getTargetPoints_FUN_005621f0(CZombie *this_ptr,CVector3f *out_points_array);
int __cdecl core_zombie_cpp_CZombie_isGrabbable_FUN_005623f0(CZombie *this_ptr,CDemonActor *grabber);
int __cdecl core_zombie_cpp_CZombie_canBeGrabbed_FUN_00562430(CZombie *this_ptr,CDemonActor *grabber,int grab_type);
int __cdecl core_zombie_cpp_CZombie_getGrabbed_FUN_00562440(CZombie *this_ptr,CDemonActor *grabber,int grab_type);
int __cdecl core_zombie_cpp_CZombie_shouldIgnoreForTargeting_FUN_005624b0(CZombie *this_ptr);
void __cdecl core_zombie_cpp_CZombie_resetChaseState_FUN_005624e0(CZombie *this_ptr);
CZombie * __cdecl core_zombie_cpp_CZombie_dtor_FUN_00562550(CZombie *this_ptr,uint flags);
void __cdecl engine_zraster_c_addRasterizerEdge_FUN_00562620(SRenderVertex *v0,SRenderVertex *v1);
void __cdecl engine_zraster_c_addRasterizerEdgeWithDepth_FUN_00562740(SRenderVertex *v0,SRenderVertex *v1);
SSoftwareEdge * __cdecl engine_zraster_c_findRasterizerEdge_FUN_00562880(int y_start,SSoftwareEdge *exclude_edge);
void __cdecl engine_zraster_c_rasterizeTriangle_FUN_005628c0(SRenderVertex *vertex_buffer,int vertex_count);
void __cdecl engine_zraster_c_rasterizePolygonCustom_FUN_00562de0(SRenderVertex *vertex_buffer,int vertex_count,CustomScanlineFunc *scanline_renderer);
template<typename T_func0>
inline void engine_zraster_c_rasterizePolygonCustom_FUN_00562de0(SRenderVertex *vertex_buffer,int vertex_count,T_func0 scanline_renderer) {
    engine_zraster_c_rasterizePolygonCustom_FUN_00562de0(vertex_buffer, vertex_count, (CustomScanlineFunc *)scanline_renderer);
}
int __cdecl crt_unknown_c_getc_helper_FUN_00563290(scanf_state_t *state);
int __watcallStack crt_unknown_c_ungetc_helper_FUN_005632b0(int character,scanf_state_t *state);
int __cdecl crt_unknown_c_vfscanf_FUN_005632c8(_FILE *file,char *format,va_list_t args);
int __cdecl crt_stdio_c_fscanf_FUN_00563350(_FILE *file,char *format,...) __attribute__((format(scanf, 2, 3)));
int __cdecl crt_stdio_c_fclose_FUN_00563380(_FILE *file_handle);
int __cdecl crt_unknown_c___CClose_FUN_005633c4(_FILE *file_handle,int close_flags);
char __watcallStack crt_unknown_c_hexDigitToChar_FUN_005633ec(int digit);
void __watcallStack crt_unknown_c__tempnam_FUN_005633fc(char *buffer,int file_handle);
int __cdecl crt_unknown_c_fclose_FUN_005634b0(_FILE *file_handle,int force_close_flag);
void * __cdecl crt_memory_c_malloc_FUN_005635b0(ulong size);
void * __cdecl crt_unknown_c_InternalHeapAlloc_FUN_005635c0(ulong size);
SIZE_T __cdecl crt_stdio_c_fread_FUN_005636d0(void *buffer,SIZE_T size,SIZE_T count,_FILE *file);
void __cdecl crt_memory_c_free_FUN_005638d0(void *ptr);
void __cdecl crt_unknown_c_ValidateHeapIntegrity_FUN_005638e0(void *ptr);
void __cdecl crt_unknown_c_StringBufferCallback_FUN_005639f0(StringOutputContext *context,char character);
int __cdecl crt_stdio_c_vsprintf_FUN_00563a08(char *buffer,char *format,va_list_t args);
double __fpureg_safe crt_math_c_round_FUN_00563a30(double value);
SIZE_T __cdecl crt_stdio_c_fwrite_FUN_00563a50(void *ptr,SIZE_T size,SIZE_T count,_FILE *file);
int __cdecl crt_stdio_c_sprintf_FUN_00563c90(char *buffer,char *format,...) __attribute__((format(printf, 2, 3)));
void * __cdecl crt_memory_c_memset_FUN_00563cc0(void *dest,int value,ulong count);
void crt_unknown_c_FUN_00563ce0(void);
void crt_unknown_c_FUN_00563d12(void);
void crt_unknown_c_FUN_00563d13(void);
void * __watcallStack crt_unknown_c_median_of_3_FUN_00563d20(void *a,void *b,void *c,QSORT_COMPARATOR compar);
template<typename T_func0>
inline void * crt_unknown_c_median_of_3_FUN_00563d20(void *a,void *b,void *c,T_func0 compar) {
    return crt_unknown_c_median_of_3_FUN_00563d20(a, b, c, (QSORT_COMPARATOR)compar);
}
void __watcallRegister crt_unknown_c_memory_swap_FUN_00563d90(void *ptr1,void *ptr2,SIZE_T bytes);
void __cdecl crt_stdlib_c__qsort_FUN_00563db8(void *base,SIZE_T num,SIZE_T size,QSORT_COMPARATOR compar);
template<typename T_func0>
inline void crt_stdlib_c__qsort_FUN_00563db8(void *base,SIZE_T num,SIZE_T size,T_func0 compar) {
    crt_stdlib_c__qsort_FUN_00563db8(base, num, size, (QSORT_COMPARATOR)compar);
}
void * __cdecl crt_memory_c___vec_delete_FUN_0056445f(void *object_ptr,WatcomTypeInfo *type_info);
void __cdecl shape_memdbg_cpp_free_FUN_00564486(void *ptr);
void __cdecl crt_memory_c_operator_delete_FUN_00564494(void *ptr);
void * __cdecl crt_memory_c___arrinit_FUN_005644a7(void *array_start,int element_count,WatcomTypeInfo *type_info);
int __cdecl crt_stdio_c_fprintf_FUN_005644f0(_FILE *file,char *format,...) __attribute__((format(printf, 2, 3)));
int __cdecl crt_string_c__stricmp_FUN_00564520(char *str1,char *str2);
int __cdecl crt_stdio_c_fgetc_FUN_00564570(_FILE *file);
int __watcallStack crt_unknown_c_FillBufferAndGetChar_FUN_00564640(_FILE *file);
int __watcallStack crt_unknown_c_FillInputBuffer_FUN_00564670(_FILE *file);
int __cdecl crt_stdio_c_ungetc_FUN_00564740(int character,_FILE *stream);
int __cdecl crt_ctype_c_tolower_FUN_00564860(int character);
uint * __watcallRegister crt_unknown_c_GetRandomSeedPointer_FUN_00564880(void);
int __cdecl crt_stdlib_c_rand_FUN_0056488c(void);
void __cdecl crt_stdlib_c_srand_FUN_005648b0(uint seed);
double __crtmath crt_math_c_floor_FUN_005648c0(double input_value);
void crt_cpp_c_pureVirtualConstructor_FUN_00564905(void);
void * __cdecl crt_unknown_c___arrdtor_FUN_00564915(WatcomTypeArrayInfo *destroy_info);
void * __cdecl crt_memory_c___arrfini_FUN_0056494f(void *obj_array,int obj_count,WatcomTypeInfo *type_info);
void * __cdecl crt_memory_c_operator_new_FUN_0056497c(ulong size);
int __cdecl crt_string_c__strcmp_FUN_005649c0(char *str1,char *str2);
void * __cdecl crt_memory_c_realloc_FUN_00564a70(void *ptr,ulong new_size);
void * __cdecl crt_unknown_c_realloc__FUN_00564a88(void *ptr,ulong new_size);
char * __cdecl crt_stdio_c_fgets_FUN_00564b20(char *str,int num,_FILE *stream);
void __cdecl crt_unknown_c__atexit_FUN_00564bb0(WatcomStaticDestructorNode *exit_node);
int __cdecl crt_string_c__strnicmp_FUN_00564bc0(char *str1,char *str2,int count);
void * __cdecl shape_memdbg_cpp_malloc_FUN_00564c18(SIZE_T size);
int __cdecl crt_stdio_c_printf_FUN_00564c30(char *format,...) __attribute__((format(printf, 1, 2)));
_istream * __cdecl crt_iostream_cpp_istream_get_FUN_00564c53(_istream *this_ptr,char *c);
_ostream * __cdecl crt_iostream_cpp_ostream_put_FUN_00564ce5(_ostream *this_ptr,int character);
_ostrstream * __cdecl crt_strstream_cpp_ostrstream_ctor_FUN_00564d92(void *this_ptr,int flags,char *buffer,int buffer_size,int mode);
void crt_unknown_c_FUN_00564e3d(int param_1,uint param_2);
void crt_unknown_c_FUN_00564e53(int param_1,uint param_2);
int __cdecl crt_strstream_cpp_ostrstream_tellp_FUN_00564e6b(void *this_ptr);
_ostrstream * __cdecl crt_strstream_cpp_ostrstream_dtor_FUN_00564e98(void *this_ptr,uint flags);
_istrstream * __cdecl crt_strstream_cpp_istrstream_ctor_FUN_00564f32(void *this_ptr,int ctor_flags,char *buffer,int size);
void crt_unknown_c_FUN_00564faa(int param_1,uint param_2);
void crt_unknown_c_FUN_00564fc0(int param_1,uint param_2);
_istrstream * __cdecl crt_strstream_cpp_istrstream_dtor_FUN_00564fd8(void *this_ptr,uint flags);
void __cdecl crt_fstream_cpp_ifstream_ctor_FUN_00565072(void *this_ptr,int ctor_flags,char *filename,int open_mode,int buffer_size);
void crt_unknown_c_FUN_005650f0(int param_1,uint param_2);
void crt_unknown_c_FUN_00565106(int param_1,uint param_2);
void __cdecl crt_fstream_cpp_ofstream_ctor_FUN_0056511e(void *this_ptr,int ctor_flags,char *filename,int open_mode,int buffer_size);
void crt_unknown_c_FUN_0056519c(int param_1,uint param_2);
void crt_unknown_c_FUN_005651b2(int param_1,uint param_2);
ofstream * __cdecl crt_fstream_cpp_ofstream_dtor_FUN_005651ca(void *this_ptr,uint flags);
ifstream * __cdecl crt_fstream_cpp_ifstream_dtor_FUN_00565264(void *this_ptr,uint flags);
ifstream * __cdecl crt_fstream_cpp_ifstream_ctor_FUN_005652fe(void *this_ptr,int c1);
ofstream * __cdecl crt_fstream_cpp_ofstream_ctor_FUN_0056536a(void *this_ptr,int c1);
int __cdecl crt_unknown_c_OpenModeStringParser_FUN_005653e0(char *mode_string,char *output_flags);
_FILE * __cdecl crt_unknown_c_OpenFileAndInitialize_FUN_0056551c(char *filename,char mode_char,int parsed_mode_flags,int stage1_result,int additional_flags,_FILE *file_struct);
_FILE * __cdecl crt_unknown_c_fopenWithFlags_FUN_00565630(char *filename,char *mode,int flags);
_FILE * __cdecl crt_stdio_c_fopen_FUN_0056568c(char *filename,char *mode);
_FILE * crt_unknown_c_FUN_005656a4(_FILE *param_1);
_FILE * __cdecl crt_stdio_c_freopen_FUN_00565724(char *filename,char *mode,_FILE *stream);
int __watcallStack crt_stdio_c_remove_FUN_005657c0(char *filename);
int __cdecl crt_unknown_c_seek_within_buffer_FUN_005657d0(int offset,_FILE *file);
int __cdecl crt_unknown_c_seek_within_buffer_FUN_00565814(_FILE *file);
int __cdecl crt_stdio_c_fseek_FUN_0056582c(_FILE *file,long offset,int whence);
_ostream * __cdecl crt_fstream_cpp_ostream_write_FUN_00565a13(_ostream *stream,void *buffer,SIZE_T count);
float10 __fpustack_safe crt_math_c_pow_FUN_00565ad6(float10 base,float10 exp);
void __fpureg crt_unknown_c_integer_power_FUN_00565c12(void);
void * __cdecl crt_memory_c_calloc_FUN_00565c50(SIZE_T count,SIZE_T size);
float10 __fpustack_safe crt_math_c_asin_FUN_00565c76(float10 sine_value);
double __fpustack_safe crt_math_c_acos_FUN_00565ca4(double x);
char * __cdecl crt_stdlib_c__fullpath_FUN_00565d00(char *buffer,char *path,SIZE_T buffer_size);
int __cdecl crt_io_c_getFileStat_FUN_00565dc0(char *filename,_stat *file_info);
int __cdecl crt_io_c__utime_FUN_00565dc6(char *filename,_utimbuf *timestamps);
DWORD __cdecl engine_dosio_cpp_setReadonlyAttribute_FUN_00565dd0(char *filename,DWORD file_attributes);
int __cdecl crt_ctype_c_toupper_FUN_00565e20(int c);
int __cdecl crt_watcom_c__mkdir_FUN_00565e40(char *path);
int __cdecl crt_iostream_cpp_ostream_flush_FUN_00565e59(void *this_ptr);
uint __cdecl crt_iostream_cpp_ios_clear_FUN_00565e94(ios *this_ptr,uint state_flags);
void __cdecl crt_fstream_cpp_openFile_FUN_00565eb5(void *stream_obj,char *filename,int open_mode,SIZE_T buffer_size);
_istream * __cdecl crt_fstream_cpp_istream_seekg_FUN_00565f14(void *this_ptr,int offset);
char * __cdecl crt_string_c__strncpy_FUN_00565f70(char *dest,char *src,SIZE_T count);
time_t __cdecl crt_time_c__mktime_FUN_00565fb0(_tm *timeptr);
void * __cdecl crt_string_c_memmove_FUN_00566170(void *dest,void *src,SIZE_T n);
void * __cdecl crt_unknown_c___arrinit_dispatch_FUN_005661c2(void *array_ptr,int element_count,WatcomTypeInfo *type_info);
void * __cdecl crt_unknown_c___vec_new_FUN_005661f4(void *dest,int element_count,WatcomTypeInfo *type_info);
void crt_unknown_c_FUN_0056621a(void *param_1,int param_2,WatcomTypeInfo *param_3);
void * __cdecl crt_memory_c___vec_new_FUN_00566234(void *array_memory,int element_count,WatcomTypeInfo *type_info);
int __cdecl crt_unknown_c_normalize_path_separator_FUN_00566250(int ch,int *preferred_separator);
void __cdecl crt_file_c_makepath_FUN_0056626c(char *path_buffer,char *drive,char *directory,char *filename,char *extension);
char * __cdecl crt_watcom_c_getcwd_FUN_00566440(char *buffer,SIZE_T size);
void __watcallStack crt_unknown_c_strncpy_safe_FUN_00566450(char *dest,char *src,int length,int maxlen);
void __cdecl crt_string_c_splitpath_FUN_00566498(char *path,char *drive,char *dir,char *fname,char *ext);
int __cdecl crt_io_c_chdir_FUN_00566570(char *path);
_tm * __cdecl crt_unknown_c_localtime_r_FUN_00566590(time_t *timer,_tm *result);
_tm * __cdecl crt_time_c__localtime_FUN_005665e8(time_t *timer);
void __cdecl crt_unknown_c_formatTwoDigits_FUN_00566600(char *buffer,int value);
uint __cdecl crt_time_c__strftime_FUN_00566634(char *dest_buffer,uint buffer_size,char *format_string,_tm *time_ptr);
char * __cdecl crt_string_c_strupr_FUN_00566ad0(char *string);
int __cdecl crt_unknown_c_string_getc_FUN_00566af0(scanf_state_t *state);
int __cdecl crt_unknown_c_string_ungetc_FUN_00566b18(int ch,scanf_state_t *state);
int __cdecl crt_unknown_c_vsscanf_FUN_00566b20(char *str,char *format,va_list_t args);
int __cdecl crt_stdio_c_sscanf_FUN_00566b5c(char *str,char *format,...) __attribute__((format(scanf, 2, 3)));
int __cdecl crt_heap_c__heapwalk_FUN_00566b90(_heapinfo *heap_info);
int __cdecl crt_unknown_c_heapWalk_FUN_00566ba0(HeapState *heap_state_ptr,Heap *heap_ptr);
int __cdecl crt_unknown_c_heapCheck_FUN_00566c44(void *heap_state_ptr);
void crt_unknown_c_FUN_00566c6c(void);
float10 __fpureg crt_math_c_atan2_FUN_00566c81(float10 y,float10 x);
double crt_unknown_c_FUN_00566c96(double param_1);
double crt_unknown_c_FUN_00566ca9(double param_1,double param_2);
int __cdecl crt_stdio_c_fputc_FUN_00566cc0(int character,_FILE *file);
char * __cdecl crt_env_c_getenv_FUN_00566e10(char *name);
long __cdecl crt_stdio_c_ftell_FUN_00566e70(_FILE *file_handle);
void crt_cpp_c_pureVirtual_FUN_00566ed7(void);
int __watcallStack crt_stdio_c_rename_FUN_00566f00(char *old_filename,char *new_filename);
int __cdecl crt_stdlib_c_atoi_FUN_00566f30(char *string_ptr);
void __cdecl crt_watcom_c_notifyAbnormalTermination_FUN_00566f90(void);
void __watcallRegister crt_unknown_c_reportAbnormalTermination_FUN_00566f98(void);
int __cdecl crt_string_c__stricmp_FUN_00566fb0(char *str1,char *str2);
double __crtmath crt_math_c_modf_FUN_00566fb6(double value,double *integer_part);
char * __cdecl crt_string_c_strstr_FUN_00566fe0(char *haystack_str,char *needle_str);
void crt_unknown_c_FUN_005670b0(void);
undefined4 crt_unknown_c_FUN_005670b1(void);
undefined4 crt_unknown_c_FUN_005670c1(void);
void __watcallStack crt_unknown_c_stack_overflow_handler_FUN_005670e0(SIZE_T required_bytes);
void __stdcall crt_unknown_c_ProbeStackSpace_FUN_005670ed(uint size);
double __crtmath crt_math_c_ceil_FUN_00567121(double value);
void __watcallRegister entry(void);
void crt_unknown_c_FUN_005671c6(void);
ThreadData * __cdecl crt_thread_c_GetTLS_FUN_005671dc(void);
void crt_sync_c_CriticalSectionStub_FUN_005671e4(void);
int __cdecl crt_io_c_register_handler_wrapper_FUN_005671e8(HANDLE file_handle);
void __cdecl crt_io_c_invalidate_handle_wrapper_FUN_005671f8(int handle_index);
undefined1 crt_sync_c_CriticalSectionStub_FUN_00567208(void);
void __cdecl crt_startup_c_initialize_runtime_FUN_0056720c(HMODULE hModule,void *pThreadParam,int unused);
void __watcallRegister crt_startup_cpp_InitializeWinAppRuntime_FUN_00567458(void *pParam);
void __cdecl crt_exit_c_ExitProcess_FUN_005674b0(int exit_code);
void crt_unknown_c_FUN_005674f8(void);
void crt_unknown_c_FUN_00567540(undefined4 *param_1);
void crt_unknown_c_FUN_0056754c(undefined4 param_1,int param_2);
int crt_unknown_c_FUN_00567560(int param_1,byte *param_2,undefined4 *param_3);
byte * crt_unknown_c_FUN_0056782c(byte *param_1,int param_2);
int crt_unknown_c_FUN_00567928(int param_1);
int crt_unknown_c_FUN_00567964(int param_1,int *param_2);
int crt_unknown_c_FUN_00567a5c(int param_1,int *param_2);
void crt_unknown_c_FUN_00567bc0(int param_1,int *param_2,undefined4 param_3);
byte * crt_unknown_c_FUN_00567c2c(byte *param_1,void *param_2);
int crt_unknown_c_FUN_00567c74(int param_1,int *param_2,undefined4 *param_3);
int crt_unknown_c_FUN_00567d88(int param_1,int *param_2);
int crt_unknown_c_FUN_0056808c(int param_1,int *param_2,int param_3,int param_4);
int crt_unknown_c_FUN_005684f8(int param_1);
undefined4 crt_unknown_c_FUN_00568528(int param_1);
_FILE * __cdecl crt_stdio_c___allocfp_FUN_00568560(int unused_param);
void __cdecl crt_stdio_c___freefp_FUN_00568620(_FILE *file_handle);
void crt_unknown_c_FUN_00568658(void);
undefined1 __cdecl crt_process_c_getpid_FUN_00568680(void);
_FILE * crt_unknown_c_FUN_00568690(void);
undefined1 __cdecl crt_io_c_getTempDirectory_FUN_005687bc(void);
int crt_unknown_c_FUN_00568890(undefined4 *param_1);
int __watcallStack crt_stdio_c_lseek_FUN_005689c0(int file_handle_index,long distance_to_move,int move_method);
int __cdecl crt_io_c_close_FUN_00568a50(int fd);
uint * __watcallRegister crt_heap_c_AllocateFromFreeList_FUN_00568b00(uint param_1,undefined4 param_2,int unaff_EBX);
void __watcallRegister crt_heap_c_CoalesceAndAddFreeBlock_FUN_00568bb0(void *ptr,HeapBlock *heap_block,ushort segment);
HeapBlock * __cdecl crt_heap_c_InsertHeapBlockInOrder_FUN_00568ce0(HeapBlock *new_block);
int __cdecl crt_heap_c_AllocateNewHeapBlock_FUN_00568d58(uint size);
void * __cdecl crt_heap_c_SystemAllocWrapper_FUN_00568e08(ulong size);
int __cdecl crt_heap_c_CalculateHeapBlockSize_FUN_00568e1c(uint *pSize);
int __cdecl crt_unknown_c_AllocatorFallbackStub_FUN_00568e70(uint size);
void __cdecl crt_errno_c_setErrno_FUN_00568e80(int error_code);
void __cdecl crt_math_c_set_domain_error_errno_FUN_00568e90(void);
void __cdecl crt_math_c_set_range_error_errno_FUN_00568e9c(void);
void __cdecl crt_errno_c_SetWindowsError_FUN_00568eb8(DWORD windows_error_code);
int __cdecl crt_unknown_c_setvbuf_FUN_00568ed0(_FILE *stream_ptr,char *buffer_ptr,int buffer_mode,SIZE_T buffer_size);
DWORD crt_unknown_c_FUN_00568f70(uint param_1,LPVOID param_2,DWORD param_3);
undefined4 crt_unknown_c_FUN_00569040(undefined4 param_1,char *param_2,int *param_3,code *param_4);
byte * crt_unknown_c_FUN_00569468(undefined4 param_1,int *param_2,int param_3);
char * crt_unknown_c_FUN_005695cc(char *param_1,int param_2);
void crt_unknown_c_FUN_0056963c(char *param_1,undefined4 param_2,int param_3);
int crt_unknown_c_FUN_0056966c(ushort *param_1,undefined4 param_2,int param_3);
void crt_unknown_c_FUN_005696e8(int param_1,char *param_2,int param_3);
void crt_unknown_c_FUN_0056974c(char *param_1,uint param_2,int param_3);
void crt_unknown_c_FUN_00569850(undefined4 param_1,undefined4 param_2,undefined4 param_3);
void crt_unknown_c_FUN_0056986c(int param_1);
void crt_unknown_c_FUN_005698b0(ushort *param_1,undefined4 param_2,int param_3,code *param_4);
undefined8 crt_unknown_c_FUN_00569928(byte *param_1,int *param_2,int param_3);
void crt_unknown_c_FUN_00569f8c(byte *param_1);
DWORD crt_unknown_c_FUN_00569fb0(uint param_1,LPCVOID param_2,DWORD param_3);
void crt_unknown_c_FUN_0056a0c0(void);
void crt_unknown_c_FUN_0056a0f7(void);
void crt_unknown_c_FUN_0056a170(void);
double __cdecl crt_unknown_c__strtod_FUN_0056a189(char *str);
undefined4 crt_unknown_c_FUN_0056a1b5(double *param_1,float *param_2);
void crt_unknown_c_FUN_0056a234(float10 *param_1,uint param_2);
void crt_unknown_c_FUN_0056a28c(float10 *param_1,int param_2);
void crt_unknown_c_FUN_0056a320(undefined4 param_1,int param_2);
uint crt_unknown_c_FUN_0056a388(uint *param_1,int *param_2,undefined1 *param_3);
void crt_unknown_c_FUN_0056a697(void);
void crt_unknown_c_FUN_0056a6ad(void);
void crt_unknown_c_FUN_0056a6c4(void);
void crt_unknown_c_FUN_0056a827(uint *param_1,char *param_2,uint param_3,uint param_4,char *param_5);
void crt_unknown_c_FUN_0056aa38(int *param_1,undefined4 *param_2,uint param_3,int param_4,undefined4 *param_5);
void crt_unknown_c_FUN_0056ad3f(void);
void crt_unknown_c_FUN_0056ada0(void);
void crt_unknown_c_FUN_0056ade4(void);
void crt_unknown_c_FUN_0056adf0(undefined4 *param_1,int param_2);
undefined4 crt_unknown_c_FUN_0056ae10(_FILE *param_1,undefined4 param_2,undefined4 param_3);
void crt_unknown_c_FUN_0056aef0(void);
int crt_unknown_c_FUN_0056aefc(uint param_1);
int crt_unknown_c_FUN_0056af50(void);
void __watcallStack crt_cpp_c_reportPureVirtualError_FUN_0056af76(char *error_message,int exit_code);
ulong __cdecl crt_heap_c_GetBlockSize_FUN_0056afc0(void *ptr);
void crt_unknown_c_FUN_0056afd0(void *param_1,ulong param_2);
undefined4 __watcallRegister crt_heap_c_ResizeBlockInPlace_FUN_0056afe8(undefined4 param_1,undefined4 param_2,int *unaff_EBX,undefined4 param_4,short param_5,int *param_6,uint param_7,uint *param_8);
void * __cdecl crt_heap_c_TryResizeInPlace_FUN_0056b1a4(void *ptr,ulong new_size);
void crt_unknown_c_FUN_0056b1ee(void);
void __cdecl crt_stdlib_c_atexitRegisterNode_FUN_0056b215(WatcomStaticDestructorNode *node_ptr);
int __watcallStack crt_stdio_c_stream_setup_FUN_0056b227(_FILE *stream,int operation_type);
_FILE * __watcallStack crt_stdio_c_fgetcInternal_FUN_0056b2b4(_FILE *stream,byte *output_byte);
void __cdecl crt_stdio_c_reportStreamError_FUN_0056b327(FileEmbeddedData *embedded_data,uint error_flags);
BOOL __cdecl crt_stdio_c_prepare_stream_for_write_FUN_0056b35c(_FILE *stream);
_FILE * __watcallStack crt_stdio_c_stream_flush_FUN_0056b3c2(_FILE *stream);
strstreambase * __cdecl crt_strstream_cpp_strstreambase_ctor_FUN_0056b405(strstreambase *this_ptr,int ctor_flags,char *buffer,int size,char *pstart);
void __cdecl crt_strstream_cpp_strstreambase_destructor_thunk_FUN_0056b491(ios *this_ptr,int dtor_flags);
_ostream * __cdecl crt_iostream_cpp_ostream_ctor_FUN_0056b4a9(_ostream *this_ptr,uint c1);
void __cdecl crt_iostream_cpp_ostream_destructor_thunk_FUN_0056b4eb(ios *this_ptr,int dtor_flags);
ios * __cdecl crt_iostream_cpp_ios_ctor_FUN_0056b503(ios *this_ptr);
_ostream * __cdecl crt_iostream_cpp_ostream_dtor_FUN_0056b538(_ostream *this_ptr,uint flags);
strstreambase * __cdecl crt_strstream_cpp_strstreambase_dtor_FUN_0056b5ad(strstreambase *this_ptr,uint flags);
ios * __cdecl crt_iostream_cpp_ios_dtor_FUN_0056b633(ios *this_ptr,uint flags);
_istream * __cdecl crt_iostream_cpp_istream_ctor_FUN_0056b67d(_istream *this_ptr,uint c1);
void __cdecl crt_iostream_cpp_istream_destructor_thunk_from_ios_FUN_0056b6d0(ios *this_ptr,int dtor_flags);
_istream * __cdecl crt_iostream_cpp_istream_dtor_FUN_0056b6e8(_istream *this_ptr,uint flags);
void __cdecl crt_fstream_cpp_fstreambase_ctor_FUN_0056b75d(fstreambase *this_ptr,int ctor_flags,int fd,int mode,char *buffer,SIZE_T buffer_size );
void __cdecl crt_fstream_cpp_fstream_destructor_thunk_from_ios_FUN_0056b7f8(ios *this_ptr,int dtor_flags);
fstreambase * __cdecl crt_fstream_cpp_fstreambase_dtor_FUN_0056b810(fstreambase *this_ptr,uint flags);
fstreambase * __cdecl crt_fstream_cpp_fstreambase_ctor_FUN_0056b896(fstreambase *this_ptr,uint c1);
int __cdecl crt_stdio_c_CreateFileVariadic_FUN_0056b934(char *filename,int access_mode,int share_mode,...);
HANDLE __cdecl crt_stdio_c_CreateFileImpl_FUN_0056b960(char *filename,dword access_mode,dword share_mode,va_list_t *extra_args);
void __cdecl crt_stdio_c_DetectDeviceAndSetBuffering_FUN_0056bbb0(_FILE *file);
int __watcallStack crt_unknown_c_remove_FUN_0056bbf0(char *filename);
long __watcallStack crt_io_c_tell_FUN_0056bc10(int file_handle_index);
int __watcallStack crt_iostream_cpp_streambuf_do_sputn_FUN_0056bc70(streambuf *buffer,void *input_buffer,SIZE_T bytes_to_write);
double __cdecl crt_math_c_math_domain_error_FUN_0056bd22(double x,double y,uchar error_type);
undefined1 crt_unknown_c_FUN_0056bdc8(void);
float10 __fpureg_safe crt_math_c_exp_FUN_0056bdd2(float10 x);
float10 __fpustack_safe crt_math_c_fdiv_FUN_0056be50(float10 dividend,float10 divisor);
float10 __watcallRegister crt_math_c_function_dispatch_FUN_0056bf67(int function_index);
void crt_unknown_c_FUN_0056bf71(void);
void crt_unknown_c_FUN_0056bf77(void);
void crt_unknown_c_FUN_0056bf7c(void);
void crt_unknown_c_FUN_0056bf82(void);
void crt_unknown_c_FUN_0056bf87(void);
void crt_unknown_c_FUN_0056bf8d(void);
void crt_unknown_c_FUN_0056bf93(void);
void crt_unknown_c_FUN_0056bf99(void);
void __watcallRegister crt_math_c_dispatch_divide_FUN_0056bf9f(void);
void crt_unknown_c_FUN_0056bfbb(void);
void crt_unknown_c_FUN_0056bfc0(void);
void crt_unknown_c_FUN_0056bfd6(void);
void __fpu_thunk crt_unknown_c_fdiv_thunk_FUN_0056bfdb(void);
void crt_unknown_c_FUN_0056bff7(void);
void __fpu_thunk crt_math_c_fdiv_thunk_FUN_0056c007(void);
void crt_unknown_c_FUN_0056c01b(void);
void crt_unknown_c_FUN_0056c02b(void);
void crt_unknown_c_FUN_0056c04b(void);
void crt_unknown_c_FUN_0056c050(void);
void crt_unknown_c_FUN_0056c06a(void);
void __fpu_thunk crt_unknown_c_fdiv_thunk_FUN_0056c06f(void);
void crt_unknown_c_FUN_0056c08f(void);
void __fpu_thunk crt_math_c_fdiv_thunk_FUN_0056c0a3(void);
void crt_unknown_c_FUN_0056c0bb(void);
void crt_unknown_c_FUN_0056c0cf(void);
void crt_unknown_c_FUN_0056c0ef(void);
void crt_unknown_c_FUN_0056c0f4(void);
void crt_unknown_c_FUN_0056c10e(void);
void crt_unknown_c_FUN_0056c113(void);
void crt_unknown_c_FUN_0056c133(void);
void crt_unknown_c_FUN_0056c147(void);
void crt_unknown_c_FUN_0056c15f(void);
void crt_unknown_c_FUN_0056c173(void);
void crt_unknown_c_FUN_0056c193(void);
void crt_unknown_c_FUN_0056c198(void);
void crt_unknown_c_FUN_0056c1b2(void);
void __fpu_thunk crt_unknown_c_fdiv_thunk_FUN_0056c1b7(void);
void crt_unknown_c_FUN_0056c1d7(void);
void __fpu_thunk crt_math_c_fdiv_thunk_FUN_0056c1eb(void);
void crt_unknown_c_FUN_0056c203(void);
void crt_unknown_c_FUN_0056c217(void);
void crt_unknown_c_FUN_0056c237(void);
void crt_unknown_c_FUN_0056c23c(void);
void crt_unknown_c_FUN_0056c256(void);
void __fpu_thunk crt_unknown_c_fdiv_thunk_FUN_0056c25b(void);
void crt_unknown_c_FUN_0056c27b(void);
void __fpu_thunk crt_math_c_fdiv_thunk_FUN_0056c28f(void);
void crt_unknown_c_FUN_0056c2a7(void);
void crt_unknown_c_FUN_0056c2bb(void);
void crt_unknown_c_FUN_0056c2db(void);
void crt_unknown_c_FUN_0056c2e0(void);
void crt_unknown_c_FUN_0056c2fa(void);
void __fpu_thunk crt_unknown_c_fdiv_thunk_FUN_0056c2ff(void);
void crt_unknown_c_FUN_0056c31f(void);
void __fpu_thunk crt_math_c_fdiv_thunk_FUN_0056c333(void);
void crt_unknown_c_FUN_0056c34b(void);
void crt_unknown_c_FUN_0056c35f(void);
void crt_unknown_c_FUN_0056c37f(void);
void crt_unknown_c_FUN_0056c384(void);
void crt_unknown_c_FUN_0056c39e(void);
void crt_unknown_c_FUN_0056c3a3(void);
void crt_unknown_c_FUN_0056c3c3(void);
void __fpu_thunk crt_math_c_fdiv_thunk_FUN_0056c3d7(void);
void crt_unknown_c_FUN_0056c3ef(void);
void __fpustack_safe crt_math_c_pentiumFdivpWorkaround_FUN_0056c403(void);
void crt_unknown_c_FUN_0056c416(void);
void crt_unknown_c_FUN_0056c429(void);
undefined4 crt_unknown_c_FUN_0056c4d4(uint param_1);
undefined4 crt_unknown_c_FUN_0056c520(undefined4 param_1,uint param_2);
double crt_unknown_c_FUN_0056c56c(int param_1,uint param_2);
double __fpureg_safe crt_math_c_sqrt_FUN_0056c5a8(double value);
char * __cdecl crt_watcom_c_getcwd_FUN_0056c5f0(char *buffer,SIZE_T size);
void crt_unknown_c_FUN_0056c6a0(undefined4 param_1,int param_2);
void crt_unknown_c_FUN_0056c6b8(DWORD param_1,int param_2);
int __cdecl crt_errno_c_convertWindowsErrorToErrno_FUN_0056c6d0(DWORD windows_error);
DWORD __cdecl crt_errno_c___set_errno_FUN_0056c73c(void);
uint __watcallStack crt_io_c_analyze_file_type_FUN_0056c750(uint open_flags,char *filename);
int __cdecl crt_io_c_getFileStat_FUN_0056c864(char *filename,_stat *file_info);
int __cdecl crt_io_c__utime_FUN_0056cb60(char *filename,_utimbuf *timestamps);
DWORD __cdecl crt_file_c___getfileattr_FUN_0056cce0(char *filename);
int crt_unknown_c_FUN_0056cd52(int param_1);
int crt_unknown_c_FUN_0056cd9b(int param_1,undefined4 param_2,uint param_3,undefined4 param_4);
int crt_unknown_c_FUN_0056ce57(_FILE *param_1,int param_2);
int __cdecl crt_time_c_is_leap_year_FUN_0056cea0(int year);
int crt_unknown_c_FUN_0056ced8(int param_1,int param_2);
undefined4 crt_unknown_c_FUN_0056cfd8(int param_1,int param_2,undefined4 param_3);
int __cdecl crt_time_c_determine_dst_status_FUN_0056d034(_tm *timeptr);
undefined4 crt_unknown_c_FUN_0056d308(int *param_1,int *param_2);
_tm * __cdecl crt_time_c_gmtime_r_FUN_0056d340(time_t days,time_t seconds,time_t timezone_offset,_tm *result);
void crt_unknown_c_FUN_0056d488(time_t *param_1,_tm *param_2);
void crt_unknown_c_FUN_0056d4ab(undefined4 param_1);
uint crt_unknown_c_FUN_0056d4d0(void);
uint crt_unknown_c_FUN_0056d4e8(void);
void __cdecl crt_time_c_tzset_FUN_0056d608(void);
char * __cdecl crt_string_c_parse_uint_FUN_0056d628(char *str,int *result);
char * __cdecl crt_time_c_parse_timezone_spec_FUN_0056d658(char *tz_string,char *name_buffer,int *offset_seconds);
char * __cdecl crt_time_c_parse_dst_rule_FUN_0056d774(char *rule_string,dst_rule *rule);
void __cdecl crt_time_c_parse_tz_string_FUN_0056d87c(char *tz_string);
void * __cdecl crt_memory_c___arrinit__FUN_0056d99b(void *array_start,int element_count,WatcomTypeInfo *type_info);
int __watcallStack crt_string_c_mbtowc_peek_FUN_0056d9f0(char *str);
void __watcallStack crt_locale_c_wchar_to_bytes_FUN_0056da30(wchar_t character,char *output_buffer);
int __watcallStack crt_locale_c_mblen_FUN_0056da50(char *mb_string);
char * __watcallStack crt_string_c_mbtowc_next_FUN_0056da80(char *str);
char * __cdecl crt_string_c_mb_get_last_char_FUN_0056dab0(char *start,char *end);
int __watcallStack crt_string_c_mbstrnlen_FUN_0056db40(char *str,int max_bytes);
char * __watcallStack crt_string_c_mbstrncpy_FUN_0056db80(char *dest,char *src,int char_count);
int __watcallStack crt_string_c_mbstrnbytes_FUN_0056dbb0(char *str,int char_count);
char * __cdecl crt_stdlib_c_itoa_FUN_0056dc10(int value,char *buffer,int base);
char * __cdecl crt_stdio_c_IntegerToString_FUN_0056dc68(int value,char *buffer,int base);
float10 __fpustack crt_math_c_atan2_FUN_0056dc98(float10 y,float10 x);
int __cdecl crt_string_c__mbstrnicmp_FUN_0056dcd0(char *str1,char *str2,SIZE_T count);
int __cdecl crt_stdio_c_fflush_FUN_0056dd60(_FILE *stream);
void __cdecl crt_startup_c_WriteErrorAndExit_FUN_0056dd80(char *error_message,int exit_code);
void __cdecl crt_startup_c_HandleRuntimeError_FUN_0056ddc0(char *error_message,int error_level);
int __cdecl crt_unknown_c_build_cmdline_FUN_0056ddf0(int argc,char **argv,char *program,char **out_cmdline,char **out_environment,char **out_buffer,int *out_bufsize,int copy_program_flag);
void crt_unknown_c_FUN_0056de90(void);
int crt_unknown_c_FUN_0056deac(int param_1);
void __watcallRegister crt_startup_cpp_WinMainBootstrap_FUN_0056df10(void);
undefined4 crt_unknown_c_FUN_0056dfc0(void);
int crt_unknown_c_FUN_0056e010(int param_1);
void crt_unknown_c_FUN_0056e09c(HANDLE param_1,uint param_2);
void crt_unknown_c_FUN_0056e174(int param_1);
void crt_unknown_c_FUN_0056e1a0(void);
HANDLE crt_unknown_c_FUN_0056e208(void);
void crt_unknown_c_FUN_0056e230(void);
void crt_unknown_c_FUN_0056e250(void);
LPCRITICAL_SECTION crt_unknown_c_FUN_0056e254(void);
void crt_unknown_c_FUN_0056e2f8(void);
void crt_unknown_c_FUN_0056e324(void);
void crt_unknown_c_FUN_0056e37c(int param_1);
void crt_unknown_c_FUN_0056e390(undefined4 *param_1);
void crt_unknown_c_FUN_0056e3f4(undefined4 *param_1);
void crt_unknown_c_FUN_0056e41c(void);
void crt_unknown_c_FUN_0056e42c(void);
void crt_unknown_c_FUN_0056e43c(uint param_1);
void crt_unknown_c_FUN_0056e458(uint param_1);
void crt_unknown_c_FUN_0056e474(undefined4 param_1);
void crt_unknown_c_FUN_0056e484(uint param_1);
void crt_unknown_c_FUN_0056e4ac(void);
void crt_unknown_c_FUN_0056e4bc(void);
void crt_unknown_c_FUN_0056e4cc(void);
void crt_unknown_c_FUN_0056e4dc(void);
void crt_unknown_c_FUN_0056e4ec(void);
void crt_unknown_c_FUN_0056e4fc(void);
void crt_unknown_c_FUN_0056e50c(void);
void crt_unknown_c_FUN_0056e51c(void);
LPVOID crt_unknown_c_FUN_0056e52c(void);
void * crt_unknown_c_FUN_0056e56c(void *param_1);
bool crt_unknown_c_FUN_0056e5ac(void);
undefined4 crt_unknown_c_FUN_0056e608(undefined4 param_1);
void crt_unknown_c_FUN_0056e664(int param_1);
BOOL crt_unknown_c_FUN_0056e6b8(void);
void crt_unknown_c_FUN_0056e6c4(void);
void crt_unknown_c_FUN_0056e6e4(void);
void crt_unknown_c_FUN_0056e7fc(void);
DWORD crt_unknown_c_FUN_0056e890(HMODULE param_1,LPWSTR param_2,DWORD param_3);
char * crt_unknown_c_FUN_0056e940(char *param_1);
void * crt_unknown_c_FUN_0056e990(undefined4 param_1);
void __cdecl crt_memory_c___GetStackLimits_FUN_0056e9d0(ThreadData *pStackBound,uint *pHeapBound);
BOOL __cdecl crt_windows_c_has_active_window_FUN_0056ea40(void);
void __cdecl crt_exception_c_FormatHexString_FUN_0056ea78(char *dest,char *format,DWORD value);
long __cdecl crt_exception_c_TopLevelExceptionFilter_FUN_0056ead4(_EXCEPTION_POINTERS *ExceptionInfo);
EXCEPTION_DISPOSITION __cdecl crt_exception_c_ExceptionHandler_FUN_0056ed08(EXCEPTION_RECORD *ExceptionRecord,void *EstablisherFrame,CONTEXT *ContextRecord,void *DispatcherContext);
void __cdecl crt_exception_c_installExceptionHandler_FUN_0056eed8(undefined4 param_1);
void __cdecl crt_exception_c_RemoveExceptionHandler_FUN_0056ef24(void);
void __cdecl crt_util_c_invokeRuntimeHandler_FUN_0056ef50(RUNTIME_HANDLER_FUNC **ppHandler);
void __cdecl crt_init_c_ProcessInitTermHandlers_FUN_0056ef60(int max_priority);
void __cdecl crt_exit_c_ProcessExitHandlers_FUN_0056efb8(uchar min_priority,uchar max_priority);
void crt_unknown_c_FUN_0056f034(void);
int __watcallStack crt_locale_c_mbtowc_FUN_0056f040(wchar_t *wide_char,char *mb_string,SIZE_T max_bytes);
void crt_unknown_c_FUN_0056f0f0(void);
float __watcallRegister crt_math_c_doubleToFloat_FUN_0056f100(double val);
ulonglong __watcallRegister crt_math_c_multiply64_FUN_0056f14c(ulonglong a,ulonglong b);
int crt_unknown_c_FUN_0056f170(LPCSTR param_1,byte param_2);
int * __cdecl crt_errno_c__errno_FUN_0056f1a0(void);
int __watcallStack crt_stdio_c_flushFileBuffers_FUN_0056f1c0(int file_handle_index);
undefined4 crt_unknown_c_FUN_0056f220(uint param_1);
void crt_unknown_c_FUN_0056f278(int param_1,uint param_2);
undefined4 crt_unknown_c_FUN_0056f2d0(void);
undefined4 crt_unknown_c_FUN_0056f30c(LPVOID param_1);
void crt_unknown_c_FUN_0056f36c(int param_1);
int __cdecl crt_stdio_c_WideCharToSingleByte_FUN_0056f3a0(wchar_t wide_char,char *output_buffer);
char * __cdecl crt_stdlib_c_i64toa_FUN_0056f3e0(longlong *value,char *buffer,int base);
char * crt_unknown_c_FUN_0056f480(uint *param_1,char *param_2,int param_3);
char * __cdecl crt_stdlib_c_utoa_FUN_0056f4f0(uint value,char *buffer,int base);
char * crt_unknown_c_FUN_0056f544(uint param_1,char *param_2,int param_3);
undefined8 crt_unknown_c_FUN_0056f573(int param_1,int *param_2,int param_3);
int __cdecl crt_string_c_parseFloatString_FUN_0056f690(char *str,void *result,char **endptr);
double __cdecl crt_string_c_strtod_main_FUN_0056f852(char *str,char **endptr);
undefined4 crt_unknown_c_FUN_0056f938(int *param_1);
char * crt_unknown_c_FUN_0056f986(char *param_1,int param_2);
void crt_unknown_c_FUN_0056f9c4(undefined4 param_1,undefined4 param_2,undefined4 param_3,undefined4 param_4,undefined4 param_5);
void crt_unknown_c_FUN_0056fa00(undefined4 param_1,undefined4 param_2,int param_3,int *param_4,undefined4 param_5);
void crt_unknown_c_FUN_0056fa40(void);
int __watcallStack crt_stdio_c_DrainConsoleInputWithBuffering_FUN_0056fa80(HANDLE hConsoleInput);
undefined1 crt_stdio_c_DrainConsoleInputAndSetup_FUN_0056fb98(void);
int __watcallStack crt_stdio_c_WriteConsoleChar_FUN_0056fc30(int character);
int __cdecl crt_debug_c_TriggerDebuggerBreak_FUN_0056fca0(char *error_message,ushort flags);
undefined1 __cdecl crt_unknown_c_ExitHookStub_FUN_0056fcd0(void);
void __cdecl crt_startup_c_ExitApplication_FUN_0056fcd4(int exit_code);
void __cdecl crt_exit_c_FinalExitHandler_FUN_0056fd00(int exit_code);
char * __watcallStack crt_string_c_mbstrncpy_core_FUN_0056fd26(char *dest,char *src,int count);
int * crt_unknown_c_FUN_0056fd65(int *param_1,undefined4 *param_2);
int * crt_unknown_c_FUN_0056fd83(int *param_1,undefined4 *param_2);
int * crt_unknown_c_FUN_0056fda1(int *param_1,undefined4 *param_2);
int * crt_unknown_c_FUN_0056fdbf(int *param_1,undefined4 *param_2);
void __watcallStack crt_stdio_c_storeErrorState_FUN_0056fddd(uint *destination,uint error_state);
_FILE * __cdecl crt_stdio_c_get_standard_file_handle_FUN_0056fdf0(int fd);
streambuf * __cdecl crt_iostream_cpp_streambuf_ctor_FUN_0056fe12(streambuf *this_ptr);
void __watcallStack crt_strstream_cpp_strstreambuf_init_FUN_0056fe65(strstreambuf *this_ptr,char *buffer_ptr,int buffer_size,char *put_start);
void __watcallStack crt_iostream_cpp_streambuf_initBuffer_FUN_0056ff2a(streambuf *this_ptr,char *buffer_ptr);
int __watcallStack crt_iostream_cpp_streambuf_do_sgetn_FUN_0056ff82(streambuf *buffer,void *output_buffer,SIZE_T bytes_to_read);

