#pragma once

// Typedef: COORD
typedef _COORD COORD;

// Typedef: FOCUS_EVENT_RECORD
typedef _FOCUS_EVENT_RECORD FOCUS_EVENT_RECORD;

// Typedef: MENU_EVENT_RECORD
typedef _MENU_EVENT_RECORD MENU_EVENT_RECORD;

// Typedef: MOUSE_EVENT_RECORD
typedef _MOUSE_EVENT_RECORD MOUSE_EVENT_RECORD;

// Typedef: PINPUT_RECORD
// pointer to _INPUT_RECORD
typedef _INPUT_RECORD* PINPUT_RECORD;

// Typedef: WINDOW_BUFFER_SIZE_RECORD
typedef _WINDOW_BUFFER_SIZE_RECORD WINDOW_BUFFER_SIZE_RECORD;

