#pragma once

// Enum: ECmdParmType
enum {
    PARM_TYPE_INT = 0x0,
    PARM_TYPE_FLOAT = 0x1,
    PARM_TYPE_TEXT = 0x2,
    PARM_TYPE_ACTOR = 0x3,
    PARM_TYPE_CONDITION = 0x4,
    PARM_TYPE_LABEL = 0x5,
    PARM_TYPE_CAMERA = 0x6,
    PARM_TYPE_ACTOR_VARIABLE = 0x7,
    PARM_TYPE_CONTROL_BUTTON = 0x8,
    PARM_TYPE_DAMAGE_TYPE = 0x9,
    PARM_TYPE_DEATH_TYPE = 0xA,
    PARM_TYPE_SFX_SET = 0xB,
    PARM_TYPE_SFX_USED = 0xC,
    PARM_TYPE_WAV = 0xD,
    PARM_TYPE_WEATHER = 0xE,
    PARM_TYPE_COUNTER_SET = 0xF,
    PARM_TYPE_COUNTER_USED = 0x10,
    PARM_TYPE_LETTER_BOX_MODE = 0x11,
    PARM_TYPE_FILENAME = 0x12,
    PARM_TYPE_SPOT_LIGHT = 0x13,
    PARM_TYPE_EVENT_COMMAND = 0x14,
    PARM_TYPE_PERSISTENT_EVENT_NAME = 0x15,
    PARM_TYPE_GAME_FLAG_NAME = 0x16,
    PARM_TYPE_MOTION_NAME = 0x17,
    PARM_TYPE_MOTION_STATE = 0x18,
    PARM_TYPE_DB_TAG = 0x19,
    PARM_TYPE_HERO_TASK = 0x1A,
    PARM_TYPE_ACTOR_CLASS = 0x1B,
    PARM_TYPE_TIMER = 0x1C,
    PARM_TYPE_REL_OP = 0x1D,
    PARM_TYPE_BODY_PART_LIST = 0x1E,
    PARM_TYPE_INI_VARIABLE = 0x1F
};
typedef int ECmdParmType;

