#pragma once

// Enum: EDamageType
enum {
    DAMAGE_TYPE_GENERIC = 0x0,
    DAMAGE_TYPE_DROWN = 0x1,
    DAMAGE_TYPE_FALL = 0x2,
    DAMAGE_TYPE_EXPLODE = 0x3,
    DAMAGE_TYPE_SHATTER = 0x4,
    DAMAGE_TYPE_FALL_APART = 0x5,
    DAMAGE_TYPE_ELECTROCUTE = 0x6,
    DAMAGE_TYPE_CHOPPED = 0x7,
    DAMAGE_TYPE_CRUSHED = 0x8,
    DAMAGE_TYPE_IMPALE = 0x9,
    DAMAGE_TYPE_FIRE = 0xA,
    DAMAGE_TYPE_IMMUNE = 0x64,
    DAMAGE_TYPE_MELEE = 0x67,
    DAMAGE_TYPE_LAUNCH = 0x68,
    DAMAGE_TYPE_NO_FLINCH = 0x69,
    DAMAGE_TYPE_DECAL = 0x6A,
    DAMAGE_TYPE_PIERCING = 0x6B,
    DAMAGE_TYPE_BURN = 0x6C
};
typedef int EDamageType;

