#pragma once

// Enum: EEditorActionType
enum {
    ACTION_TYPE_CURSOR_LEFT = 0x0,
    ACTION_TYPE_CURSOR_RIGHT = 0x1,
    ACTION_TYPE_CURSOR_UP = 0x2,
    ACTION_TYPE_CURSOR_DOWN = 0x3,
    ACTION_TYPE_PAGE_UP = 0x4,
    ACTION_TYPE_PAGE_DOWN = 0x5,
    ACTION_TYPE_HOME = 0x6,
    ACTION_TYPE_END = 0x7,
    ACTION_TYPE_CTRL_HOME = 0x8,
    ACTION_TYPE_CTRL_END = 0x9,
    ACTION_TYPE_UNKNOWN1 = 0xA,
    ACTION_TYPE_UNKNOWN2 = 0xB,
    ACTION_TYPE_SELECT_WORD = 0xC,
    ACTION_TYPE_COPY = 0xD,
    ACTION_TYPE_PASTE = 0xE,
    ACTION_TYPE_CUT = 0xF,
    ACTION_TYPE_BACKSPACE = 0x10,
    ACTION_TYPE_DELETE = 0x11,
    ACTION_TYPE_ENTER = 0x12
};
typedef int EEditorActionType;

