#pragma once

// Enum: ECmdParmType
typedef enum ECmdParmType {
    PARM_TYPE_INT = 0,
    PARM_TYPE_FLOAT = 1,
    PARM_TYPE_TEXT = 2,
    PARM_TYPE_ACTOR = 3,
    PARM_TYPE_CONDITION = 4,
    PARM_TYPE_LABEL = 5,
    PARM_TYPE_CAMERA = 6,
    PARM_TYPE_ACTOR_VARIABLE = 7,
    PARM_TYPE_CONTROL_BUTTON = 8,
    PARM_TYPE_DAMAGE_TYPE = 9,
    PARM_TYPE_DEATH_TYPE = 10,
    PARM_TYPE_SFX_SET = 11,
    PARM_TYPE_SFX_USED = 12,
    PARM_TYPE_WAV = 13,
    PARM_TYPE_WEATHER = 14,
    PARM_TYPE_COUNTER_SET = 15,
    PARM_TYPE_COUNTER_USED = 16,
    PARM_TYPE_LETTER_BOX_MODE = 17,
    PARM_TYPE_FILENAME = 18,
    PARM_TYPE_SPOT_LIGHT = 19,
    PARM_TYPE_EVENT_COMMAND = 20,
    PARM_TYPE_PERSISTENT_EVENT_NAME = 21,
    PARM_TYPE_GAME_FLAG_NAME = 22,
    PARM_TYPE_MOTION_NAME = 23,
    PARM_TYPE_MOTION_STATE = 24,
    PARM_TYPE_DB_TAG = 25,
    PARM_TYPE_HERO_TASK = 26,
    PARM_TYPE_ACTOR_CLASS = 27,
    PARM_TYPE_TIMER = 28,
    PARM_TYPE_REL_OP = 29,
    PARM_TYPE_BODY_PART_LIST = 30,
    PARM_TYPE_INI_VARIABLE = 31
} ECmdParmType;

