#pragma once

// Enum: EConnectionStatus
enum {
    CONNECTION_STATUS_WAITING = 0x0,
    CONNECTION_STATUS_ACCEPTED_BY_SERVER = 0x1,
    CONNECTION_STATUS_REJECTED_NOT_SERVER = 0x2,
    CONNECTION_STATUS_REJECTED_GAME_FULL = 0x3,
    CONNECTION_STATUS_REJECTED_ALREADY_IN_GAME = 0x4
};
typedef int EConnectionStatus;

