#pragma once

// Enum: EConnectionStatus
enum {
    CONNECTION_STATUS_WAITING = 0,
    CONNECTION_STATUS_ACCEPTED_BY_SERVER = 1,
    CONNECTION_STATUS_REJECTED_NOT_SERVER = 2,
    CONNECTION_STATUS_REJECTED_GAME_FULL = 3,
    CONNECTION_STATUS_REJECTED_ALREADY_IN_GAME = 4
};
typedef int EConnectionStatus;

