#pragma once

// Enum: EDamageType
enum {
    DAMAGE_TYPE_GENERIC = 0,
    DAMAGE_TYPE_DROWN = 1,
    DAMAGE_TYPE_FALL = 2,
    DAMAGE_TYPE_EXPLODE = 3,
    DAMAGE_TYPE_SHATTER = 4,
    DAMAGE_TYPE_FALL_APART = 5,
    DAMAGE_TYPE_ELECTROCUTE = 6,
    DAMAGE_TYPE_CHOPPED = 7,
    DAMAGE_TYPE_CRUSHED = 8,
    DAMAGE_TYPE_IMPALE = 9,
    DAMAGE_TYPE_FIRE = 10,
    DAMAGE_TYPE_IMMUNE = 100,
    DAMAGE_TYPE_MELEE = 103,
    DAMAGE_TYPE_LAUNCH = 104,
    DAMAGE_TYPE_NO_FLINCH = 105,
    DAMAGE_TYPE_DECAL = 106,
    DAMAGE_TYPE_PIERCING = 107,
    DAMAGE_TYPE_BURN = 108
};
typedef int EDamageType;

