#pragma once

// Enum: EEditorActionType
typedef enum EEditorActionType {
    ACTION_TYPE_CURSOR_LEFT = 0,
    ACTION_TYPE_CURSOR_RIGHT = 1,
    ACTION_TYPE_CURSOR_UP = 2,
    ACTION_TYPE_CURSOR_DOWN = 3,
    ACTION_TYPE_PAGE_UP = 4,
    ACTION_TYPE_PAGE_DOWN = 5,
    ACTION_TYPE_HOME = 6,
    ACTION_TYPE_END = 7,
    ACTION_TYPE_CTRL_HOME = 8,
    ACTION_TYPE_CTRL_END = 9,
    ACTION_TYPE_UNKNOWN1 = 10,
    ACTION_TYPE_UNKNOWN2 = 11,
    ACTION_TYPE_SELECT_WORD = 12,
    ACTION_TYPE_COPY = 13,
    ACTION_TYPE_PASTE = 14,
    ACTION_TYPE_CUT = 15,
    ACTION_TYPE_BACKSPACE = 16,
    ACTION_TYPE_DELETE = 17,
    ACTION_TYPE_ENTER = 18
} EEditorActionType;

