#pragma once

// Dependencies
#include "system/basetypes.h"

// Enum: ENetPacketType
enum {
    PACKET_NONE = 0,
    PACKET_PLAYER_ANNOUNCE = 1,
    PACKET_SERVER_ACCEPT = 2,
    PACKET_GAME_START = 3,
    PACKET_PING = 4,
    PACKET_PING_RESPONSE = 5,
    PACKET_CHAT_MESSAGE = 6,
    PACKET_CHAT_ACK = 7,
    PACKET_SYNC_STAGE_REQ = 8,
    PACKET_SYNC_STAGE_RESP = 9,
    PACKET_PLAYER_STATE = 10,
    PACKET_GAME_SETTINGS = 11,
    PACKET_SETTINGS_ACK = 12,
    PACKET_DISCONNECT = 13,
    PACKET_UNUSED = 14,
    PACKET_SIM_FRAME = 15,
    PACKET_PLAYER_INPUT = 16
};
typedef uchar ENetPacketType;

