#pragma once

// =============================================================================
// ENUMS - Aggregate Header
// =============================================================================
// Auto-generated aggregate of all enums type definitions.

#include "types/enums/EActionType.h"
#include "types/enums/EActorPropertyType.h"
#include "types/enums/EAimLockState.h"
#include "types/enums/EAimMode.h"
#include "types/enums/EAmmoBoxType.h"
#include "types/enums/EAmmoType.h"
#include "types/enums/ECmdParmType.h"
#include "types/enums/EConnectionStatus.h"
#include "types/enums/EConnectionType.h"
#include "types/enums/EControlMode.h"
#include "types/enums/EDamageType.h"
#include "types/enums/EDeathType.h"
#include "types/enums/EDoorState.h"
#include "types/enums/EDoorType.h"
#include "types/enums/EDripType.h"
#include "types/enums/EEditorActionType.h"
#include "types/enums/EFireMode.h"
#include "types/enums/EGroundType.h"
#include "types/enums/EHealthBarMode.h"
#include "types/enums/EHeroControlType.h"
#include "types/enums/EHeroTask.h"
#include "types/enums/EHeroType.h"
#include "types/enums/EHostageState.h"
#include "types/enums/EHostageType.h"
#include "types/enums/EInputCodeType.h"
#include "types/enums/ELeverType.h"
#include "types/enums/ELightActorType.h"
#include "types/enums/EMotionTransitionCmd.h"
#include "types/enums/ENetPacketType.h"
#include "types/enums/ENetworkMode.h"
#include "types/enums/EPlatformStateType.h"
#include "types/enums/EPlatformType.h"
#include "types/enums/ETextAlignment.h"
#include "types/enums/ETriggerEventType.h"
#include "types/enums/EWeaponState.h"
#include "types/enums/EWeaponType.h"
#include "types/enums/EWerewolfType.h"

