#pragma once

// =============================================================================
// TYPEDEFS - Aggregate Header
// =============================================================================
// Auto-generated aggregate of all typedefs type definitions.

#include "types/typedefs/CAmmoBox_ptr_344.h"
#include "types/typedefs/CAmmo_ptr_344.h"
#include "types/typedefs/CAnvil_ptr_344.h"
#include "types/typedefs/CBackgroundActor_ptr_344.h"
#include "types/typedefs/CBat_ptr_376.h"
#include "types/typedefs/CBat_ptr_392.h"
#include "types/typedefs/CBattery_ptr_344.h"
#include "types/typedefs/CBiggs_ptr_48828.h"
#include "types/typedefs/CBiggs_ptr_49216.h"
#include "types/typedefs/CBodyPart_ptr_1872.h"
#include "types/typedefs/CBodyPart_ptr_3276.h"
#include "types/typedefs/CBodyPart_ptr_656.h"
#include "types/typedefs/CBoneGuy_ptr_48956.h"
#include "types/typedefs/CBoxActor_ptr_344.h"
#include "types/typedefs/CBoxActor_ptr_394.h"
#include "types/typedefs/CBoxActor_ptr_916.h"
#include "types/typedefs/CBox_ptr_180.h"
#include "types/typedefs/CBugs_ptr_48828.h"
#include "types/typedefs/CBugs_ptr_74440.h"
#include "types/typedefs/CCharacter_ptr_10900.h"
#include "types/typedefs/CCharacter_ptr_11356.h"
#include "types/typedefs/CCharacter_ptr_11536.h"
#include "types/typedefs/CCharacter_ptr_12060.h"
#include "types/typedefs/CCharacter_ptr_13260.h"
#include "types/typedefs/CCharacter_ptr_344.h"
#include "types/typedefs/CCrate_ptr_344.h"
#include "types/typedefs/CCrossbow_ptr_1404.h"
#include "types/typedefs/CDemonActor_ptr_296.h"
#include "types/typedefs/CDoor_ptr_344.h"
#include "types/typedefs/CDrip_ptr_344.h"
#include "types/typedefs/CEmitter_ptr_584.h"
#include "types/typedefs/CFilmProjector_ptr_500.h"
#include "types/typedefs/CFilmReel_ptr_344.h"
#include "types/typedefs/CHealthItem_ptr_344.h"
#include "types/typedefs/CLightActor_ptr_1648.h"
#include "types/typedefs/CScript_ptr_56.h"
#include "types/typedefs/CTVBat_ptr_48832.h"
#include "types/typedefs/CTurret_ptr_1412.h"
#include "types/typedefs/SBitBuffer_ptr_8.h"
#include "types/typedefs/SBodyPartFire_ptr_12.h"
#include "types/typedefs/SBodyPartModel_ptr_24.h"
#include "types/typedefs/SScrape_ptr_1020.h"

